- dipy/reconst/sfm.py
This works with the new release 0.22, but also with older versions (at least one version back).
Fixes #2010
> BF: Use the `sklearn.base` interface, instead of deprecated `sklearn.linear_model.base`

- dipy/io/stateful_tractogram.py
- dipy/io/streamline.py
- dipy/io/tests/test_stateful_tractogram.py
- dipy/io/tests/test_utils.py
- dipy/io/utils.py
Fix the inversion in the documentation about the standard (trackvis vs nifti).
Replace the unclear variable name (`shifted_origin` -> `origin_at_corner`)
Added a small catch for all-zero affine that was crashing in `nib.aff2axcodes`
> Fix origin nomenclature sft (center/corner)

- dipy/io/stateful_tractogram.py
- dipy/io/tests/test_stateful_tractogram.py
- dipy/stats/analysis.py
- dipy/tracking/streamlinespeed.pyx
- dipy/tracking/tests/test_tracking.py
As you can see on this PR (https://github.com/nipy/nibabel/pull/811), `ArraySequence.data` will now return a copy of the data. This way, altering the data of the sliced/indexed tractogram will not affect the original data.
So, the goal of this PR is to prevent this copy since the future release of Nibabel is quite soon.
> [FIX] Avoid copy of  Streamlines data

- dipy/io/stateful_tractogram.py
- dipy/io/streamline.py
- dipy/io/tests/test_stateful_tractogram.py
- dipy/io/tests/test_streamline.py
- dipy/io/tests/test_utils.py
- dipy/io/utils.py
Instead of creating a `StatefulTractogram` from scratch providing the the reference, the space, the `voxel_at_origin` is cumbersome if the user wanted to have the exact same state as another SFT.
Colleagues were trying to do that and sometime forgot to pass along  `voxel_at_origin` messing up the new SFT state.
So to simplifying the operation (or at least provide a clear function for that), a constructor was added for that situation. Quite specific, but useful and clear functionality.
Added function to improve usability.
The reference for `StatefulTractogram` can now be (on top of the 6 other ways) a tuple similar to what `get_reference_info` was returning. The function `is_reference_info_valid` now check the basic type and value of the element to decrease chance of mistake.
This will …
> SFT constructor from another SFT

- dipy/tracking/tests/test_utils.py
- dipy/tracking/utils.py
Hi, this is Ross Lawrence (a research assistant in Jovo's lab). This is my first dipy PR, so forgive any formatting issues. In this PR I added the option for connectivity_matrix to use the entire streamline in its analysis (instead of just the start and end points). This method is essentially what is used for our [ndmg ](https://github.com/neurodata/ndmg/tree/staging) connectome pipeline. This allows for connectivity matrices to use label volumes of white matter structures and record the connections between them.
- Works by looking at all the rois the streamline goes through and recording the connection between each roi. For example, if the streamlines path is through rois 3->2->4->5, then a connection will be recorded for (3,2), (3,4), (3,5), (2,4), (2,5), and (4,5).
- This is added …
> Add ability to analyze entire streamline in connectivity_matrix

- .pep8speaks.yml
Ignore the examples folder, because many of these files will not comply with PEP8. For example, see all the messages that popped up in #2021
> Update pep8speaks configuration

- dipy/io/image.py
- dipy/tracking/tests/test_life.py
- dipy/viz/app.py
- doc/api_changes.rst
- doc/examples/denoise_gibbs.py
- doc/examples/reconst_forecast.py
- doc/examples/reconst_fwdti.py
- doc/examples/streamline_registration.py
In Nibabel, `get_data` was using the array proxy by default which seems to not be the case for `get_fdata`. So now, we use `np.asarray(img.dataobj)` to keep the default behavior.
this is a PR for the maintenance branch, I will have to cut a new release which will be DIPY 1.1.1 and announce this one by default instead of DIPY 1.1.0.
> [MAINT] Use the array proxy instead of get_fdata()

- dipy/reconst/sfm.py
- dipy/reconst/tests/test_sfm.py
This fixes a bug in the way that SFM does signal prediction when fit with a mask. This is something I just stumbled upon earlier today while I was working with @dPys on https://github.com/nipreps/dmriprep/pull/62. This should fix the issues we were seeing there.
> BF: SFM prediction with mask

- dipy/tracking/local_tracking.py
- dipy/tracking/tests/test_tracking.py
A small PR to fix #2034. I just check the `seed` type to avoid an error later with a much more complex message.
> [FIX] check seeds dtype

- .travis.yml
- azure-pipelines.yml
- dipy/info.py
- requirements.txt
This should help with this: https://github.com/dipy/dipy/pull/2033#issuecomment-587558735. It seems that nibabel has upped their minimal requirement for 3.0
and we can follow along.
> MAINT: Up Numpy version to 1.12.

- CONTRIBUTING.md
Fix `Sphinx` link in `CONTRIBUTING.md`: use `Markdown` syntax instead of
`reStructuredText` syntax.
> DOC: Fix `Sphinx` link in `CONTRIBUTING.md`

- doc/examples/syn_registration_2d.py
I think if all the modules are imported in the top to avoid added import calls in the middle of the code plus it seems more systematic.
> Placed all imports in the beginning

- dipy/core/gradients.py
reorient_gradients creates a new gradient table, but it was not possible to manually define the b0_threshold. So, when a b0 image has a bval of 60, the function crashes.
> Small fix reorient_bvecs

- dipy/io/tests/test_stateful_tractogram.py
- dipy/io/tests/test_streamline.py
- dipy/io/tests/test_utils.py
- dipy/io/utils.py
A simple switch to a much more robust Nibabel `get_best_affine()`
Manual getting the sform was often giving full zeros affine when they came from ITK/MITK/ANTs
> Replace manual sform values with get_best_affine

- dipy/core/gradients.py
- dipy/core/tests/test_gradients.py
I suggest extending the GradientTable class to contain information about b-tensor shapes.
This preliminary code calculates the b-tensors for each acquisition and saves the information as an attribute of the GradientTable. The user can explicitly define the used tensor shapes as linear, planar, or spherical. Next step is to add support for arbitrary tensor shapes in the form of a 3 x 3 matrix or an array of such matrices. If the user does not specify the tensor shape, the code assumes the acquisition to have been performed using linear tensors (traditional single diffusion encoding), so the gradient_table function and GradientTable class can be used as before.
Before finishing the implementation, I would like to ask you for your opinion on the organization of the proposed code.
After this …
> Multidimensional gradient table

- doc/examples/streamline_length.py
Based on proposition https://github.com/dipy/dipy/pull/2093 to import all required modules in the top to avoid callbacks in the middle of example and makes it look more systematic.
> Minor Typos and imports in the beginning

- dipy/align/tests/test_imaffine.py
Renaming local variables to avoid conflict with `scipy` library local namespace `sp`,See issue #2118
> rename var sp to sph

- dipy/core/gradients.py
- dipy/core/tests/test_gradients.py
This PR provides a function (`btensor_to_bdelta`) to calculate the normalized anisotropy of b-tensors.
The idea was to implement this so that the new `btens` attribute from the `GradientTable` class could be directly fed to `btensor_to_bdelta` to get the tensor anisotropy for each measurement. I believe this will be useful for future implementations of microstructure models that rely on datasets acquired with multiple b-tensor shapes (e.g. [ref1](https://linkinghub.elsevier.com/retrieve/pii/S1053-8119(16)30345-7), [ref2](https://linkinghub.elsevier.com/retrieve/pii/S1053-8119(16)00148-8)).
I placed this function in _dipy/core/gradients.py_ as I think it is general enough that it might be useful in the implementation of different models (e.g. to help sort data before powder-averaging …
> ENH: function to calculate anisotropy of b-tensors

- dipy/reconst/tests/test_ivim.py
Fix NumPy warning when creating arrays from ragged sequences in IVIM
reconstruction test.
Fixes
```
VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences
(which is a list-or-tuple of lists-or-tuples-or ndarrays with different
lengths or shapes) is deprecated. If you meant to do this, you must specify
'dtype=object' when creating the ndarray
```
triggered in
https://travis-ci.org/github/dipy/dipy/jobs/676101427#L5495
Rationale:
https://numpy.org/neps/nep-0034-infer-dtype-is-object.html
> BF: Fix NumPy warning when creating arrays from ragged sequences

- dipy/tracking/life.py
Fix sequence stacking warning in LiFE tracking
Fixes:
```
FutureWarning: arrays to stack must be passed as a "sequence" type such as list
or tuple. Support for non-sequence iterables such as generators is deprecated as
of NumPy 1.16 and will raise an error in the future.
```
raised for example in
https://dev.azure.com/dipy/46625eaf-7255-4a2c-9e92-befcdbdca2a8/_apis/build/builds/293/logs/262
> BF: Fix sequence stacking warning in LiFE tracking

- dipy/core/gradients.py
- dipy/core/tests/test_gradients.py
Create an instance of the [GradientTable](https://github.com/dipy/dipy/blob/85738ae82223aae9af9893220665f1203ea3dd8a/dipy/core/gradients.py#L17) class without specifying the `btens` attribute:
>>> gt = GradientTable(gradients)
Where `gradients` is a gradient table without specifying b-tensors (e.g. see [here](https://github.com/dipy/dipy/blob/85738ae82223aae9af9893220665f1203ea3dd8a/dipy/core/tests/test_gradients.py#L87)).
Query the `btens` attribute on that instance:
>>> print(gt.btens)
AttributeError: 'GradientTable' object has no attribute 'btens'
This error being triggered does seem to be the expected behaviour, as judging by [dipy/core/tests/test_gradients.py](https://github.com/dipy/dipy/blob/master/dipy/core/tests/test_gradients.py), specifically …
> BF: ensure `btens` attribute of `GradientTable` is initialised

- dipy/viz/app.py
- dipy/viz/panel.py
- dipy/workflows/tests/test_viz.py
- dipy/workflows/viz.py
When the slicer goes up or down we need to update the scene clipping range because some of the slices are not immediately visible.
I use this opportunity to add 2 new optionq in Horizon: 
- `--bg_color 0.5 0.5 0.5` or `--bg_color 0.5`(change background color of the scene)
- `--disable_order_transparency`
> [Horizon] Update clipping range on slicer

- dipy/viz/regtools.py
- dipy/workflows/base.py
Use equality check instead of identity check.
Fixes for example
```
/home/vsts/work/1/s/venv/lib/python3.8/site-packages/dipy/viz/regtools.py:227:
SyntaxWarning: "is" with a literal. Did you mean "=="?
if direct_grid2world is -1:
```
Reported for example in
https://dev.azure.com/dipy/46625eaf-7255-4a2c-9e92-befcdbdca2a8/_apis/build/builds/310/logs/267
> BF: Use equality check instead of identity check

- dipy/reconst/mapmri.py
- dipy/reconst/tests/test_mapmri.py
- dipy/sims/voxel.py
A laplacian_regularization condition was always `True` so this is a quick fix. I use the opportunity to clean some warnings for the CI's and tests. The following warning should disappear:
```python
dipy/reconst/tests/test_mapmri.py::test_orthogonality_basis_functions
/Users/koudoro/Software/dipy/dipy/reconst/tests/test_mapmri.py:92: IntegrationWarning: The occurrence of roundoff error is detected, which prevents 
the requested tolerance from being achieved.  The error may be 
underestimated.
4, 0, diffusivity, q) * q ** 2, qmin, qmax)[0]
dipy/reconst/tests/test_mapmri.py::test_orthogonality_basis_functions
/Users/koudoro/Software/dipy/dipy/reconst/tests/test_mapmri.py:97: IntegrationWarning: The occurrence of roundoff error is detected, which prevents 
the requested tolerance from being …
```
> [Fix]  laplacian_regularization on MAPMRI + cleanup warning

- dipy/reconst/csdeconv.py
- dipy/reconst/shm.py
- dipy/reconst/tests/test_shm.py
Fix RuntimeWarnings that appear in tutorials or continuous integration tests:
```python
direction/tests/test_pmf.py::test_boot_pmf
/home/travis/build/dipy/dipy/venv/lib/python3.8/site-packages/dipy/reconst/shm.py:768: RuntimeWarning: invalid value encountered in sqrt
leverages = sqrt(1 - H.diagonal())
direction/tests/test_pmf.py::test_boot_pmf
/home/travis/build/dipy/dipy/venv/lib/python3.8/site-packages/dipy/reconst/csdeconv.py:550: RuntimeWarning: invalid value encountered in less
where_fodf_small = (fodf < threshold).nonzero()[0]
direction/tests/test_pmf.py::test_boot_pmf
/home/travis/build/dipy/dipy/venv/lib/python3.8/site-packages/dipy/reconst/csdeconv.py:556: RuntimeWarning: invalid value encountered in less
where_fodf_small = (fodf < threshold).nonzero()[0] …
```
> [Fix] shm.py RuntimeWarning

- dipy/io/stateful_tractogram.py
- dipy/io/tests/test_stateful_tractogram.py
Thanks to new code from @MarcCote in Nibabel, interaction with StatefulTractogram are now much safer for slicing and/or adding.
Code such as this is now possible, it makes sure the spatial attributes are the same, that the sft share the same space, origin and have the same keys for data_per_*. Then it basically concatenates everything creating a new sft.
`new_sft = sft_cc[0:2000] + sft_pt[0:2000] + sft_af[0:2000]`
These operations are strict, in line with everything else in the StatefulTractogram.
For example an operation like this is not possible (inconsistent space):
```
sft_1.to_vox()
sft_2.to_rasmm()
sft_3 = sft_1 + sft_2 
```
Also important to know, to avoid side effects, like the rest of StatefulTractogram, nothing is done inplace. For example:
```
sft.to_rasmm()
sft_subset = …
```
> Slicing, adding function of StatefulTractogram

- dipy/segment/bundles.py
- dipy/workflows/stats.py
- doc/interfaces/buan_flow.rst
Added cluster threshold (clust_thr) as an optional argument in dipy_buan_shapes workflow. 
Updated default clust_thr values as well.
This small update makes the workflow faster.
> Cluster threshold parameter in dipy_buan_shapes workflow

- .gitignore
- dipy/stats/analysis.py
- dipy/tracking/metrics.py
- dipy/workflows/stats.py
- dipy/workflows/tests/test_stats.py
The goal of this PR is to fix some warning on the stats module
```python
workflows/tests/test_stats.py::test_stats
/home/travis/build/dipy/dipy/venv/lib/python3.8/site-packages/numpy/core/fromnumeric.py:3334: RuntimeWarning: Mean of empty slice.
return _methods._mean(a, axis=axis, dtype=dtype,
workflows/tests/test_stats.py::test_stats
/home/travis/build/dipy/dipy/venv/lib/python3.8/site-packages/numpy/core/_methods.py:153: RuntimeWarning: invalid value encountered in true_divide
ret = um.true_divide(
workflows/tests/test_stats.py::test_stats
/home/travis/build/dipy/dipy/venv/lib/python3.8/site-packages/numpy/core/_methods.py:216: RuntimeWarning: Degrees of freedom <= 0 for slice
ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
workflows/tests/test_stats.py::test_stats …
```
> [Fix] some warning on stats module

- dipy/reconst/tests/test_multi_voxel.py
- dipy/segment/tests/test_clustering.py
Remove/fixing the following warning:
```python
segment/tests/test_clustering.py: 18 tests with warnings
/home/travis/build/dipy/dipy/venv/lib/python3.8/site-packages/numpy/testing/_private/utils.py:402: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
if isdesnan and isactnan:
reconst/tests/test_multi_voxel.py::test_squash
reconst/tests/test_multi_voxel.py::test_squash
/home/travis/build/dipy/dipy/venv/lib/python3.8/site-packages/numpy/testing/_private/utils.py:794: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
val = comparison(x, y)
```
fix #2130
> [Fix] some warning on clustering test

- setup.py
Fix `distutils` Python version requirement option warning.
Fixes
```
/opt/python/3.7.1/lib/python3.7/distutils/dist.py:274: UserWarning: Unknown
distribution option: 'python_requires'
warnings.warn(msg)
```
raised for example in
https://dev.azure.com/dipy/dipy/_build/results?buildId=343&view=logs&j=d9aefae6-c332-51b5-d933-a85009f5a2ac&t=10ba5eab-67e4-5f58-2aec-60b4dbb37e45&l=1948
or
https://travis-ci.org/github/dipy/dipy/jobs/679159532
(warning in raw log: https://api.travis-ci.org/v3/job/679159532/log.txt)
> BF: Fix `distutils` Python version requirement option warning

- dipy/reconst/eudx_direction_getter.pyx
Fix Cython function override warning.
A `cpdef` function can be only overriden by a `cpdef` function in a derived
class that is an extension type (`cdef class`).
Fixes:
```
warning: dipy/reconst/eudx_direction_getter.pyx:44:4: Overriding cdef method
with def method.
```
raised for example in
https://dev.azure.com/dipy/dipy/_build/results?buildId=343&view=logs&j=d9aefae6-c332-51b5-d933-a85009f5a2ac&t=10ba5eab-67e4-5f58-2aec-60b4dbb37e45&l=1950
or
https://travis-ci.org/github/dipy/dipy/jobs/679159532
(warning in raw log: https://api.travis-ci.org/v3/job/679159532/log.txt)
> BF: Fix Cython function  override warning

- dipy/reconst/sfm.py
- dipy/reconst/tests/test_sfm.py
- dipy/sims/voxel.py
Small PR to fix some CI's warning on sfm module. I use the opportunity to fix some pep8 too.
The warnings fixed are:
```python
reconst/tests/test_mcsd.py::test_mcsd_model_delta
reconst/tests/test_mcsd.py::test_compartments
reconst/tests/test_mcsd.py::test_MultiShellDeconvModel
/home/travis/build/dipy/dipy/venv/lib/python3.7/site-packages/dipy/sims/voxel.py:1050: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
response[i, 2:] = np.linalg.lstsq(B, wm_response)[0]
reconst/tests/test_sfm.py::test_sfm
reconst/tests/test_sfm.py::test_sfm …
```
> [Fix] sfm RuntimeWarning

- dipy/tracking/localtrack.pyx
Fix Cython floating point absolute value warning:
```
dipy/tracking/localtrack.c:2846:21: warning: using integer absolute value
function 'abs' when argument is of floating point type [-Wabsolute-value]
__pyx_r = (1. / abs(__pyx_v_increment));
^
dipy/tracking/localtrack.c:2846:21: note: use function 'fabs' instead
__pyx_r = (1. / abs(__pyx_v_increment));
^~~
fabs
```
raised for example in
https://dev.azure.com/dipy/dipy/_build/results?buildId=374&view=logs&j=eb71c31b-0e3f-5817-821a-71ddffa66479&t=c96ee7eb-f012-52fa-7392-c7ee03227595&l=698
> BF: Fix Cython floating point absolute value warning

- dipy/tracking/distances.pyx
Fix Cython signed vs. unsigned integer comparison warning.
Fixes:
```
dipy/tracking/distances.c: In function
â€˜__pyx_f_4dipy_8tracking_9distances_min_distancesâ€™:
dipy/tracking/distances.c:8874:41: warning:
comparison between signed and unsigned integer expressions [-Wsign-compare]
for (__pyx_v_t2_pi = 0; __pyx_v_t2_pi <
__pyx_t_1; __pyx_v_t2_pi++) {
^
```
and
```
dipy/tracking/distances.c:11524:38: warning: comparison between signed and
unsigned integer expressions [-Wsign-compare]
__pyx_t_12 = ((__pyx_v_mid_index < (__pyx_v_t_len - 1)) != 0);
^
```
https://dev.azure.com/dipy/dipy/_build/results?buildId=373&view=logs&j=ad7c9750-8a16-5492-49ac-3815bac6d5d2&t=baa9a672-c8e1-55fc-55ff-b7fd664eb7f3&l=652
and
https://dev.azure.com/dipy/dipy/_build/results?buildId=373&vi …
> BF: Fix Cython signed vs. unsigned integer comparison warning

- dipy/reconst/qtdmri.py
Fix string literal comparison warning.
Fixes
```
/home/vsts/work/1/s/venv/lib/python3.8/site-packages/dipy/reconst/qtdmri.py:157:
SyntaxWarning: "is not" with a literal. Did you mean "!="?
if laplacian_weighting is not 'GCV':
/home/vsts/work/1/s/venv/lib/python3.8/site-packages/dipy/reconst/qtdmri.py:175:
SyntaxWarning: "is not" with a literal. Did you mean "!="?
if l1_weighting is not 'CV'
```
https://dev.azure.com/dipy/dipy/_build/results?buildId=399&view=logs&j=d9aefae6-c332-51b5-d933-a85009f5a2ac&t=10ba5eab-67e4-5f58-2aec-60b4dbb37e45&l=1926
> BF: Fix string literal comparison warning

- doc/interfaces/bundle_segmentation_flow.rst
- doc/interfaces/index.rst
Added bundle_segmentation_flow.rst file which explains how to extract white matter bundles from target tractogram using RecoBundles.
Figures added in the tutorial.
> Bundle segmentation CLI tutorial

- CONTRIBUTING.md
- README.rst
- doc/_templates/layout.html
- doc/links_names.inc
Links updated after Gitter migration.
**old:** https://gitter.im/nipy/dipy   -> redirect to 
**new:** https://gitter.im/dipy/dipy
fix #2144
> Gitter url update: from nipy/dipy to dipy/dipy

- doc/theory/sh_basis.rst
I'm doing a summer internship with @mdesco. I'm working on full spherical harmonic basis (including odd and even order terms) for reconstructing asymmetric spherical functions (coming soon in other pull request). There were inconsistencies between implementation of functions `real_sym_sh_mrtrix` and `real_sym_sh_basis` from module `dipy.reconst.shm` and documentation of theory on spherical harmonic bases. I fixed the doc for it to agree with the implementation.
> [DOC] Update SH basis documentation

- dipy/reconst/mapmri.py
- dipy/workflows/reconst.py
- dipy/workflows/stats.py
This PR fixes the following errors/warnings:
```
/home/travis/build/dipy/dipy/venv/lib/python3.5/site-packages/cvxpy/expressions/expression.py:516: UserWarning: 
This use of ``*`` has resulted in matrix multiplication.
Using ``*`` for matrix multiplication has been deprecated since CVXPY 1.1.
Use ``*`` for matrix-scalar and vector-scalar multiplication.
Use ``@`` for matrix-matrix and matrix-vector multiplication.
Use ``multiply`` for elementwise multiplication.
warnings.warn(__STAR_MATMUL_WARNING__, UserWarning)
```
I think we just need to do a FURY release to fix the last errors and make the CI's completely happy.
> [Fix] update mapmri due to cvxpy 1.1

- dipy/reconst/shm.py
- dipy/reconst/tests/test_shm.py
- doc/examples/reconst_sh.py
- doc/examples/valid_examples.txt
- doc/examples_index.rst
- doc/theory/sh_basis.rst
Add bases `descoteaux07_full `and `tournier07_full` as available SH basis in `dipy/reconst/shm.py`. These bases add odd order spherical harmonics to the symmetric basis and can approximate symmetric and asymmetric spherical functions. New functions are `real_full_sh_mrtrix` (tournier07_full), `real_full_sh_basis` (descoteaux07_full) and `sph_harm_full_ind_list` (used to construct index list of orders and degrees of the complete SH basis).
> Add full SH basis

- dipy/segment/mrf.pyx
This PR improves the performance of tissue classification by modifying the Cython code in the `seg_stats` method of `ConstantObservationModel` to avoid high overhead. There should be no change in behavior with this PR.
This initial call to `seg_stats` in the `classify` method of `TissueClassifierHMRF` for the example data in `doc/demo/tissue_classification.py` takes > 60 seconds on my system prior to this PR and ~60 ms afterwards. So, the setup prior to iteration is now nearly instantaneous. The iterated conditional modes loop itself still takes the same time as before (~2 minutes), giving an overall speedup of around 30% for the demo.
I would recommend reviewing the first commit in isolation as it has all of the important changes.
The remaining commits are just minor maintenance/style …
> Improve performance of tissue classification

- dipy/tracking/stopping_criterion.pxd
- dipy/tracking/stopping_criterion.pyx
Fix Cython label defined but not used warning.
Fixes
```
dipy/tracking/stopping_criterion.c: In function
â€˜__pyx_f_4dipy_8tracking_18stopping_criterion_27AnatomicalStoppingCriterion_get_exclude_câ€™:
2020-04-29T06:37:02.4069497Z dipy/tracking/stopping_criterion.c:5359:3: warning:
label â€˜__pyx_L1_errorâ€™ defined but not used [-Wunused-label]
__pyx_L1_error:;
^
dipy/tracking/stopping_criterion.c: In function
â€˜__pyx_f_4dipy_8tracking_18stopping_criterion_27AnatomicalStoppingCriterion_get_include_câ€™:
dipy/tracking/stopping_criterion.c:5655:3: warning: label â€˜__pyx_L1_errorâ€™
defined but not used [-Wunused-label]
__pyx_L1_error:;
^
```
https://dev.azure.com/dipy/dipy/_build/results?buildId=373&view=logs&j=ad7c9750-8a16-5492-49ac-3815bac6d5d2&t=baa9a672-c8e1-55f …
> BF: Fix Cython label defined but not used warning

- dipy/segment/mask.py
- dipy/segment/tests/test_mask.py
- doc/api_changes.rst
This PR works around a bug in SciPy. input/output arrays cannot overlap in memory during calls to `scipy.ndimage.median` (see scipy/scipy#9553).
The issue will be fixed upstream by scipy/scipy#11986 (See the figure in the first comment there, which illustrates the severity of the issue!)
The solution proposed here works with current SciPy and should be kept even once the SciPy minimum version is updated, as it avoids repeatedly creating a new temporary array within `scipy.ndimage.median` in each iteration.
I have plotted the smoothed volumes from the following small script pre and post-PR below:
```Python
import numpy as np
from dipy.data import get_fnames
from dipy.io.image import load_nifti
from dipy.segment.mask import multi_median
hardi_fname, hardi_bval_fname, hardi_bvec_fname = …
```
> Fix a memory overlap bug in multi_median (and median_otsu)

- dipy/tracking/life.py
- dipy/tracking/tests/test_life.py
Maybe we could also add an optional brain mask argument to ensure we're only considering fibers inside the brain?
> [ENH] Validate streamlines pre-LiFE

- dipy/core/gradients.py
- dipy/core/tests/test_gradients.py
This PR refactors and enhances the function previously known as `btensor_to_bdelta` which I implemented in a previous PR (#2125). This function, which I renamed to `btens_to_params` now also outputs other b-tensor parameters: the trace (b-value) and the assymetry. In continuation with my previous PR (#2125), this further simplifies a future implementation of microstructure models using data acquired with b-tensors of arbitrary shapes.
This PR further includes a utility function `params_to_btens` which does the reverse of the above, that is, computes a b-tensor from its "parameters" trace, normalized anisotropy and assymetry.
New/updated tests provided for everything. Thanks @kerkelae for useful discussions 😉.
> ENH: function to calculate size/shape parameters of b-tensors and vice-versa

- dipy/io/stateful_tractogram.py
- dipy/io/streamline.py
Every logging and Raise message now has a period at the end of the line. It was a mix before, which annoyed me.
One bounding box raise message also hed missing space.
After 2 months of testing "in the field" I now realized that the epsilon for the `remove_invalid_streamlines()` function is too low. At 1e-6 it does not remove enough streamlines WHEN the affine of the data has a mild rotational component and crash (often) at saving due to floating-point difference. I never have problems with 1e-3, which is what I expect after a call to `remove_invalid_streamlines()`
Any typo anyone saw in the last few months is welcome: @GuillaumeTh @ppoulin91 @AntoineTheb @fullbat
> End of line period in sft

- dipy/tracking/tests/test_utils.py
- dipy/tracking/vox2track.pyx
Closes https://github.com/dipy/dipy/issues/2182
Adds bound checking in _streamlines_in_mask when accessing the mask array.
I also changed it to explicitly return 1 or 0  for the final point to avoid returning unwanted values given in the mask array
> _streamlines_in_mask bounds check

- dipy/info.py
- setup.py
Follow up on https://github.com/dipy/dipy/pull/2204#issuecomment-675530197 iin #2204:
This would entail that installing with:
`pip install dipy[all]`
would now include all the optional dependencies specified in this dict. 
Question: what else do we need to include in this dict (if anything)?
> Add optional installs for different settings.

- dipy/align/bundlemin.pyx
- dipy/segment/clusteringspeed.pyx
- dipy/tracking/distances.pyx
- dipy/tracking/fbcmeasures.pyx
Fix variable may be used uninitialized warning.
Fixes:
```
dipy/tracking/distances.c: In function
‘__pyx_f_4dipy_8tracking_9distances_czhang’:
dipy/tracking/distances.c:8842:10: warning: ‘__pyx_v_dist_val’ may be used
uninitialized in this function [-Wmaybe-uninitialized]
return __pyx_r;
^
```
and
```
dipy/tracking/distances.c: In function
‘__pyx_pf_4dipy_8tracking_9distances_14cut_plane.isra.43’:
dipy/tracking/distances.c:3310:59: warning: ‘*((void *)&__pyx_v_normal+8)’ may
be used uninitialized in this function [-Wmaybe-uninitialized]
__pyx_v_ip = (__pyx_v_ip + ((__pyx_v_vec1[__pyx_v_i]) *
(__pyx_v_vec2[__pyx_v_i])));
^
dipy/tracking/distances.c:4696:9: note: ‘*((void *)&__pyx_v_normal+8)’ was
declared here
float __pyx_v_normal[3];
^
```
and
```
dipy/tracking/fbcmeasures.c: In function …
```
> BF: Fix variable may be used uninitialized warning

- doc/examples/streamline_registration.py
> [FIX] renamed Direct Streamline Normalization tutorial title

- dipy/reconst/mcsd.py
This small PR is for fixing the numpy version issue encountered with the `rcond` parameter of `numpy.linalg.lstsq`, more precisely with numpy==1.13.
> Fixing numpy version rcond issue in numpy.linalg.lstsq

- dipy/tracking/utils.py
Removed the 'streamlines' variable name from the 'Returns' list since the method returns a generator, and hence not the value of a variable named 'streamlines'.
> DOC : inconsistent save_seeds documentation

- dipy/tracking/tests/test_life.py
Quick PR to replace `pytest.xfail` by `npt.assert_raises` due to some confusion during the Pytest report.
> Replace pytest.xfail by npt.assert_raises

- .gitignore
- .travis.yml
- azure-pipelines.yml
- ci/azure/osx.yml
- ci/azure/script.ps1
- ci/azure/script.sh
- ci/azure/windows.yml
This PR should fix #2214.
As explained before, Rackspace does not exist anymore. Many packages (numpy, scipy, pandas) upload their nightly wheels to [this anaconda server. ](https://anaconda.org/scipy-wheels-nightly)
Also, DIPY uploads to this server (twice per week)  `dev` wheels from `master`.
EDIT :  ~~The only important missing package is Cython. We need to find a solution to test the future wheels of this package.~~  it is available
> [CI] Replace Rackspace by https://anaconda.org/scipy-wheels-nightly

- doc/examples/denoise_localpca.py
- doc/examples/denoise_mppca.py
- doc/examples/reconst_csd.py
- doc/examples/reconst_dki.py
Conform to `reStructuredText` syntax in examples sections.
> STYLE: Conform to `reStructuredText` syntax in examples sections

- dipy/reconst/mcsd.py
- dipy/reconst/tests/test_mcsd.py
Just a small clarifying of `auto_response_msmt` and `response_from_mask_msmt` docstring with regards to the bvalues usage.
> Clarifying msmt response function docstrings

- doc/installation.rst
Add tips to the documentation build section:
- Add how to avoid building the documentation for the examples.
- Add a section about how to solve `Sphinx` being unable to import `dipy` when
building the documentation.
> DOC: Add tips to the documentation build section

- .pep8speaks.yml
Exclude package information file from PEP8 checks.
> STYLE: Exclude package information file from PEP8 checks

- dipy/segment/bundles.py
- dipy/workflows/stats.py
This PR is for maintenance of bundle_shape_similarity function in segment/bundles.py
It updates line 196 in segment/bundles.py
from: 
```
ba_value = ba_analysis(bundle1_centroids, bundle2_centroids,
threshold)
```
to:
```
ba_value = ba_analysis(recognized_bundle=bundle1_centroids,
expert_bundle=bundle2_centroids,
threshold=threshold)
```
> maintenance of bundle_shape_similarity function

- dipy/denoise/gibbs.py
- dipy/denoise/tests/test_gibbs.py
Added `inplace` kwarg to `gibbs_removal`. Set to `True` by default. The inplace behavior is consistent regardless of the dimensionality of input data. 
Note that I had to modify the original tests by adding `inplace=False` in some cases to keep the original behavior, which assumed 2d inputs always returned a copy.
Closes #2237
> [ENH] Add inplace kwarg to gibbs_removal

- doc/devel/coding_style_guideline.rst
Simple backticks are not rendered in reStructuredText
> [DOC] Replace simple backticks with double backticks

- dipy/tracking/life.py
When the mean-removed relative signal is a nan (this can arise when the b0 is 0), the sensible thing to do is to ignore it, which means setting it to 0.
> BF: In  LiFE, set nan signals to 0.

- dipy/viz/panel.py
This PR fix #2243.
Sometimes, the range value of the first dataset volume is empty/null. This is the case with our isbi2013_3shell dataset. 
So the goal of this fix is to select the volume with a relevant value range for the HORIZON visualization
> [fix] fix value_range in HORIZON

- dipy/denoise/localpca.py
Set tau factor to parameter value in local PCA denoising.
Fixes #2251.
> BUG: Set tau factor to parameter value in local PCA

- dipy/denoise/gibbs.py
- dipy/denoise/tests/test_gibbs.py
- dipy/workflows/denoise.py
- doc/examples/denoise_gibbs.py
Added parallelization to gibbs denoising. I used the utility class `MapWrapper` from scipy for parallelization, which really just a wrapper for `Pool` in `multiprocessing` module with some convenient functionality for dealing with number of workers, etc. Let me know if this is acceptable.
Main thing I changed is how the axis of the input data are ordered within the `gibbs_denoise` function since its much easier to work with the array as an iterable if the axis we are iterating is the first one, not the last one. Some lines had to be changed to accommodate for this change in axis ordering.
Closes #2236
> [ENH] Add parallelization to gibbs denoising

- .travis.yml
- azure-pipelines.yml
- ci/azure/linux.yml
- ci/azure/osx.yml
- ci/azure/windows.yml
- dipy/data/fetcher.py
- dipy/info.py
- requirements.txt
- setup.py
> RF: Replaces our own custom progressbar with a tqdm progressbar.

- dipy/sims/tests/test_voxel.py
- dipy/sims/voxel.py
In this PR, I am adapting the single and multi tensor simulations to run with the gradiant_table btensor when this is not None. 
This PR will be usefull to carry on with the implemenation of techniques based on advanced diffusion sequences - in particular for code testing.
> Make single and multi tensor simulations compatible with btensors

- dipy/align/imaffine.py
- dipy/align/tests/test_imaffine.py
- dipy/utils/deprecator.py
- dipy/utils/tests/test_deprecator.py
- doc/api_changes.rst
The goal is to improve consistency between `AffineMap` and `DiffeomorpicMap`. More information on issue #2192.
To do so, a new decorator has been added: `deprecate_params`.
This PR close #2192.
> [ENH] Deprecate interp parameter name in AffineMap

- dipy/denoise/gibbs.py
This PR makes two changes that give an additional 35% reduction in runtime for me when applied on top of the existing parallel Gibbs PR (#2250).
1.) The first commit uses uncentered frequency coordinates in `k` so that no calls to `fftshift` are required in the inner loops.
2.) The second swaps out `numpy.fft` for `scipy.fft` (or `scipy.fftpack` on older SciPy). The primary benefit of this is that SciPy's FFTs support single precision which ends up being faster when the input is single precision.
> Improve FFT efficiency in gibbs_removal

- doc/examples_index.rst
- doc/reconstruction_models_list.rst
- tools/make_examples.py
The goal of this PR is to fix #1489.
This table should give an overview of all model available in DIPY and some additional information like which model is Multi/ Single shell.
It still needs some work and I will need help @sitek @scott-trinkle @arokem @RafaelNH @ShreyasFadnavis  @Garyfallidis. 
You can not see it but each model link to their tutorial section. 
It would be good to have this in before DIPY 1.0 release.
Thank you.
> [DOC] Add an overview of reconstruction models

- dipy/core/interpolation.pyx
- dipy/tracking/distances.pyx
- dipy/tracking/tests/test_distances.py
This PR fixes #342 (a very old "issue"). This is just adding a warning to the user when `bundles_distances_mdf` or `bundles_distances_mam` do not have 2 tracks with the same number of points.
Also, pep8 and docstring has been updated too.
> [Fix] warning if not the same number of points

- azure-pipelines.yml
- Update the version of our macOS virtual machine. from macOS-10.14 to macOS-latest. This should fix our SSL issue with python
- Remove all Linux matrix on Azure Pipeline. It was experimental. The goal was to see if we can have only one tool to maintain, stop Travis, and switch completely to Azure Pipeline. After this long experimental experience, I think we should keep both, Azure pipeline and Travis. So I just removed the duplicated Linux matrices to speed up a bit the building time of our PR
> [FIX] update Azure OSX CI + remove Azure Linux CI's

- dipy/align/imwarp.py
- dipy/align/tests/test_imwarp.py
This PR fixes #2202. It replaces a cryptic error with an error message when the user tries to get the Diffeormorphic map before running the optimizer.
> [Fix] Better error handling in Diffeomorphic map `get_map`

- dipy/segment/tests/test_clustering.py
- dipy/tracking/tests/test_streamline.py
This PR fixes #2132.  [NEP 34](https://numpy.org/neps/nep-0034-infer-dtype-is-object.html) disallow inferring `dtype=object` from sequences. So the tests have been updated to follow this rule.
> [FIX] update tests to respect numpy NEP 34 

- dipy/workflows/align.py
- dipy/workflows/tests/test_align.py
Fix `dipy_align_syn` default value assumptions: ensure that the `mopt_smooth`,
`mopt_inner_iter` and `mopt_step_type`/`step_type` parameters get appropriate
values for all possible combinations of the optional input arguments.
Fixes:
```
INFO:Starting Diffeomorphic Registration
INFO:Using CC Metric
File "./bin/dipy_align_syn", line 7, in <module>
run_flow(SynRegistrationFlow())
File "/path/to/dipy/dipy/workflows/flow_runner.py", line 89, in run_flow
return flow.run(**args)
File "/path/to/dipy/dipy/workflows/align.py", line 869, in run
mopt_smooth = mopt_smooth or init_param[metric]['mopt_smooth']
KeyError: 'cc'
```
The workflow was failing with the above error when being called with default
parameters, e.g.
```
dipy_align_syn /path/to/data/static.nii.gz …
```
> BF: Fix `dipy_align_syn` default value assumptions

- dipy/io/gradients.py
- dipy/io/tests/test_io_gradients.py
This PR fixes #2046.  Even if in diffusion, it is recommended to have at least 3 directions/volumes, `read_bvals_bvecs` should offer the possibility to load bvals/bvecs files of only 1-2 volume(s).  Now, it is possible with this PR.
bonus: pep8 + some reshaping of the function
> [Fix]  Allow read_bvals_bvecs to have 1 or 2 dwi volumes only

- dipy/reconst/forecast.py
- dipy/reconst/mcsd.py
- dipy/reconst/qtdmri.py
- dipy/reconst/shore.py
- dipy/reconst/tests/test_mcsd.py
- dipy/reconst/tests/test_qtdmri.py
- dipy/reconst/tests/test_shore.py
This PR fixes #2190 and more specifically the following errors/warnings:
```
/home/travis/build/dipy/dipy/venv/lib/python3.5/site-packages/cvxpy/expressions/expression.py:516: UserWarning: 
This use of ``*`` has resulted in matrix multiplication.
Using ``*`` for matrix multiplication has been deprecated since CVXPY 1.1.
Use ``*`` for matrix-scalar and vector-scalar multiplication.
Use ``@`` for matrix-matrix and matrix-vector multiplication.
Use ``multiply`` for elementwise multiplication.
warnings.warn(__STAR_MATMUL_WARNING__, UserWarning)
```
The problem was fixed in the MAPMRI module via #2188 so this PR is just an extension of it.
> [FIX] update multiple models due to cvxpy 1.1 (part2)

- ci/azure/linux.yml
- ci/azure/osx.yml
- ci/azure/windows.yml
This is strange, the default timeout for Azure pipelines should be 6h. However, it is 1h for us.  It seems that we hit this limit with our windows Matrix. So, this PR increases the limit to 2h.  
Let's see if it behaves correctly...
> Increase Azure pipeline timeout

- dipy/reconst/dti.py
- dipy/reconst/tests/test_dti.py
Here is a small modification to `dti.design_matrix`, that enables the used of DTI on btensor data, using the new `gtab.btens` feature. The way to use and call `dti.TensorModel` and `dti.TensorFit` is the same as before. The user just has to create the `GradientTable` with the right `btens` option, and the tensor fit will work as before.
It allows to compute an FA map from a planar acquisition, for example. Unfortunately, the FA map from planar data seems to be extremely sensitive to noise (not in the white matter), but I think this is due to the nature of the data, not the method.
Let me know what you think of it!
> Modifying dti.design_matrix to take gtab.btens into account

- dipy/segment/mrf.pyx
- dipy/segment/tests/test_mrf.py
- dipy/segment/tissue.py
- doc/api_changes.rst
This PR is mainly a style-based refactor of some things in the tissue segmentation code that I had modified some time ago when working on a GPU-based implementation. It will be best to review the various commits in isolation as they tend to address different aspects.
Overall, I don't consider this PR very high priority as there is no new feature or substantial performance impact. Commit 
4a1678d does result in a net decrease in code to maintain, however, as there were two code paths with nearly identical code in each.
The one behavior change here is that in bca8123 I switched to checking the tolerance at every iteration rather than every 10 iterations, so it is possible the loop will might terminate earlier than before if the tolerance is reached at a number of iterations that s not a …
> STYLE: minor refactoring in TissueClassifierHMRF

- dipy/direction/tests/test_peaks.py
- dipy/direction/tests/test_pmf.py
- dipy/reconst/shm.py
- dipy/reconst/tests/test_csdeconv.py
- dipy/reconst/tests/test_mapmri.py
- dipy/reconst/tests/test_mcsd.py
- dipy/reconst/tests/test_shm.py
- dipy/reconst/tests/test_shore_odf.py
- doc/examples/reconst_sh.py
- doc/theory/sh_basis.rst
Update of spherical harmonics and their associated documentation for better agreement with literature as well as MRtrix. This pull request mostly consists of:
1. A new `descoteaux07` basis corresponding exactly to the one from the cited paper, that is without an absolute value for negative values of `m`;
2. A new `tournier07` basis corresponding to the new MRtrix3 definition;
3. New functions `real_sh_descoteaux` and `real_sh_tournier` to replace `real_sym_sh_mrtrix` and `real_sym_sh_basis`. These function allow to chose between the new bases (by default) and the _legacy_ bases. Furthermore, they allow the user to use a full SH basis by setting `is_full_basis=True`;
4. Deprecation warnings for the _legacy_ bases and functions `real_sym_sh_mrtrix` and `real_sym_sh_basis`;
5. Utility …
> NF: Update definitions of SH bases and documentation

- dipy/denoise/gibbs.py
Here is one more efficiency improvement I came across for the Gibbs artifact removal last week.
The FFT only needs to be applied along the axis where the subvoxel shifts are being applied. There is no need to FFT along the orthogonal direction as well. Because of an earlier transpose at https://github.com/dipy/dipy/blob/9c5769912e50e6c7639ada4d928fd0add33cc604/dipy/denoise/gibbs.py#L93, the axis to FFT is always axis 1.
This gives an additional ~25% performance improvement on the example for me.
cc @j1c, @skoudoro and @arokem who were involved with other recent Gibbs PRs.
> Gibbs denoising: fft only along the axis of interest

- dipy/viz/app.py
- dipy/workflows/tests/test_viz.py
- dipy/workflows/viz.py
Added functionality in `dipy_horizon` to show highlighted areas/segments on a bundle where pvalues (negative log of pvalues) are greater than a certain threshold (threshold is a parameter).
Usage:
`dipy_horizon IFOF_L.trk IFOF_L_fa_pvalues_log.npy --buan --buan_thr 2`
`buan_thr 2` for `-log(pvalues)` is equal to `0.01` pvalues.
Resulting visualization looks something like this:
Where, red color indicates -log(pvalues) greater than a buan threshold of 2.
We can also provide `pvalues` instead of `-log(pvalues)`.
`dipy_horizon IFOF_L.trk IFOF_L_fa_pvalues.npy --buan --buan_thr 0.01`
Results will be the same but with inverted colors. 
Now, green is the highlighted area.
> BUAN bundle highlight option in horizon

- dipy/workflows/reconst.py
If no output directory is specified, the results are saved to the current directory, not the input data directory.
> [DOC] Fix incorrect default output directory in doctsrings

- doc/interfaces/buan_flow.rst
- doc/interfaces/bundle_segmentation_flow.rst
- doc/interfaces/denoise_flow.rst
- doc/interfaces/gibbs_unringing_flow.rst
We should stick to named references rather than numbered for consistent citation style.
> [DOC] fix inconsistent citation style

- dipy/workflows/reconst.py
It becomes difficult to maintain default values in docstrings. Default values are mentioned in function parameters.
Similarly, will remove default values from docstrings for the remaining methods
> [DOC] Remove default values from doctstrings for reconstruction methods

- doc/interfaces/denoise_flow.rst
Improve the denoising workflow documentation:
- Move general comments about PCA to the place where it is introduced for the
first time.
- Improve the explanations about the command arguments.
- Fix grammar.
- Use a given line length consistently.
> DOC: Improve the denoising workflow documentation

- dipy/workflows/align.py
Some parameters were inconsistent e.g. static_img_files and static_image_files. They are made consistent to avoid any confusion.
> [DOC]: Fix inconsistent function parameters

- doc/interfaces/gibbs_unringing_flow.rst
Only positive integers can be passed to the num_threads attribute. ``None`` does not work.
> [DOC] Fix the 'None' value in num_threads attribute

- doc/interfaces/buan_flow.rst
Hi,
Sorry, somehow in the last PR (#2278 ), the `native space` got swapped with `common space` in the BUAN interface tutorial explanation.
`The org_bundles folder has extracted bundles in common space. The rec_bundles folder has extracted bundles in native space.`
Fixed this line in this PR.
> BUAN Documentation Typo

- dipy/reconst/mcsd.py
This is a very small PR where I only added some lines to the function `response_from_mask_msmt` from `dipy.reconst.mcsd` in order to keep track of the b-tensor (the attribute `btens` from `gtab`) associated with each bvalue. This allows for the calculation of response functions from different b-tensor encodings. The function `response_from_mask_ssst` did not have to be modified, since it only uses `TensorModel`, which already works with `btens`.
> Allowing response_from_mask_msmt to take btens into account

- dipy/core/tests/test_gradients.py
- dipy/reconst/tests/test_csdeconv.py
- dipy/tracking/tests/test_metrics.py
4 functions were deprecated after release 1.4.0. This is just an update of these deprecated functions.
> [FIX] fix tests for all new deprecated functions

- dipy/direction/pmf.pyx
One-line change here, to avoid raising the deprecation warning on this basis name.
> RF: Replaces deprecated basis by its new name.

- dipy/core/gradients.py
- dipy/core/tests/test_gradients.py
- dipy/reconst/tests/test_csdeconv.py
- dipy/tracking/tests/test_metrics.py
This is PR is to fix #2331. The work done here is:
- replace `logging` by `print`
- add `__str__` function to `GradientTable` class
This PR should be merged after #2332
> Add __str__ to GradientTable

- .gitignore
- dipy/align/tests/test_metrics.py
- dipy/align/tests/test_streamlinear.py
- dipy/core/gradients.py
- dipy/core/interpolation.pyx
- dipy/core/rng.py
- dipy/core/sphere_stats.py
- dipy/denoise/adaptive_soft_matching.py
- dipy/denoise/noise_estimate.py
- dipy/denoise/non_local_means.py
- dipy/denoise/patch2self.py
- dipy/direction/tests/test_peaks.py
- dipy/io/utils.py
- dipy/reconst/recspeed.pyx
- dipy/reconst/shm.py
- dipy/reconst/tests/test_multi_voxel.py
- dipy/reconst/tests/test_reco_utils.py
- dipy/segment/bundles.py
- dipy/segment/clustering.py
- dipy/segment/threshold.py
- dipy/tracking/life.py
- dipy/tracking/streamline.py
- dipy/tracking/tests/test_utils.py
- dipy/tracking/vox2track.pyx
- dipy/workflows/reconst.py
- dipy/workflows/tests/test_align.py
- doc/examples/piesno.py
- doc/examples/reconst_dsi_metrics.py
This PR fixes the following warnings:
```python
DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations …
```
> [FIX] Cleanup deprecated np.float, np.bool, np.int

- doc/examples/denoise_nlmeans.py
This PR fixes #1847. The tutorial of Nlmeans looks as if it is not working because of the data being used. 
This PR replaces the `sherbrooke_3shell` with `stanford_t1 hardi`
> Replacing Data in NLMeans Tutorial

- dipy/align/bundlemin.pyx
- dipy/core/interpolation.pyx
- dipy/reconst/recspeed.pyx
- dipy/tracking/distances.pyx
- dipy/tracking/localtrack.pyx
- dipy/tracking/mesh.py
- dipy/tracking/propspeed.pyx
- dipy/tracking/tests/test_mesh.py
- dipy/tracking/vox2track.pyx
- setup.py
- src/conditional_omp.h
The goal of this PR is to prepare Cython 0.3.x. it fixes the following warnings:
```python
```
```python
In function ‘__Pyx_InitGlobals’:
dipy/tracking/fbcmeasures.c:23988:1: warning: ‘PyEval_InitThreads’ is deprecated [-Wdeprecated-declarations]
PyEval_InitThreads();
```
```python
```
Also, 
- it closes #545 by replacing `cnp.PyArray_DATA` wherever possible 
- it closes #1895
> [MNT]  Update and fix Cython warnings and use cnp.PyArray_DATA wherever possible

- dipy/align/bundlemin.pyx
- dipy/align/crosscorr.pyx
- dipy/align/expectmax.pyx
- dipy/align/sumsqdiff.pyx
- dipy/align/vector_fields.pyx
- dipy/core/interpolation.pyx
- dipy/denoise/nlmeans_block.pyx
- dipy/direction/bootstrap_direction_getter.pyx
- dipy/direction/closest_peak_direction_getter.pyx
- dipy/direction/pmf.pyx
- dipy/direction/probabilistic_direction_getter.pyx
- dipy/reconst/eudx_direction_getter.pyx
- dipy/reconst/recspeed.pyx
- dipy/tracking/direction_getter.pyx
- dipy/tracking/distances.pyx
- dipy/tracking/localtrack.pyx
- dipy/tracking/streamlinespeed.pyx
> [FIX] Use npy_intp variables instead of int and size_t to iterate over numpy arrays

- dipy/stats/analysis.py
- dipy/stats/tests/test_analysis.py
Median can be a useful way to calculate tract profiles.
> [ENH] Allow for other statistics, like median, in afq_profile

- .codecov.yml
- doc/tools/apigen.py
This PR adds `pyx` files in the doc generation. Currently, many functions are not documented in the API because of that. This fixes the problem. I used this opportunity to clean also the documentation
- supersedes and close #1311
- fixes #1302 
- fixes #366
- relax a bit Codecov
> [ENH] Adding cython file(*.pyx) in documentation

- dipy/direction/closest_peak_direction_getter.pyx
- dipy/direction/tests/test_bootstrap_direction_getter.py
- dipy/reconst/csdeconv.py
- dipy/reconst/forecast.py
- dipy/reconst/mapmri.py
- dipy/reconst/mcsd.py
- dipy/reconst/qtdmri.py
- dipy/reconst/shm.py
- dipy/reconst/shore.py
- dipy/reconst/tests/test_csdeconv.py
- dipy/reconst/tests/test_mcsd.py
- dipy/reconst/tests/test_shm.py
This shouid eliminate warnings that now routinely appear
> RF: Use new name for this function.

- dipy/denoise/patch2self.py
- dipy/denoise/tests/test_patch2self.py
if patch radius is an int, it needs to be expanded to (1,3) array before calling _extract_3d_patches.
> Expand patch radius if input is int

- dipy/align/bundlemin.pyx
- dipy/align/crosscorr.pyx
- dipy/align/reslice.py
- dipy/align/streamlinear.py
- dipy/align/tests/test_reslice.py
- dipy/align/tests/test_streamlinear.py
- dipy/denoise/denspeed.pyx
- dipy/denoise/gibbs.py
- dipy/denoise/nlmeans.py
- dipy/denoise/shift_twist_convolution.pyx
- dipy/denoise/tests/test_gibbs.py
- dipy/denoise/tests/test_nlmeans.py
- dipy/direction/peaks.py
- dipy/direction/tests/test_peaks.py
- dipy/reconst/csdeconv.py
- dipy/segment/bundles.py
- dipy/segment/tests/test_bundles.py
- dipy/tracking/fbcmeasures.pyx
- dipy/utils/multiproc.py
- dipy/utils/omp.pyx
- dipy/utils/tests/test_multiproc.py
- dipy/utils/tests/test_omp.py
- dipy/workflows/align.py
- dipy/workflows/denoise.py
- dipy/workflows/reconst.py
- doc/api_changes.rst
- doc/examples/denoise_gibbs.py
- doc/interfaces/gibbs_unringing_flow.rst
Related to #2300 and a continuation of #2341.
- Configure  ``num_threads<=0`` as the option to use all cores across the codebase
- Modify the name of the argument ``num_proceses --> num_threads`` in **reslice.py** and **test_reslice.py**
- Delete the ``num_threads`` argument where it is not used
Unlike in #2341, most of the functions edited here used all cores by default (using ``None``) so, to keep this behavior, I set the new default to ``0``.  This implies that:
1. The number of used cores by default differs between functions. Does it make sense to use all cores by default in some functions and only ``1`` in others?
2. This PR modifies the default value of ``num_threads`` in several functions, which was one of the main concerns discussed in #2300. What do you think …
> RF: configure num_threads==-1 as the value to use all cores

- dipy/workflows/base.py
- dipy/workflows/segment.py
- dipy/workflows/tests/test_iap.py
- dipy/workflows/tests/workflow_tests_utils.py
This PR fix #2300. It allows `None` value as a parameter of a Worflow.  An example below to change the default value of `num_threads` from `1` to `None`:
`dipy_gibbs_ringing ~/.dipy/tissue_data/t1_brain_denoised.nii.gz --num_threads None  --out_dir "gibbs_ringing_output"`
> [Fix] Add "None" options in the CLIs

- README.rst
- dipy/core/geometry.py
- dipy/core/tests/test_geometry.py
``vec2vec_rotmat`` function can provide incorrect results when the dot product of the input vectors is slightly a bit beyond one. This is happening when both vectors (u, v) are close to collinear. Or at least this is what I currently observe. I found this problem when I used this function for a FURY application. In both bellow examples, I used ``vec2vec_rotmat`` function to rotate the arrows. In these examples, one arrow that is rotating around the center (0,0,0) is the leader and the other arrow is follower. 
Here in  ``vec2vec_rotmat`` function, using ``cosa = np.dot(u, v)`` . Notice that at some point the follower vector (purple) is flipping which is not correct.
Here in  ``vec2vec_rotmat`` function, ``cosa = np.clip(np.dot(u, v), -1, 1)``. The follower vector does not flip anymore.
> Updating Vec2vec_rotmat to deal with numerical issues

- doc/examples/bundle_extraction.py
Hi,
I removed CST_L bundle from Bundle Segmentation in my previous PR. Extracted CST_L is needed for the AFQ tutorial. So adding it back.
> Adding CST_L back in Bundle Segmentation Tutorial

- dipy/core/gradients.py
- dipy/core/tests/test_gradients.py
Is there a reason why a 3x3 matrix is assumed to be a rotation-only matrix, but not the 4x4 matrix?
Adding polar decomposition also when the matrix is present in 3x3 form.
> Add decomposition

- dipy/tracking/tests/test_streamline.py
The CI's are failing regularly due to the `test_deform_streamlines()` function. 
The reason: I suppose the random affine is sometimes irrealistic
So I converted the test to a deterministic one.
> from random to deterministic test for deform_streamlines

- dipy/direction/closest_peak_direction_getter.pyx
- dipy/direction/pmf.pxd
- dipy/direction/pmf.pyx
- dipy/direction/probabilistic_direction_getter.pyx
- dipy/direction/tests/test_bootstrap_direction_getter.py
- dipy/direction/tests/test_pmf.py
- doc/api_changes.rst
This PR adds a utility function to the `SHCoeffPmfGen` object. 
- It adds the function `get_pmf_val(point, xyz)`, which return the pmf (ODF/FOD) value at the position `point` and orientation `xyz`. 
- The closest vertex of the sphere is used to approximate the value at `xyz`.
In the current implementation, the pmf is computed for all vertices, to return the value for one vertex. This could be further optimized. 
@guaje @skoudoro For the PTT implementation, I think we need to move this function to the parent class `PmfGen`. but it doesn't work with child `class SimplePmfGen(PmfGen)`, since this class doesn't have a sphere object. I think there is a bit of a design flaw, and simply moving/requiring the sphere for `PmfGen` (as for `SHCoeffPmfGen`) might solve this. I can add this commit to …
> NF - Sample PMF for an input position and direction

- dipy/direction/pmf.pyx
Prefer using a typed index to get the PMF value from the direction.
Fixes:
```
warning: dipy/direction/pmf.pyx:31:59: Index should be typed for more efficient access
```
Raised for example in
https://dev.azure.com/dipy/dipy/_build/results?buildId=1196&view=logs&j=d9aefae6-c332-51b5-d933-a85009f5a2ac&t=7b3c05b2-26bc-5cc7-178d-37c39b6402cb&l=1670
> OPT: Prefer using a typed index to get the PMF value

- dipy/tracking/streamlinespeed.pyx
- dipy/tracking/tests/test_streamline.py
This PR is to fix issue #1805.
The code is removing some points if they are consecutive and identical like [(0,1), (0,1), (0,20)]
However, If you have the following 2D streamline [(0,1), (0,20), (0,1)], we keep it as it is.
You can check the tests for more examples.
It would be good if @jchoude or @MarcCote  could review this PR since it addresses your discussion.
Thank you
> [FIX] `c_compress_streamline` discard identical points

- dipy/tracking/distances.pyx
- dipy/tracking/tests/test_distances.py
This PR should fix #2314. 
It just avoids the division by zero when 2 consecutive repeated points appeared.
It should solve your problem @dulietina, can you test it? 
Thank you
> Manage Approx_polygon_track with repeated points

- dipy/segment/featurespeed.pyx
Initialize `Shape` struct from provided data.
Fixes:
```
building 'dipy.segment.featurespeed' extension
x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION -Isrc -I/home/local/USHERBROOKE/legj1809/.virtualenvs/dipy/lib/python3.8/site-packages/numpy/core/include -Ibuild -I/home/local/USHERBROOKE/legj1809/.virtualenvs/dipy/include -I/usr/include/python3.8 -c dipy/segment/featurespeed.c -o build/temp.linux-x86_64-3.8/dipy/segment/featurespeed.o -msse2 -mfpmath=sse -fopenmp
dipy/segment/featurespeed.c: In function …
```
> OPT: Initialize `Shape` struct

- dipy/align/__init__.py
- dipy/align/_public.py
- dipy/align/tests/test_api.py
- dipy/workflows/align.py
- dipy/workflows/tests/test_align.py
- doc/examples/affine_registration_3d.py
Part of #2276 
- Add RigidIsoScaling and RigidScaling options to the align workflow
- Update corresponding tests
By the way, I've noticed that the registration parameters defined [here](https://github.com/dipy/dipy/pull/2390/files#diff-b6bf9b9a51f8dfc421e3896b6ea103012d81d9eae8b07e252e0f5a66a220f42fL204) are not used as the [setup_random_transform ](https://github.com/dipy/dipy/blob/master/dipy/align/tests/test_parzenhist.py#L259)function calculates them randomly.
> NF: extend the align workflow with Rigid+IsoScaling and Rigid+Scaling

- dipy/denoise/patch2self.py
Because of the comma, `"give denoising performance."` gets passed as a second argument  to the `warn()` function, causing this error:
```python
File "/home/joshua/repos/spinalcordtoolbox/testing/cli/test_cli_sct_dmri_denoise_patch2self.py", line 12, in test_sct_denoising_onlm_no_checks
'-b', 'sct_testing_data/dmri/bvals.txt', '-v', '2'])
File "/home/joshua/repos/spinalcordtoolbox/spinalcordtoolbox/scripts/sct_denoise_patch2self.py", line 121, in main
verbose=True)
File "/home/joshua/repos/spinalcordtoolbox/python/envs/venv_sct/lib/python3.6/site-packages/dipy/denoise/patch2self.py", line 248, in patch2self
"give denoising performance.")
TypeError: category must be a Warning subclass, not 'str'
```
(Since this is such a small fix, I skipped creating an …
> BUG: Fix misplaced comma in `warn()` call from `patch2self.py`

- dipy/reconst/tests/test_dki_micro.py
Should fix [this error](https://dev.azure.com/dipy/dipy/_build/results?buildId=1238&view=logs&jobId=c4497b2b-649a-591e-539b-0d716883e33e&j=c4497b2b-649a-591e-539b-0d716883e33e&t=315e67fb-8bac-5822-ff35-e6ec3c18835a) that popped up in #2434:
```
wmtiM = dki_micro.KurtosisMicrostructureModel(gtab_2s, fit_method="WLS")
wmtiF = wmtiM.fit(signal)
>       assert_almost_equal(wmtiF.awf, AWF)
E       AssertionError: 
E       Arrays are not almost equal to 7 decimals
E       
E       Mismatched elements: 1 / 1 (100%)
E       Max absolute difference: 1.7266712437624676e-07
E       Max relative difference: 3.5238188646389464e-07
E        x: array(0.48999982735824127)
E        y: array(0.49000000002536565)
```
> MAINT: Bump tolerance

- dipy/align/__init__.py
- dipy/align/_public.py
- dipy/align/tests/test_api.py
Prior to #2390 code like this worked:
```
from dipy.align import (affine_registration, center_of_mass,
translation, rigid, affine, resample,
imwarp, metrics)
moving_zoomed, reg_affine = affine_registration(
moving_zoomed, static_zoomed, moving_affine, static_affine,
nbins=32, metric='MI', pipeline=[center_of_mass, translation],
level_iters=niter[step], sigmas=sigmas, factors=factors)
```
But due to #2390 moving `pipeline` from `list of callable` to `list of str` arguments, this now raises:
```
../../.local/lib/python3.10/site-packages/dipy/align/_public.py:475: in affine_registration
raise ValueError("Not supported registration method")
E   ValueError: Not supported registration method
```
I saw two ways out:
1. Allow any `callable` and refactor a bunch of code (probably difficult, doubt …
> BUG: Backward compat support for pipeline

- dipy/io/bvectxt.py
- dipy/io/tests/test_bvectxt.py
The module `dipy.io.bvectxt` is not used in the DIPY codebase. Furthermore, it seems that some functions contain mistakes like `read_bvec_file`, other functions have been duplicated in `dipy.io.gradients` like `reorient_vectors`.
fix #2460
> deprecate dipy.io.bvectxt module

- dipy/workflows/reconst.py
This PR should fix #2463.  RESTORE is available as a fitting method for DTI; however, CLI support is absent. So this PR goal is to provide RESTORE and other fitting method options.
> [ENH] Add fit_method option in DTI and DKI CLI

- azure-pipelines.yml
We are currently using `vs2017-win2016` Image on our Azure pipeline. However, The windows-2016 environment will be deprecated on November 15, 2021, and removed on March 15, 2022. 
So, we Migrate to windows-latest instead (which uses vs2019).
For more details see https://github.com/actions/virtual-environments/issues/4312
> [MNT] Use windows-latest on azure pipeline

- dipy/data/fetcher.py
- dipy/reconst/tests/test_dti.py
Fix `dipy.io.bvectxt` deprecation warning: prefer using the
`dipy.io.gradients` module to read b-val and b-vec files.
Fixes:
```
reconst/tests/test_dti.py::test_tensor_model
/usr/share/miniconda/envs/venv/lib/python3.7/site-packages/dipy/reconst/tests/test_dti.py:100:
DeprecationWarning: dipy.io.bvectxt module is deprecated, Please use dipy.core.gradients module instead
```
and related warnings.
Reported, for example, at:
https://dev.azure.com/dipy/dipy/_build/results?buildId=1329&view=logs&j=81eb4d60-76fc-5ac4-a959-9ebb9871bfee&t=0be92317-04dc-59eb-8af8-1d8747db115d&l=5303
Add the `55dir_grad` dataset name to return both the b-val and the b-vec
filenames. Remove the no longer necessary `55dir_grad.bvec` dataset
name.
> ENH: Fix `dipy.io.bvectxt` deprecation warning

- dipy/reconst/mapmri.py
Fix `complex` type `NumPy` alias deprecation warnings.
`NumPy` aliases for built-in types are deprecated since release `1.20.0`:
https://numpy.org/doc/stable/release/1.20.0-notes.html#deprecations
Fixes:
```
DeprecationWarning: `np.complex` is a deprecated alias for the builtin `complex`.
To silence this warning, use `complex` by itself.
Doing this will not modify any behavior and is safe.
If you specifically wanted the numpy scalar type, use `np.complex128` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
```
Consistently reported across CI builds using recent `NumPy` versions, e.g.:
https://dev.azure.com/dipy/dipy/_build/results?buildId=1329&view=logs&j=81eb4d60-76fc-5ac4-a959-9ebb9871bfee&t=0be92317-04dc-59eb …
> ENH: Fix `complex` type `NumPy` alias deprecation warnings

- dipy/core/gradients.py
- dipy/reconst/shm.py
- dipy/reconst/tests/test_ivim.py
- dipy/reconst/tests/test_mcsd.py
- dipy/reconst/tests/test_shm.py
- ENH: Appropriately deal with user warnings in tests
- STYLE: Improve the warning message style
- DOC: Fix method name typo in deprecation warning
> ENH: Deal appropriately with user warnings

- dipy/denoise/patch2self.py
- dipy/denoise/tests/test_patch2self.py
- dipy/reconst/sfm.py
- dipy/reconst/tests/test_sfm.py
- dipy/workflows/tests/test_denoise.py
Make `sklearn` import warning messages consistent.
Allows to show:
```
UserWarning: We need package sklearn for these functions, but ``import sklearn`` raised an ImportError
warn(sklearn._msg)
```
and
```
UserWarning: We need package sklearn for these functions, but ``import sklearn`` raised an ImportError
Alternatively, you can use 'nnls' method to fit the SparseFascicleModel
```
instead of
```
UserWarning: Scikit-Learn is required to denoise the data via Patch2Self.
```
and
```
UserWarning: sklearn is not available, you can use 'nnls' method to fit the SparseFascicleModel
```
and
```
"Requires Scikit-Learn"
```
> STYLE: Make `sklearn` import warning messages consistent

- dipy/align/_public.py
Import ABCs from `collections.abc` instead of from `collections`.
Fixes:
```
align/tests/test_api.py::test_register_dwi_series
/home/vsts/work/1/s/venv/lib/python3.8/site-packages/dipy/align/_public.py:639:
DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.10 it will stop working
if isinstance(gtab, collections.Sequence):
```
being raised consistently, for example, at:
https://dev.azure.com/dipy/dipy/_build/results?buildId=1351&view=logs&j=d9aefae6-c332-51b5-d933-a85009f5a2ac&t=7b3c05b2-26bc-5cc7-178d-37c39b6402cb&l=5184
From the documentation:
```
New in version 3.3: Formerly, this module was part of the collections module.
```
https://docs.python.org/3/library/collections.abc.html
DIPY does not …
> ENH: Import ABCs from `collections.abc`

- bin/dipy_correct_motion
- dipy/align/__init__.py
- dipy/align/_public.py
- dipy/align/tests/test_api.py
- dipy/workflows/align.py
- dipy/workflows/tests/test_align.py
- doc/examples/motion_correction.py
- doc/examples/valid_examples.txt
- doc/interfaces/index.rst
- doc/interfaces/motion_flow.rst
This PR just adds explicitly a new function named `motion_correction` (Between-Volumes Motion correction). It also adds the associated workflow.  This function has been requested many times since the last Workshop.
To use it, you just to do the following import: `from dipy.align import motion_correction`
Todo:
------
> [NF] Add Motion correction workflow

- dipy/align/metrics.py
Just a minor update to improve the error message.
Also, are the units of `radius` and `sigma_diff` for CCMetric in voxels (I assume it's this), or mm (i.e., the image's `affine` dims will be factored in to compute the number of voxels)?
> ENH: Better error message

- dipy/reconst/sfm.py
- dipy/reconst/tests/test_sfm.py
This is a reboot of PR #2488, with fresh commit history + rebased with master (i.e. no more missing utils/multiproc.py file), and a fix on the test per @skoudoro 's request. 
@arokem -- I discovered that when fitting the solver in parallel, the `warm_start` feature was causing numerical divergence. Intuitively, this makes sense because fitting solvers in an embarrassingly parallel manner precludes the possibility of sequentially drawing upon the previous fit estimates for initialization. After disabling, this is no longer an issue, and the results are identical with joblib (when specifying any number of n_procs). And frankly, I propose keeping it disabled in this context anyway because as sklearn notes in their docs: "repeatedly calling an sklearn estimator fit when `warm_start=True` can …
> Optimize sfm (reboot)

- dipy/tracking/tests/test_utils.py
- dipy/tracking/utils.py
Per [the discussion on the issue thread](https://github.com/dipy/dipy/issues/2509), I went ahead and cleaned up [the test_utils section where I had created a test for null streamlines](https://github.com/DanNBullock/dipy/blob/01df7ba4042c90f1d7dc3eedac55bb598c21bb31/dipy/tracking/tests/test_utils.py#L357-L371).  It's slightly inelegant, in that I have to append a non-null streamline to the front in order to bypass issues with near_roi and tol/dtc computations, but it works as implemented.
The [streamline_near_roi change itself](https://github.com/DanNBullock/dipy/blob/01df7ba4042c90f1d7dc3eedac55bb598c21bb31/dipy/tracking/utils.py#L706-L707) appears to be effective and well behaved.
Let me know if additional adjustments are suggested/required.
> Default to False output for null streamlines in streamline_near_roi

- README.rst
Use GitHub action status badge in README. Remove the legacy CI services
badges.
> DOC: Use GitHub actions status badge in README

- dipy/denoise/tests/test_kernel.py
- dipy/direction/peaks.py
- dipy/direction/tests/test_pmf.py
- dipy/reconst/forecast.py
- dipy/reconst/mapmri.py
- dipy/reconst/qtdmri.py
- dipy/reconst/tests/test_cross_validation.py
- dipy/reconst/tests/test_csdeconv.py
- dipy/reconst/tests/test_shore_metrics.py
- DOC: Document missing parameters
- ENH: Remove unused import statement
- ENH: Remove unused local variables
- ENH: Remove unused method parameter
- STYLE: Remove redundant parentheses
- STYLE: Simplify chained comparisons
- DOC: Fix spelling mistakes
> ENH: Miscellaneous cleanup

- dipy/reconst/tests/test_rumba.py
Fix intermittent RUMBA test check failure: allow comparing with
tolerance.
Fixes:
```
>       assert_array_equal(kernel, kernel_multi)
E       AssertionError:
E       Arrays are not equal
E
E       (mismatch 12.812333297770195%)
E        x: array([  1.000000e+00,   1.000000e+00,   1.000000e+00, ...,   1.404835e-05,
E                7.939220e-01,   9.261458e-16])
E        y: array([  1.000000e+00,   1.000000e+00,   1.000000e+00, ...,   1.404835e-05,
E                7.939220e-01,   9.261458e-16])
../venv/lib/python3.7/site-packages/dipy/reconst/tests/test_rumba.py:388: AssertionError
```
https://github.com/dipy/dipy/runs/5259123098?check_suite_focus=true#step:9:3318
> TEST: Fix intermittent RUMBA test check failure

- dipy/align/tests/test_crosscorr.py
- dipy/align/tests/test_expectmax.py
- dipy/align/tests/test_metrics.py
- dipy/align/tests/test_sumsqdiff.py
- dipy/align/tests/test_transforms.py
- dipy/core/tests/test_rng.py
- dipy/nn/tests/test_tf.py
- dipy/sims/tests/test_voxel.py
- dipy/testing/tests/test_testing.py
- dipy/tracking/tests/test_fbc.py
- dipy/viz/tests/test_apps.py
- dipy/workflows/tests/test_denoise.py
- dipy/workflows/tests/test_iap.py
- dipy/workflows/tests/test_io.py
- dipy/workflows/tests/test_masking.py
- dipy/workflows/tests/test_reconst_csa_csd.py
- dipy/workflows/tests/test_reconst_dki.py
- dipy/workflows/tests/test_reconst_dti.py
- dipy/workflows/tests/test_reconst_ivim.py
- dipy/workflows/tests/test_reconst_mapmri.py
- dipy/workflows/tests/test_tracking.py
- dipy/workflows/tests/test_viz.py
- dipy/workflows/tests/test_workflow.py
Remove unnecessary `main` method definition in tests: `pytest` collects
any method having the `test` prefix, so for all practical purposes the
`main` method was being disregarded.
> TEST: Remove unnecessary `main` method definition in tests

- dipy/denoise/tests/test_kernel.py
- dipy/direction/tests/test_bootstrap_direction_getter.py
- dipy/direction/tests/test_peaks.py
- dipy/direction/tests/test_pmf.py
- dipy/reconst/forecast.py
- dipy/reconst/shore.py
- dipy/reconst/tests/test_cross_validation.py
- dipy/reconst/tests/test_csdeconv.py
- dipy/reconst/tests/test_eudx_dg.py
- dipy/reconst/tests/test_forecast.py
- dipy/reconst/tests/test_mapmri.py
- dipy/reconst/tests/test_mcsd.py
- dipy/reconst/tests/test_qtdmri.py
- dipy/reconst/tests/test_rumba.py
- dipy/reconst/tests/test_shore.py
- dipy/reconst/tests/test_shore_metrics.py
- dipy/reconst/tests/test_shore_odf.py
- dipy/tracking/tests/test_tracking.py
- dipy/viz/tests/test_fury.py
- dipy/workflows/tests/test_reconst_csa_csd.py
- dipy/workflows/tests/test_tracking.py
Filter legacy SH bases warnings in tests. Warnings are already being
tested, and there is no further need to ensure that these warnings are
raised.
Filtering them avoids having them printed in the standard output, and
thus, unnecessary clutter.
Fixes:
```
workflows/tests/test_tracking.py: 16 warnings
dipy/venv/lib/python3.8/site-packages/dipy/reconst/shm.py:346:
PendingDeprecationWarning:
The legacy descoteaux07 SH basis uses absolute values for negative harmonic degrees.
It is outdated and will be deprecated in a future DIPY release.
Consider using the new descoteaux07 basis by setting the `legacy` parameter to `False`.
warn(descoteaux07_legacy_msg, category=PendingDeprecationWarning)
```
and
```
direction/tests/test_peaks.py::test_peaks_shm_coeff …
```
> TEST: Filter legacy SH bases warnings in tests

- dipy/align/_public.py
- dipy/align/imaffine.py
- dipy/align/scalespace.py
- dipy/align/tests/test_imaffine.py
- doc/examples/affine_registration_masks.py
- doc/examples/valid_examples.txt
- doc/examples_index.rst
Implementation of masking for affine registration. It is possible to use a static_mask and moving_mask, and to use the pipeline interface. A new example is included.
See #2508, #2179, and #1969 for related discussions and requests. This implementation finished and expanded the implementation referenced in #2179.
> Masking for affine registration

- dipy/workflows/tests/test_iap.py
- dipy/workflows/tests/workflow_tests_utils.py
- dipy/workflows/viz.py
This PR fixes #2429 and restores the `--random_colors` functionality introduced in #2374.
Additionally, a new test is included for cases when optional strings have different configurations.
> Random colors fix in horizon

- dipy/info.py
- requirements.txt
A small update of our minimal dependencies version:
```python
cython>=0.29.24
numpy>=1.14.5
scipy>=1.1
nibabel>=3.0.0
h5py>=2.8.0
packaging>=19.0
tqdm>=4.30.0
```
fixes #2477
> [MNT] Update mininal dependencies version

- doc/examples/reconst_sh.py
This PR fixes #2546. 
To clarify the tutorial, It removes the `gradients_spheres`tutorial dependency.
> [ENH] Clarify reconst_sh tutorial

- dipy/segment/metric.py
- doc/examples/reconst_sfm.py
- doc/examples/segment_clustering_features.py
- doc/examples/segment_clustering_metrics.py
- doc/examples/segment_extending_clustering_framework.py
- doc/examples/valid_examples.txt
- doc/examples_index.rst
This PR fixes some tutorials from `dipy.segment`. Most of them were failing due to some previous code refactoring. 
I also use the opportunity to rename `sfm_reconst` to `reconst_sfm` in order to respect the current convention.
> [FIX] Update `dipy.segment` tutorials

- dipy/info.py
Just a tiny tweak to become PEP440 compatible and avoid warnings like the following when installing:
``
/home/larsoner/.local/lib/python3.10/site-packages/setuptools/dist.py:505: UserWarning: Normalizing '1.5.0dev' to '1.5.0.dev0'
```
> MAINT: Fix version

- dipy/align/_public.py
Over in MNE-Python we are getting warnigs (that our test suite [turns into errors](https://github.com/mne-tools/mne-python/runs/5470293960?check_suite_focus=true)) of the form:
```
mne/transforms.py:1724: in _compute_volume_registration
moved_zoomed, reg_affine = affine_registration(
/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/dipy/align/_public.py:491: in affine_registration
warn(wm, UserWarning)
E   UserWarning: starting_affine overwritten by centre_of_mass transform
```
This is true even though our call passes `starting_affine=None`.
I think this is due to #2512. Not 100% sure this is the right fix, but it seems reasonable. `_handle_pipeline_inputs` returns `np.eye(4)` for `starting_affine`, and it seems more invasive to make that return `None` (which would also …
> BUG: Fix errant warning about starting_affine

- .mailmap
- Changelog
- LICENSE
- doc/api_changes.rst
- doc/conf.py
- doc/index.rst
- doc/old_highlights.rst
- doc/old_news.rst
- doc/reconstruction_models_list.rst
- doc/release_notes/release1.5.rst
- doc/stateoftheart.rst
Preparation for 1.5.0 release, targeting ~~November 7th-8th~~  March 1st. 
There is room for the following PR to be finished and merge
> [Upcoming] Release 1.5.0 

- dipy/reconst/csdeconv.py
- dipy/reconst/rumba.py
- doc/examples/reconst_rumba.py
- DOC: Fix typos
- DOC: Remove non-breaking spaces
- DOC: Fix code block formatting
- DOC: Remove nonexistent parameters from docstring 
- DOC: Use triple double-quoted strings in docstrings
> DOC: Documentation fixes

- dipy/io/stateful_tractogram.py
I don't know what happens, I think I accidentally swap lines.
As of right now, this forces the logging to be the default when importing dipy.io.stateful_tractogram (rather than the SFT logger specifically)
And users cannot reset it using the classic `logging.basicConfig(level=logging.INFO)`, but they could if using `logging.getLogger().setLevel(logging.INFO)`.
Anyway, this is fixed now.
> Fix logger in SFT

- dipy/tracking/streamline.py
- dipy/tracking/tests/test_streamline.py
Keep the same dtype when using transform_streamlines (with array_sequence)
This problem was identified when saving VTK files, it was always double precision.
> transform_streamlines changes dtype to float64

- dipy/denoise/localpca.py
- dipy/denoise/pca_noise_estimate.pyx
- dipy/denoise/tests/test_lpca.py
Generalizes PCA to work when some spatial dimensions have size 1 (i.e. the data array is 4D, but the data is really 3D -- two spatial dimensions * number of acquisitions). 
I have compared the results from this code with the results obtained by padding 3D data with repeated copies of the dimension of size 1, in this case the third dimension:
```
tmp_1 = np.expand_dims(data, 2)[:, :, [0, 0, 0, 0, 0, 0, 0], :]
sigma_1 = pca_noise_estimate(tmp_1, gtab, patch_radius=3, correct_bias=True, smooth=3)
tmp_2 = np.expand_dims(data, 2)
sigma_2 = pca_noise_estimate(tmp_2, gtab, patch_radius=3, correct_bias=True, smooth=3)
denoised_arr_1 = localpca(tmp_1, sigma_1, tau_factor=2.3, patch_radius=3)
denoised_arr_1 = denoised_arr_1[:, :, 3, :]
denoised_arr_2 = localpca(tmp_2, sigma_2, tau_factor=2.3, …
```
> Generalized PCA to less than 3 spatial dims

- .github/workflows/test_compat.yml
- .github/workflows/test_template.yml
- dipy/info.py
- requirements.txt
We currently have an issue with cython 0.29.29 described in the issue https://github.com/dipy/dipy/issues/2594.
To avoid blocking some PRs, this PR skips this Cython version (0.29.29) until we solve our issue.
> Temporary skip Cython 0.29.29 

- dipy/io/streamline.py
- dipy/io/tests/test_streamline.py
This PR fixes #2572. It allows users to save streamlines as VTP
> [FIX ] Handle save VTP

- doc/devel/index.rst
- doc/documentation.rst
this PR fixes #2564. For now, we disable the search index on our documentation since this functionality is not working with our Django framework. This is something we will have to bring it back when we decide to switch back to a classic static website.
> [DOC] Remove search index

- dipy/workflows/denoise.py
- doc/interfaces/denoise_flow.rst
This PR fixes #2559. It allows providing only one value when we call CLI DIPY denoise methods.  Before this PR, it was generating a `ValueError`. You could also provide 3 values.
It is interesting to see our documentation [here](https://dipy.org/documentation/1.4.1./interfaces/denoise_flow/#denoising-using-marcenko-pastur-pca) was not working as expected.
> [FIX] Allow patch size parameter to be an int on denoise Workflow

- dipy/align/imwarp.py
- dipy/align/tests/test_imwarp.py
- dipy/align/vector_fields.pyx
- dipy/tracking/streamline.py
- doc/examples/streamline_registration.py
This PR is just a follow-up and close #936. Many people ask for this feature and we never merged it. 
it adds 2 functions to apply warp fields on point: `transform_points` and `transform_points_inverse`.  After registering two images, you can use this function to transform your streamlines/points. 
You might be interested @vigji @wjy73 @dPys. Feel free to test this PR and give feedback/review. Thanks in advance!
fixes #2327
fixes #2313
TODO
------
> Transform points with DiffeormorphicMap

- dipy/workflows/reconst.py
Fix DTI fit CLI docstring: document the `ReconstDtiFlow:run` arguments following the sorting in the method prototype.
Resolves #2662.
> DOC: Fix DTI fit CLI docstring

- dipy/denoise/patch2self.py
Remove inaccurate `patch2self` docstring default values: rely on the default values in the method prototype for documentation.
> DOC: Remove inaccurate `patch2self` docstring default values

- dipy/workflows/denoise.py
- dipy/workflows/multi_io.py
- DOC: Fix parameter name in docstring
- DOC: Mark optional parameters as such in docstring
- DOC: Add parameter description to docstring
> DOC: Miscellaneous docstring fixes

- dipy/reconst/dti.py
- doc/examples/reconst_dti.py
- doc/interfaces/reconstruction_flow.rst
This should fix issue https://github.com/dipy/dipy/issues/2673
Adding the information on the order of the tensor values in a few places in both doc and docstrings.
> Improve doc (tensor values' order)

- dipy/workflows/reconst.py
Make the DTI fit CLI metric saving message accurate: print the actual output filenames of the metrics that are saved.
Previously, only the dirname of the eigen values was being printed (if it existed), printing the default saving directory name otherwise. However, if the metrics' output filenames were specified using the `--out_*` output optional arguments, the above message would result inaccurate/misleading.
> ENH: Make the DTI fit CLI metric saving message accurate

- dipy/workflows/reconst.py
Remove unnecessary b-value threshold/min value print in CSD reconstruction flow.
> STYLE: Remove unnecessary b-val print in CSD reconstruction flow

- .github/workflows/test_template.yml
Fix `Node.js` warnings linked to GitHub actions: transition to `actions/checkout@v3` and `actions/setup-python@v3`.
Fixes:
```
pip / build (3.8, ubuntu-latest, pip)
Node.js 12 actions are deprecated.
For more information see:
https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
Please update the following actions to use Node.js 16:
actions/checkout@v2, actions/setup-python@v2
```
https://github.com/dipy/dipy/actions/runs/3665144550
> TEST: Fix `Node.js` warnings linked to GitHub actions

- dipy/reconst/tests/test_rumba.py
Improve multi-shell RUMBA test WM response parameterization: avoid hard-coding the multi-shell eigenvalue count, and compute it from the gradient table b-values.
> RF: Improve multi-shell RUMBA test WM response parameterization

- dipy/workflows/tests/test_iap.py
Since the last release of Numpy,  array with different type inside should be define as object. e.g ` np.array([1, "test"], dtype=object)`.
> [FIX] incompatible type in numpy array

- dipy/reconst/dti.py
- dipy/reconst/tests/test_dti.py
I have adjusted the function `restore_fit_tensor` to be able to accept a spatially varying sigma, rather than only a sigma that varies for each image (or a constant sigma). In this way, the noise estimate from functions such as `pca_noise_estimate` can be used (I have not allowed to have a sigma that varies across both space and image, because I can't see the use case for this).
I have left notes in this file, with questions and thoughts, because I have made a few other adjustments (some of which could be applied to `nlls_fit_tensor` as well).
Very much a work in progress, but fundamentally the changes are fairly simple. I just need some feedback.
edit: also addresses #2574 for RESTORE
> RESTORE can use spatially varying sigma

- dipy/reconst/dti.py
- dipy/reconst/tests/test_dti.py
When using NLLS or RESTORE, there was a bug with using a mask if wanting to return S0. This wasn't caught because the tests did not cover non-linear fitting when using both masks and S0.
> fixed bug for non-linear fitting with masks

- dipy/utils/fast_numpy.pxd
- dipy/utils/fast_numpy.pyx
- dipy/utils/tests/test_fast_numpy.py
Utility functions for PTT tracking PR #2596.
Is there a good way to add unit tests on these?
> NF - Added cython utility functions 

- dipy/denoise/localpca.py
- dipy/denoise/pca_noise_estimate.pyx
- dipy/denoise/tests/test_lpca.py
- dipy/denoise/tests/test_noise_estimate.py
- doc/api_changes.rst
Following on from https://github.com/dipy/dipy/discussions/2678 I have attempted to do several things:
1. fix `genpca` to work when the number of samples (voxels) is less than the number of features (images) by modifying `_pca_classifier`
2. fix `pca_noise_estimate` to be able to use the canonical algorithm
This is a new pull request to replace #2707 which became totally corrupted for reasons I don't understand, and I simply could not fix. Sorry about that. But I addressed all comments left at the time.
> fixed pca for features > samples, and fixed pca_noise_estimate

- dipy/direction/peaks.py
- dipy/direction/tests/test_peaks.py
- dipy/reconst/recspeed.pyx
Hello,
Add a `is_symmetric` flag to `dipy.direction.peaks.peak_directions` to enable peak extraction on asymmetric ODFs. `is_symmetric` is `True` by default, so that the default behaviour does not change. When set to `False`, the sphere directions `v` and `-v` are considered distinct, such that it is possible to find a maxima along `v` but not along `-v`. 
I simply removed the absolute value in `remove_similar_vertices` so that opposite sphere directions are not considered close to each other.
Have a good one!
> [ENH] Asymmetric peak_directions

- dipy/segment/tests/test_qbx.py
- dipy/viz/app.py
Thanks to @guaje for reporting a strange issue in ``dipy_horizon`` with the ``--cluster`` option.
```
File "C:\Users\Eleftherios\Devel\dipy\bin\dipy_horizon", line 7, in <module>
run_flow(HorizonFlow())
File "c:\users\eleftherios\devel\dipy\dipy\workflows\flow_runner.py", line 89, in run_flow
return flow.run(**args)
File "c:\users\eleftherios\devel\dipy\dipy\workflows\viz.py", line 238, in run
horizon(tractograms=tractograms, images=images, pams=pams,
File "c:\users\eleftherios\devel\dipy\dipy\viz\app.py", line 939, in horizon
scene = hz.build_scene()
File "c:\users\eleftherios\devel\dipy\dipy\viz\app.py", line 203, in build_scene
self.add_cluster_actors(scene, self.tractograms,
File "c:\users\eleftherios\devel\dipy\dipy\viz\app.py", line 277, in …
```
> BF: QBX and merge clusters should return streamlines

- dipy/align/streamlinear.py
- dipy/align/tests/test_whole_brain_slr.py
This PR addresses issue #2530.
It changes the default value of rm_small_clusters from 50 to 0 in slr_with_qbx function.
> Updates the default value of rm_small_clusters variable in slr_with_qbx function 

- dipy/core/gradients.py
- dipy/core/tests/test_gradients.py
I figured that get_item method is most closely related to gradients.py file which is inside dipy/core/gradients.py folder because i saw the bvech bvals method. 
#since we can call a getItem method by simply using square brackets, 
gtab = MyGradientTable(gradients)
gtab_selected = gtab[2:10]  # Select b-values from 2 to 10. 
Please let me know if I need to make any changes to this method.
> adding a new getitem method

- dipy/__init__.py
- dipy/core/__init__.py
- dipy/core/tests/__init__.py
- dipy/denoise/__init__.py
- dipy/io/tests/__init__.py
- dipy/nn/__init__.py
- dipy/reconst/__init__.py
- dipy/sims/tests/__init__.py
- dipy/tracking/__init__.py
- dipy/tracking/tests/__init__.py
- dipy/viz/tests/__init__.py
- dipy/workflows/io.py
- dipy/workflows/tests/__init__.py
- dipy/workflows/tests/test_io.py
NoseTester is deprecated and removed from Numpy testing on their next release.
To avoid having issue with future Numpy release, this PR remove it from our codebase.
Also, I use the opportunity to fix a small issue with `dipy_fetch`( Not good to do it in the same PR, but emergency)
> Remove NoseTester

- .mailmap
- Changelog
- dipy/align/_public.py
- doc/examples/motion_correction.py
- doc/index.rst
- doc/old_highlights.rst
- doc/old_news.rst
- doc/release_notes/release1.7.rst
- doc/stateoftheart.rst
Preparation for 1.7.0 release, targeting April 7, 2023 or April 14 2023. 
- ~~Masked P2S Algorithm~~. (will not be added)
- ~~NUQ Algorithm~~. (will not be added)
> [UPCOMING]  Release 1.7.0 - workshop release

- dipy/info.py
- doc/doc-requirements.txt
- requirements.txt
- setup.py
Small PR to bump our minimal version. 
numpy 1.14.5 -> 1.22.4
scipy 1.1 -> 1.8.1
nibabel 3.0.0 -> 4.0.0
h5py 2.8.0 -> 3.7.0
fury 0.8 -> 0.9.0
python_requires 3.6 -> 3.8
Note: This will give us access to typing module which we should start to do.
> bump dependencies mininal version

- Makefile
- doc/devel/make_release.rst
- version_helpers.py
Nibabel has deprecated `nisext`. We were almost not using those tools. After checking, only `check-files` was used `sometimes`. Also, those tools depends on `distutils` that we plan to remove completely. 
This is why this PR remove completely `nisext` since this is a package that we will not use in a close future. it also allow `Nibabel` to move forward. 
Thanks for all the good services `nisext`!
closes #2706
> Remove the Deprecating nisext 

- dipy/align/tests/test_api.py
- dipy/io/tests/test_dpy.py
- dipy/io/tests/test_io_gradients.py
- dipy/io/tests/test_io_peaks.py
- dipy/io/tests/test_stateful_tractogram.py
- dipy/tests/test_scripts.py
`InTemporaryDirectory` or `TemporaryDirectory` is deprecated in Nibabel in favor of the standard package `tempfile`.
So this PR clean a bit our codebase
> remove Nibabel InTemporaryDirectory

- bin/dipy_evac_plus
- dipy/workflows/nn.py
- dipy/workflows/segment.py
- dipy/workflows/tests/test_nn.py
- dipy/workflows/tests/test_segment.py
During the workshop, we realize that the workflow `evacs+` needs to leave the `segment` module and go to its own module named `nn` due to tensorflow dependency. 
All algorithms depending on tensorflow will go to this `nn` module. 
Tensorflow have some installation issue and bring confusion when you use a not related workflow. (like recobundle here).
> Move evac+ to new module `nn`

- doc/conf.py
- doc/posts/2023/2023_05_19_Shilpi_week0_journey_to_GSoC.rst
- doc/posts/2023/2023_05_29_Shipi_week1.rst
- doc/sphinxext/docscrape.py
This folder should provide a place to put all the blog posts.
> First Blog

- dipy/align/streamwarp.py
- doc/interfaces/index.rst
1. Added BundleWarp CLI tutorial to [interfaces/index.rst](https://github.com/dipy/dipy/blob/master/doc/interfaces/index.rst).
3. If streamlines are not set as float type, FURY won't visualize them, so updated that in the BundleWarp code.
This PR addresses issue #2827
> BundleWarp: added tutorial and fixed a small bug

- dipy/reconst/shm.py
Seems like a parenthesis was misplaced as it returns a float currently. From the test:
~~~python
In [7]:     for sh_order in [2, 4, 6, 8, 12, 24]:
...:         m, n = sph_harm_ind_list(sh_order)
...:         n_coef = m.shape[0]
...:         assert_equal(order_from_ncoef(n_coef), sh_order)
...:         print(order_from_ncoef(n_coef))
...:         # Try out full basis
...:         m_full, n_full = sph_harm_ind_list(sh_order, True)
...:         n_coef_full = m_full.shape[0]
...:         assert_equal(order_from_ncoef(n_coef_full, True), sh_order)
...:         print(order_from_ncoef(n_coef_full, True))
...: 
2.0
2
4.0
4
6.0
6
8.0
8
12.0
12
24.0
24
~~~
So the full order returns an int, but the old real only part returns a float, which means the output of the function can not be used as is in a …
> make order_from_ncoef return an int

- dipy/direction/pmf.pyx
- dipy/direction/probabilistic_direction_getter.pxd
- dipy/direction/probabilistic_direction_getter.pyx
- dipy/tracking/local_tracking.py
- dipy/tracking/localtrack.pyx
- dipy/tracking/tests/test_tracking.py
- dipy/utils/fast_numpy.pxd
- dipy/utils/fast_numpy.pyx
This address issue #2805.
- Reverts changes in `dipy/tracking/localtrack.pyx` from https://github.com/dipy/dipy/commit/045a1ee5485af33675726675a010c3a6fda5d9b3
- fix a minor infrequent bug in probabilistic tracking where the forward and backward direction could be sample in such a way it is bigger that `max_angle`. This was fixed by changing the initial direction to the true first direction selected in the forward segment, instead of the tentative initial direction obtained from the peaks.
> BF - initial backward orientation of local tracking

- dipy/tracking/local_tracking.py
- dipy/tracking/localtrack.pyx
- dipy/tracking/stopping_criterion.pyx
- dipy/tracking/tests/test_tracking.py
- dipy/workflows/tracking.py
- doc/examples/tracking_pft.py
This is the part 1 of 2 of refactoring PR #1627, adding a new parameter to PFT.
The new optional parameter (default value is 0), `min_wm_pve_before_stopping`, improves PFT starting in voxel with non-zero GM partial volume estimate (PVE). The 'ENDPOINT' streamline status is ignored until the tracking reaches a position with `WM PVE > min_wm_pve_before_stopping`. This is useful when seeding from the GM-WM interface or in subcortical GM, where tractography may stop prematurely in the GM. This parameter forces the tracking to reach the deep WM before stopping, or to reach voxels with WM PVE of 0.
> NF -  added pft min wm parameter

- dipy/reconst/dki.py
- dipy/reconst/dki_micro.py
- dipy/reconst/dti.py
- dipy/reconst/tests/test_dti.py
- dipy/utils/tests/test_volume.py
- dipy/utils/volume.py
Added the ability to return and store extra information from the fitting functions, in this case applied to retrieving a mask of non-outlier voxels from the RESTORE algorithm, but which could be used to return other data from different functions (for example, the leverages for linear fitting algorithms). This data is stored in TensorFit.model.extra to avoid changing the interface.
I have also added a function to calculate adjacency of voxels, taking account of arbitrary masks. This currently has no use, but it works correctly for a new fitting function I am working on, and will make it possible to include algorithms that utilize multiple voxels for fitting.
The code should work exactly as before as far as the user is concerned. I can add some additional tests, but am currently a little …
> Fix weighted Jacobians, return extra fit data, add adjacency function

- doc/reconstruction_models_list.rst
Updates Reconstruction table to include descriptions of data acquired in references for more of the listed models. Links to DOIs for references are also added where `href`s  previously did not point to any URL.
> Adding diffusion data descriptions from references to reconstruction table

- dipy/data/fetcher.py
- dipy/workflows/tests/test_io.py
Hi all! I've added a fetcher for a sample CTI dataset that can be used for the implementation in PR #2816.
To fetch and load the data, you can use the following lines of code:
```
from dipy.data import get_fnames
from dipy.io import read_bvals_bvecs
from dipy.io.image import load_nifti
fdata, fbvals1, fbvecs1, fbvals2, fbvecs2, fmask = get_fnames('cti_rat1')
data, affine = load_nifti(fdata)
bvals1, bvecs1 = read_bvals_bvecs(fbvals1, fbvecs1)
bvals2, bvecs2 = read_bvals_bvecs(fbvals2, fbvecs2)
mask, affine = load_nifti(fmask)
```
Full details of the dataset can be found in the manuscript: Henriques et al., (2021). Evidence for microscopic kurtosis in neural tissue revealed by correlation tensor MRI. Magn Reson Med 86 (6): 3111-3130.
Fetched dataset correspond to the data for Rat 1 of that …
> Add fetcher for a sample CTI dataset

- dipy/data/fetcher.py
This is for the use-case where the user wants to define the output path. This wasn't working, because it always downloaded into the ~/.dipy path until this change.
> BF: Bug when downloading hbn data.

- dipy/tracking/utils.py
This PR simply removes the zip operation in `transform_tracking_output` when `save_seeds` is enabled. Else, it is not possible to perform lazy saving of (streamline, seed) tuples using `nibabel LazyTractogram`.
However if anyone knows why it is there and/or how to lazily save streamlines and seeds using the actual implementation, this fix might not be required.
@gabknight @frheault
> Remove zip operation in transform_tracking_output

- dipy/viz/__init__.py
- dipy/viz/tests/test_apps.py
- dipy/workflows/viz.py
- This PR introduces the smaller import for horizon.
- Old import: `from dipy.viz.horizon.app import horizon`
- New import: `from dipy.viz import horizon`.
A test is also included to test that both the import have same signature.
> Short import for horizon

- .github/workflows/test_optional.yml
- dipy/reconst/dti.py
All in the Title. 
Our Conda CI's are failing due to `cvxpy` version  we have to pin scipy. 
Supersed #2890
> [FIX] Pin scipy for the conda failing CI's

- dipy/tracking/local_tracking.py
- dipy/tracking/tests/test_tracking.py
- dipy/utils/fast_numpy.pxd
- dipy/utils/fast_numpy.pyx
- dipy/utils/tests/test_fast_numpy.py
`fast_numpy.seed(int s)` could raise an error if the input value was too high for an `int`. I changed the input to `fast_numpy.seed(cnp.npy_uint32 s)` as it should have been and added a new test.
Thanks @EmmaRenauld for reporting this.
> BF - fixed random generator seed `value too large to convert to int` error

- dipy/tracking/local_tracking.py
- dipy/tracking/tests/test_tracking.py
This is the part 2 of 2 of refactoring PR https://github.com/dipy/dipy/pull/1627, adding initial tracking direction to local tracking.
PR #2806 need merging before this one.
- Add option to input a list of tracking orientation alongside each input seed.
- Add option to tracking only in the forward orientation.
- Add option to randomize the sign of the initial tracking orientation ( 1, -1).
> NF -  add initial directions to local tracking

- dipy/align/streamwarp.py
Delegate to NumPy creating a random matrix, instead of creating each row independently using a list comprehension.
Additionally, fixes:
```
Local variable 'si' value is not used
```
> OPT: Delegate to NumPy creating a random matrix

- dipy/segment/tests/test_mrf.py
This commit adds seeds to test_square_iter and test_icm_square to stabilize the tests. square_gauss and square_1, which were originally global variables are now loaded through a function which has a numpy random generator inside with fixed seed. The variables were wrapped in a function because 1. there is no need for the variables to be global 2. this complies with a future PR that will add decorators on tests that require seed values.
Note that this is a separate PR created from a discussion in #2929 for immediate increase in stability of the tests while a PR to change all random functions in DIPY to the recent numpy convention is underway.
> TEST: Adding random generator with seed to icm tests

- dipy/direction/tests/test_ptt_direction_getter.py
Filter legacy SH bases warnings in PTT direction getter test. Warnings are already being tested, and there is no further need to ensure that these warnings are raised.
Filtering them avoids having them printed in the standard output, and thus, unnecessary clutter.
Fixes:
```
direction/tests/test_ptt_direction_getter.py::test_PTTDirectionGetter
/home/runner/work/dipy/dipy/venv/lib/python3.11/site-packages/dipy/reconst/shm.py:351:
PendingDeprecationWarning:
The legacy descoteaux07 SH basis uses absolute values for negative harmonic degrees.
It is outdated and will be deprecated in a future DIPY release.
Consider using the new descoteaux07 basis by setting the `legacy` parameter to `False`.
warn(descoteaux07_legacy_msg, category=PendingDeprecationWarning)
```
and
``` …
```
> TEST: Filter legacy SH bases warnings in PTT direction getter test

- dipy/reconst/qtdmri.py
Refactor duplicate code in `qtdmri` to `mapmri` coefficient mapping matrix computiation: create a new private function that holds the logic for both the isotropic and anisotropic cases that is called from the separate isotropic/anisotropic, and using a flag to characterize the different behavior.
> RF: Refactor duplicate code in `qtdmri` to `mapmri` coeff computation

- .github/workflows/test.yml
- .github/workflows/test_compat.yml
Bring back Python 3.8 testing to GHA workflows.
Removed in commit cf4338d.
Raise the minimum required NumPy version for the Python 3.8
compatibility test to 1.23.0 from the previously required 1.22.0 version
in commit https://github.com/dipy/dipy/commit/318bfc68635fdd9410d7372e47ce734cea4ed64b so that tests can pass. Fixes:
```
ImportError: numpy.core.multiarray failed to import
```
https://github.com/dipy/dipy/actions/runs/6620737573/job/17983666930#step:9:12437
> TEST: Bring back Python 3.8 testing to GHA workflows

- dipy/denoise/tests/test_ascm.py
- dipy/reconst/dki.py
- dipy/reconst/msdki.py
- dipy/reconst/qtdmri.py
- dipy/reconst/tests/test_qtdmri.py
- dipy/segment/tests/test_metric.py
- STYLE: Conform to the expected return value in reconst dki method
- TEST: Fix NumPy array to scalar value conversion warning
> TEST: Fix NumPy array to scalar value conversion warning

- dipy/reconst/tests/test_msdki.py
Fix typo in `msdki` reconstruction test name.
> STYLE: Fix typo in `msdki` reconstruction test name

- dipy/direction/tests/test_bootstrap_direction_getter.py
Filter legacy SH bases warnings in bootstrap direction getter test. Warnings are already being tested, and there is no further need to ensure that these warnings are raised.
Filtering them avoids having them printed in the standard output, and thus, unnecessary clutter.
Fixes:
```
direction/tests/test_bootstrap_direction_getter.py::test_bdg_get_direction
/home/runner/work/dipy/dipy/venv/lib/python3.11/site-packages/dipy/reconst/shm.py:351:
PendingDeprecationWarning:
The legacy descoteaux07 SH basis uses absolute values for negative harmonic degrees.
It is outdated and will be deprecated in a future DIPY release.
Consider using the new descoteaux07 basis by setting the `legacy` parameter to `False`.
warn(descoteaux07_legacy_msg, category=PendingDeprecationWarning)
```
Raised for example …
> TEST: Filter legacy SH bases warnings in bootstrap direction getter test

- dipy/viz/horizon/tab/slice.py
This PR enables the volume slider to be functional. For nii data with volume dimension.
> volume slider fix

- dipy/workflows/viz.py
As a horizon user, if you use once the stealth mode of horizon it generates an output file. Once the output file is generated it mandates the user to use --force in every new run otherwise the viewer shows empty screen.
- Every run will by default overwrite the file if any output is generated. Thus, the user does not need to append --force option on every single run.
- The `Workflow` class provides a flag named force, which by default is set to `False`. While creating the HorizonWorkflow, we can enable the flag by calling `__init__` function of the Workflow class.
1. Run any visualization in stealth mode. For that use command `dipy_horizon <file> --stealth`.
2. Make sure you have a tmp.png file created in your folder structure.
3. Run the same visualization in normal flow without --force …
> bugfix for --force issue

- dipy/reconst/mcsd.py
- dipy/reconst/tests/test_mcsd.py
Hi!
This is a really small modification of `reconst.mcsd.multi_shell_fiber_response` , adding support for the b-tensor (btens) option. I used the new implementation of btens in `gradient_table` and `single_tensor`, so that the `reconst.mcsd.multi_shell_fiber_response` function now returns the response function according to the b-tensor shape of each inputed b-value. For example, I use this for multi-encoding msmt-CSD (see my paper for more details https://doi.org/10.1016/j.media.2022.102476) on Scilpy (I am a PhD student supervised by Maxime Descoteaux), and I had this version of the function in my code. It runs as usual when no btens is given, by setting every b-value as LTE (linear tensor encoding).
It would be very appreciated if this could go in the next release. @gabknight
> Adding support for btens to multi_shell_fiber_response function

- dipy/data/fetcher.py
- dipy/nn/evac.py
- dipy/nn/tests/test_evac.py
- dipy/nn/tests/test_utils.py
- dipy/nn/utils.py
This commit changes the EVAC+ model and its default weights for better brain extraction output. It also adds an option to only select the largest foreground and remove its holes, so that most prediction noises can be removed.
> NF: Updating EVAC+ model and adding util function

- dipy/tracking/utils.py
Following discussion #2972 , here is a pull request with the new code. The main objective was to speed up the code when 'inclusive' was set to True.
For a tractogram of 500 000 streamlines, the code now runs in less than 20s with all parameters set to True, compared to more than 2 minutes previously. The code is also shorter and subjectively more readable.
Main differences:
- 'inclusive' is now faster, with a x3 speed up for a tractogram of 2000 streamlines and >x6 speed up for a tractogram of 500 000 streamlines. Speed when 'inclusive' is set to False is unchanged.
- 'symmetric' now returns only the top half of the matrix when set to False. The results thus differ from the previous implementation when set to False. To be honest, 'symmetric'=False does not make sense to me since …
> connectivity_matrix code speed up

- dipy/tracking/_utils.py
- dipy/tracking/local_tracking.py
- dipy/tracking/localtrack.pyx
- dipy/tracking/vox2track.pyx
In Numpy 2.0, `int_t` type is not available anymore and it is not recommended to use it. 
In our case, it can be safely replaced by `npy_intp`.
This fix DIPY compilation with Numpy 2.0. 
A follow up PR should come today for the tests
PS: #2979
> [FIX] int_t to npy_intp

- dipy/reconst/tests/test_multi_voxel.py
`np.sctypes` is removed from Numpy 2.0 (https://numpy.org/devdocs/numpy_2_0_migration_guide.html#main-namespace)
This is something that we used only one time. So this PR provide an alternative to fix the future issue. 
follow up of https://github.com/dipy/dipy/issues/2979
> [MTN] replace the deprecated sctypes

- dipy/reconst/csdeconv.py
- dipy/tracking/streamline.py
Fix boolean variable negation warnings: use the `not` operator instead of the `~` opertor.
Fixes:
```
reconst/tests/test_csdeconv.py::test_odfdeconv
reconst/tests/test_csdeconv.py::test_odf_sh_to_sharp
reconst/tests/test_csdeconv.py::test_r2_term_odf_sharp
dipy/venv/lib/python3.12/site-packages/dipy/reconst/csdeconv.py:768:
DeprecationWarning: Bitwise inversion '~' on bool is deprecated.
This returns the bitwise inversion of the underlying int object and is
usually not what you expect from negating a bool. Use the 'not'
operator for boolean negation or ~int(x) if you really want the bitwise
inversion of the underlying int.
if ~r2_term:
```
and
```
tracking/streamline.py: 9 warnings
tracking/tests/test_streamline.py: 18 warnings
dipy/venv/lib/python3.12/site-packages/dipy/tracking/streamlin …
```
> STYLE: Fix boolean variable negation warnings

- dipy/reconst/shm.py
Fix typos and grammar in `lcr_matrix` function documentation.
> DOC: Fix typos and grammar in `lcr_matrix` function documentation

- dipy/align/streamwarp.py
- dipy/stats/analysis.py
Miscellaneous documentation improvements:
- Document the return value in `assignment_map`.
- Remove documenting default values to avoid any risk of the values not being sync'ed with the actual values in the method signature.
- Add the `optional` label to optional parameter.
- Improve syntax and fix inaccurate docstring variable names.
> DOC: Miscellaneous documentation improvements

- dipy/align/tests/test_parzenhist.py
Use `.empty_like()` over `.astype()` on uninitialized array casting: use `np.empty_like()` with data type specification to avoid casting warnings.
Fixes:
```
align/tests/test_parzenhist.py::test_exceptions
python3.10/site-packages/dipy/align/tests/test_parzenhist.py:597:
RuntimeWarning: invalid value encountered in cast
invalid_grad_type = valid_grad.astype(np.int32)
```
https://github.com/dipy/dipy/actions/runs/7073407086/job/19253289839#step:9:4359
> STYLE: Use `.astype()` on uninitialized array casting

- dipy/reconst/tests/test_mcsd.py
Make `cvxpy`-dependent test checking consistent in `test_mcsd`: use the `needs_cvxpy` decorator consistently in `test_mcsd`.
> STYLE: Make `cvxpy`-dependent test checking consistent in `test_mcsd`

- dipy/reconst/dti.py
- dipy/reconst/tests/test_dti.py
Filter warning about resorting to `OLS` fitting method.
Fixes:
```
reconst/tests/test_dti.py::test_nlls_fit_tensor
dipy/reconst/dti.py:1836: UserWarning:
Resorted to OLS solution in some voxels
warnings.warn("Resorted to OLS solution in some voxels", UserWarning)
```
https://github.com/dipy/dipy/actions/runs/7146907000/job/19465502675#step:9:4439
> TEST: Filter warning about resorting to `OLS` fitting method

- dipy/denoise/patch2self.py
- dipy/denoise/tests/test_patch2self.py
- dipy/reconst/sfm.py
- dipy/reconst/tests/test_sfm.py
Prefer raising `sklearn` package warnings when required: do not raise the warnings at the module level since they cannot be effectively checked and filtered otherwise in tests.
Fixes:
```
../venv/lib/python3.10/site-packages/dipy/denoise/patch2self.py:11
dipy/denoise/patch2self.py:11: UserWarning:
We need package sklearn for these functions, but ``import sklearn`` raised an ImportError
warn(sklearn._msg)
```
and
```
../venv/lib/python3.10/site-packages/dipy/reconst/sfm.py:48
dipy/reconst/sfm.py:48: UserWarning:
We need package sklearn for these functions, but ``import sklearn`` raised an ImportError
Alternatively, you can use 'nnls' method to fit the SparseFascicleModel
warnings.warn(w)
```
https://github.com/dipy/dipy/actions/runs/7146907000/job/19465502675#step:9 …
> RF: Prefer raising `sklearn` package warnings when required

- dipy/denoise/localpca.py
- dipy/denoise/tests/test_lpca.py
Create PCA denoising utils methods: refactor code blocks into their own methods to improve encapsulation.
Add the corresponding tests.
Add a method to report about the dimensionality problem message.
The above allows for the dimensionality problem message to be checked and filtered in tests.
Fixes:
```
denoise/tests/test_lpca.py::test_mppca_returned_sigma
denoise/localpca.py:194: UserWarning:
Number of samples 27 - 1 < Dimensionality 104.
This might have a performance impact.
Increase patch_radius to 2 to avoid this warning,
or supply suppress_warning=True to your function call.
warn(e_s, UserWarning)
```
reported, for example, at:
https://github.com/dipy/dipy/actions/runs/7146907000/job/19465502675#step:9:4410
> RF: Create PCA denoising utils methods

- dipy/nn/tests/test_utils.py
Filter SciPy 0.18.0 1-D affine transform array warning in test.
Fixes:
```
nn/tests/test_utils.py::test_transform
scipy/ndimage/_interpolation.py:606: UserWarning:
The behavior of affine_transform with a 1-D array supplied for the matrix parameter has changed in SciPy 0.18.0.
warnings.warn(
```
https://github.com/dipy/dipy/actions/runs/7146907000/job/19465502675#step:9:4426
> TEST: Filter SciPy 0.18.0 1-D affine transform array warning in test

- dipy/denoise/tests/test_lpca.py
Check and filter PCA dimensionality problem warning in MPPCA test.
Fixes:
```
denoise/tests/test_lpca.py::test_mppca_in_phantom
denoise/localpca.py:295: UserWarning:
Number of samples 27 - 1 < Dimensionality 104.
This might have a performance impact.
Increase patch_radius to 2 to avoid this.
warn(dimensionality_problem_message(arr, num_samples, spr), UserWarning)
```
https://github.com/dipy/dipy/actions/runs/7159954273/job/19493785864#step:9:3932
Left behind in commit fe33ea9.
> TEST: Check and filter PCA dimensionality problem warning

- dipy/core/profile.py
- dipy/utils/optpkg.py
- dipy/utils/tests/meson.build
- dipy/utils/tests/test_optpkg.py
- dipy/viz/__init__.py
This PR helps to handle minimum version for optional package. 
Currently, this is hard to handle, not standardize and can bring difficulties for the maintenance. 
I also added some test for `optional_package` function which was not tested
> [NF] Introduce minimum version in `optional_package`

- dipy/reconst/shm.py
Mask strict `1` values in leveraged, residual matrix computation: when the diagonal of `H` turns out to have `1`s, `1 - H.diagonal()` gives `0`s, and then a divide by 0 operation is encountered and makes NumPy raise a warning.
Fixes:
```
direction/tests/test_bootstrap_direction_getter.py::test_boot_pmf
python3.10/site-packages/dipy/reconst/shm.py:1023: RuntimeWarning:
divide by zero encountered in divide
R = (np.eye(len(H)) - H) / leverages
```
and
```
direction/tests/test_bootstrap_direction_getter.py::test_boot_pmf
python3.10/site-packages/dipy/reconst/shm.py:1024: RuntimeWarning:
invalid value encountered in subtract
return R - R.mean(0)
```
https://github.com/dipy/dipy/actions/runs/7073407086/job/19253289839#step:9:4400
Masking `<=1` diagonal values was …
> BF: Mask `1` values in leveraged, residual matrix computation

- dipy/align/streamwarp.py
Fix bundlewarp shape analysis profile values for the case where all mask values are `False`: set the value to `np.nan` instead of relying on NumPy to compute the mean and the std values on an empty array.
Fixes:
```
align/tests/test_streamwarp.py::test_bundle_shape_profile
/home/runner/work/dipy/dipy/venv/lib/python3.11/site-packages/numpy/core/fromnumeric.py:3504:
RuntimeWarning: Mean of empty slice.
return _methods._mean(a, axis=axis, dtype=dtype,
align/tests/test_streamwarp.py::test_bundle_shape_profile
/home/runner/work/dipy/dipy/venv/lib/python3.11/site-packages/numpy/core/_methods.py:129:
RuntimeWarning: invalid value encountered in scalar divide
ret = ret.dtype.type(ret / rcount)
align/tests/test_streamwarp.py::test_bundle_shape_profile …
```
> BF: Fix bundlewarp shape analysis profile values for all `False` mask

- dipy/reconst/tests/test_dki.py
Set explicitly `CLARABEL` as the CVXPY solver instead of relying on CVXPY choosing the solver: CVXPY resorts to `ECOS` by default, which will be deprecated starting CVXPY 1.5.0.
Fixes:
```
reconst/tests/test_dki.py::test_dki_fits
python3.10/site-packages/cvxpy/reductions/solvers/solving_chain.py:336: FutureWarning:
Your problem is being solved with the ECOS solver by default. Starting in
CVXPY 1.5.0, Clarabel will be used as the default solver instead. To continue
using ECOS, specify the ECOS solver explicitly using the ``solver=cp.ECOS``
argument to the ``problem.solve`` method.
warnings.warn(ECOS_DEPRECATION_MSG, FutureWarning)
```
https://github.com/dipy/dipy/actions/runs/7146907000/job/19465502675#step:9:4433
> TEST: Set explicitly `CLARABEL` as the CVXPY solver

- README.rst
- doc/links_names.inc
- doc/user_guide/dependencies.rst
Document observance for Scientific Python minimum supported versions recommendation.
> DOC: Document observance for Scientific Python min supported versions

- README.rst
Fix link to toolchain roadmap page in `README`: use a URL link syntax instead of a reference to a page.
> DOC: Fix link to toolchain roadmap page in `README`

- dipy/core/sphere.py
- dipy/core/tests/test_sphere.py
The `fibonacci_sphere` method is designed for efficiently generating points on the surface of a sphere, such as in the iterations of disperse charges. The time complexity is reduced because of the analytical solution as opposed to an optimization problem solution in disperse charges
```python
def fibonacci_sphere(n_points: int, randomize: bool) -> numpy.ndarray of shape (n_points,3)
```
```python
from dipy.core.sphere import fibonacci_sphere,Sphere
points = fibonacci_sphere(n_points=1000, randomize=True)
sph = Sphere(xyz = points)
```
> Added Fibonacci spiral and test for it

- dipy/testing/__init__.py
- dipy/viz/horizon/app.py
- dipy/viz/horizon/tab/tests/test_base.py
- dipy/viz/horizon/util.py
- dipy/viz/tests/meson.build
- dipy/viz/tests/test_apps.py
- dipy/viz/tests/test_util.py
This PR resolves the issue https://github.com/dipy/dipy/issues/2789 about checking dtype of the passed image arrays.
- When horizon is invoked from either we do not check the type of the data passed in the images. It is implicitly assumed to be an appropriate numerical type supported by horizon.
- This causes issues when users are using the horizon from the python code as the type is not verified.
All the images will be checked for dtype and the following cases can be the result.
1. Data is of type int32 or float32 or float64, data will be added to the valid images.
2. Data is of a different integer subtype than int32, data will be cast to int32 and then will be added to the valid images. There will be a warning provided.
3. Data is of a different floating subtype than float32 or float64, …
> Bugfix: Horizon image's dtype validation

- dipy/io/tests/test_stateful_tractogram.py
This PR provides an alternative when there is http issue with `fetch_gold_standard_io`. 
Instead of failing, we just skip the tests and provide a reason. It also one step further concerning offline testing (see https://github.com/dipy/dipy/issues/2647)
It also cleanup some global variable.
> [TEST] Manage http errors for stateful tractograms

- pyproject.toml
As first identified in [Debian bug #1060438], the pyproject.toml declares a run time dependency on cython for dipy, but running the program and suite after cythonizing the code does not require cython anymore.  In such configuration, the cython requirement for the build system should be sufficient.
[Debian bug #1060438]: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1060438
> pyproject.toml: no cython at run time.

- dipy/data/tests/test_data.py
test_sphere_dtypes produces consistently little endian float64 numpy objects.  This is usually not an issue, but big endian systems, the little endian value is compared against a big endian float64, causing the test to fail.  This fixes/worksaround the test failure on big endian CPUs.
> d/d/t/test_data.py: endian independent dtype.

- dipy/reconst/mcsd.py
Fix array dimensions in the `multi_shell_fiber_response` docstring
> [DOC] fix `multi_shell_fiber_response` docstring array dims [ci skip]

- dipy/__init__.py
- dipy/conftest.py
- dipy/denoise/localpca.py
- dipy/reconst/dti.py
- dipy/reconst/mcsd.py
- dipy/testing/__init__.py
- dipy/viz/horizon/app.py
- doc/conf.py
This Pr removes `from packaging.version import Version` in many modules due to the incoherence with DIPY minimal dependencies versions.
> [MTN] code cleaning: remove some dependencies version checking

- dipy/direction/bootstrap_direction_getter.pyx
- dipy/direction/closest_peak_direction_getter.pxd
- dipy/direction/closest_peak_direction_getter.pyx
- dipy/direction/pmf.pxd
- dipy/direction/pmf.pyx
- dipy/direction/probabilistic_direction_getter.pyx
- dipy/reconst/eudx_direction_getter.pyx
- dipy/tracking/direction_getter.pxd
- dipy/tracking/direction_getter.pyx
- dipy/tracking/localtrack.pyx
This PR is a small refactoring to remove the `cpdef` in  pmf.pyx.   
`cpdef = def + cdef` , so it does not make sense to have cpdef + cdef.     it is either `def +cdef ` or `cpdef`
I also use the opportunity to replace some pointer by memoryview. When using memoryview, we should make sure to use aligned memory by using [::1] for speed reason.
@gabknight, can you have a look and try?
> [RF] remove cpdef in PmfGen

- README.rst
This PR is to simply change the broken installation link in the README file.
> [DOC] Fix installation link in README  [ci skip]

- .github/dependabot.yml
- .github/workflows/nightly.yml
* Update the scientific-python/upload-nightly-action to v0.5.0 for dependency stability and to take advantage of Anaconda Cloud upload bug fixes.
- c.f. https://github.com/scientific-python/upload-nightly-action/releases/tag/0.5.0
* Group dependabot updates to reduce the number of PRs.
- c.f. sp-repo-review GH212: Require GHA update grouping
https://learn.scientific-python.org/development/guides/gha-basic/#GH212
> [CI] Update scientific-python/upload-nightly-action to 0.5.0

- doc/links_names.inc
- doc/user_guide/installation.rst
DIPY has been available in Fedora for some time. The NeuroFedora SIG
(special interest group) has packaged it along with a multitude of other
neuroscience software.
> Add Fedora installation instructions [ci skip] 

- dipy/viz/horizon/app.py
- dipy/viz/horizon/util.py
- dipy/viz/tests/test_util.py
This PR introduces the change to the `np.unique` check whether an image is binary or not.
- This creates a lot of overhead on the system as the images can be in the size of gigabytes.
- A function is introduced to check an image is binary or not.
- This function samples 100 points (default, can be changed via parameter) and verifies if the image provided is a binary image.
> Np.unique check removed.

- dipy/viz/horizon/tab/slice.py
This PR is for the issue #3075 
It introduces the fix for when the volume slider is accessed the 3D slices stops working for that specific slice.
The display_extent of the slice actor was changed via a partial and was given an initial object. But while accessing the volume we create new actors for that specific volume value. But when we move the slider it access the old objects, hence providing no updates on ui.
- The partials are moved to a function which is called again when the volume is changed and new actors are created.
> fixed 4d slice issue

- .github/workflows/nightly.yml
- tools/ci/install_dependencies.sh
Due to issue with --doctest-module flags, it seems that `setup_module` is not recognized with pytest 8.0.1 or 8.0.2.
For now, we pin pytest to 8.0.0 until a fix appears.
> [TEST] Pin pytest 

- dipy/core/interpolation.pxd
- dipy/core/interpolation.pyx
- dipy/direction/bootstrap_direction_getter.pyx
- dipy/direction/pmf.pyx
- dipy/tracking/stopping_criterion.pyx
- Changed the `out` type from `memoryview` to `double*` in `dipy.core.interpolation.trilinear_interpolation_4d_c`. This allows for the use of trilinear_interpolation4d_c in pure cython. In particular when the `out` needs to be instanciated in cython.  This is relevant for PR #3089
- Replaced `dipy.core.interpolation.trilinear_interpolation_4d` declaration to `def` from `cpdef`
> RF - changed memory view to double* trilinear_interpolation_4d

- dipy/viz/horizon/app.py
- dipy/viz/horizon/tab/base.py
- dipy/viz/horizon/tab/slice.py
- dipy/viz/horizon/util.py
- dipy/viz/tests/test_util.py
This PR introduces the changes for a feature where the volume slider will be synchronized.
**When to synchronize**
- All the provided images have the same shape.
- All the images with volume should have the same volume samples.
**Images with the same shape and same volumes**
The slices will be synchronized and volumes will also be synchronized.
**Images with the same shape but different volumes**
The slices will be synchronized but volumes will not be synchronized.
**Images with different shapes but same volumes** and **Images with different shapes and different volumes**
Nothing will be synchronized and a warning will be visible.
> Feature: volume synchronizing

- dipy/testing/decorators.py
- dipy/viz/horizon/app.py
- dipy/viz/horizon/tab/base.py
- dipy/viz/horizon/tab/slice.py
- dipy/viz/horizon/util.py
- dipy/viz/tests/test_apps.py
- dipy/viz/tests/test_util.py
- dipy/workflows/tests/test_viz.py
- dipy/workflows/viz.py
This PR introduces a data field saying file name
- On the page a field `Filename` got added with the file name next to it.
-
- I have updated all the test cases accordingly to take care of file while unpacking the images data.
> Tab names for slice tabs as file names.

- dipy/reconst/tests/test_utils.py
- dipy/reconst/utils.py
- dipy/workflows/cli.py
- dipy/workflows/io.py
- dipy/workflows/tests/test_io.py
- doc/recipes.rst
- pyproject.toml
This PR allow the possible to convert tensor files from different software.  it should help user to import their data from other software or visualize data processed by DIPY in other software.
> [NF] Add workflow to convert tensors in different formats

- dipy/viz/horizon/tab/slice.py
This PR fixes the bug for hiding the slices and reappearing them when data with volume is used.
> volume slices visibility fixed

- dipy/workflows/io.py
This PR update the output type of `convert_tractogram`  (from `variable string` to `string`) to avoid a crash during the use of this command line
> [BF] convert_tractogram fix

- .mailmap
- Changelog
- LICENSE
- dipy/align/imaffine.py
- dipy/denoise/gibbs.py
- dipy/direction/peaks.py
- dipy/reconst/csdeconv.py
- dipy/segment/bundles.py
- dipy/workflows/denoise.py
- dipy/workflows/reconst.py
- doc/api_changes.rst
- doc/index.rst
- doc/old_highlights.rst
- doc/old_news.rst
- doc/release_notes/release1.9.rst
- doc/stateoftheart.rst
Preparation for 1.9.0 release, targeting **March 5-6, 2024**.
> [UPCOMING] Release preparation for 1.9.0

- .github/CONTRIBUTING.md
- pyproject.toml
Fix documentation URLs: the DIPY documentation was moved from dipy.org/documentation to docs.dipy.org starting DIPY 1.8.0:
- Fix the project documentation URL in `pyproject.toml`.
- Fix the URL to the development documentation section in the `CONTRIBUTING.md` file.
> DOC: Fix documentation URLs

- dipy/segment/tissue.py
- doc/doc-requirements.txt
This PR introduces removal of 'allow_break' from the TissueClassifierHMRF as mentioned in issue #3096. 
- Removed the `allow_break` variable to simplify loop exit logic.
- The `tolerance` parameter now explicitly disables the early stopping condition when set to `0`, allowing for clear differentiation between using and not using the tolerance check for loop control.
- Clarified documentation for the `tolerance` parameter to indicate how users can disable the tolerance check.
* #3096 
I ran this [tutorial](https://docs.dipy.org/stable/examples_built/segmentation/tissue_classification.html#sphx-glr-examples-built-segmentation-tissue-classification-py) to check if the changes were functional. Here are the results.
Old Code
New Code
* I also ran the test mentioned in `test_mrf.py` by running …
> BF: Removed allow_break

- dipy/nn/cnn_1d_denoising.py
- dipy/nn/evac.py
Keras3, a new default for Tensorflow, deprecates the orthogonal option when initializing layers, which is addressed by directly calling the class. It also deprecates the ability to control number of processes and workers when running the model, which the PR removes. Both were previously throwing errors in CNN1Denoising. Finally, it also has a change of behavior in how the input dictionary's tensors should be named, throwing warning in EVACPlus, which is also taken care of in this PR.
> BF: Removing Error/Warning from Tensorflow 2.16

- dipy/viz/horizon/app.py
- dipy/viz/horizon/util.py
- dipy/viz/horizon/visualizer/slice.py
- dipy/viz/tests/test_apps.py
This PR fixes the change of `--roi_images` option throwing an error.
- Instead of checking entire dataset for unique data, we can pickup 3D box at the center of the 3D image, and check the box for binary values.
- For 4D images we are checking the values of the different 3D boxes.
- By default, the box is of size **(15, 15, 15)** and 15 volumes for 4D dataset.
- If the size of dimension less than the box the box will adjust to dimension.
> Bugfix for ROI images updates

- dipy/io/utils.py
Fix HDF5 key warning when saving BUAN profile data: if a key is not provided, use the file's rootname (i.e. removing the extension to the file's basename) as the key.
Fix BUAN profile key warning when saving data to HDF5
Fixes:
```
workflows/tests/test_stats.py::test_buan_bundle_profiles
C:\Miniconda\envs\venv\lib\site-packages\tables\path.py:137:
NaturalNameWarning: object name is not a valid Python identifier:
'C:\\Users\\RUNNER~1\\AppData\\Local\\Temp\\tmp6wee0ijp\\output\\temp_fa';
it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``;
you will not be able to use natural naming to access this object;
using ``getattr()`` will still work, though
check_attribute_name(name)
```
https://github.com/dipy/dipy/actions/runs/8404604242/job/23016386753#step:10:4147
> ENH: Fix HDF5 key warning when saving BUAN profile data

- .github/workflows/test_pre.yml
- tools/ci/install.sh
- tools/ci/install_dependencies.sh
Currently, our `PRE_WHEELS` are not using Numpy 2.0 because a dependency uninstall it. 
So, this update should force the use of `PRE_WHEELS`.
ref: #2979
> [FIX] Force the use of pre-wheels

- dipy/viz/projections.py
Fix variable potentially being referenced before assignment in `viz.projections.sph_project`.
Fixes:
```
Local variable 'fig' might be referenced before assignment
```
> ENH: Fix variable potentially being referenced before assignment

- dipy/viz/tests/test_streamline.py
Make `fury` and `matplotlib` presence message in visualization test consistent: remove the comma.
> STYLE: Make `fury` and `matplotlib` presence message in test consistent

- dipy/viz/projections.py
Fix `tri` parameter docstring in `viz.projections.sph_project`:
- Make the method signature parameter name match the corresponding name in the docstring.
- Rename the `matplotlib.tri` imported package name to avoid the `tri` argument name shadowing it. Prefer to rename the package instead of renaming the argument so as to avoid breaking the API.
Rename the returned variable name `ax` to `_ax` in the docstring example to avoid shadowing `ax` from outer scope.
Take advantage of the commit to make the docstring style consistent with the style used across the package.
> DOC: Fix `tri` parameter docstring in `viz.projections.sph_project`

- dipy/viz/horizon/app.py
- dipy/viz/horizon/tab/__init__.py
- dipy/viz/horizon/tab/base.py
- dipy/viz/horizon/tab/cluster.py
- dipy/viz/horizon/tab/peak.py
- dipy/viz/horizon/tab/roi.py
- dipy/viz/horizon/tab/slice.py
- dipy/viz/horizon/tab/surface.py
- dipy/viz/horizon/tab/tests/test_base.py
**Changes**
- This PR ensures that all the tabs do not have `tab_ui` while building the tab elements ensuring the **abstraction**.
- This PR ensures all the methods that are not used by any other class are kept private, ensuring the **encapsulation**.
- This PR replaces all the direct fury UI objects to the `HorizonUIElement` wrapper data class for maintaining the standard course of usage of the horizon.
- This PR moves methods common into the base `HorizonTab` class to ensure we are getting the benefits of **inheritance** and **polymorphism**.
**Goals**
- This PR aims to achieve intractability while having multiple visualizations in the window. The problem arises when you have an ROI, a Surface, or a Peak visualized. It creates problems in interacting with clusters or images. Both of …
> Clean up for tabs and tab manager

- dipy/utils/convert.py
- dipy/utils/meson.build
- dipy/utils/tests/meson.build
- dipy/utils/tests/test_convert.py
- dipy/workflows/segment.py
- dipy/workflows/tests/test_segment.py
- doc/api_changes.rst
- doc/interfaces/basic_flow.rst
- doc/interfaces/reconstruction_flow.rst
This PR enable range to `vol_idx` parameter for `dipy_median_otsu`. here some examples:
- `dipy_median_otsu dwi.nii --vol_idx 10-50`
- `dipy_median_otsu dwi.nii --vol_idx 15-20,23-45,47,48,49,50`
This option can be enable for other workflows argumentS.
> [ENH] Enable range for dipy_median_otsu workflow 

- dipy/reconst/dti.py
- dipy/reconst/tests/test_dti.py
Hi all.
This PR is to resolve an issue reported in #3145.
Although the issue was detected when running `dipy_fit_dki`, it appears to be a more general issue with the tensor mode calculation in `dti.py`. The calculation involves dividing by the norm of the deviatoric component of the diffusion tensor, leading to problems when the tensor is isotropic. To address this, I've adapted the code in `mode` to bypass the mode calculation for voxels where the norm of the deviatoric diffusion tensor is zero. In cases where the norm is zero, the mode value will be set to zero, which is appropriate since isotropic tensors should indeed have a mode of zero.
Let me know if there are any questions or comments.
> BF: Fix bug in mode for isotropic tensors

- dipy/viz/horizon/visualizer/peak.py
**Changes**
- This PR changes the functionality back to FURY where we avoid calculating voxels that don't contain any peaks.
- Ensuring the sizes will still correspond to the actual image.
**Goals**
- This PR makes much faster than the current Horizon peaks loading time.
**Speed Up**
- Measuring the speedup on a Linux machine with below given specifications
- Measuring was done using peaks generated from stanford_hardi data.
| Before | After |
|--------|--------|
| 63s | 5s |
> Loading Peaks faster with complete range and synchronization functionality.

- dipy/reconst/dti.py
This PR is just a clean up of `dti.py`. It fixes pep8 and docstring style.
I was looking for a function and all these issues disturbed me 😅 so [boy scout rule](https://www.linkedin.com/pulse/boy-scout-rule-simple-programming-principle-mudassar-saleem-rywlf/) and here is the PR
> [PEP8] fix pep8 and docstring style in `dti.py` file

- dipy/reconst/tests/test_mapmri.py
Specify the solver for the MAP-MRI positivity constraint test: the solver picked up by `cvxpy` as the most appropriate one (`OSQP`) finds a solution that it suspects may be inaccurate, so set it to `CLARABEL`.
In either case, the optimal value found is 5.729e-01.
Fixes:
```
reconst/tests/test_mapmri.py::test_positivity_constraint
/home/runner/work/dipy/dipy/venv/lib/python3.10/site-packages/cvxpy/problems/problem.py:1403:
UserWarning: Solution may be inaccurate.
Try another solver, adjusting the solver settings, or solve with verbose=True for more information.
warnings.warn(
```
https://github.com/dipy/dipy/actions/runs/8649253830/job/23715040118#step:10:4368
> ENH: Specify the solver for the MAP-MRI positivity constraint test

- pyproject.toml
Add `pre-commit` to project `dev` dependencies: will allow to run `ruff` as a pre-commit hook when installing DIPY in development mode.
Left behind in commit 91fd582.
> ENH: Add `pre-commit` to project `dev` dependencies

- dipy/align/_public.py
Changed name of return variable in the docstring to match the actual function return. Added a copy of starting_affine named final_affine after registrations to clarify the flow of data.
> Update affine_registration to clarify returns and make them consistent with docstring

- dipy/core/interpolation.pxd
- dipy/core/interpolation.pyx
- dipy/core/tests/test_interpolation.py
This PR should fix #3186.  It allows `float` and `double` for `trilinear_interpolate4d_c`.
To see the definition of `floating`, see https://cython.readthedocs.io/en/latest/src/userguide/fusedtypes.html#built-in-fused-types
> [RF] allow float and double for `trilinear_interpolate4d_c`

- dipy/core/geometry.py
Ensure that the argument to `arccos` in `cart2sphere` is in the [-1,1] range. Rather than clipping the values to the [-1,1] range, leave them uninitialized to keep the previous behavior.
Fixes:
```
reconst/tests/test_forecast.py::test_forecast_predict
reconst/tests/test_mapmri.py::test_mapmri_isotropic_static_scale_factor
reconst/tests/test_mapmri.py::test_mapmri_isotropic_design_matrix_separability
C:\Miniconda\envs\venv\lib\site-packages\dipy\core\geometry.py:131: RuntimeWarning: invalid value encountered in arccos
theta = np.arccos(np.divide(z, r, where=r > 0))
```
https://github.com/dipy/dipy/actions/runs/8767689276/job/24061232823?pr=3197#step:10:4212
> ENH: Ensure that `arccos` argument is in the [-1,1] range

- dipy/reconst/dki.py
- dipy/reconst/tests/test_dki.py
- doc/examples/reconst_dki.py
Fix miscellaneous warnings in `dki` reconstruction module:
- Add the `NLS` fit method to the list of methods that understand the `cvxpy_solver` keyword argument when instantiating DKI objects.
Require `cvxpy` when instantiating a DKI model with the `NLS` fit method in `test_dki_errors`.
- Use the `CLARABEL` `cvxpy` solver.
- Extract the single element in the retuned directional kurtosis array.
- Capture and test the convexity level warning.
Fixes:
```
reconst/tests/test_dki.py::test_dki_fits
/dipy/venv/lib/python3.10/site-packages/cvxpy/reductions/solvers/solving_chain.py:336:
FutureWarning:
Your problem is being solved with the ECOS solver by default. Starting in
CVXPY 1.5.0, Clarabel will be used as the default solver instead. To continue
using ECOS, specify the ECOS solver explicitly …
```
> ENH: Fix miscellaneous warnings in `dki` reconstruction module

- dipy/data/__init__.py
- dipy/data/fetcher.py
- dipy/workflows/tests/test_io.py
- doc/examples/reconst_dki.py
This PR adds DiSCo challenge data fetcher for tractography tutorials, benchmarks and tests.
More information about this dataset in the following link: DOI: 10.17632/fgf86jdfg6.2
4 fetchers has been added:
- `fetch_disco_dataset`  -> 4.94 GB (contains disco1 + disco2+disco3)
- `fetch_disco1_dataset` -> 1.65 GB
- `fetch_disco2_dataset` -> 1.65 GB
-  `fetch_disco3_dataset` -> 1.65 GB
> [NF] Add DiSCo challenge data fetcher

- dipy/workflows/tests/test_reconst_dki.py
- dipy/workflows/tests/test_reconst_dti.py
Fixes issue here https://github.com/dipy/dipy/pull/3153#issuecomment-2053689778.
I considered setting `legacy=False` in `peaks_from_model` but I only saw that in tests so I figured best just to capture and ignore the warning.
> MAINT: fix warning

- .github/workflows/test_template.yml
- dipy/conftest.py
This PR adds a new flag to pytest to turn uncaught warnings into errors. We use `hookimpl` feature to enable this.
This flag is mandatory with the CI's but optional when you run your test locally. to activate it locally just do:
`pytest --warnings-as-errors -svv dipy/viz` for example.
you can also use an environment variable to activate it. `export DIPY_WERRORS=1`
Supersed #3201 
here an output example:
> [TEST] Add flag to turn warnings into errors for pytest

- dipy/denoise/nlmeans_block.pyx
- dipy/direction/ptt_direction_getter.pyx
- dipy/segment/clusteringspeed.pyx
- dipy/segment/cythonutils.pyx
- dipy/segment/featurespeed.pyx
- dipy/segment/metricspeed.pyx
- dipy/segment/mrf.pyx
- dipy/tracking/distances.pyx
- dipy/utils/fast_numpy.pyx
Use `cnp.npy_intp` instead of `int` to as a counter/to iterate over arrays/as.
> BF: Use `cnp.npy_intp` instead of `int` as counter

- dipy/align/parzenhist.pyx
Fix Cython method parameter type description.
> DOC: Fix Cython method parameter type description

- dipy/direction/peaks.py
- dipy/direction/tests/test_peaks.py
- dipy/tracking/tests/test_utils.py
- dipy/tracking/utils.py
This PR is related to #3089. It adds 2 functions:
- The function `dipy.direction.peaks.peaks_from_positions(.)` allows for extracting peaks at any 3D positions of an ODF image.
- The function `dipy.tracking.utils.seeds_directions_pairs(.)` allows matching seeds positions to the corresponding peaks. If more than 1 peak is available and selected at the position, the seed position is repeated for each peak. The output is 2 arrays of shape (N,3) corresponding to all selected peaks and their location.
Examples using those functions for tractography will be included in #3089.
> NF - initial directions from seed positions

- dipy/denoise/denspeed.pyx
- dipy/denoise/pca_noise_estimate.pyx
Declare variables holding the result of an integer product as `cnp.npy_intp` instead of `double` in denoising Cython code.
Fixes:
```
dipy/denoise/denspeed.cp39-win_amd64.pyd.p/denspeed.c(21239):
warning C4244: '=': conversion from 'npy_intp' to 'double', possible loss of data
```
and
```
dipy/denoise/pca_noise_estimate.cp39-win_amd64.pyd.p/pca_noise_estimate.c(20299):
warning C4244: '=': conversion from 'npy_intp' to 'double', possible loss of data
```
https://github.com/dipy/dipy/actions/runs/8822497881/job/24220827033#step:8:268
https://github.com/dipy/dipy/actions/runs/8822497881/job/24220827033#step:8:319
> BF: Declare variables holding integers as `cnp.npy_intp` over `double`

- pyproject.toml
Relocate `pre-commit` and `ruff` packages to `style` requirements.
> STYLE: Relocate `pre-commit` and `ruff` packages to style requirements

- dipy/tracking/tests/test_tracking.py
- dipy/utils/tests/test_deprecator.py
Python 3.13 will remove the deprecated alias `warn` from `logging`.
> Python 3.13: Fix tests for next Python release

- dipy/direction/closest_peak_direction_getter.pxd
- dipy/direction/closest_peak_direction_getter.pyx
- dipy/direction/pmf.pxd
- dipy/direction/pmf.pyx
- dipy/direction/probabilistic_direction_getter.pyx
- dipy/direction/ptt_direction_getter.pyx
- dipy/direction/tests/test_pmf.py
- dipy/utils/fast_numpy.pyx
To help the parallelization of the tracking framework, we needed to convert some memoryview to pointer and make sure that `nogil` is allowed. 
This change has no impact to the current tracking framework. This is a simple redesign. 
In a close future, we mightnneed to change the `pmf` object
> [RF] PMF Gen: from memoryview to pointer

- dipy/reconst/tests/test_shore.py
Fixes: https://github.com/dipy/dipy/issues/3165
See https://docs.pytest.org/en/7.4.x/how-to/xunit_setup.html
> tests: correct module-level setup

- dipy/direction/pmf.pxd
- dipy/direction/pmf.pyx
- dipy/direction/ptt_direction_getter.pyx
This PR removed an unnecessary argument `pmf_buffer` added in PR https://github.com/dipy/dipy/pull/3211
This is a speed and memory improvement. Because `get_pmf_value()` returns a double, the computation can be done for a single point on the sphere, rather than the whole sphere, thus removing the need for the buffer.
> RF - remove buffer argument in pmf_gen.get_pmf_value(.)

- dipy/align/reslice.py
- dipy/denoise/gibbs.py
- dipy/direction/peaks.py
`os.fork` is not recommended with multithread so forcing `spawn` on Linux. It was already the default setting for macOs and Windows. 
This should also remove the following warning for python3.12 on Linux:
```
=============================== warnings summary ===============================
align/tests/test_reslice.py: 8 warnings
denoise/tests/test_gibbs.py: 19 warnings
direction/tests/test_peaks.py: 22 warnings
workflows/tests/test_denoise.py: 1 warning
workflows/tests/test_reconst_csa_csd.py: 12 warnings
workflows/tests/test_reconst_rumba.py: 4 warnings
/opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/multiprocessing/popen_fork.py:66: DeprecationWarning: This process (pid=2605) is multi-threaded, use of fork() may lead to deadlocks in the child.
self.pid = os.fork()
```
> [RF] from `os.fork` to `spawn` for multiprocessing

- pyproject.toml
This PR is just a follow up of the discussion in #2593.
Since we adopted the no-warning policy, we needed a way to filterwarnings that was generated by optional dependencies during the import. 
Now, we handle that in the `conftest.py`.
> [CI] Move filterwarnings from pyproject to conftest 

- .codespellrc
- dipy/denoise/noise_estimate.py
- dipy/denoise/tests/test_noise_estimate.py
- dipy/viz/streamline.py
- dipy/viz/tests/test_streamline.py
- STYLE: Fix typo in view parameter `sagital`
- STYLE: Deprecate `l` parameter name in favor of `step` in PIESNO
> STYLE: Fix codespell issues

- dipy/data/fetcher.py
- doc/examples/afq_tract_profiles.py
This also adds the capability to download AFQ derivatives for all of the HBN subjects from the FCP INDI bucket where those are stored as part of the HBN POD2 study.
Addresses #3175, hopefully once and for all.
> DOC: Fixes the AFQ tract profile tutorial.

- dipy/nn/tests/test_evac.py
Rewrite list creation as `list()` instead of `[]`: place each item as a separate item in the list instea of having a single item in the list.
Fixes:
```
__________________________ test_default_weights_batch __________________________
(...)
>       results_arr = evac_model.predict(
input_arr, fake_affine, fake_voxsize, batch_size=2, return_prob=True
)
../venv/lib/python3.10/site-packages/dipy/nn/tests/test_evac.py:35:
(...)
if matrix.ndim == 2 and matrix.shape[1] != output.ndim:
>           raise RuntimeError('affine matrix has wrong number of columns')
E           RuntimeError: affine matrix has wrong number of columns
```
raised in:
https://github.com/dipy/dipy/actions/runs/9121652815/job/25081178023#step:10:7582
Inadvertently introudced in 23f978f.
> BF: Rewrite list creation as `list()` instead of `[]`

- dipy/align/_public.py
- dipy/align/imaffine.py
- dipy/align/imwarp.py
- dipy/core/sphere.py
- dipy/io/stateful_tractogram.py
- dipy/io/streamline.py
- dipy/nn/cnn_1d_denoising.py
- dipy/nn/evac.py
- dipy/reconst/mapmri.py
- dipy/tracking/local_tracking.py
- dipy/tracking/metrics.py
- dipy/utils/tractogram.py
- dipy/viz/horizon/app.py
- dipy/workflows/align.py
- dipy/workflows/io.py
- dipy/workflows/tests/test_stats.py
- doc/examples/reconst_ivim.py
- doc/examples/snr_in_cc.py
Simplify implicitly concatenated strings of the form:
```
msg = "first part of string " + "second part of string"
```
to a single string, i.e.
```
msg = "first part of string second part of string"
```
Related to the `ISC001` `ruff` rule.
> STYLE: Simplify implicitly concatenated strings

- dipy/reconst/csdeconv.py
Fix function definition loop variable binding warning.
Fixes:
```
dipy/reconst/csdeconv.py:531:31:
B023 Function definition does not bind loop variable `j`
dipy/reconst/csdeconv.py:540:31:
B023 Function definition does not bind loop variable `j`
```
https://github.com/dipy/dipy/actions/runs/9141052535/job/25135036670?pr=3228#step:4:114
> STYLE: Fix function definition loop variable binding warning

- dipy/io/dpy.py
- dipy/reconst/dsi.py
- dipy/tracking/metrics.py
Do not allow running as scripts modules that are not intended for that: remove the `if __name__ == "__main__": pass` statements.
> STYLE: Do not allow running unintended modules as scripts

- doc/examples/combined_workflow_creation.py
Fix unused loop control variable warning: show how to specify multiple output filenames for a combined workflow, and provide them to the corresponding sub-workflows.
Fixes:
```
doc/examples/combined_workflow_creation.py:68:22:
B007 Loop control variable `out_file` not used within loop body
```
https://github.com/dipy/dipy/actions/runs/9131684633/job/25111443178#step:4:116
> STYLE: Fix unused loop control variable warning

- dipy/direction/__init__.py
- ruff.toml
Import explicitly `direction.peaks` symbols.
Fixes:
```
dipy/direction/__init__.py:3:1: F403
`from .peaks import *` used; unable to detect undefined names
```
https://github.com/dipy/dipy/actions/runs/9045357134/job/24855013530#step:4:281
Remove the corresponding rule from the `ruff` per-file ignore list.
> STYLE: Import explicitly `direction.peaks` symbols

- benchmarks/benchmarks/bench_reconst.py
- dipy/segment/tests/test_fss.py
Prefer using `isin` over `in1d` in preparation for full NumPy 2.0 compatibility.
Fixes:
```
segment/tests/test_fss.py::test_fss_radius_search
dipy/venv/lib/python3.12/site-packages/dipy/segment/tests/test_fss.py:96:
DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
assert_true(np.all(np.in1d(rs_f1_sd.row, rs_f2_in_f1.row)))
```
reported for example in:
https://github.com/dipy/dipy/actions/runs/9605741685/job/26493943578?pr=3266#step:10:10205
> STYLE: Prefer using `isin` over `in1d`

- dipy/align/_public.py
Just fixes an issue where params were listed in the wrong order.
FYI if you haven't considered it, you could use [numpydoc's checks](https://numpydoc.readthedocs.io/en/latest/validation.html#built-in-validation-checks) in your doc build to catch this particular error with something like:
```
numpydoc_validate = True
numpydoc_validation_checks = {"PR03"}
```
But it looks like you use some custom vendored version (?) so you'd need to switch back to the official one.
As a numpydoc maintainer I'm also curious why you vendor your own parser. :thinking:
> DOC: Fix param order

- dipy/denoise/gibbs.py
- DOC: Add missing optional label to optional parameter docstring
- RF: Do not use `np.any` for checking optional array parameters
> RF: Do not use `np.any` for checking optional array parameters

- dipy/core/interpolation.pyx
- dipy/core/sphere.py
- dipy/reconst/dki.py
- dipy/reconst/dki_micro.py
- dipy/reconst/dti.py
- dipy/reconst/eudx_direction_getter.pyx
- dipy/reconst/fwdti.py
- dipy/reconst/msdki.py
- dipy/reconst/qti.py
- dipy/reconst/sfm.py
- dipy/tracking/utils.py
Prefer using `np.asarray` to avoid copy while creating an array in preparation for full NumPy 2.0 compatibility.
Fixes:
```
FAILED core/tests/test_interpolation.py::test_TriLinearInterpolator -
ValueError: Unable to avoid copy while creating an array as requested.
If using `np.array(obj, copy=False)` replace it with `np.asarray(obj)`
to allow a copy when needed (no behavior change in NumPy 1.x).
```
https://github.com/dipy/dipy/actions/runs/9605741685/job/26493943578?pr=3266#step:10:7997
> STYLE: Prefer using `np.asarray` to avoid copy while creating an array

- dipy/segment/tests/test_mrf.py
We applied this patch in Debian to fix https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1053265
> TEST: avoid direct comparison of floating point numbers

- dipy/align/imwarp.py
- dipy/reconst/mcsd.py
- dipy/stats/tests/test_qc.py
- dipy/tracking/tests/test_tracking.py
- doc/examples/linear_fascicle_evaluation.py
Avoid deprecated NumPy types and methods in preparation for full NumPy 2.0 compatibility.
Fixes:
```
dipy/align/imwarp.py:1585:13: NPY201 [*]
`np.row_stack` will be removed in NumPy 2.0.
Use `numpy.vstack` instead.
dipy/reconst/mcsd.py:411:18: NPY201 [*]
`np.NaN` will be removed in NumPy 2.0.
Use `numpy.nan` instead.
dipy/stats/tests/test_qc.py:69:13: NPY201 [*]
`np.row_stack` will be removed in NumPy 2.0.
Use `numpy.vstack` instead.
dipy/stats/tests/test_qc.py:70:32: NPY201 [*]
`np.row_stack` will be removed in NumPy 2.0.
Use `numpy.vstack` instead.
dipy/tracking/tests/test_tracking.py:1168:13:
NPY201 [*] `np.row_stack` will be removed in NumPy 2.0.
Use `numpy.vstack` instead.
doc/examples/linear_fascicle_evaluation.py:165:17:
NPY201 [*] `np.row_stack` will be removed in NumPy 2.0.
Use …
```
> STYLE: Avoid deprecated NumPy types and methods for NumPy 2.0 compat

- dipy/core/interpolation.pyx
- dipy/core/tests/test_interpolation.py
Fixes #3236.
This PR adds support for tensor-valued spherical functions in `interp_rbf`. When the user calls this function, specifying `legacy=True` internally uses `scipy.interpolate.Rbf` which is the original behavior; specifying `legacy=False` internally uses `scipy.interpolate.RBFInterpolator`, which allows `data` to have arbitrary dimensions. 
It would be great if I could get some feedbacks on the following questions:
* I saw the kwarg `norm` is already pending deprecation and is not used in `scipy.interpolate.RBFInterpolator`. As of my initial commit, `norm` is ignored when `legacy=False`. Do we still want to keep `norm`?
* In the docstring, `function` is said to be one of `{'multiquadric', 'inverse', 'gaussian'}`, but both `scipy.interpolate.Rbf` and …
> Add support for tensor-valued spherical functions in `interp_rbf`

- dipy/reconst/tests/test_mapmri.py
- dipy/testing/__init__.py
- pyproject.toml
> A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.
make sure that we always build DIPY with `numpy>=2.0.0rc1`
> RF: Update pyproject.toml for numpy 2.0

- .github/workflows/test_optional.yml
- .github/workflows/test_parallel.yml
- .github/workflows/test_template.yml
- dipy/reconst/csdeconv.py
- dipy/reconst/dsi.py
- dipy/reconst/forecast.py
- dipy/reconst/fwdti.py
- dipy/reconst/gqi.py
- dipy/reconst/ivim.py
- dipy/reconst/mapmri.py
- dipy/reconst/mcsd.py
- dipy/reconst/multi_voxel.py
- dipy/reconst/qtdmri.py
- dipy/reconst/sfm.py
- dipy/reconst/shore.py
- dipy/reconst/tests/test_multi_voxel.py
- dipy/utils/parallel.py
- pyproject.toml
- tools/ci/install_dependencies.sh
I've started playing around with the idea that the multi_voxel_fit decorator could use `paramap` instead of iterating over voxels. If we can make this work generally that would be pretty cool. So far, I've only tested this with the fwdti model, and in that case, the change to the additional changes to the code are rather minimal, which gives me hope that we might be able to use this wherever we use this decorator, so in csd, dsi, forecast, fwdti, gqi, ivim, mapmri, mcsd, qtdmri, and shore (!).
> Embed parallelization into the multi_voxel_fit decorator.

- dipy/stats/analysis.py
- dipy/stats/qc.py
- dipy/stats/resampling.py
- dipy/stats/tests/test_qc.py
- dipy/testing/decorators.py
- dipy/testing/tests/test_decorators.py
This PR introduces new feature of decorator function for Keyword-Only arguments as mentioned in issue #3029.
- Added Decorator function in decorators.py
- Added Testing function in test_decorators.py
- Added decorator function to functions in stats module
- #3029
> NF: Decorator for keyword-only argument

- dipy/testing/tests/test_testing.py
- ruff.toml
Set `stacklevel` argument explicitly to warning messages in
`testing.tests.test_testing.py` module. Set its value to 1, as opposed
to the `ruff` recommendation of using 2 [1], since otherwise the tests
do not pass: the `__warningregistry__` seems not to be created (and
cannot be queried) otherwise. This is related to the fact that the
`stacklevel` option to warnings causes the attribute to be set for the
module the warning was issued "in the name of", not necessarily the one
where `warn()` was called, e.g. if we specify a value larger than 1.
Fixes:
```
dipy/testing/tests/test_testing.py:52:9:
B028 No explicit `stacklevel` keyword argument found
dipy/testing/tests/test_testing.py:56:9:
B028 No explicit `stacklevel` keyword argument found
dipy/testing/tests/test_testing.py:60:9:
B028 No …
```
> STYLE: Set `stacklevel` argument explicitly to warning messages

- dipy/denoise/enhancement_kernel.pyx
This PR solves the following error:
```  
Error compiling Cython file:
------------------------------------------------------------
...
rng = np.random.default_rng()
if isinstance(orientations, Sphere):
sphere = orientations
elif isinstance(orientations, (int, long, float)):
^
------------------------------------------------------------
/Users/devel/dipy/dipy/denoise/enhancement_kernel.pyx:81:44: undeclared name not builtin: long
```
This error appear with the latest development version of cython. it should fix the `PRE` matrix
> FIX: Explicit type origin for long to solve the cython error during compilation

- dipy/core/gradients.py
- dipy/core/tests/test_gradients.py
- doc/examples/quick_start.py
Add the `__len__` method to `GradientTable`: adds the ability to query the number of gradients using `len()`.
Add the corresponding tests.
Add a doctest example.
Demonstrate it in the `Getting started with DIPY` `Quick Start` documentation section.
Resolves #3282.
> NF: Add `__len__` to `GradientTable`

- .github/workflows/nightly.yml
small PR to fix our nightly wheels for macOS arm64.
We were encountering the following error:
```
delocate.libsana.DelocationError: Library dependencies do not satisfy target MacOS version 11.0:
/private/var/folders/h9/l1shxhdd69nct08ylzq0n6q00000gn/T/tmpws13eaj7/wheel/dipy/.dylibs/libomp.dylib has a minimum target of 14.0
``` 
So, the `MACOSX_DEPLOYMENT_TARGET` environment variable should fix this issue.
> FIX: nighlty wheels for macOS arm64

- README.rst
- dipy/align/streamlinear.py
- dipy/core/gradients.py
- dipy/denoise/nlmeans.py
- dipy/reconst/base.py
- dipy/reconst/csdeconv.py
- dipy/reconst/dki.py
- dipy/reconst/dki_micro.py
- dipy/reconst/dsi.py
- dipy/reconst/dti.py
- dipy/reconst/fwdti.py
- dipy/reconst/mcsd.py
- dipy/reconst/msdki.py
- dipy/reconst/rumba.py
- dipy/reconst/sfm.py
- dipy/segment/bundles.py
- dipy/sims/voxel.py
- dipy/tracking/life.py
- dipy/workflows/align.py
- doc/api_changes.rst
- doc/devel/make_release.rst
- doc/examples/denoise_mppca.py
- doc/examples/denoise_patch2self.py
- doc/examples/fast_streamline_search.py
- doc/examples/reconst_dki.py
- doc/examples/reconst_dki_micro.py
- doc/examples/reconst_mcsd.py
- doc/examples/reconst_msdki.py
- DOC: Add documentation build action status badge to README
- DOC: Enclose absolute value math expression within LaTeX markup
- DOC: Add missing description to parameters across methods
- DOC: Add blank line before list
- DOC: Remove unnecessary indentation in documentation block
- DOC: Remove unnecessary indentations in citation text in examples
- DOC: Indent appropriately documentation block after `note` directive
- DOC: Use accurate citation cross-reference keys
> DOC: Miscellaneous doc formatting fixes (part 3)

- doc/references.bib
Use `misc` for other types of BibTeX entries: `dataset` and `electronic` entries are supported by `biblatex` but not by BibTeX, so use `misc` for such types.
> DOC: Use `misc` for other types of BibTeX entries

- dipy/reconst/cti.py
- dipy/reconst/dki.py
- doc/cite.rst
- doc/conf.py
- doc/devel/bibliography.rst
- doc/doc-requirements.txt
- doc/examples/gradients_spheres.py
- doc/references.bib
- doc/user_guide/bibliography.rst
- doc/user_guide/index.rst
> build succeeded, 1871 warnings.
A lot of those warning are due to references. This PR add `sphinxcontrib-bibtex` to manage references, avoid duplication, avoid formatting error, etc. 
This PR will take a bit of time to be finalize so I wonder if I should split it in multiple PR or not.  It should make review process easier. Looking forward for your feedback.
> [DOC] introducing sphinxcontrib-Bibtex to improve reference management

- dipy/align/streamlinear.py
- dipy/data/fetcher.py
- dipy/denoise/gibbs.py
- dipy/denoise/shift_twist_convolution.pyx
- dipy/reconst/csdeconv.py
- dipy/reconst/cti.py
- dipy/reconst/dki.py
- dipy/reconst/dti.py
- dipy/reconst/fwdti.py
- dipy/reconst/gqi.py
- dipy/reconst/ivim.py
- dipy/reconst/msdki.py
- dipy/reconst/qtdmri.py
- dipy/reconst/shm.py
- dipy/segment/bundles.py
- dipy/sims/voxel.py
- dipy/tracking/streamline.py
- dipy/viz/horizon/app.py
- dipy/workflows/align.py
- doc/examples/reconst_msdki.py
- DOC: Use the appropriate Python data type to document parameter
- DOC: Enclose absolute value math expression within LaTeX markup
- DOC: Increase consistency in default cvxpy solver docstrings
- DOC: Fix typos and grammar
- STYLE: Remove unused import
- DOC: Improve explanation on DIPY's default download data folder
- DOC: Add missing doctrings to method input parameters
- DOC: Use the appropriate indentation in docstrings
- DOC: Match docstring parameter names with names in function signature
- DOC: Remove non-existing parameter docstring
> DOC: Miscellaneous documentation improvements (part 2)

- dipy/reconst/qtdmri.py
- dipy/workflows/multi_io.py
- dipy/workflows/workflow.py
Use a leading underscore to name private methods: using a trailing underscore is translated by Sphinx into the same method name as its underscoreless counterpart.
Fixes:
```
/dipy/dipy/doc/reference/dipy.workflows.rst:651:
ERROR: Duplicate target name, cannot be used as a unique reference: "io_iterator".
```
and similar errors raised for example in:
https://github.com/dipy/dipy/actions/runs/10472634043/job/29002561651#step:5:1146
Documentation:
https://peps.python.org/pep-0008/#method-names-and-instance-variables
> STYLE: Use a leading underscore to name private methods

- dipy/align/_public.py
- dipy/align/imaffine.py
- dipy/align/streamlinear.py
- dipy/reconst/cti.py
- dipy/reconst/dki.py
- dipy/reconst/fwdti.py
- dipy/reconst/qti.py
- dipy/segment/bundles.py
- DOC: Fix typos and grammar
- DOC: Format properly returned parameter docstrings
- DOC: Make the parameter type dwell on a single line
- DOC: Indent appropriately a parameter docstring
- DOC: Enclose inline literal in double bacticks
- DOC: Add description to parameter docstring
- DOC: Use the appropriate indentation in docstrings
- DOC: Add parameter name/type line to return docstring
- DOC: Add an empty line before list items
- DOC: Indent appropriately enumerated lists
> DOC: Miscellaneous documentation improvements (part 3)

- .github/workflows/test_optional.yml
- .github/workflows/test_template.yml
- doc/doc-requirements.txt
- pyproject.toml
We are getting these errors below with the 1.5.x serie of CVXPY
```python
=========================== short test summary info ===========================
FAILED reconst/tests/test_qti.py::test_cvxpy_1x6_to_3x3 - TypeError: reshape() takes from 1 to 2 positional arguments but 3 were given
FAILED reconst/tests/test_qti.py::test_cvxpy_1x21_to_6x6 - TypeError: reshape() takes from 1 to 2 positional arguments but 3 were given
FAILED reconst/tests/test_qti.py::test_ls_sdp_fits - AssertionError: 
Arrays are not almost equal to 2 decimals
Mismatched elements: 24 / 56 (42.9%)
Max absolute difference among violations: 0.3333333333333333
Max relative difference among violations: 1.0
ACTUAL: array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
0.,  0.,  0.,  0.,  0.,  0.,  0., …
```
> CI: pin cvxpy  to 1.4.4 until 1.5.x issues are solved

- dipy/align/streamlinear.py
- dipy/workflows/align.py
- doc/cite.rst
- doc/references.bib
- doc/user_guide/bibliography.rst
Use references bibliography file for DIPY citation file.
Add missing citations to `references.bib`.
Add a missing comma after the `Garyfallidis2014` cite key (now renamed to `Garyfallidis2014` since another work from the same author/year is added in this commit).
Remove the `:list: enumerated` flag in `bibliography.rst` to avoid
```
/home/runner/work/dipy/dipy/doc/cite.rst:5:
WARNING: could not find bibtex key "Garyfallidis2014a"
```
and similar errors.
> DOC: Use references bibliography file for DIPY citation file

- doc/sphinxext/github.py
- doc/sphinxext/math_dollar.py
Small PR to allow parallel processing during doc generation for our sphinx extension.
It should also fix the following warning during doc generation: 
`{extension_name} extension does not declare if it is safe for parallel reading, assuming it isn't - please ask the extension author to check and make it explicit`
> RF: Allow parallel processing for sphinx extension

- dipy/core/onetime.py
- dipy/nn/deepn4.py
- dipy/nn/evac.py
- dipy/nn/synb0.py
- dipy/nn/tests/test_evac.py
- dipy/reconst/dki.py
- dipy/reconst/mapmri.py
- dipy/testing/decorators.py
- dipy/testing/tests/test_decorators.py
- dipy/viz/horizon/app.py
- dipy/viz/horizon/tab/peak.py
- dipy/viz/horizon/tab/tests/test_base.py
- dipy/viz/horizon/visualizer/peak.py
- dipy/viz/tests/test_apps.py
- dipy/viz/tests/test_streamline.py
- dipy/workflows/nn.py
- dipy/workflows/stats.py
- dipy/workflows/tests/test_viz.py
This PR refactors the version handling logic in the warning_for_keywords decorator by using the packaging module for parsing and comparing versions.
- Added packaging.version.parse for accurate version parsing.
- Improved version comparisons by using the base_version attribute, which removes any pre-release or development suffixes.
This change improves the reliability of version-based warnings and argument handling in the decorator.
> RF: Decorator fix

- dipy/data/fetcher.py
- doc/references.bib
Host MNI template note references in references file.
Fixes:
```
/home/runner/work/dipy/dipy/doc/reference/dipy.data.rst:11:
WARNING: Citation [Rdd61b42961d4-1] is not referenced.
/home/runner/work/dipy/dipy/doc/reference/dipy.data.rst:16:
WARNING: Citation [Rdd61b42961d4-2] is not referenced.
/home/runner/work/dipy/dipy/doc/reference/dipy.data.rst:36:
WARNING: Citation [R85b62a945869-1] is not referenced.
/home/runner/work/dipy/dipy/doc/reference/dipy.data.rst:41:
WARNING: Citation [R85b62a945869-2] is not referenced.
```
https://github.com/dipy/dipy/actions/runs/10603092244/job/29386606308#step:5:1016
> DOC: Host MNI template note references in references file

- doc/examples/denoise_patch2self.py
- doc/interfaces/denoise_flow.rst
Do not use the `scale` option for URL-based images as Sphinx cannot determine the image size from a URL:
- Remove the option for the `denoise_flow` images, as they are embedded in a table cell and will use the available cell width by default.
- Use the `image` directive and the `width` option for `denoise_patch2self` (in lieu of the `figure` directive). Make the `width` value be 70% as it provides a reasonably looking result.
Fixes:
```
/dipy/doc/examples_built/preprocessing/denoise_patch2self.rst::
WARNING: Could not obtain image size. :scale: option is ignored.
```
and
```
/dipy/doc/interfaces/denoise_flow.rst:103:
WARNING: Could not obtain image size. :scale: option is ignored.
/dipy/doc/interfaces/denoise_flow.rst:106:
WARNING: Could not obtain image size. :scale: option is ignored. …
```
> DOC: Do not use the `scale` option for URL-based images

- dipy/reconst/shm.py
- dipy/viz/horizon/tab/base.py
- DOC: Add blank line before displayed math `.. math::` directive
- DOC: Fix typo in method docstring return section name
- DOC: Document properly `viz.horizon.tab.base.build_slider` return params
- DOC: Document missing input arg in `viz.horizon.tab.base.build_slider`
- STYLE: Remove redundant parentheses in method return statement
> DOC: Fix miscellaneous documentation build warnings (part 3)

- doc/examples/denoise_gibbs.py
- doc/examples/denoise_localpca.py
- doc/examples/denoise_mppca.py
- doc/examples/motion_correction.py
- doc/examples/reconst_dki_micro.py
- doc/examples/reconst_dsid.py
- doc/examples/reconst_forecast.py
- doc/examples/reconst_msdki.py
- doc/examples/simulate_multi_tensor.py
- doc/examples/syn_registration_2d.py
- doc/examples/syn_registration_3d.py
This short PR fix some warnings on our tutorials.
All warnings were coming from keyword-only arguments feature recently added
> FIX: missing keyword only arguments on example

- doc/interfaces/bundlewarp_registration_flow.rst
Remove unnecessary leading whitespace in reStructuredText doc paragraph.
Fixes:
```
/dipy/doc/interfaces/bundlewarp_registration_flow.rst:53:
WARNING: Definition list ends without a blank line; unexpected unindent.
```
https://github.com/dipy/dipy/actions/runs/10812941556/job/29995758096#step:5:564
Appeared after PR https://github.com/dipy/dipy/pull/3221 was merged.
> DOC: Remove unnecessary leading whitespace in rst doc paragraph

- dipy/io/tests/test_stateful_tractogram.py
- dipy/segment/tests/test_bundles.py
- dipy/tracking/streamlinespeed.pyx
- dipy/utils/tests/test_tractogram.py
- dipy/workflows/tests/test_io.py
This PR fixes big-endian system (like s390x) compatibility. It fixes this particular error:
`E   ValueError: Little-endian buffer not supported on big-endian compiler`
Some tests had to be skipped due to TRX file format which seems to not be compatible with big endian system. We need to warn @arokem and @frheault  concerning `[trx-python](https://github.com/tee-ar-ex/trx-python)` package.
this fixes #2886
Thanks to [sharkcz](https://github.com/sharkcz) for giving me access to a s390x machine and Thanks to @penguinpee and @nteodosio for pushing this issue here.
if you have time, feel free to try this PR.
> BF: fix s390x compatibility

- doc/cite.rst
There was some mis-directions on this page: https://docs.dipy.org/stable/cite
> DOC: Fix some cites.

- dipy/sims/voxel.py
Make `rng` optional parameter docstrings consistent:
- Improve the description of the parameter and the behavior in the default case.
- Remove the default value from the parameter docstring.
- Remove the mention to "class" in the parameter type.
- Add the parameter docstring to the methods that were missing it.
> DOC: Make `rng` optional parameter docstrings consistent

- .github/workflows/nightly.yml
* scientific-python/upload-nightly-action v0.6.1 fixes a breaking bug in v0.6.0.
- c.f. https://github.com/scientific-python/upload-nightly-action/releases/tag/0.6.1
c.f. https://github.com/scientific-python/upload-nightly-action/issues/106
> ci: Bump scientific-python/upload-nightly-action from 0.6.0 to 0.6.1

- doc/examples/streamline_tools.py
Reference footnote in `streamline_tools`.
Fixes:
```
/dipy/doc/examples_built/streamline_analysis/streamline_tools.rst:336:
WARNING: Footnote [#] is not referenced. [ref.footnote]
```
https://github.com/dipy/dipy/actions/runs/11284383070/job/31385471672?pr=3373#step:5:686
> DOC: Reference footnote in `streamline_tools`

- dipy/viz/horizon/visualizer/peak.py
- DOC: Remove default values from `PeakActor` parameters docstrings
- DOC: Avoid splitting parameter type documentation over multiple lines
> DOC: Miscellaneous improvements to `PeakActor` docstring

- doc/conf.py
- doc/examples/_valid_examples.toml
- doc/sphinxext/prepare_gallery.py
this PR fixes #3347 and address the warnings:
```
/home/runner/work/dipy/dipy/doc/examples_built/reconstruction/index.rst:13: CRITICAL: Problems with "include" directive path:
InputError: [Errno 2] No such file or directory: 'examples_built/reconstruction_models_list.rst'.
```
The approach here is to preprocess the `..include`ndirectives before sphinx/sphinx-gallery which seems to be confused by this inclusion.
> doc: Link reconstruction model list to multiple pages

- .github/workflows/build_docs.yml
Consider warnings as errors in documentation CI build.
> DOC: Consider warnings as errors in documentation CI build

- doc/examples/streamline_tools.py
Use `_` as a placeholder for the unused `affine` variable in `streamline_tools` example when loading the Stanford dataset HARDI data. This reduces confusion as a few lines later the same variable is set to the identity matrix.
Follow-up to commit e6f5ab0.
> DOC: Use placeholder for unused variable in `streamline_tools`

- Makefile
- dipy/core/profile.py
- doc/Makefile
- doc/devel/installation_from_source.rst
- doc/devel/make_release.rst
- tools/osxbuild.py
- tools/toollib.py
This patch is from the Debian package for `dipy`.
> ensure all calls to a python executable are to `python3`

- dipy/viz/horizon/app.py
- dipy/viz/horizon/tab/slice.py
- dipy/viz/horizon/util.py
- dipy/viz/horizon/visualizer/slice.py
- dipy/viz/tests/test_util.py
This PR aims to support the new Atlas (Images with intensities from 0 to 0.9).
**Underlying issue:**
The slice visualizer in Horizon supported the intensity percentile from (2, 98), due to underlying errors from earlier versions of FURY when trying to move the slider to min or max values.
**Solution:**
The current minimum required version of the FURY does not have that issue. So, updating the percentile range will open the image properly.
**Additional Changes**
Fixed a method call where the `visibility` argument was not passed as a keyword argument. Resulting in user warnings.
> BugFix: New Atlas OMM not working with Horizon

- doc/conf.py
Skip element in documentation generation: add a function to the Sphinx setup in the configuration file so that the element at issue is not rendered when generating the documentation.
> DOC: Skip element in documentation generation

- .pre-commit-config.yaml
- dipy/nn/evac.py
- dipy/nn/utils.py
- dipy/segment/mask.py
- dipy/segment/meson.build
- dipy/segment/tests/meson.build
- dipy/segment/tests/test_utils.py
- dipy/segment/utils.py
- dipy/workflows/segment.py
- dipy/workflows/tests/test_segment.py
- ruff.toml
This PR aims to add a function that removes holes or islands of a binary mask to median_otsu.
The function was already being used in
dipy/nn/utils.py, so it has been moved to dipy/segment/utils.py, as it makes more sense for mask correction to be in segmentation module.
Slice-wise hole removal was excluded from the function, since it can cause huge false positives if there is a lack of axial slices.
Finally, the function's name has been changed to
remove_holes_and_islands, to be more explicit about the functionality.
This PR is related to #3124
> NF: Adding correct_mask to median_otsu

- dipy/denoise/non_local_means.py
- dipy/denoise/tests/test_non_local_means.py
Fixes #3285 
- Added the option for sigma to also be an ndarray so that it works nicely with the output of
estimate_sigma on a 4D dataset. Made the decision that if the input is scalar and arr is 4D, repeat input arr.shape[-1] times. That way the old behaviour when the input is a scalar on 4D arr is preserved while also allowing sigma to have multiple values in the final for loop. New code works with old tests.
- Added tests for the new checks.
- Updated non_local_means docs.
> BF: Updated non_local_means

- .github/CONTRIBUTING.md
Update the CI tool in `CONTRIBUTNG` file: the switch from Azure Pipelines and Travis CI took place across several commits in pull requests
https://github.com/dipy/dipy/pull/2315
https://github.com/dipy/dipy/pull/2518
and released as of version 1.5.0 (Mar 11, 2022).
> DOC: Update the CI tool to GHA in `CONTRIBUTING` file

- doc/tools/apigen.py
In some unique case, API generation seems to fail due to not finding a local DIPY installation.
This small PR fixes this issue. 
It was quite hard to reproduce this error. it happens only with editable installation.
> RF: fix API generation

- dipy/segment/tests/meson.build
- dipy/segment/tests/test_tissue.py
- dipy/segment/tissue.py
- doc/references.bib
This PR is for addition of tissue classifier method based on Directional Average maps based on the paper
Cheng, H., Newman, S., Afzali, M., Fadnavis, S. S., & Garyfallidis, E. (2020). Segmentation of the brain using direction-averaged signal of DWI images. Magnetic Resonance Imaging, 69, 1–7. https://doi.org/10.1016/j.mri.2020.02.010 .
Usage Example:
```
from dipy.io.gradients import read_bvals_bvecs
from dipy.io.image import load_nifti
from dipy.core.gradients import gradient_table
from dipy.segment.mask import median_otsu
import matplotlib.pyplot as plt
from dipy.segment.tissue import dam_classifier
data, affine = load_nifti("100307/T1w/Diffusion/data.nii.gz")
bvals, bvecs = read_bvals_bvecs("100307/T1w/Diffusion/bvals", "100307/T1w/Diffusion/bvecs")
gtab = gradient_table(bvals, bvecs) …
```
> [NF] DAM implementation for tissue classification using DMRI signal properties.

- doc/devel/index.rst
Remove empty quoted paragraph in developer guide index: remove the whitespace before the document label.
> STYLE: Remove empty quoted paragraph in developer guide index

- doc/examples/syn_registration_3d.py
- doc/recipes.rst
Exporting and importing Mapping field in Syn registration is a recurrent request. 
This PR adds this information:
- In the recipe as an How to
- in a tutorial which will help the user to understand the different steps.
This PR fixes #3361 and address https://github.com/dipy/dipy/discussions/3272 discussion
> DOC: Add Exporting and importing Mapping field information in recipes and registration tutorial

- dipy/reconst/dti.py
- dipy/reconst/tests/test_dti.py
this PR fixes #3030
It warns user that `step` can not be used for NLLS.
This is a problem found by @captainnova. Can you have a quick look into it. Thanks!
> RF: fix step argument in DTI NLLS model

- dipy/workflows/reconst.py
- pyproject.toml
- tools/ci/run_tests.sh
This is a follow-up of #3415.
it should address the following warnings:
```
../venv/lib/python3.10/site-packages/_pytest/cacheprovider.py:445
/home/runner/work/dipy/dipy/venv/lib/python3.10/site-packages/_pytest/cacheprovider.py:445: PytestCacheWarning: could not create cache path /home/runner/work/dipy/dipy/for_testing/.pytest_cache/v/cache/nodeids: [Errno 13] Permission denied: '/home/runner/work/dipy/dipy/for_testing/.pytest_cache'
config.cache.set("cache/nodeids", sorted(self.cached_nodeids))
../venv/lib/python3.10/site-packages/_pytest/cacheprovider.py:397
/home/runner/work/dipy/dipy/venv/lib/python3.10/site-packages/_pytest/cacheprovider.py:397: PytestCacheWarning: could not create cache path /home/runner/work/dipy/dipy/for_testing/.pytest_cache/v/cache/lastfailed: [Errno 13] …
```
> CI: define output path for coverage

- dipy/reconst/sfm.py
This PR address the following warning
```
/home/runner/work/dipy/dipy/venv/lib/python3.12/site-packages/joblib/parallel.py:598: UserWarning: Pass ['parallel'] as keyword args. From version 2.0.0 passing these as positional arguments will result in an error.
```
this is a warning that you can see in the PRE-CI's
> RF: fix joblib warning in sfm 

- doc/conf.py
When building the docs and determining the current year for the copyright entry: If the environment variable [`$SOURCE_DATE_EPOCH`](https://reproducible-builds.org/docs/source-date-epoch/) is defined, use that instead of `time.time()`.
Without this patch, building the dipy docs using a source release from a prior year would result in different output;  hampering reproducible builds.
This issue was discovered by the Debian reproducibility test for dipy: https://tests.reproducible-builds.org/debian/rb-pkg/unstable/amd64/diffoscope-results/dipy.html (there are other reproducibility issues, but they are `cython`'s issues, not the fault of dipy)
> Make the docs more reproducible

- dipy/meson.build
Add type annotation information: add the `py.typed` file and distribute the type information with the package by adding the corresponding entry in the `pyproject.toml` file  so that third-party tools can use the DIPY type annotation information.
Documentation:
https://typing.readthedocs.io/en/latest/spec/distributing.html#packaging-typed-libraries
> ENH: Add type annotation information

- benchmarks/benchmarks/bench_tracking.py
- dipy/nn/tf/cnn_1d_denoising.py
- dipy/tracking/streamline.py
- dipy/tracking/streamlinespeed.pyx
- dipy/viz/horizon/app.py
- doc/examples/bundle_extraction.py
Transition remaining `NumPy` `random` module `RandomState` instances to `Generator` instances following the deprecation of the former.
Documentation:
https://numpy.org/doc/2.1/reference/random/new-or-different.html#what-s-new-or-different
Change the relevant docstrings accordingly.
Left behind in commit abbfbb6.
> ENH: Transition remaining `NumPy` `RandomState` instances to `Generator`

- dipy/core/sphere.py
- dipy/core/tests/test_sphere.py
This PR fixes #3431.
This import does not need to be optional since Scipy is a mandatory dependency. 
This is mainly an update of legacy code.
> TEST: remove skip if not have_delaunay

- dipy/reconst/csdeconv.py
- dipy/reconst/shm.py
- dipy/reconst/tests/test_shm.py
- dipy/utils/compatibility.py
- dipy/utils/meson.build
- dipy/utils/tests/meson.build
- dipy/utils/tests/test_compatibility.py
Since the last release of Scipy (1.15.0, on January 3, 2025), many functions have been deprecated in `scipy.special` module.
for this reason, we encounter a bunch of warnings as you can see below. 
This PR fixes those issues.
```python
/home/runner/work/dipy/dipy/venv/lib/python3.10/site-packages/dipy/reconst/shm.py:235: DeprecationWarning: `scipy.special.sph_harm` is deprecated as of SciPy 1.15.0 and will be removed in SciPy 1.17.0. Please use `scipy.special.sph_harm_y` instead.
return sps.sph_harm(m_values, l_values, theta, phi, dtype=complex)
direction/tests/test_peaks.py: 2 warnings
reconst/tests/test_csdeconv.py: 1 warning
reconst/tests/test_shm.py: 24 warnings
workflows/tests/test_reconst_csa_csd.py: 9 warnings
/home/runner/work/dipy/dipy/venv/lib/python3.10/site-packages/dipy/recons …
```
> RF: Update ``scipy.special`` deprecated functions

- dipy/nn/__init__.py
- dipy/nn/tests/test_cnn_1denoiser.py
- dipy/nn/tests/test_deepn4.py
- dipy/nn/tests/test_evac.py
- dipy/nn/tests/test_histo_resdnn.py
- dipy/nn/tests/test_synb0.py
- dipy/nn/tests/test_tf.py
- dipy/nn/tf/cnn_1d_denoising.py
- dipy/nn/tf/deepn4.py
- dipy/nn/tf/evac.py
- dipy/nn/tf/histo_resdnn.py
- dipy/nn/tf/model.py
- dipy/nn/tf/synb0.py
- dipy/workflows/tests/test_nn.py
- pyproject.toml
This PR just bumps TensorFlow minimal version to 2.18.0. This is the first version compatible to numpy 2.0 and we need to enforce that to avoid weird error.
> RF: bump tensorflow minimal version to 2.18.0.

- .github/workflows/benchmark.yml
- benchmarks/benchmarks/bench_tracking.py
- pyproject.toml
Add GitHub CI workflow file to run benchmarks using `asv`.
Add the corresponding new `benchmark` section to the project optional dependencies in `pyproject.toml`
> ENH: Add GitHub CI workflow file to run benchmarks using `asv`

- dipy/direction/peaks.py
- dipy/direction/pmf.pyx
- dipy/direction/tests/test_peaks.py
- dipy/direction/tests/test_pmf.py
- dipy/direction/tests/test_prob_direction_getter.py
This PR adds a new optional argument to `dipy.direction.peaks.peaks_from_positions`. When provided, positional arguments `odfs` and `sphere` are ignored. This is needed in PR #3089.
-added the corresponding tests
-The error `ValueError("pmf should not have negative values.")`  was removed from `SimplePmfGen` for consistency with `SHCoeffPmfGen` and to allow interpolation of odfs with negative value. Negative values were already tolerated/managed in the tracking functions using `pmf_gen` because of `SHCoeffPmfGen`.
> RF - add pmf_gen argument to peaks_from_positions

- dipy/core/math.pxd
- dipy/core/math.pyx
- dipy/core/meson.build
- dipy/core/tests/meson.build
- dipy/core/tests/test_math.pyx
- dipy/direction/peaks.py
- dipy/reconst/dirspeed.pyx
- dipy/reconst/meson.build
- dipy/reconst/recspeed.pxd
- dipy/reconst/recspeed.pyx
- dipy/utils/fast_numpy.pxd
- dipy/utils/fast_numpy.pyx
- dipy/utils/tests/test_fast_numpy.pyx
This PR will allow the use of nogil in the following methods:
- peak_directions_c
- local_maxima_c
- search_descending_c
- remove_similar_vertices_c
Multiple refactor has been made to make it possible. This work has been made to facilitate the integration of some algoritms for the parallel tracking work #3089.
> RF: update of peak_directions to allow nogil

- dipy/io/peaks.py
There was a minor change in the deprecation warning, it says 
"Please usedipy.io.peaks.save_pam" 
So corrected the spacing
> Spelling error in the deprecation warning

- doc/examples/tracking_fast_tractography.py
our build_docs CI was failing due to some markup issues in the tracking tutorial.
This PR fixes the problem below:
```
/home/runner/work/dipy/dipy/doc/examples_built/multiprocessing/tracking_fast_tractography.rst:185: WARNING: Explicit markup ends without a blank line; unexpected unindent. [docutils]
/home/runner/work/dipy/dipy/doc/examples_built/multiprocessing/tracking_fast_tractography.rst:229: WARNING: Explicit markup ends without a blank line; unexpected unindent. [docutils]
/home/runner/work/dipy/dipy/doc/examples_built/multiprocessing/tracking_fast_tractography.rst:273: WARNING: Explicit markup ends without a blank line; unexpected unindent. [docutils]
/home/runner/work/dipy/dipy/doc/examples_built/multiprocessing/tracking_fast_tractography.rst:313: WARNING: Explicit markup ends …
```
> DOC: fix markup issues with tracking tutorial

- dipy/workflows/align.py
- dipy/workflows/base.py
- dipy/workflows/denoise.py
- dipy/workflows/io.py
- dipy/workflows/mask.py
- dipy/workflows/nn.py
- dipy/workflows/reconst.py
- dipy/workflows/segment.py
- dipy/workflows/stats.py
- dipy/workflows/tests/test_iap.py
- dipy/workflows/tracking.py
- dipy/workflows/viz.py
When an user is calling the help of a CLI, having the default value of argument can be very helpful, especially when you want to tune it.
This PR adds a function to automatically adds the default value in the docstring.
to check it, just call the help of a cli (e.g `dipy_fit_csa --help`) and you should see all the default value of a CLI.
fixes #3454
> NF: Add default value to docstring for the CLI

- dipy/workflows/io.py
- dipy/workflows/tests/test_io.py
In some case, this cli was failing because a `bvecs` were missing. 
However, bvecs are not really needed in this case so we generate a random one to avoid any issue.
Can you try @iprajwalreddy?
> RF: Enforce bvecs for the cli extract_b0 

- dipy/data/fetcher.py
- dipy/data/tests/test_fetcher.py
- dipy/tracking/tests/test_tracker.py
- dipy/tracking/tests/test_tractogen.pyx
- dipy/workflows/io.py
- doc/examples/tracking_fast_tractography.py
This PR allows our fetcher to have optional data.
Disco datasets are too big, it allows a faster download and the user can include optional dataset via a flag/keyword argument
fixes #3190
> NF: Add optional fetcher

- dipy/tracking/tests/test_tracker.py
- dipy/tracking/tracker.py
- dipy/tracking/tractogen.pyx
The tractography is fully performed in image space. However, seed coordinates are generated and passed in world space. This fixes the issue by applying the inverse affine to seed coordinates before calling `generate_tractogram(.)`.
I think it would be better to do it inside the  `generate_tractogram(.)` function, but I'm not sure how to do it properly in Cython. @skoudoro can you have a look?
> BF - generate_tractogram needs seed coordinate in image space

- dipy/utils/optpkg.py
- dipy/utils/tests/test_optpkg.py
When you uninstall Tensorflow, there are  still many residual files that needs to be removed manually.
Our function `optional_package` get confused because it find an incomplete installation and crash. 
this PR fix that by warning the user if the installation seems corrupted.
See below the kind of error that you can received:
```python
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[2], line 1
----> 1 from dipy.nn.torch.deepn4 import DeepN4
File ~/Devel/dipy/dipy/nn/__init__.py:88
80         print(
81             "Warning: Neither TensorFlow nor PyTorch is installed. "
82             "Please install one of these packages."
83         )
85     return __all__
---> 88 __all__ = …
```
> RF: Avoid crash of `optional_package` when dirty install

- dipy/viz/horizon/tab/slice.py
- dipy/viz/horizon/visualizer/slice.py
**Resolves**
#3371 Horizon miscalculating contrast when returning to previous volume.
#3112 Horizon fails with a single channel 4D volume.
**PR Contents**
- Replaces the percentile based placement of the sliders from previous volume to new volume. It provides support for the smaller range of the intensities.
- Ignores the selection of the intensity range with a warning. If the intensity range selection does not have any contrast in it while changing to newer volume.
- Ignores the volume slider if only single channel provided in volume.
**Local Testing**
- The changes have been tested on the `provided example`, `stanford hardi` and `cenir_multib` datasets.
- To get the warning from the _adaptive_percentile method please move both the sliders of the intensities super close in the example …
> BF: Handling binary and small intensity value range and Volume slider not be shown if single channel provided.

- dipy/nn/torch/deepn4.py
- dipy/nn/torch/evac.py
- dipy/nn/torch/histo_resdnn.py
This PR adds a use_cuda option when initializing torch models so that one can avoid using the GPU.
Tensorflow models do not have this option because 1. they do not have a way of doing this without changing a variable and 2. will be deprecated soon.
Related to https://github.com/dipy/dipy/pull/3475#discussion_r1987966358
> ENH: Add use_cuda option to torch models

- dipy/denoise/patch2self.py
- changed the alpha value from 0 to 1e-10 for performing ridge_regression which is faster than using ols. This is done when the model parameter is 'ols'.
> RF: Fixed Warnings of Patch2self3

- dipy/workflows/io.py
The modulo in `dipy_math` docstring was causing an error was the help was called.
This is fixed now. 
`dipy_math -h`
```python
File "/home/elef/miniconda3/bin/dipy_math", line 8, in <module>
sys.exit(run())
^^^^^
File "/home/elef/Devel/dipy/dipy/workflows/cli.py", line 66, in run
run_flow(getattr(mod, flow_name)())
File "/home/elef/Devel/dipy/dipy/workflows/flow_runner.py", line 83, in run_flow
args = parser.get_flow_args()
^^^^^^^^^^^^^^^^^^^^^^
File "/home/elef/Devel/dipy/dipy/workflows/base.py", line 351, in get_flow_args
ns_args = self.parse_args(args, namespace)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/elef/miniconda3/lib/python3.11/argparse.py", line 1869, in parse_args
args, argv = self.parse_known_args(args, namespace) …
```
> DOC: remove modulo in dipy_math docstring

- dipy/tracking/tracker.py
- doc/examples/_valid_examples.toml
- doc/examples/tracking_disco_phantom.py
- Change default PTT angle to `max_angle=10`. It my test it provide better results on human data. `max_angle=20` is better on disco to allow sharper turns.
- Renamed the fast tracking example to `tracking_disco_phantom.py`. Since we are now using the fast tracking module in other examples, I think it is better to focus this example on the disco data.
The example should be extented to include other tracking methods later.
> DOC - Renamed fast tracking example

- dipy/viz/horizon/visualizer/slice.py
It is a quick for the failing testcase due to None value in the file name.
> BF: Handled None case for pathlib

- dipy/denoise/patch2self.py
- dipy/workflows/denoise.py
- dipy/workflows/segment.py
This PR fixes an issue where dipy_classify_tissue workflow with the dam option returns a float type array as output.
Instead, it returns it as np.int32 array now.
This solves problems when visualizing the labels on the image the labels had floating points, due to interpolation.
Some documentation errors in patch2self has been addressed as well.
> BF: Fixing minor issue in dipy_classify_tissue dam option

- dipy/workflows/io.py
Call `warning` instead of the deprecated `warn` function.
Fixes:
```
The 'warn' function is deprecated, use 'warning' instead
```
signaled by the IDE.
> STYLE: Call `warning` instead of the deprecated `warn` function

- pyproject.toml
CVXPY generates warning that we can not control. this PR ignore them.  they should be fixed on a new CVXPY release. 
we might need to keep this until our minimal version of CVXPY contain this update.
See the warnings below not due to our codebase:
```
reconst/tests/test_forecast.py: 1 warning
reconst/tests/test_ivim.py: 3 warnings
reconst/tests/test_mapmri.py: 3 warnings
reconst/tests/test_mcsd.py: 3 warnings
reconst/tests/test_shore.py: 2 warnings
workflows/tests/test_reconst_mapmri.py: 320 warnings
/Users/runner/work/dipy/dipy/venv/lib/python3.10/site-packages/osqp/interface.py:290: DeprecationWarning: "polish" is deprecated. Please use "polishing" instead.
warnings.warn(
reconst/tests/test_forecast.py: 1 warning
reconst/tests/test_ivim.py: 3 warnings
reconst/tests/test_mapmri.py: 3 …
```
> CI: Ignore specific cvxpy warnings to avoid CI failure.

- dipy/sims/voxel.py
Small documentation error in the simulation function fixed. There was a style mismatch in the documentation for the simulation and a mistype. So fixed that with unified style.
**Changes made:**
- The capitalization of the functions' description from for eg: 'rtop' to 'RTOP'
- The descriptions have been corrected which had been mistakenly copied from the methods already present in the script
- The writing style now follows a uniform pattern i.e. " Simulate a XYZ"  with methods' name now in the same type cases
> DOC: Changed documentation errors in dipy.sims.voxel

- dipy/reconst/dti.py
- dipy/reconst/tests/test_dti.py
Fix both bugs mentioned in #3453:
1. Reshapes the weights passed to `nlls_fit_tensor` to have the same shape as the flattened data
2. Make sure the extra output is always None when doing the fitting in chunks with the `iter_fit_tensor` decorator
> Fix Bugs in #3453: Ensure Correct Weight Reshaping & Consistent Extra Output in iter_fit_tensor

- dipy/tracking/tracker.py
- dipy/tracking/tracker_parameters.pxd
- dipy/tracking/tracker_parameters.pyx
- dipy/tracking/tractogen.pyx
- dipy/workflows/tracking.py
- doc/examples/tracking_bootstrap_peaks.py
- doc/examples/tracking_deterministic.py
- doc/examples/tracking_pft.py
- doc/examples/tracking_probabilistic.py
- doc/examples/tracking_ptt.py
- doc/examples/tracking_rumba.py
- doc/examples/tracking_stopping_criterion.py
This PR changes the min/max length tracking parameter from number of points to mm. Variables were renamed for clarity.
Working in number of points requires the user to adapt those parameters when changing the step size. The default `max_len` is set to 500, which is not enough when tracking at 0.2mm `step_size` on human data.
> RF - changed min/max len from nbr pts to mm

- dipy/workflows/io.py
- dipy/workflows/tests/test_io.py
This is a small PR to allow unsafe use of dipy_math via a flag, and also, to allow broadcasting. 
Array with different dimension can be used. a `None` dimension will be added to the smallest one automatically. 
all of this is possible only by using the flag `--disable_check`
> NF: allow broadcasting in dipy_math

- dipy/tracking/propspeed.pyx
- dipy/tracking/tests/test_propspeed.pyx
- dipy/tracking/tractogen.pyx
since the last release of cython, our current CI's are failing because Cython is more sensitive. This PR improves the TrackerStatus enum management to avoid the error below. it should fix many of our CI's
```
==================================== ERRORS ====================================
_____ ERROR collecting tracking/tests/test_propspeed.cpython-310-darwin.so _____
../venv/lib/python3.10/site-packages/dipy/conftest.py:76: in collect
mod = importlib.import_module(mod_name)
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/importlib/__init__.py:126: in import_module
return _bootstrap._gcd_import(name[level:], package, level)
<frozen importlib._bootstrap>:1050: in _gcd_import
???
<frozen importlib._bootstrap>:1027: in _find_and_load
???
<frozen importlib._bootstrap>:1006: …
```
> BF: Improves Cython enum management.

- dipy/workflows/io.py
Quick PR to fix a small typo when calling the `fetch_hcp` function.
> RF: fix typo in hcp fetcher function argument name

- doc/examples/reconst_gqi.py
- doc/interfaces/reconstruction_flow.rst
- doc/interfaces/tracking_flow.rst
- doc/reconstruction_models_list.rst
Quick PR to fix some typos. it should fix #3413
- Reconstruction Tab: MSMT typo fixed
-  Reconstruction > Reconstruct with Generalized Q-Sampling Imaging, the line 'The parameter sampling_length is used here to" ompleted.
- Interfaces > reconstruction_flow, "the vol_idx" is in form a string now.
- Interfaces/tracking_flow, clarification of the GFA origin.
> Doc: Fix typo in multiple tutorial

- doc/examples/streamline_tools.py
Make affine variable naming consistent in streamline tools example.
> STYLE: Make affine variable naming consistent

- dipy/denoise/nlmeans.py
- dipy/direction/peaks.py
Add missing opening backtick to reference syntax.
> DOC: Add missing opening backtick to reference syntax.

- dipy/segment/mask.py
- dipy/segment/tests/test_mask.py
- dipy/workflows/segment.py
- dipy/workflows/tests/test_segment.py
- dipy/workflows/tests/test_workflow.py
This PR deprecate `autocrop` from `median_otsu` function. 
this feature brings a lot of errors and confusion when the  voxel size is not isotropic and size (1,1,1). You endup with a image with a different size of the original image and the mask.  it exists a crop function if the user wishes to do so.
fixes  #3537
> RF: Deprecate autocrop in median_otsu

- dipy/denoise/noise_estimate.py
- dipy/reconst/dti.py
- dipy/reconst/tests/test_dti.py
this PR fixes #3418.
it addresses some zero division warnings and update some tests.
> RF: Address some Zero division warnings

- dipy/align/imaffine.py
- dipy/reconst/qtdmri.py
we're seeing an MNE-Python CI failure:
> DeprecationWarning: scipy.optimize: The `disp` and `iprint` options of the L-BFGS-B solver are deprecated and will be removed in SciPy 1.18.0.
It's coming from the init of `dipy.core.optimize.Optimizer`. Full traceback:
<details>
```
../examples/inverse/morph_volume_stc.py failed leaving traceback:
File "/home/circleci/project/examples/inverse/morph_volume_stc.py", line 86, in <module>
morph = mne.compute_source_morph(
^^^^^^^^^^^^^^^^^^^^^^^^^
File "<decorator-gen-501>", line 10, in compute_source_morph
File "/home/circleci/project/mne/morph.py", line 258, in compute_source_morph
shape, zooms, affine, pre_affine, sdr_morph = _compute_morph_sdr(
^^^^^^^^^^^^^^^^^^^
File "/home/circleci/project/mne/morph.py", line …
```
> SciPy deprecation of "disp" in optimizer

- doc/devel/commit_codes.rst
Change unused commit prefixes to some other more useful ones.
Original proposal: https://github.com/dipy/dipy/pull/3582#issuecomment-3011959757
> DOC: Change unused commit prefixes to some other more useful ones

- dipy/workflows/tests/workflow_tests_utils.py
Remove default arguments from docstrings: their values are clearly visible in the function signatures and reduces maintenance burden. Also, the modified file is not part of the API.
Take advantage of the commit to fix a parameter name.
> DOC: Remove default arguments from docstrings

- dipy/workflows/tests/workflow_tests_utils.py
Fix workflows test utils parameter name in docstring.
Fixes:
```
Missing parameter positional_int in docstring
```
and
```
Function 'run' does not have a parameter 'positional_variable_int'
```
raised by the IDE.
> DOC: Fix workflows test utils parameter name in docstring

- dipy/align/_public.py
- dipy/align/tests/test_api.py
- dipy/data/fetcher.py
- dipy/viz/horizon/app.py
- dipy/workflows/align.py
- dipy/workflows/segment.py
- dipy/workflows/tests/test_align.py
- dipy/workflows/tests/test_tracking.py
- dipy/workflows/tracking.py
- dipy/workflows/viz.py
- doc/examples/afq_tract_profiles.py
- doc/examples/bundle_assignment_maps.py
- doc/examples/bundle_extraction.py
- doc/examples/bundlewarp_registration.py
- doc/examples/fast_streamline_search.py
- doc/examples/linear_fascicle_evaluation.py
- doc/examples/streamline_tools.py
- doc/examples/tracking_bootstrap_peaks.py
- doc/examples/tracking_deterministic.py
- doc/examples/tracking_disco_phantom.py
- doc/examples/tracking_introduction_eudx.py
- doc/examples/tracking_pft.py
- doc/examples/tracking_probabilistic.py
- doc/examples/tracking_ptt.py
- doc/examples/tracking_rumba.py
- doc/examples/tracking_sfm.py
- doc/examples/tracking_stopping_criterion.py
- doc/faq.rst
This PR should fix https://github.com/dipy/dipy/issues/3506.
TRX becomes our new default file format. It shows better performance (memory and speeed). The only drawback could be few visualizations tool support this format but we provide already a CLI to convert TRX to the desired format.
Of course, all the others tracks file format will be always supported.
> RF: from TRK to TRX as default file format for tracks

- dipy/workflows/align.py
- dipy/workflows/denoise.py
- dipy/workflows/io.py
- dipy/workflows/mask.py
- dipy/workflows/multi_io.py
- dipy/workflows/nn.py
- dipy/workflows/reconst.py
- dipy/workflows/segment.py
- dipy/workflows/stats.py
- dipy/workflows/tests/test_align.py
- dipy/workflows/tests/test_denoise.py
- dipy/workflows/tests/test_io.py
- dipy/workflows/tests/test_masking.py
- dipy/workflows/tests/test_nn.py
- dipy/workflows/tests/test_reconst.py
- dipy/workflows/tests/test_reconst_csa_csd.py
- dipy/workflows/tests/test_reconst_dki.py
- dipy/workflows/tests/test_reconst_dsi.py
- dipy/workflows/tests/test_reconst_dti.py
- dipy/workflows/tests/test_reconst_ivim.py
- dipy/workflows/tests/test_reconst_mapmri.py
- dipy/workflows/tests/test_segment.py
- dipy/workflows/tests/test_stats.py
- dipy/workflows/tests/test_tracking.py
- dipy/workflows/tests/test_viz.py
- dipy/workflows/tests/test_workflow.py
- dipy/workflows/tests/workflow_tests_utils.py
- dipy/workflows/tracking.py
- dipy/workflows/viz.py
Adopt `pathlib` for workflows.
Used `Path` instances across tests for path-like objects.
> ENH: Adopt `pathlib` for workflows

- dipy/tracking/streamlinespeed.pyx
- dipy/tracking/tests/test_streamline.py
This PR is a follow up of https://github.com/dipy/dipy/discussions/3611.
Saving streamlines as `np.float16` can be useful for saving disk space.
Unfortunately, it seems, `length` was not handling that correctly. This PR fix this issue.
In general, this is something to track. Maybe other cython function do not handle correctly this datatype.
> BF: Allow `length` to work with float16 streamlines
