doc/examples/linear_fascicle_evaluation.py
Added empty line for rendering LiFE example in website and a Happy New Year to all!!! :wine_glass:
=> Happy New Year PR! 

requirements.txt
=> NF: add requirements.txt file

doc/release0.8.rst
=> Some additions to the release notes.

dipy/info.py
=> Starting 0.9.dev

Changelog
=> DOC: Small typo fix.

doc/index.rst
=> Website update

Changelog
=> Added non-local means in Changelog

src/conditional_omp.h
From suggestion by Stefan Behnel.
=> RF: change config variable to C define

doc/examples/gradients_spheres.py
=> fixed typo

doc/installation.rst
Does this address https://github.com/nipy/dipy/issues/394?
=> DOC: How to install vtk using conda.

dipy/viz/regtools.py
For now, just created a function to handle some boilerplate
=> Small refactor of viz.regtools 

dipy/reconst/csdeconv.py
To deal with this kind of thing: 
http://nipy.bic.berkeley.edu/builders/dipy-py2.7-osx-10.6/builds/387/steps/shell_6/logs/stdio
=> RF: Compatibility with scipy 0.11

dipy/reconst/gqi.py
A long overdue fix, , with thanks to @qytian for fixing this and reminding me to
put in this PR on his behalf.
Follow-up of this conversation: http://mail.scipy.org/pipermail/nipy-devel/2013-November/009574.html
=> BF: Normalization of GQI2 `gqi_vector`.

dipy/reconst/gqi.py, doc/api_changes.rst
Following up on https://github.com/nipy/dipy/pull/581
=> DOC: explain the changes made to the integration lenght in GQI2.

doc/examples/segment_quickbundles.py
Just some minor corrections to the Quickbundles tutorial.
=> DOC: minor typographic corrections

dipy/reconst/tests/test_csdeconv.py
=> DOC + PEP8: Clean up a few typos, PEP8 things, etc.

dipy/segment/tests/test_feature.py
=> Fix precision error in test_center_of_mass

dipy/tracking/life.py, dipy/tracking/tests/test_life.py, dipy/tracking/vox2track.pyx, doc/examples/linear_fascicle_evaluation.py
Some small changes to reduce the memory footprint of the LiFE implementation and to speed up the model formation.
=> Speeding up LiFE

dipy/reconst/csdeconv.py, dipy/reconst/tests/test_csdeconv.py, doc/examples/reconst_csd.py
And a few small edits on the csd example.
=> DOC + PEP8: Mostly just line-wrapping.

AUTHOR, Changelog
=> Release mode: updating Changelog and Authors

Changelog
=> Removed the word new

doc/release0.9.rst, doc/stateoftheart.rst
=> DOC: Detailed github stats for 0.9

doc/examples/reconst_shore.py
getting familiar with github workflow and starting with this simple fix
=> bugfix for double word in doc example issue #387

dipy/align/imwarp.py, dipy/align/sumsqdiff.pyx, dipy/align/tests/test_vector_fields.py, dipy/align/vector_fields.pyx, doc/developers.rst
Closes issue #613.
Also, comparing against None with '==' will change behavior soon, using 'is' instead.
=> Raise ValueError when invalid matrix is given

README.rst
Added DIPY with caps everywhere in the README and added neurostars as a new users' list. Or should I say forum?
=> Update README file

doc/examples/valid_examples.txt
=> DOC: Include the PIESNO example.

dipy/core/optimize.py, dipy/reconst/shm.py
=> Use LooseVersion to check for scipy versions

doc/examples/reconst_csd.py
Addresses: 
https://github.com/nipy/dipy/issues/638
=> DOC: Render the following line in the code cell.

doc/Makefile, doc/_templates/layout.html, doc/devel/gitwash/git_links.txt, doc/devel/gitwash/known_projects.inc, doc/devel/gitwash/this_project.inc, doc/introduction.rst, doc/links_names.inc
Move to new neuroimaging@python.org list.
=> DOC: move mailing list links to neuroimaging

doc/examples_index.rst
The previous one was not really saying what it was about, so this one might attract more people to it.
=> Change title of piesno example

doc/examples/bundle_registration.py
Added citation in the bundle registration tutorial.
=> DOC: added NI citation

tools/make_examples.py
Otherwise, this list seems to be ignored.
=> BF: Use only validated examples when building docs.

dipy/tracking/streamlinespeed.pyx
=> Fix example in function compress_streamline

doc/api_changes.rst
=> DOC: API changes in gh707.

doc/examples/denoise_nlmeans.py
In case people take the example too literally.
=> Added comment on nlmeans example about selecting one volume

dipy/reconst/dti.py, dipy/reconst/tests/test_dti.py
The first commit demonstrates the issue. The second commit fixes it.
=> BF: tensor predict

dipy/data/fetcher.py
=> BF: Typo in data file name.

.gitignore, dipy/reconst/dti.py
as requested in https://github.com/nipy/dipy/pull/766#discussion_r44182878
=> Document dipy.reconst.dti.iter_fit_tensor params

doc/_templates/layout.html, doc/index.rst, doc/old_highlights.rst, doc/old_news.rst, tools/github_stats.py
For an example of what that looks like see: https://sidecar.gitter.im/
=> DOC: Should we add a side-car gitter chat to the website?

tools/make_examples.py
Sometimes I want to build the docs on a headless machine.
=> DOC: Use xvfb when building the docs in a headless machine.

dipy/sims/phantom.py, dipy/tracking/distances.pyx
Where "small" refers to the number of changes to the code!
Should help with: http://nipy.bic.berkeley.edu/builders/dipy-bdist-mpkg-3.3/builds/247/steps/shell_10/logs/stdio
=> BF: Inplace assignment is a bit more strict in numpy 1.10 ufuncs.

dipy/testing/decorators.py
This will hopefully help deal with this business: http://nipy.bic.berkeley.edu/builders/dipy-py2.6/builds/606/steps/shell_9/logs/stdio
=> TST: buildbot-proof testing with XVFB, in case the env variable gets crunked.

dipy/sims/phantom.py
So that we can wade through logs like this:
http://nipy.bic.berkeley.edu/builders/dipy-py2.6-32/builds/640/steps/shell_9/logs/stdio
Also, a bit of PEP8.
=> RF: Enforce integer indices

LICENSE, dipy/segment/mask.py
This supersedes #750 and should finally close #284 (!).
Just cleaning up a bit, while waiting for Travis/buildbots.
=> DOC: Add the license/copyright to skimage into median_otsu.

dipy/reconst/csdeconv.py
This is caught by a test for something else. For example here:
http://nipy.bic.berkeley.edu/builders/dipy-py2.6-32/builds/646/steps/shell_9/logs/stdio
=> BF: Indexing with integers raises warnings on some platforms.

dipy/align/streamlinear.py, dipy/direction/peaks.py, dipy/reconst/cross_validation.py, dipy/reconst/csdeconv.py, dipy/reconst/shore.py, dipy/sims/phantom.py, dipy/tracking/local/tests/test_local_tracking.py
Fixes array indexing with floating point values shown as warnings here:
http://nipy.bic.berkeley.edu/builders/dipy-py2.6-32/builds/646/steps/shell_9/logs/stdio
=> BF: Convert floating point values to ints for array indexing

dipy/align/imaffine.py, dipy/align/imwarp.py, dipy/align/tests/test_imwarp.py, dipy/reconst/interpolate.py, dipy/reconst/shore.py
Fixes more deprecation warnings. Here is the resulting log after running `try_branch`:
http://nipy.bic.berkeley.edu/builders/dipy-py2.6-32/builds/651/steps/shell_9/logs/stdio
Most of the remaining warnings are caused by #795
=> Fix deprecation warnings.

dipy/viz/tests/test_fvtk_widgets.py, dipy/viz/tests/test_fvtk_window.py
Previous PR #793 neglected to implement this in a few places in the code. Now all working: 
http://nipy.bic.berkeley.edu/builders/dipy-py2.6/builds/621/steps/shell_9/logs/stdio
=> Further refactor of XVFB skipping

dipy/align/imaffine.py
There might be a better way to do this. Suggestions are most welcome.
=> RF: Allow setting the verbosity of the AffineRegistration while running it

dipy/align/reslice.py, dipy/core/geometry.py, dipy/core/sphere_stats.py, dipy/data/__init__.py, dipy/reconst/benchmarks/bench_squash.py
Implements suggestion #812:
http://nipy.bic.berkeley.edu/builders/dipy-bdist64-27/builds/10/steps/shell_11/logs/stdio
=> TEST: compare array shapes directly

dipy/reconst/csdeconv.py
I stumbled upon what seems some discrepancies with the SDT paper https://www.ncbi.nlm.nih.gov/pubmed/19188114. Anyone can pitch in to say this is not a late friday afternoon mistake?
=> Fixed doc of SDT

doc/examples/viz_slice.py
https://en.wikipedia.org/wiki/Sagittal_plane
=> DOC: fix typo

doc/developers.rst, doc/examples/contextual_enhancement.py, doc/examples_index.rst
One more check with the website. The website compiled smoothly. It took one hour for the examples to run and no memory issues. @arokem please merge this and you have okay from me to move ahead with the release. GGT!!
=> Website 0.11 update and more devs

dipy/tests/scriptrunner.py, dipy/tests/test_scripts.py
=> Fix PEP8 in top-level tests

dipy/info.py
Maybe hang back with merging this until we have mac wheels uploaded for 0.11?
=> Setup: go on to version 0.12 development.

dipy/align/tests/test_scalespace.py, dipy/align/tests/test_sumsqdiff.py
Fixes the script mentioned in Issue #869 and #868 to adhere to PEP8 standards.
=> FIX: PEP8 for  test_sumsqdiff and test_scalespace

dipy/direction/__init__.py, dipy/direction/peaks.py, dipy/direction/tests/test_peaks.py, dipy/direction/tests/test_prob_direction_getter.py, dipy/tracking/markov.py
=> FIX: PEP8 in direction

dipy/align/imaffine.py, dipy/align/imwarp.py, dipy/align/metrics.py, dipy/align/tests/test_imwarp.py, dipy/align/tests/test_metrics.py
FIX: issue #975 plus some codes in dipy/align/tests/ having the same problem.
=> Relative import fix in dipy/align

doc/conf.py
Fixes https://github.com/nipy/dipy/issues/988
=> copyright 2008-2016

dipy/align/scalespace.py, dipy/align/tests/test_crosscorr.py, dipy/align/tests/test_expectmax.py, dipy/align/tests/test_scalespace.py, dipy/align/tests/test_sumsqdiff.py, dipy/align/tests/test_transforms.py, dipy/align/tests/test_vector_fields.py
#978 fix, except the .pyx files
=> FIX: relative imports in dipy/align

dipy/direction/tests/test_prob_direction_getter.py, dipy/external/fsl.py, dipy/external/tests/__init__.py
=> FIX: PEP8 in external

dipy/reconst/benchmarks/bench_bounding_box.py, dipy/reconst/benchmarks/bench_csd.py, dipy/reconst/benchmarks/bench_peaks.py, dipy/reconst/benchmarks/bench_squash.py, dipy/reconst/benchmarks/bench_vec_val_sum.py, dipy/reconst/tests/test_cache.py, dipy/reconst/tests/test_csdeconv.py, dipy/reconst/tests/test_dsi.py, dipy/reconst/tests/test_gqi.py, dipy/reconst/tests/test_interpolate.py, dipy/reconst/tests/test_mapmri.py, dipy/reconst/tests/test_mapmri_odf.py, dipy/reconst/tests/test_multi_voxel.py, dipy/reconst/tests/test_odf.py, dipy/reconst/tests/test_peak_finding.py, dipy/reconst/tests/test_reco_utils.py, dipy/reconst/tests/test_shm.py, dipy/reconst/tests/test_shore_fitting.py, dipy/reconst/tests/test_shore_metrics.py, dipy/reconst/tests/test_shore_odf.py, dipy/reconst/tests/test_vec_val_vect.py
=> FIX: PEP8 in reconst/test and reconst/benchmarks

dipy/viz/fvtk.py, dipy/viz/projections.py, dipy/viz/regtools.py
Fixes https://github.com/nipy/dipy/issues/1007
=> Absolute Imports in Viz

dipy/direction/peaks.py, dipy/direction/probabilistic_direction_getter.py
Use absolute import in the direction scripts.
Fixes https://github.com/nipy/dipy/issues/996
=> FIX: Change the import statements in direction

doc/examples/reconst_dsid.py
Prior to this commit, the auto-documentation had a problem with web rendering.
=> Documnetation fix for reconst_dsid.py

dipy/viz/fvtk.py
Gives a warning for VTK not installed
=> Added warning for VTK not installed

bin/dipy_reconst_dti, bin/dipy_reconst_dti_restore, dipy/workflows/multi_io.py, dipy/workflows/reconst.py, dipy/workflows/tests/test_reconst_dti.py, doc/examples/workflow_creation.py, setup.py
DTI reconstruction workflow and some minor comments correction.
=> Add the reconst_dti workflow

dipy/segment/mask.py, dipy/testing/__init__.py, dipy/testing/tests/test_decorators.py, dipy/tests/scriptrunner.py, dipy/tests/test_scripts.py
Supersedes #993, which seems to have been abandoned.
=> Rebase of https://github.com/nipy/dipy/pull/993

dipy/io/dpy.py
This request resolve and refer to the issue #1142
=> add this fix for newer version of pytables. 

dipy/segment/tests/test_clustering.py
=> Use assert_arrays_equal when needed.

.travis.yml, dipy/segment/tests/test_quickbundles.py, dipy/tracking/tests/test_streamline.py
=> MRG: Use dipy's array comparisons for tests 

dipy/reconst/benchmarks/bench_vec_val_sum.py, dipy/reconst/dti.py, dipy/reconst/gqi.py, dipy/reconst/mapmri.py, dipy/reconst/multi_voxel.py, dipy/reconst/odf.py, dipy/reconst/shore.py, dipy/reconst/tests/test_interpolate.py, dipy/reconst/tests/test_shore.py, dipy/reconst/tests/test_vec_val_vect.py
The goal of this PR is just to resolve #999
=> removing absolute path in reconst

dipy/tracking/local/localtracking.py, dipy/tracking/metrics.py, dipy/tracking/tests/test_metrics.py, dipy/tracking/tests/test_utils.py, dipy/tracking/utils.py
The goal of this PR is just to resolve #1001
=> removing absolute path in tracking module

dipy/denoise/nlmeans.py, doc/examples/denoise_nlmeans.py, doc/examples/valid_examples.txt, doc/examples_index.rst
- Removes non_local_mean, ascm, piesno from documentation since there are not validated
- Remove deprecation warning from nlmeans
=> Doc cleaning deprecation warning

dipy/tracking/streamline.py, doc/examples/tracking_quick_start.py, doc/examples_index.rst
This PR fixes the quick start tracking tutorial to use the Streamlines API and LocalTracking.
=> Release 0.12 doc fix

doc/release0.12.rst
commit summarise from 0.11 to 0.12.0
=> new release info (0.12.0)

.mailmap, Changelog, doc/api_changes.rst, doc/index.rst, doc/release0.12.rst
=> Release 0.12 updates for index.rst, api_changes and changelog

dipy/core/tests/test_gradients.py, doc/examples/viz_ui.py
=> One test (decimal issue) and a fix in viz_ui tutorial.

dipy/info.py
=> Moving ahead with 0.13 (dev version)

doc/examples/valid_examples.txt, doc/examples_index.rst
=> Added missing tutorials

doc/examples/fiber_to_bundle_coherence.py, doc/examples_index.rst, doc/index.rst
some tutorials link correction. @Garyfallidis , is it fine for you ?
=> Last doc error fix on 0.12.x

doc/examples/viz_advanced.py
Hi @dmreagan, and all. Check this out. Some minor updates and a typo fix.
=> UI advanced fix

setup_helpers.py
Correct the error message described in #1309 + some pep8 correction
=> Fix error message

doc/examples/tracking_quick_start.py
Insert missing blank line at 35
=> Update tracking_quick_start.py rebase of #1332

dipy/workflows/base.py
@Garyfallidis, this small PR should fix #1359
=> [FIX] references order in workflow

.mailmap, Changelog, doc/api_changes.rst, doc/index.rst, doc/release0.13.rst
Hi Everybody,
Can you have a look on changelog and let me know if I forgot something.
Thanks !
=> update release 0.13 information

doc/devel/make_release.rst
Test and upload wheels before uploading the source distribution.
=> MRG: add procedure for building, uploading wheels

doc/examples/reconst_dki.py
This should close #1301. One step closer to 0.14.0!
"This is perfect!" --@maurozucchelli
=> DOC - re-orientation of figures in the DKI example

dipy/reconst/dti.py, dipy/reconst/tests/test_dti.py
Also, more testing, just to be sure.
=> BF: fixes #1399, removing an un-needed singleton dimension.

doc/examples/reconst_csa.py, doc/examples/reconst_forecast.py
=> Updated color map in reconst_csa.py and reconst_forecast.py 

dipy/io/gradients.py
=> Added eddy_rotated_bvecs extension

dipy/reconst/mapmri.py, dipy/tracking/local/tissue_classifier.pyx, dipy/workflows/reconst.py, doc/examples/reconst_mapmri.py, doc/examples/tissue_classification.py
=> BF - replaced non-ascii character in workflows/reconst.py

dipy/align/imwarp.py
related to #1470 since somehow after rebase it was automatically closed
=> Refactor demon registration - _iterate

dipy/align/tests/test_whole_brain_slr.py
fix tests precision for test_whole_brain_slr.
This needs to be improved in a close future
=> Fix test_whole_brain_slr precision

.mailmap, Changelog, doc/api_changes.rst, doc/index.rst, doc/release0.14.rst, doc/stateoftheart.rst
update information for release 0.14.0
=> Release 0.14.0 information updates

dipy/info.py
=> moving to 0.15.0 dev

dipy/reconst/dki.py
This should at least partially address #1507
=> Adds whitespace, to appease the sphinx.

doc/index.rst, doc/old_highlights.rst, doc/old_news.rst
The front page was getting pretty long and rather cluttered, so I moved some old news to the archives. 
Also made me wonder: what's the difference between "highlights" and "announcements"?
=> Moved some older highlights and announcements to the old news files.

doc/developers.rst
Update Rafael's current institution in the developers list.
=> DOC: Update Rafael's current institution.

README.rst
Just a minor thing. It's only one reference for now. Do merge.
=> References to reference

dipy/reconst/mapmri.py, dipy/reconst/shore.py, dipy/reconst/tests/test_forecast.py, dipy/reconst/tests/test_shore.py
updating the optimization problems since the cvxpy does not support the strict inequalities
=> fix for using cvxpy solver

doc/examples/tracking_bootstrap_peaks.py
@Garyfallidis: Here is the modified bootstrap tutorial with @MrBago dissertation added and citing the Berman 2008 paper with a functional link.
=> Fixed references per request of @garyfallidis.

dipy/viz/actor.py
=> Fix bug in actor.label

dipy/viz/ui.py
This PR fixes a bug in #1547 and resolves #1573 .
=> Fixed Bug in PR #1547

doc/dependencies.rst
As discussed on #1607, small update for `Nibabel` version on documentation
=> [DOC] update dependencies file

doc/examples/path_length_map.py, doc/examples/valid_examples.txt, doc/examples_index.rst
This PR supersede #1631.
it fixes @arokem request and rebase to resolve merge conflict.
=> Path Length Map example rebase

.codecov.yml, dipy/align/tests/test_imaffine.py, doc/examples/denoise_localpca.py, doc/examples/introduction_to_basic_tracking.py, doc/examples/linear_fascicle_evaluation.py, doc/examples/particle_filtering_fiber_tracking.py, doc/examples/path_length_map.py, doc/examples/sfm_tracking.py, doc/examples/streamline_tools.py, doc/examples/tracking_bootstrap_peaks.py, doc/examples/tracking_eudx_odf.py, doc/examples/tracking_eudx_tensor.py, doc/examples/tracking_tissue_classifier.py, doc/examples/viz_roi_contour.py
It seems that some examples were broken after the migration to FURY package. So this is just an update.
=> [FIX] Example Update

doc/examples/linear_fascicle_evaluation.py, doc/examples/valid_examples.txt, doc/examples/viz_surfaces.py
Quick fix for some failing examples.
=> [Fix] Typo on examples

.mailmap, AUTHOR, Changelog, LICENSE, dipy/info.py, doc/api_changes.rst, doc/conf.py, doc/index.rst, doc/release0.15.rst, doc/stateoftheart.rst
Hi @arokem, @Garyfallidis,
Can you check this PR for the Release 0.15.0?
Thank you
=> Update information for release 0.15.0

doc/index.rst
=> Changed the GSoC conduction years

dipy/data/fetcher.py, doc/diffusion.bib, doc/examples/reconst_qtdmri.py
Same as https://github.com/nipy/nipype/pull/2833 ;-)
=> Hyperlink DOIs to preferred resolver

dipy/reconst/mapmri.py, dipy/reconst/qtdmri.py
Fix Sphinx math notation documentation warnings.
Partially addresses #1664.
=> BUG: Fix Sphinx math notation documentation warnings.

dipy/reconst/ivim.py
@arokem Let me know if I misunderstood!
=> Minor Doc Fix

dipy/viz/__init__.py, doc/examples/afq_tract_profiles.py, doc/examples/reconst_qtdmri.py, doc/examples/valid_examples.txt, doc/examples/viz_advanced.py, doc/examples/viz_roi_contour.py, doc/examples/viz_slice.py, doc/examples/viz_timers.py, doc/examples/viz_ui.py, doc/examples_index.rst, tools/ex2rst
The goal of this PR is to fix all tutorial errors like figures, syntax, forgotten tutorial, etc. during the doc generation
=> [Fix] Tutorial syntax

doc/index.rst
INCF supported @RafaelNH's trip to Seattle a couple of years ago!
=> Add one more acknowledgement

dipy/workflows/base.py, dipy/workflows/tests/test_iap.py
This PR fix the problem with the description disappearing on the workflow help. 
Reference: #1793
Before:
After:
=> [Fix] workflows description

doc/theory/b_and_q.rst
this PR fix #1499. 
Thanks to @albayenes, Good catch!
=> [DOC] fix rank order typo

dipy/data/fetcher.py
=> [Fix] Remove tput from fetcher

dipy/workflows/tracking.py
Fix documentation oversights: a typo and the default value given to a
parameter.
=> DOC: Fix documentation oversights.

dipy/core/tests/test_gradients.py, dipy/workflows/reconst.py
Fix typos and improve documentation.
=> DOC: Fix typos and improve documentation

dipy/align/vector_fields.pyx, dipy/reconst/fwdti.py, dipy/reconst/tests/test_dki.py, dipy/tracking/utils.py, doc/examples/particle_filtering_fiber_tracking.py
=> DOC: Fix typos

dipy/align/imaffine.py, dipy/core/onetime.py
Still cleaning... 😄. This PR just remove some old functions.
=> Remove deprecated functions from imaffine

tools/ex2rst
A strange commit generating invalid example links was added in 04cc19c. Fixing ...
=> DOC: fixing examples links

dipy/tracking/life.py
Fix parameter docstring in LiFE tracking script.
=> DOC: Fix parameter docstring in LiFE tracking script

dipy/core/tests/test_sphere.py
Remove unused import statements.
=> STYLE: Remove unused import statements

README.rst
Display `master` branch AppVeyor status.
=> DOC: Display `master` branch AppVeyor status

dipy/data/__init__.py, dipy/reconst/mcsd.py, dipy/reconst/tests/test_mcsd.py, dipy/sims/voxel.py
Relocate the `sim_response` method to allow re-use.
=> ENH: Relocate the `sim_response` method to allow re-use

dipy/data/fetcher.py, dipy/io/stateful_tractogram.py, dipy/io/streamline.py, dipy/io/tests/test_stateful_tractogram.py, dipy/io/tests/test_streamline.py, dipy/io/utils.py, doc/examples/bundle_extraction.py, doc/examples/streamline_formats.py
Fix mssing docstring
Added `to_space` function
Useful private attribute are now accessible
Fetcher now uses checksum instead of re-downloading
=> stateful_tractogram_post_1.0_fixes

doc/README.md
Improve the `doc/README` file contents:
- Match the explained folder list with the actual folders in the `doc`
folder.
- Improve markup.
- Improve wording.
=> DOC: Improve the `doc/README` file contents

doc/examples/bundle_extraction.py
=> Fix the random state for SLR and Recobundles in bundle_extraction.

doc/examples/reconst_mcsd.py, doc/examples/valid_examples.txt, doc/examples_index.rst
=> DOC: Multi-Shell Multi-Tissue CSD Example

bin/dipy_split, dipy/workflows/io.py, dipy/workflows/tests/test_io.py
New workflow to split the input files from the command line to ease the creation of new interfaces such as registration. Currently aimed at extracting 3D volume from 4D data
=> NF: SplitFlow 

dipy/data/fetcher.py, dipy/denoise/tests/test_noise_estimate.py, dipy/io/image.py, dipy/io/tests/test_utils.py, dipy/io/utils.py, dipy/reconst/benchmarks/bench_csd.py, dipy/reconst/csdeconv.py, dipy/reconst/dki.py, dipy/reconst/mapmri.py, dipy/reconst/tests/test_cross_validation.py, dipy/reconst/tests/test_csdeconv.py, dipy/reconst/tests/test_dti.py, dipy/reconst/tests/test_ivim.py, dipy/reconst/tests/test_sfm.py, dipy/segment/tests/test_mask.py, dipy/tracking/tests/test_life.py, dipy/workflows/reconst.py, dipy/workflows/tests/test_align.py, dipy/workflows/tests/test_denoise.py, dipy/workflows/tests/test_io.py, dipy/workflows/tests/test_masking.py, dipy/workflows/tests/test_reconst_csa_csd.py, dipy/workflows/tests/test_reconst_dki.py, dipy/workflows/tests/test_reconst_dti.py, dipy/workflows/tests/test_reconst_ivim.py, dipy/workflows/tests/test_reconst_mapmri.py, dipy/workflows/tests/test_segment.py, dipy/workflows/tests/test_stats.py, dipy/workflows/tests/test_tracking.py, doc/examples/afq_tract_profiles.py
Introduce a small interface for `get_fdata` function. The function name is more explicit and makes easier the maintenance.
=> replace get_fdata by load_nifti_data

.travis.yml, README.rst, azure-pipelines.yml, dipy/workflows/flow_runner.py, dipy/workflows/stats.py
- Just add python3.8 to our CI's
- keeping python 3.5 at the moment
=> [CI] add python3.8 matrix

.mailmap, AUTHOR, Changelog, LICENSE, doc/api_changes.rst, doc/conf.py, doc/developers.rst, doc/examples/reconst_ivim.py, doc/examples/restore_dti.py, doc/examples/streamline_formats.py, doc/examples/streamline_registration.py, doc/examples/viz_advanced.py, doc/index.rst, doc/old_highlights.rst, doc/old_news.rst, doc/release_notes/release1.1.rst, doc/stateoftheart.rst
Preparation for 1.1.0 release, targeting Monday, January 6. 
=> [Upcoming] Release 1.1.0

doc/api_changes.rst, doc/doc-requirements.txt, doc/index.rst, doc/release_notes/release1.1.rst
This release fixes the memory issue. More information on #2029
=> [MAINT] Release 1.1.1

dipy/io/image.py
=> DOC: Documents I/O functions.

doc/examples/reconst_dki.py
Just a small correction in DKI's example. We forgot to update the documentation when changing the read data functions.
=> DOC: Update DKI documentation according to the new get data functions

dipy/denoise/localpca.py, dipy/denoise/tests/test_lpca.py
=> Adapted for patch_radius with radii differing xyz direction. 

doc/examples/reconst_fwdti.py
=> DOC: fix typo in FW DTI tutorial

.pep8speaks.yml, CONTRIBUTING.md, Changelog, README.rst, azure-pipelines.yml, dipy/align/reslice.py, dipy/direction/peaks.py, dipy/info.py, doc/Makefile, doc/conf.py, doc/devel/gitwash/following_latest.rst, doc/devel/gitwash/git_links.txt, doc/devel/gitwash/known_projects.inc, doc/devel/gitwash/maintainer_workflow.rst, doc/devel/gitwash/patching.rst, doc/devel/gitwash/set_up_fork.rst, doc/devel/gitwash/this_project.inc, doc/devel/intro.rst, doc/examples/fiber_to_bundle_coherence.py, doc/installation.rst, doc/links_names.inc, doc/make.bat, doc/mission.rst, doc/release_notes/release0.12.rst, doc/release_notes/release0.6.rst, doc/upload-gh-pages.sh, doc/upload_docs.py, tools/github_stats.py
- Update repo path a bit everywhere before the announcement.
- Add azure badge
=> [DOC] Update repo path

dipy/core/gradients.py, dipy/reconst/sfm.py, dipy/workflows/reconst.py
Also, fixes a typo in the warning in core.gradients.
=> RF: Swallow a couple of warnings that are safe to ignore.

dipy/core/rng.py, dipy/core/tests/test_rng.py
This PR adds tests for `WichmannHill2006`, `WichmannHill1982`, `LEcuyer`.
fix #1864
=> Add tests to rng module

dipy/io/image.py, dipy/reconst/forecast.py
this PR fixes a small issue that blocks the doc generation.
=> [fix] Doc generation issue

CONTRIBUTING.md
Add `Azure Pipelines` to CI tools in `CONTRIBUTING.md`.
=> DOC: Add `Azure Pipelines` to CI tools in `CONTRIBUTING.md`

dipy/workflows/multi_io.py, dipy/workflows/reconst.py
A quick fix to make sure that we unpack variable string when we check file existence. Also, some docstring + pep8 improvement
=> [Fix] workflow variable string

doc/installation.rst
=> some typos

doc/theory/bmatrix.rst
I have fixed some grammatical and spelling errors
=> Some spelling and grammatical errors

doc/gimbal_lock.rst
Merged the other recent pull requests
=> Kunakl07 patch 8

Changelog, README.rst, dipy/viz/regtools.py, doc/faq.rst, doc/tools/apigen.py
Here are the combined errors of 6 pull request I had sent earlier
=> Kunakl07 patch 7

doc/devel/coding_style_guideline.rst
I have done some changes again, could you please suggest to me whether they are correct?
Thank you
=> Some change backs

doc/theory/spherical.rst
I have fixed some spelling and grammatical mistakes
=> Some spelling and grammatical mistakes

doc/api_changes.rst
I have fixed some typing and some grammatical mistakes.
=> Some typos and grammatical errors

doc/examples/afq_tract_profiles.py
=> Fixed minor typos

doc/examples/brain_extraction_dwi.py
Fixed some documentation and grammatical typos and import time in the beginning to avoid calls in between. Same as previous PRs.
=> Modules imported in the beginning

dipy/align/bundlemin.pyx, dipy/align/expectmax.pyx, dipy/align/imwarp.py, dipy/align/metrics.py, dipy/align/streamlinear.py
I have fixed some typos and some repeated words in streamliner.py, bundlemin.pyx, expectmax.pyx, imwrap.pyx and metrices.py.
=> Fixed typos in dipy.align

dipy/core/gradients.py
Found a small bug in the new code for multidimensional gradient table support.
=> BF: refer to cigar_tensor

doc/examples/segment_extending_clustering_framework.py
Corrected some minor typos and placed modules in the beginning to avoid calls in between code.
=> Documentation typos, grammar corrections & imports

doc/data.rst, doc/dataset_list.rst, doc/documentation.rst
Add DIPY dataset list to documentation.
=> DOC: Add DIPY dataset list to documentation.

dipy/nn/model.py, dipy/nn/tests/test_tf.py, dipy/viz/regtools.py
I have added a new class to implement multi layer percepton. 
- The user could able to build model by passing a list of hidden number of units (ex: `num_hidden=[128,128]`) for each hidden layers.
- I have also added a function `summary()` to get details of each layer of the model.
=> Modified the model for multiple hidden layers

doc/interfaces/BUAN_flow.rst, doc/interfaces/index.rst
Added BUAN_flow.rst file for the documentation of Bundle Analytics pipeline CLIs.
=> BUAN framework documentation

dipy/nn/tests/test_tf.py
This is just a small pet peeve I have.
=> TST: Change assert_equal(statement, True) to assert_(statement).

ci/azure/install.ps1, ci/azure/windows.yml
It seems we have an SSL certificate issue on Azure Windows.
Let's see if everything is going well when we force the installation.
=> [WIP] Install ssl certificate for azure pipeline windows

dipy/io/tests/test_streamline.py, dipy/io/vtk.py, dipy/viz/__init__.py
This PR should fix the current issue with VTK9.  I just replace the old code with [FURY](https://github.com/fury-gl/fury) functions. This will make maintenance easier.
this PR supersede #2175
=> [Fix] update save_vtk_streamlines and load_vtk_streamlines

dipy/viz/regtools.py
I found quite convenient to add extra figure arguments
=> add fig_kwargs

.travis.yml, azure-pipelines.yml, ci/azure/install.sh, setup.py
Quick update of Travis and Azure due to Python 3.5 end of life (2020-09-13)
=> Removing Python 3.5 from Travis and Azure due to its end of life (2020-09-13)

dipy/viz/app.py
Quick PR to fix Horizon warning due to VTK9
=> [FIX] Horizon shader warning

.codecov.yml, .mailmap, AUTHOR, Changelog, dipy/reconst/ivim.py, doc/examples/brain_extraction_dwi.py, doc/index.rst, doc/old_highlights.rst, doc/old_news.rst, doc/release_notes/release1.2.rst, doc/stateoftheart.rst
Preparation for 1.2.0 release, targeting Monday, April 13. 
A lot of PR's, but most of them can be done on time, I think :smile:
Time for a push, DIPY Team!!
=> [Upcoming] Release 1.2.0

dipy/reconst/dti.py
=> [FIX] used numerical indices for references

doc/dataset_list.rst
Fix HTML tag in dataset list documentation table.
=> DOC: Fix HTML tag in dataset list documentation table

doc/interfaces/data_fetch.rst, doc/interfaces/index.rst
=> [DOC] fetching dataset

dipy/segment/bundles.py, dipy/stats/analysis.py, dipy/workflows/segment.py, dipy/workflows/stats.py, doc/interfaces/buan_flow.rst
This PR updates BUAN paper citations.
=> update BUAN citations

doc/examples_index.rst
=> [DOC]:Removed tracking evaluation section

doc/interfaces/denoise_flow.rst, doc/interfaces/index.rst
Add denoising CLI documentation
=> DOC : Denoising CLI

dipy/core/sphere.py
Takes care of the `\` in the string.
=> BUG: Fix string literal

dipy/core/sphere.py
Sorry for not grouping these together, found one more.
=> BUG: Fix literal

doc/interfaces/gibbs_unringing_flow.rst
Gibbs Unringing CLI Documentation
=> [DOC] Gibbs Unringing CLI

dipy/workflows/align.py, dipy/workflows/base.py, dipy/workflows/denoise.py, dipy/workflows/io.py, dipy/workflows/mask.py, dipy/workflows/reconst.py, dipy/workflows/segment.py, dipy/workflows/stats.py, dipy/workflows/tracking.py, dipy/workflows/viz.py
It becomes difficult to maintain default values in docstrings. Default values are mentioned in function parameters.
Duplicating values are error-prone and involve a heavier maintenance burden, hence removing them.
=> [DOC]: Remove default values from docstrings

doc/interfaces/index.rst, doc/interfaces/tracking_flow.rst
Add tracking CLI Documentation
=> [DOC]: Add Tracking CLI Documentation

bin/dipy_denoise_patch2self, dipy/denoise/patch2self.py, dipy/denoise/tests/test_patch2self.py, dipy/workflows/denoise.py, dipy/workflows/tests/test_denoise.py, doc/examples/denoise_patch2self.py, doc/examples/valid_examples.txt, doc/examples_index.rst
Hi Everyone,
This PR adds the basic version of our method: `Patch2Self: Denoising Diffusion MRI with Self-supervised Learning` 
The paper was accepted to NeurIPS 2020 as a Spotlight! Link: [Paper](https://papers.nips.cc/paper/2020/hash/bc047286b224b7bfa73d4cb02de1238d-Abstract.html)
TO-DO on this PR:
@skoudoro -- I know that we have fancier comparison page now! Can you point me to where all this should go?
=> Patch2Self: Denoising Diffusion MRI with Self-supervised Learning

doc/interfaces/index.rst, doc/interfaces/registration_flow.rst
Registration CLI Documentation
=> [DOC] Registration CLI

doc/interfaces/index.rst, doc/interfaces/reconstruction_flow.rst
Add reconstruction CLI documentation
=> [DOC]: Reconstruction CLI

dipy/denoise/patch2self.py, dipy/denoise/tests/test_patch2self.py
Small fix as an alternative to clipping to a minimum via `np.clip` !
=> [MAINT] Fixed Handling Negative Values for P2S

.mailmap, Changelog, LICENSE, doc/api_changes.rst, doc/conf.py, doc/glossary.rst, doc/index.rst, doc/old_highlights.rst, doc/old_news.rst, doc/release_notes/release1.4.rst, doc/stateoftheart.rst
Preparation for 1.3.0 release, targeting Monday, October 26. 
There is room for the following PR to be finished and merge
=> [Upcoming] Release 1.4.0

dipy/denoise/patch2self.py
=> BF: Change patch2self defaults.

doc/examples/bundle_extraction.py
This PR is a quick fix to address #2309.
=> [FIX] Tractogram Header in RecoBundles Tutorial

.coveragerc, azure-pipelines.yml, ci/azure/install.sh, ci/azure/linux.yml, ci/azure/script.sh
It seems that codecov was not working anymore. This is an attempt to reactivate it.
TODO:
fix #1872
fix #1646
=> [FIX] reactivate codecov

doc/examples/denoise_patch2self.py
Hi everyone,
I know that the defaults in `Patch2Self` were changed recently by @arokem, but they won't be visible to the users until the next release. I am making this small PR for adding it to the documentation to ensure that people still use the correct options!
@skoudoro : would it be possible to update the documentation with these changes before the next release?
=> [DOC]: Change defaults in Patch2Self example

dipy/denoise/patch2self.py, doc/examples/denoise_patch2self.py
=> Updated docs for using P2S optimally

doc/examples/bundle_assignment_maps.py, doc/examples/bundle_extraction.py, doc/examples/bundle_shape_similarity.py
In this PR, I plan to expand the Bundle Segmentation using RecoBundles tutorial. 
Bramsh
=> Expanding Bundle Segmentation Tutorial

doc/examples/afq_tract_profiles.py, doc/examples/bundle_extraction.py
Added CST_L examples in bundle segmentation tutorial and also updated names of files in AFQ tutorial.
=> added all examples of CST and updated AFQ file name

.mailmap, AUTHOR, Changelog, azure-pipelines.yml, dipy/info.py, doc/api_changes.rst, doc/examples/bundle_assignment_maps.py, doc/examples/bundle_extraction.py, doc/examples/denoise_patch2self.py, doc/examples/segment_clustering_features.py, doc/examples/segment_clustering_metrics.py, doc/examples/segment_extending_clustering_framework.py, doc/examples/segment_quickbundles.py, doc/examples/surface_seed.py, doc/examples/tissue_classification.py, doc/index.rst, doc/old_highlights.rst, doc/old_news.rst, doc/release_notes/release1.4.1.rst, doc/stateoftheart.rst
Preparation for 1.4.1 release, targeting ~~Friday, April 23~~ Saturday, May 1rst. 
There is room for the following PR to be finished and merge
=> [Upcoming] Release 1.4.1

dipy/reconst/dki.py, dipy/reconst/tests/test_dki.py
This should be a small correction on KFA definition - it has to be zero if the kurtosis tensor is null.
=> Small correction on KFA 

dipy/reconst/shore.py, dipy/reconst/tests/test_shore.py, dipy/reconst/tests/test_shore_metrics.py, dipy/reconst/tests/test_shore_odf.py
This PR should fix #365. 
Some tests have been added to fulfill @arokem old review.
For more information, please go to #365.
=> [ENH] Improve Shore Tests

dipy/reconst/multi_voxel.py
Hello everyone,
I started using the dipy for analyze my IVIM images, for fit an entire image will take some time. Without a progress bar, I'll be in the dark.I used tqdm for implement a simple progress bar.
have a good day.
=> Implementation multi_voxel_fit progress bar

dipy/workflows/denoise.py
=> Fixes the default option in the command line for Patch2Self 'ridge' -> 'ols'

dipy/align/imaffine.py, dipy/align/metrics.py, dipy/align/scalespace.py, dipy/align/tests/test_metrics.py, dipy/align/tests/test_parzenhist.py, dipy/align/tests/test_scalespace.py, dipy/align/tests/test_vector_fields.py, dipy/core/interpolation.pyx, dipy/core/tests/test_interpolation.py, dipy/denoise/noise_estimate.py, dipy/segment/mask.py, dipy/segment/tests/test_mask.py, dipy/stats/analysis.py, dipy/workflows/stats.py, doc/examples/reconst_dki.py, doc/examples/reconst_dki_micro.py, doc/examples/snr_in_cc.py, doc/examples/streamline_tools.py
Avoids deprecation warnings in SciPy `master` about importing from `scipy.ndimage.measurements` EDIT: *and other similar namespaces*
=> MAINT: Update import from ndimage

doc/dataset_list.rst
Hi everyone,
I have added the citation of the IVIM dataset in the docs with reference to closed issue [#2443](https://github.com/dipy/dipy/issues/2443).
=> [DOC] : Added citation for IVIM dataset

.github/CONTRIBUTING.md
Fix coding style guideline link and make links consistent.
=> DOC: Fix coding style guideline link

dipy/io/stateful_tractogram.py, dipy/io/tests/test_stateful_tractogram.py
- ENH: Return unique invalid streamline removal indices
- STYLE: Improve the invalid streamline removal test
- STYLE: Prefer returning a list for indices to keep
=> ENH: Return unique invalid streamline removal indices

dipy/reconst/tests/test_ivim.py, dipy/reconst/tests/test_mcsd.py
- STYLE: Remove unused imports and variables
- STYLE: Remove redundant parentheses
=> STYLE: Improve style in misc files

dipy/info.py, doc/cite.rst, doc/faq.rst
1. Adds more datasets to the FAQ
2. Adds the Frontiers DKI paper reference.
3. Removes comment about clinical use. This is implicit to the license.
=> DOC: Small updates.

dipy/tracking/tests/test_utils.py, dipy/tracking/utils.py
This PR adds some utility functions for the tracking framework.  The conversion between radius curvature and maximum deviation angle is based on the following paper: https://onlinelibrary.wiley.com/doi/full/10.1002/ima.22005.
I also use the opportunity to do some styling cleaning.
=> Add utilities functions:  radius curvature <--> maximum deviation angle

dipy/viz/__init__.py, dipy/viz/app.py, dipy/viz/panel.py, dipy/workflows/viz.py, doc/examples/viz_advanced.py
We are updating Horizon to use new FURY version.
=> Horizon FURY update

cythexts.py, dipy/conftest.py, dipy/nn/model.py, dipy/nn/tests/test_tf.py, dipy/reconst/forecast.py, dipy/reconst/ivim.py, dipy/reconst/mapmri.py, dipy/reconst/mcsd.py, dipy/reconst/qtdmri.py, dipy/reconst/shore.py, dipy/segment/clustering_algorithms.pyx, dipy/segment/clusteringspeed.pyx, dipy/segment/cythonutils.pxd, dipy/segment/cythonutils.pyx, dipy/segment/featurespeed.pyx, dipy/segment/metricspeed.pyx, dipy/testing/__init__.py, dipy/tracking/streamlinespeed.pxd, dipy/tracking/streamlinespeed.pyx, dipy/viz/__init__.py, doc/conf.py, doc/installation.rst, doc/tools/build_modref_templates.py, doc/tools/docgen_cmd.py, setup.py, setup_helpers.py, version_helpers.py
Drop `distutils` since it is deprecated
=> [MNT] Drop distutils

dipy/direction/tests/test_prob_direction_getter.py, dipy/reconst/shm.py, dipy/reconst/tests/test_shm.py
- DOC: Fix typos in documentation
- ENH: Remove duplicate import statement
- ENH: Improve SH bases warning messages
- ENH: Rename test methods to avoid duplicate names
- ENH: Filter legacy SH bases warnings in tests
Closes #2449.
=> ENH: Improve SH bases warning messages

dipy/workflows/reconst.py
this PR should fix #2542.
`sigma` was missing when you use the DTI or DKI workflows with RESTORE as a fitting method.  See #2542 for more information.
Can you test this PR @GalBenZvi?
Thank you
=> [ENH] Add sigma to DTI/DKI RESTORE workflow

.github/workflows/test_template.yml
This PR adds a timeout to our Github Actions.
=> Add timeout + concurrency to GHA

dipy/io/stateful_tractogram.py
=> Stateful Tractogram DPS and DPP keys ordering

dipy/io/streamline.py, dipy/io/vtk.py
This PR fixes #2525. It allows ".vtp" extension for streamlines management.
=> Support .vtp files 

dipy/reconst/csdeconv.py, dipy/workflows/tests/test_reconst_csa_csd.py, doc/examples/motion_correction.py, doc/examples/reconst_csd.py, doc/examples/reconst_rumba.py
this PR fixes the last failing tutorials.
=> [FIX] Motion correction tutorial

dipy/align/_public.py
=> DOC: Fix the docstring of `write_mapping`

dipy/workflows/denoise.py
Allow specifying non-default parameters to `Patch2Self` CLI.
=> ENH: Allow non-default parameters to `Patch2Self` CLI

dipy/reconst/shm.py
Document Dirac delta generation method missing member.
=> DOC: Document Dirac delta generation method missing member

dipy/data/fetcher.py, dipy/info.py, dipy/workflows/tests/test_io.py
=> NF: Adds a fetcher for HCP data.

dipy/workflows/reconst.py, dipy/workflows/tests/test_reconst_rumba.py
Add RUMBA-SD reconstruction workflow.
Add the accompanying test.
=> NF: Add RUMBA-SD reconstruction workflow

MANIFEST.in, dipy/direction/pmf.pyx
At least some of what I think could make https://github.com/conda-forge/dipy-feedstock/pull/41 work
=> MAINT: Fixes for 3.11 and sdist

dipy/data/fetcher.py
I think this is equivalent, but just to be sure.
=> One more small fix to the hcp fetcher.

doc/examples/fiber_to_bundle_coherence.py, doc/examples/viz_slice.py, tools/ex2rst
A quick PR that fixes some bad rendering on different tutorials
=> small fixes for tutorials

dipy/data/__init__.py, dipy/data/fetcher.py, dipy/workflows/tests/test_io.py, doc/examples/reconst_forecast.py, doc/examples/reconst_fwdti.py
For now, I have only addressed the first part of this, which is to create a fetcher for preprocessed HBN data. 
This is implemented on top of #2696, because it uses a function introduced there.
=> Replace CENIR with HBN

.mailmap, AUTHOR, Changelog, LICENSE, README.rst, dipy/data/fetcher.py, dipy/reconst/dti.py, dipy/reconst/recspeed.pyx, dipy/tracking/distances.pyx, dipy/tracking/streamlinespeed.pyx, doc/api_changes.rst, doc/conf.py, doc/examples/linear_fascicle_evaluation.py, doc/examples/reconst_dsi.py, doc/examples_index.rst, doc/index.rst, doc/old_highlights.rst, doc/old_news.rst, doc/release_notes/release1.6.rst, doc/stateoftheart.rst, tools/doctest_extmods.py
Preparation for 1.6.0 release, targeting ~~August 1st~~  January 13-14. 
There is room for the following PR to be finished and merge
=> [Upcoming] Release 1.6.0

doc/reconstruction_models_list.rst
Minor documentation fix for the website. Our implementation of RUMBA supports single/multi shells and cartesian data.
=> DOC - Update RUMBA-SD data requirement

dipy/info.py
=> Fix EXTRAS_REQUIRE

dipy/io/stateful_tractogram.py, dipy/io/streamline.py, dipy/io/tests/test_stateful_tractogram.py, dipy/io/utils.py
This is a small addition for an attribute in the StatefulTractogram that would help the manipulation for the TRX file format.
https://github.com/tee-ar-ex/trx-python/pull/50
=> TRX integration, requires new attributes for SFT

dipy/workflows/align.py
Updated the class to save inverse transformed static image
=> Update SynRegistrationFlow for #2648

dipy/reconst/mcsd.py
Here is a quick fix for the `solve_qp` method used for msmt-CSD. When using complicated schemes such as b-tensor encoding, I ended up with an ArpackNoConvergence error from cvxpy. It also occured with some multi-shell data. I found this issue in cvxpy https://github.com/cvxpy/cvxpy/issues/1995, and applied this very simple solution to assume the matrix is PSD (Positive Semidefinite). I don't know how exactly I should handle the cvxpy version dependancy. The fix works for version 1.2 and 1.3, does not work for version 1.1 and version 1.0 didn't have the issue, but is now quite old and I had some problems when pip installing it (related to the setuptools version). So my solution was to force a cvxpy version >= 1.2.
Here is some data and a small python script to compare before and after my …
=> Fixing solve_qp error

dipy/utils/fast_numpy.pxd, dipy/utils/fast_numpy.pyx, dipy/utils/tests/test_fast_numpy.py
- Utility functions were moved from PTT (PR #2596) to the fast_numpy module.
- Added tests.
=> NF - add utility functions to fast_numpy

.github/workflows/test_template.yml, dipy/info.py, dipy/viz/tests/test_apps.py, tools/ci/archives/.travis.yml.old, tools/ci/archives/appveyor.yml, tools/ci/archives/create_env_install_dependencies.sh, tools/ci/install_dependencies.sh, tools/ci/run_tests.sh
Last week, Codecov removed the whole project from PyPI. That's why our codecov CI's is failing.  
So we need to switch to the CI-host-specific uploader. This is what this PR does
=> [MTN] Fix CI codecov upload

dipy/viz/tests/test_apps.py
This PR fixes the `test_roi_images` in `dipy/viz/tests/test_apps.py`.
=> Fix test_roi_images

bin/dipy_evac_plus, dipy/workflows/segment.py, dipy/workflows/tests/test_segment.py
This adds a workflow for EVAC+ with a test for it.
=> EVAC+ workflow

dipy/workflows/denoise.py, dipy/workflows/tests/test_denoise.py
=> Add `patch_radius` parameter to Patch2Self denoise workflow

doc/posts/2023/2023_05_19_vara_week0.rst, doc/posts/2023/2023_05_29_vara_week1.rst, doc/posts/2023/2023_06_05_vara_week2.rst
=> Vara's week 0 blog

dipy/data/fetcher.py
Small update to reflect changes to the BIDS spec since this was first written.
=> Updates HCP fetcher dataset_description to be compatible with current BIDS

dipy/direction/tests/test_ptt_direction_getter.py, dipy/tracking/local_tracking.py, dipy/tracking/tests/test_tracking.py
This can be useful if you are going to use the streamlines for bundle recognition, and you don't want to have to deal with small streamlines.
=> [ENH] Add minimum length to streamline generator

dipy/align/_public.py, dipy/align/streamlinear.py, dipy/core/gradients.py, dipy/core/profile.py, dipy/data/fetcher.py, dipy/denoise/adaptive_soft_matching.py, dipy/direction/peaks.py, dipy/io/stateful_tractogram.py, dipy/reconst/forecast.py, dipy/reconst/mapmri.py, dipy/reconst/msdki.py, dipy/reconst/qtdmri.py, dipy/reconst/qti.py, dipy/reconst/sfm.py, dipy/reconst/tests/test_qti.py, dipy/segment/clustering.py, dipy/tracking/local_tracking.py, dipy/tracking/streamline.py, dipy/tracking/tests/test_tracking.py, dipy/tracking/utils.py, dipy/viz/horizon/app.py, dipy/workflows/base.py, dipy/workflows/tests/test_align.py, dipy/workflows/tests/test_reconst_dki.py, dipy/workflows/tests/test_reconst_dti.py, doc/examples/affine_registration_masks.py, doc/sphinxext/github.py, doc/upload_docs.py, tools/github_stats.py, tools/pack_examples.py
Apply some [refurb](https://github.com/dosisod/refurb) suggestions.
I have omitted those that don't seem to improve readability, as well as suggestions that seem too intrusive and would be better left for later.
=> Apply refurb suggestions

dipy/segment/bundles.py, dipy/segment/clustering.py
https://www.bipm.org/en/si-base-units/second
=> MAINT: the symbol for second is s, not sec.

dipy/data/fetcher.py
=> [FIX] tiny fix to HBN fetcher to also grab T1 for each subject

dipy/info.py, dipy/reconst/mapmri.py, dipy/reconst/shm.py, dipy/reconst/tests/test_dti.py, dipy/segment/bundles.py, doc/examples/reconst_shore_metrics.py, doc/sphinxext/docscrape.py, doc/sphinxext/docscrape_sphinx.py, doc/sphinxext/math_dollar.py, doc/upload_docs.py, setup_helpers.py, tools/dipnost, tools/github_stats.py, tools/make_examples.py, tools/osxbuild.py, tools/toollib.py
Change to f-strings where possible.
Batch **1**
Addresses #2900.
=> STYLE: f-strings

dipy/reconst/qti.py, dipy/reconst/tests/test_dsi.py, dipy/reconst/tests/test_dsi_deconv.py, dipy/reconst/tests/test_rumba.py, dipy/reconst/tests/test_shore_odf.py, dipy/segment/tests/test_fss.py
- STYLE: Fix `np.product` deprecation warning
- STYLE: Fix `np.alltrue` deprecation warning
=> STYLE: Fix miscellaneous Numpy warnings

doc/conf.py
Fix package name in documentation config file comment.
=> DOC: Fix package name in documentation config file comment

dipy/align/imwarp.py, doc/examples/streamline_registration.py
The goal of this PR is to fix a tutorial that give wrong result. 
Also, we got many times this question so it was tie to fix the tutorial. 
This is a follow up of #2369
it should resolves #2703, resolves #2400 and resolves #2786
it should answer #2646 discussion.
Sorry for the delay @WilliamFCB, it would be great if you could test it.
=> Update of the tutorial apply image-based registration to streamlines

doc/developers.rst
Update jhlegarreta affiliation in developers.
=> DOC: Update jhlegarreta affiliation in developers

dipy/reconst/msdki.py
- DOC: Fix parameter name in `msdki` function
- DOC: Fix return parameter names in miscellaneous `msdki` functions
=> DOC: Fix miscellaneous docstrings

dipy/viz/horizon/app.py, dipy/viz/horizon/tab/__init__.py, dipy/viz/horizon/tab/base.py, dipy/viz/horizon/tab/cluster.py, dipy/viz/horizon/tab/peak.py, dipy/viz/horizon/tab/roi.py, dipy/viz/horizon/tab/slice.py, dipy/viz/horizon/tab/tests/test_base.py, dipy/viz/horizon/util.py
- This PR fixes a bug for synchronizing the slicers.
- It will synchronize the slicers only if the sizes are same. If they are different a warning will be printed in the terminal that they cannot be synchronized
=> synchronized-slicers for same size

.codecov.yml
The goal of this PR is to disable annotations on a PR. 
it bring unneeded noise and confuse first contributors
=> [MTN] Disable github check annotations

.github/ISSUE_TEMPLATE.md
The interior quotes either need to be escaped or changed to single quotes, the latter seemed simpler
=> DOC: Fix issue template [ci skip]

dipy/core/gradients.py
Remove unused import in `dipy/core/gradients.py`.
=> STYLE: Remove unused import in `dipy/core/gradients.py`

dipy/core/gradients.py, dipy/core/tests/test_gradients.py, dipy/reconst/tests/test_ivim.py, dipy/workflows/align.py, dipy/workflows/reconst.py, dipy/workflows/tests/test_reconst_dki.py
- DOC: Fix typo in b0_threshold parameter docstring
- RF: Refactor the b0 thresholding logic
- RF: Consolidate b0 threshold value update at slicing
=> RF: Fix b0 threshold warnings

doc/_static/css/common/override.css, doc/_static/css/dipy.css, doc/_static/version_switcher.json, doc/conf.py
This PR is a quick fix to update the logo url and size. it also fixes the version_switcher
=> [DOC] Fix logo size and link [ci skip]

.github/workflows/nightly.yml, .github/workflows/test.yml, .github/workflows/test_compat.yml
=> [MTN] Remove 3.8 Ci's

dipy/data/tests/test_fetcher.py, dipy/workflows/base.py, dipy/workflows/tests/test_docstring_parser.py, doc/sphinxext/docscrape.py, doc/sphinxext/numpydoc.py
This PR is just a cleanup of some remaining python 2 references.
=> [BW] Remove some python2 reference

.github/workflows/nightly.yml, .github/workflows/test_template.yml, dipy/meson.build, doc/devel/installation_from_source.rst
It seems that openmp was not available for macOS user since quite a long time. 
This PR fixes this issue and improve the instructions for macOS Users
=> [OPT] Enable openmp for macOS wheel and CI's

dipy/__init__.py, doc/examples/reconst_dti.py, doc/tools/build_modref_templates.py
This PR is just a quick fix concerning DTI tutorial where the matrix does not show up correctly.
I also use the opportunity to clean some left over of `boots` .
=> [DOC] Fix DTI Tutorial [ci skip]

dipy/viz/horizon/util.py
This PR is a follow-up PR to fix the compatibility issue mentioned in #3085 by @skoudoro .
Now all the test cases work for python 3.9.
Thank you!
=> backward compatibility fixed

dipy/direction/peaks.py
Hi,
Following issue #3079 , I added legacy option support to `peaks_from_model` from `dipy.direction.peaks`. This was pretty straight forward, and should not change anything if no legacy=False is set.
=> Adding SH basis legacy option support to peaks_from_model

.github/workflows/coverage.yml, dipy/nn/deepn4.py, dipy/nn/synb0.py, dipy/nn/tests/test_deepn4.py, dipy/nn/tests/test_synb0.py, pyproject.toml
This commit is to remove the optional dependency of tensorflow addon due to its deprecation. I have also removed some repeated code in Synb0.
=> Removing tensorflow addon from DL models

dipy/workflows/io.py, dipy/workflows/reconst.py, doc/recipes.rst, pyproject.toml, requirements.txt, requirements/build.txt
- fix log message in reconst
- fix cython version
- fix recipes
=> [BF] Uniformize cython version

dipy/reconst/dki.py, dipy/reconst/tests/test_dki.py
DKI fitting was not allowing to save S0 so I have made some updates.
=> return S0 from dki fit

dipy/reconst/dki.py, dipy/reconst/tests/test_dki.py, dipy/viz/horizon/app.py, dipy/viz/horizon/tab/base.py, dipy/viz/horizon/tab/peak.py, dipy/viz/horizon/tab/slice.py, dipy/viz/horizon/util.py, dipy/viz/horizon/visualizer/__init__.py, dipy/viz/horizon/visualizer/meson.build, dipy/viz/horizon/visualizer/peak.py, dipy/viz/tests/test_util.py, dipy/workflows/io.py, dipy/workflows/reconst.py, doc/recipes.rst, pyproject.toml, requirements.txt, requirements/build.txt
This PR introduces bug fixes for Peaks, making the slicer range till the start and end of the native coordinates.
It also introduces synchronization for the peak actors and images.
=> Bugfix for peaks slices and synchronization.

dipy/reconst/dki.py, dipy/reconst/tests/test_dki.py
Extra fixes for masking for NLLS DKI which solves #3033
=> Dkimaskfix

dipy/reconst/dki.py, dipy/reconst/tests/test_dki.py
this PR should fix #2994.
it makes sure that we use the mask for NLLS fitting. This feature has been removed accidentally on previous PR. 
I added a test to make sure we can catch it next time.
=> [RF] fix dki mask for nlls

dipy/workflows/viz.py, doc/interfaces/index.rst, doc/interfaces/viz_flow.rst
This PR introduces a CLI tutorial for Viz.
The tutorial talks about
- Opening a brain image.
- Opening a brain image with volumes.
- Opening a tractogram.
- Opening a surface.
=> Viz cli tutorial updated

doc/examples/tracking_introduction_eudx.py
- the tracking example included the response calculation, which is not required for csa odf fit.
- re-ordered imports
Thanks @ebrahimebrahim
=> DOC - Removed unnecessary line from tracking example

dipy/nn/model.py, dipy/nn/tests/test_histo_resdnn.py, dipy/nn/tests/test_tf.py
- ENH: Prefer using an Input(shape) as first layer in Sequential models
- TEST: Filter legacy SH bases warnings in histology ResDNN model test
=> ENH: Fix miscellaneous warnings

.github/workflows/nightly.yml, .github/workflows/test.yml, .github/workflows/test_pre.yml, .github/workflows/test_template.yml
=> [CI] update CI's script

dipy/workflows/stats.py
- DOC: Fix parameter name in `buan_bundle_profiles` docstring
- ENH: Remove unused parameters in `stats` module
=> ENH: Miscellaneous cleanup

dipy/workflows/reconst.py, dipy/workflows/tests/test_reconst_dki.py, dipy/workflows/tests/test_reconst_dsi.py, dipy/workflows/tests/test_reconst_dti.py
Fixes https://github.com/dipy/dipy/issues/3122
Since I was there, I also added saving the peaks to the dki workflow and the generalized FA value to the dsi workflow for standardization.
Maybe you'd have a minute to review @skoudoro?
=> ENH: add save peaks to dipy_fit_dti, dki

dipy/core/sphere.py, dipy/core/tests/test_sphere.py
- This pull request introduces a new feature: the Fibonacci Hemisphere function, added to the core functionality of the project.
* Added Fibonacci Hemisphere function to core.
* Added Test for Fibonacci Hemisphere.
=> NF: Fibonacci Hemisphere

dipy/conftest.py, dipy/viz/__init__.py
- STYLE: Define a unique `FURY` package absence import warning message
- ENH: Remove filtering `UserWarning` warnings in test config file
=> ENH: Remove filtering `UserWarning` warnings in test config file

dipy/align/expectmax.pyx, dipy/denoise/pca_noise_estimate.pyx, dipy/direction/ptt_direction_getter.pyx
- DOC: Fix typos in method docstrings
- DOC: Fix method parameter name in docstring
=> DOC: Fix documentation typos

dipy/reconst/msdki.py, dipy/tracking/distances.pyx, doc/devel/installation_from_source.rst, doc/examples/reconst_msdki.py, doc/reconstruction_models_list.rst, doc/release_notes/release0.15.rst
This PR refactors codespell issues in CI pipeline.
- acquistion ==> acquisition
- Hombrew ==> Homebrew
- metrices ==> metrics
- intrisic ==> intrinsic
- fliped ==> flipped
=> RF: Codespell fix for CI

dipy/core/optimize.py, dipy/segment/fss.py, dipy/segment/tests/test_fss.py, dipy/tracking/life.py
See also:
- https://github.com/mne-tools/mne-python/issues/12642
- https://github.com/mne-tools/mne-python/pull/12646
=> RF: Switch from using sparse *_matrix to *_array.

dipy/stats/tests/test_qc.py
Fix style: make statement dwell on a single line to make ruff happy.
Inadvertently left behind in commit
3795945e1ef2bcacccea744efa88351cc09ecb62.
=> STYLE: Make statement dwell on a single line

dipy/data/__init__.py, dipy/data/fetcher.py
=> NF: Applying Decorators in Module (Data)

dipy/io/dpy.py, dipy/io/image.py, dipy/io/peaks.py, dipy/io/stateful_tractogram.py, dipy/io/streamline.py, dipy/io/surface.py, dipy/io/utils.py, dipy/io/vtk.py
=> NF: Applying Decorators in Module (Io)

dipy/utils/arrfuncs.py, dipy/utils/deprecator.py, dipy/utils/parallel.py, dipy/utils/volume.py
=> NF: Applying Decorators in Module (Utils)

dipy/sims/phantom.py, dipy/sims/voxel.py
=> NF: Applying Decorators in Module (Sims)

dipy/core/geometry.py, dipy/core/gradients.py, dipy/core/graph.py, dipy/core/histeq.py, dipy/core/interpolation.pyx, dipy/core/onetime.py, dipy/core/optimize.py, dipy/core/profile.py, dipy/core/rng.py, dipy/core/sphere.py, dipy/core/sphere_stats.py, dipy/core/subdivide_octahedron.py, dipy/core/wavelet.py
=> NF: Applying Decorators in Module (Core)

dipy/align/_public.py, dipy/align/bundlemin.pyx, dipy/align/cpd.py, dipy/align/imaffine.py, dipy/align/imwarp.py, dipy/align/metrics.py, dipy/align/parzenhist.pyx, dipy/align/reslice.py, dipy/align/scalespace.py, dipy/align/streamlinear.py, dipy/align/streamwarp.py, dipy/align/vector_fields.pyx
=> NF: Applying Decorators in Module (Align)

dipy/segment/bundles.py, dipy/segment/clustering.py, dipy/segment/clustering_algorithms.pyx, dipy/segment/fss.py, dipy/segment/mask.py, dipy/segment/threshold.py, dipy/segment/tissue.py
=> NF: Applying Decorators in Module (Segment) 

dipy/nn/cnn_1d_denoising.py, dipy/nn/deepn4.py, dipy/nn/evac.py, dipy/nn/histo_resdnn.py, dipy/nn/model.py, dipy/nn/synb0.py, dipy/nn/utils.py
=> NF: Applying Decorators in Module (NeuralNetwork)

dipy/workflows/align.py, dipy/workflows/combined_workflow.py, dipy/workflows/denoise.py, dipy/workflows/docstring_parser.py, dipy/workflows/io.py, dipy/workflows/mask.py, dipy/workflows/multi_io.py, dipy/workflows/nn.py, dipy/workflows/reconst.py, dipy/workflows/segment.py, dipy/workflows/stats.py, dipy/workflows/tracking.py, dipy/workflows/viz.py, dipy/workflows/workflow.py
=> NF: Applying Decorators in Module (Workflow)

dipy/viz/horizon/app.py, dipy/viz/horizon/tab/base.py, dipy/viz/horizon/tab/peak.py, dipy/viz/horizon/tab/slice.py, dipy/viz/horizon/util.py, dipy/viz/horizon/visualizer/cluster.py, dipy/viz/horizon/visualizer/peak.py, dipy/viz/horizon/visualizer/slice.py, dipy/viz/panel.py, dipy/viz/plotting.py, dipy/viz/projections.py, dipy/viz/regtools.py, dipy/viz/streamline.py
=> NF: Applying Decorators in Module (Visualization)

.github/workflows/build_docs.yml
Add a GHA workflow file to build the documentation (excluding the examples).
=> ENH: Add a GHA workflow file to build docs

dipy/nn/cnn_1d_denoising.py, dipy/nn/deepn4.py, dipy/nn/evac.py, dipy/nn/histo_resdnn.py, dipy/nn/synb0.py, dipy/workflows/nn.py, doc/theory/sh_basis.rst
- DOC: Cite `nn` references through `sphinxcontrib-bibtex`
- DOC: Cite `theory` references through `sphinxcontrib-bibtex`
=> DOC: Cite `nn` references through `sphinxcontrib-bibtex`

dipy/reconst/dki.py
Remove unused parameters from method signature and non-existing input parameters from docstring.
=> RF: Remove unused parameters from method signature

dipy/align/imaffine.py, dipy/data/fetcher.py, dipy/reconst/cross_validation.py, dipy/reconst/dki.py, dipy/reconst/dsi.py, dipy/reconst/forecast.py, dipy/reconst/qtdmri.py, dipy/reconst/shm.py, dipy/reconst/shore.py
- DOC: Mark as raw strings docstrings using LaTeX math expressions
- DOC: Fix warnings related to displayed math expressions
=> DOC: Fix warnings related to displayed math expressions

dipy/reconst/fwdti.py
Set the `Diso` parameter value to the one provided in `wls_fit_tensor`.
=> BF: Set the `Diso` parameter value to the one provided 

dipy/core/geometry.py, dipy/core/graph.py, dipy/core/sphere_stats.py, dipy/data/__init__.py, dipy/io/dpy.py, dipy/reconst/gqi.py, dipy/stats/qc.py, dipy/tracking/metrics.py, dipy/tracking/utils.py, dipy/utils/deprecator.py
This PR is to fix some of the doctest warnings.
=> RF: Doctest warnings

dipy/align/bundlemin.pyx, dipy/align/parzenhist.pyx, dipy/align/vector_fields.pyx, dipy/core/interpolation.pyx, dipy/denoise/denspeed.pyx, dipy/denoise/enhancement_kernel.pyx, dipy/denoise/pca_noise_estimate.pyx, dipy/denoise/shift_twist_convolution.pyx, dipy/segment/clustering_algorithms.pyx, dipy/tracking/fbcmeasures.pyx, dipy/tracking/streamlinespeed.pyx, dipy/tracking/vox2track.pyx
=> RF: Removal of keyword form Cython files

dipy/direction/bootstrap_direction_getter.pyx, dipy/direction/closest_peak_direction_getter.pyx, dipy/direction/peaks.py, dipy/direction/probabilistic_direction_getter.pyx, dipy/direction/ptt_direction_getter.pyx, dipy/direction/tests/test_bootstrap_direction_getter.py, dipy/direction/tests/test_peaks.py, dipy/reconst/tests/test_dsi_deconv.py, dipy/reconst/tests/test_forecast.py, dipy/reconst/tests/test_gqi.py, dipy/reconst/tests/test_mapmri.py, dipy/reconst/tests/test_rumba.py, dipy/reconst/tests/test_shore_odf.py
=> NF: Applying Decorators in Module (Direction)

.pep8speaks.yml, dipy/data/fetcher.py, dipy/nn/deepn4.py, dipy/nn/evac.py, dipy/nn/tests/test_utils.py, dipy/nn/utils.py
This commit aims to fix the transformation function in dipy.nn.utils to make it work on more various cases of images. Any functions that use the transform_img and recover_img functions have been changed accordingly as well. batch_size bug in evac was fixed as it was a minor error.
=> BF Fixing transformation function

.github/workflows/build_docs.yml, dipy/align/crosscorr.pyx, dipy/align/expectmax.pyx, dipy/core/interpolation.pyx, dipy/core/optimize.py, dipy/denoise/denspeed.pyx, dipy/denoise/pca_noise_estimate.pyx, dipy/denoise/shift_twist_convolution.pyx, dipy/segment/featurespeed.pyx, dipy/tracking/stopping_criterion.pyx, dipy/viz/horizon/visualizer/peak.py, dipy/workflows/base.py, doc/conf.py, doc/examples/gradients_spheres.py, doc/tools/apigen.py, doc/tools/build_modref_templates.py, doc/tools/docgen_cmd.py, pyproject.toml
- [doc: fix Inline emphasis start-string without end-string](https://github.com/dipy/dipy/commit/7183d6f563cc3e644c86b614ce3de3ce354e0024)
- [doc: remove link_names](https://github.com/dipy/dipy/commit/f3b1318c886702727fb2b2f132e128fb7f507879)
- fix #3326
- bump python version for `build_docs` CI
=> DOC: Address remaining some warnings

dipy/denoise/gibbs.py
This PR fixes https://github.com/dipy/dipy/issues/2757.
if `num_processes=1`, the function `_gibbs_removal_2d` will be called sequentially for each slice, avoiding multiprocessing module.
Can you have a quick look @tashrifbillah? Can you test it. 
Thanks
=> RF: Add support for sequential processing in Gibbs unringing

.github/workflows/first_interaction.yml, doc/devel/commit_codes.rst
- DOC: Add first interaction GHA workflow file
- DOC: Use sentence case for example commit message subject
=> DOC: Add first interaction GHA workflow file

doc/examples/reconst_csd.py, doc/examples/reconst_cti.py, doc/examples/reconst_dki.py, doc/examples/reconst_dki_micro.py, doc/examples/reconst_dsi.py, doc/examples/reconst_dsid.py, doc/examples/reconst_dti.py, doc/examples/reconst_ivim.py, doc/examples/reconst_rumba.py, doc/examples/reconst_sfm.py
fix #3389
- small PR to update DTI tutorial title to make it more explicit.
- Other Reconstructions tutorial has been updated by adding the acronym
=> DOC: Update DTI tutorial title

.github/workflows/first_interaction.yml
- STYLE: Improve first interaction text layout
- DOC: Use URLs to link to CoC and CONTRIBUTING files in workflow config
=> DOC: Improve first interaction GitHub Actions config file

dipy/reconst/dki.py, dipy/reconst/dti.py, dipy/reconst/meson.build, dipy/reconst/multi_voxel.py, dipy/reconst/tests/meson.build, dipy/reconst/tests/test_dki.py, dipy/reconst/tests/test_dti.py, dipy/reconst/tests/test_weights_method.py, dipy/reconst/weights_method.py, dipy/utils/parallel.py, doc/references.bib
Supersedes #3401 
Also, rebased on master again just now.
=> Robust split idea rebase tidy

.github/workflows/test_template.yml, doc/doc-requirements.txt
Small PR to unpin CVXPY since a bug for numpy 2.0 has been resolve on recent release
=> CI: unpin cvxpy 

.github/workflows/test_template.yml, .mailmap, Changelog, Makefile, doc/_static/version_switcher.json, doc/api_changes.rst, doc/devel/make_release.rst, doc/devel/toolchain.rst, doc/examples/fiber_to_bundle_coherence.py, doc/index.rst, doc/old_highlights.rst, doc/old_news.rst, doc/release_notes/release1.10.rst, doc/stateoftheart.rst
Preparation for 1.10.0 release, targeting **~~October 11, 2024~~ December 12th, 2024**
=> UPCOMING:  Release 1.10.0

doc/conf.py, doc/examples/_valid_examples.toml, doc/tractography_methods_list.rst
- DOC: Fix grammar in local reconstruction example doc index passage
- DOC: Add implemented tractography method table to tracking example index
=> DOC: Add implemented tractography method table to tracking example index

.github/workflows/nightly.yml, .github/workflows/test.yml, .github/workflows/test_pre.yml, .github/workflows/test_template.yml
This PR add python.3.13 to our CI's list.
Currently checking the freed-threaded version that's why it is in WIP.
ps: Python 3.9 will be removed after the DIPY 1.10.0 release in a new PR
=> CI: Add python 3.13

dipy/denoise/patch2self.py, dipy/workflows/denoise.py
Fixed an error where skipping b0_denoising was throwing an error, indicating mismatched volume indexes.
=> Patch2Self3 skipping b0_denoising error fixed.

dipy/io/streamline.py, dipy/tracking/tracker.py, dipy/tracking/tractogen.pyx, dipy/workflows/tests/test_tracking.py, dipy/workflows/tracking.py, doc/examples/tracking_bootstrap_peaks.py, doc/examples/tracking_introduction_eudx.py, doc/examples/tracking_pft.py, doc/examples/tracking_rumba.py, doc/examples/tracking_sfm.py, doc/examples/tracking_stopping_criterion.py
This PR update the tracking CLI to use the new framework.
Some tutorials still needs to be updated.
Let me know if you have comment on this PR, thank yoi
=> RF: update tracking cli

dipy/io/utils.py, dipy/workflows/io.py, doc/devel/installation_from_source.rst
- DOC: Improve the `IoInfoFlow` workflow `run` method docstring
- DOC: Fix reference information retrieval method short description
- DOC: Fix grammar in DIPY installation documentation
=> DOC: Miscellaneous doc improvements

doc/examples/tissue_classification_dam.py
Figure was not being saved for the doc build. Added the saving function
=> [RF]: Saving the figure in the example.

dipy/reconst/multi_voxel.py
=> FIX: Avoid division by zero on single-CPU systems (issue #3521)

.github/workflows/first_interaction.yml
Add additional emojis to first interaction message to make the messages more visually appealing.
Put all emojis at the beginning of the corresponding sentences.
=> STYLE: Add additional emojis to first interaction message

doc/examples/reconst_dti.py
This fix is solving issue with latex mentioned here. https://github.com/dipy/dipy/issues/3536
to
=> RF: Fixed the latex

dipy/workflows/io.py
Improve the information printed by the `dipy_info` command:
- Right-align printed values using the longest property name width so that the displayed data can be read more easily.
- Use a consistent style when printing 1D arrays: map them to tuples so that values are separated with commas and they use parentheses instead of square brackets.
- Improve the way the stats are printed: print the property only once and indent the stats with a tab character.
- Add the median to the printed stats.
- Print additional relevant properties for tractography data: affine matrix, data type, origin, space, and voxel order and size.
Refactor the `IoInfoFlow` workflow `run` method: encapsulate methods so that future changes can be more localized.
Take advantage of the commit to:
- Define the properties as …
=> RF: Improve `dipy_info` printed output

.github/labeler.yml, .github/workflows/label-pr.yml
=> NF: Add PR labeler workflow

dipy/align/imwarp.py, dipy/core/geometry.py, dipy/core/sphere_stats.py, dipy/direction/pmf.pyx, dipy/io/streamline.py, dipy/io/surface.py, dipy/reconst/rumba.py, dipy/tracking/distances.pyx, dipy/workflows/denoise.py, dipy/workflows/io.py
- DOC: Fix a typo in a docstring
- STYLE: Adopt f-strings in miscellaneous places
- DOC: Adopt f-strings in docstring tests
- STYLE: Fix Space and Origin choice error messages
=> STYLE: Miscellaneous style fixes

dipy/viz/tests/test_fury.py, doc/examples/cluster_confidence.py, doc/examples/fiber_to_bundle_coherence.py, doc/examples/path_length_map.py, doc/examples/streamline_tools.py, doc/examples/tracking_stopping_criterion.py, doc/examples/viz_roi_contour.py
We were still using our old Tracking API in many places. 
So, This PR make sure that we use our new tracking API.
=> RF: replace old LocalTracking by our new tracking interface
