- dipy/tracking/propspeed.pyx
- dipy/tracking/tests/test_propagation.py
This supersedes https://github.com/nipy/dipy/pull/540, and includes the whitespace comments that @Garyfallidis made on the previous PR. Just trying to move things along here.
> Refactor propspeed - updated

- dipy/info.py
NBD. The previous upload link is no longer existent. See also:
https://github.com/blog/1302-goodbye-uploads.
> DOC: Update download link.

- dipy/reconst/csdeconv.py
- dipy/reconst/tests/test_csdeconv.py
As per the title, I added an option to return the number of voxels used in the response function estimation. That way, one can increase the roi or lower the threshold if only a small number of voxel is found.
A warning is also raised if no voxel fitting the threshold is found, which is inherently lower than 0.7 in small animal data, highly noisy data, badly behaved synthetic data, etc.
> Added option to return the number of voxels fitting the fa threshold

- dipy/reconst/dti.py
- dipy/reconst/tests/test_dti.py
geodesic anisotropy (GA) is from Batchelor et al MRM 2005. It can viewed as the log-Euclidean version of FA.
> NF: geodesic anisotropy

- dipy/core/geometry.py
- dipy/core/tests/test_geometry.py
I don't think `cart2sphere(0, 0, 0)` should return any nans. Here is a fix.
> Bf cart2sphere

- dipy/reconst/benchmarks/bench_csd.py
- dipy/reconst/csdeconv.py
- dipy/reconst/tests/test_csdeconv.py
I've implemented the CSD fitting using the Cholesky decomposition. Here are the fitting times I get with the new and old versions:
New:
SH order - 8, gradient directons - 150 :: 1.76 sec
SH order - 8, gradient directons - 65 :: 2.01 sec
SH order - 12, gradient directons - 65 :: 5.77 sec
Old:
SH order - 8, gradient directons - 150 :: 7.81 sec
SH order - 8, gradient directons - 65 :: 8.22 sec
SH order - 12, gradient directons - 65 :: 30.87 sec
I'd like to include the document I got from @Garyfallidis as a reference in this PR somehow, but it's a PDF and I'm not sure the best way to do it. Should we maybe upload the PDF tot he website and include a link?
> RF: use cholesky to solve csd

- dipy/reconst/peak_direction_getter.pyx
- dipy/tracking/local/direction_getter.pxd
- dipy/tracking/local/direction_getter.pyx
- dipy/tracking/local/tissue_classifier.pxd
- dipy/tracking/local/tissue_classifier.pyx
Latest (using Cython post-0.22) seems to require that except values in the pxd
signature match the signature in the pyx signature.
> BF: update cython signatures with except values

- dipy/reconst/dti.py
Small kind of typo according to line 762.
While I'm at it, would it be easier to instead create a mask excluding a non zero voxel like when the scanner masks the background instead of processing all voxels? All submodels could call a subfunction creating a mask where at least one voxel is not zero along the 4th D.
> docstring for tensor fit was wrong

- dipy/core/geometry.py
- dipy/sims/tests/test_voxel.py
- dipy/sims/voxel.py
This also entails removing some hackish stuff in geometry.
H/T to @cpoetter for pointing this out.
> BF: all_tensor_evecs should rotate from eye(3) to e0.

- dipy/reconst/csdeconv.py
- dipy/reconst/tests/test_csdeconv.py
- doc/examples/reconst_csd.py
I re-based #404 to clean it up a little bit. The changes I made are:
1) Took out new functions in `dipy.reconst.shm`, these functions were not being called or tested. (Did this via rebase).
2) I re-worked a little bit how the SH response was being handled. Only axially symmetric SH functions are needed so we don't bother to fit all the SH functions and zero out the non-symmetric coefficients. This should improve accuracy and performance.
3) Changed recursive_response to use `default_sphere`. 
4) Fixed issue with response_scaling being wrong when an SH response was used.
@arokem  @ChantalTax can you guys look over this.
> Nf csd calibration

- dipy/segment/clusteringspeed.pyx
- dipy/segment/featurespeed.pyx
- dipy/segment/metricspeed.pxd
- dipy/segment/metricspeed.pyx
- dipy/tracking/local/tissue_classifier.pyx
Fixes compilation errors in Cython code.
Cython's version 0.22 fixes the following bug "* Mismatching 'except' declarations on signatures in .pxd and .pyx files failed to produce a compile error".
Closes #597
> Fixed undetected compilation errors prior to Cython 0.22

- dipy/reconst/sfm.py
On the other hand, scipy deprecates nanmean from 0.15 and onwards.
Addresses gh-600
> BF: Some versions (<0.18) of numpy don't have nanmean.

- dipy/tracking/local/tissue_classifier.pyx
Windows complains for lack of the `round` symbol; use dpy_rint instead
(implemented in the dpy_math.h header).
> BF: use dpy_rint instead of round for Windows

- dipy/reconst/csdeconv.py
- dipy/reconst/multi_voxel.py
- dipy/reconst/shm.py
- dipy/reconst/tests/test_csdeconv.py
Prediction from arrays of models was failing. Specifically, for multi-voxel fits, we need to provide an array of S0, which matches the 3D shape of the data. In the previous implementation, this silently added multiple dimensions to the array. The solution proposed here is to push the prediction in the `MultiVoxelFit` object, so that it calls out to each individual item's prediction, with the right S0 taken from the inputs (or defaulting to the right thing - all 1's).
> BF: csd predict multi

- dipy/COMMIT_INFO.txt
- dipy/denoise/noise_estimate.py
- doc/examples/denoise_nlmeans.py
- doc/examples/piesno.py
- doc/examples/snr_in_cc.py
- doc/examples_index.rst
This supersedes https://github.com/nipy/dipy/pull/390
> Piesno example

- doc/developers.rst
Simply readd a missing developer from the contributor list. It seems to have been lost when updating the developers list during one of the last releases.
I also saw that there were other missing contributors (with low commit counts, as I do). @Garyfallidis said to wait before adding them.
> DOC: Added missing contributor to developer list

- dipy/reconst/dti.py
- doc/examples/restore_dti.py
Found 2 small typos in the restore tutorial + a missing closing parenthesis in reconst/dti.py.
> DOC: Corrected typos in Restore tutorial and docstring.

- dipy/viz/fvtk.py
I'm playing with some example visualizations of points and lines, and noticed that changing opacity argument in point actor didn't work so I added it. It works, but it also shows some little artifacts in order of rendering when you use lower opacity---works as before with opacity=1. I'll explore the topic.
> BF: Add missing opacity property to point actor

- doc/examples/reconst_dti.py
I was ~~stealing~~ lazily borrowing equations and stumbled upon a long forgotten typo.
> fixed typo in dti example

- dipy/tracking/local/__init__.py
TissueTypes was in `__all__` but it was never imported.
> BF - no import of TissueTypes

- dipy/align/vector_fields.pxd
- dipy/align/vector_fields.pyx
If inline functions are just declared in the pxd, cython attempts to declare inline pointers to them, which is invalid since variables cannot be declared inline. According to this:
http://docs.cython.org/src/tutorial/pxd_files.html
inline functions should be defined, not just declared in the pxd.
Unfortunately, right now I don't have access to the buildbots to try this, but in theory this should fix the issue.
> Fix compilation error caused by inline functions 

- dipy/viz/fvtk.py
Otherwise, each consecutive frame over-writes the previous one.
> BF: If n_frames is larger than one use path-numbering.

- dipy/denoise/noise_estimate.py
- dipy/denoise/tests/test_noise_estimate.py
- dipy/reconst/dti.py
- doc/examples/denoise_nlmeans.py
So I added the correction factor for computing the std of magnitude images. Since they do not include any negative value, the variance is lower and the mean is shifted as compared ot a gaussian distribution. This factor corrects that fact and returns a closer estimate of the variance.
I also updated the example to show this fact and changed it to show a slice of diffusion instea,d since b0 images are always relatively clean.
Since estimate_sigma is the same as computing the variance over the background, the correction factor needs an estimate of the local magnitude SNR, but it is zero in that specific case. Hence, the value can be precomputed without using hyp1f1. Next step is to have it on a voxelwise basis with said hyp1f1 function in need of love over here : …
> Added estimate_sigma bias correction + update example

- dipy/reconst/shm.py
- dipy/reconst/tests/test_csdeconv.py
Addresses https://github.com/nipy/dipy/issues/611 ?
> BF: Differences in spherical harmonic calculations wrt scipy 0.15

- dipy/viz/fvtk.py
Otherwise, we get an indexing error on line 1413.
> BF: If scalar-color input has len(shape)<4, need to fill that in.

- dipy/core/geometry.py
> Improve check of collinearity in vec2vec_rotmat

- .mailmap
- AUTHOR
More professional than a gmail address.
> changed samuel st-jean email to the usherbrooke one

- dipy/data/fetcher.py
While I was there, I did a bit of PEP8 cleaning and functionalized some repeated boiler-plate.
> NF: Fetch and Read the MNI T1 and/or T2 template.

- dipy/pkg_info.py
Also, fix issues with ConfigParser on python 3.
Related to this SO post: http://stackoverflow.com/questions/14340366/configparser-and-string-with
> BF + NF: Provide dipy version info when running dipy.get_info()

- dipy/core/geometry.py
- dipy/core/tests/test_geometry.py
Hello!
I implemented a function to sample perpendicular directions relative to a given vector. I will need this function for the future steps of the development of the diffusion kurtosis module (work in progress at #664), however since this function is quite general and might be useful for other techniques, I decided to submit it in a different pull request. I am suggesting to have this function in dipy.core.geometry. The function is being tested in the relevant testing file.
For the math details of the function, you can see the following post:
http://gsoc2015dipydki.blogspot.it/2015/07/rnh-post-8-computing-perpendicular.html
> NF: Function to sample perpendicular directions relative to a given vector

- dipy/segment/clusteringspeed.pyx
- dipy/segment/tests/test_quickbundles.py
- dipy/testing/memory.py
- dipy/testing/tests/test_memory.py
This PR fixes a memory leak that was present in `ClusterCentroid` used by the QuickBundles algorithm. The `__dealloc__` function was missing a free statement for a variable. In addition to that, references count of `memoryview` objects were not decremented automatically/correctly when freeing the allocated memory. I found that assigning them to `None` (before freeing the memory) works.
This PR also add a testing tool that retrieves the refcount of a given object type. This tool is used in the new unit test function that check there are no memory leaks in QuickBundles.
> BF: Fixed memory leak in QuickBundles.

- dipy/denoise/noise_estimate.py
- dipy/denoise/tests/test_noise_estimate.py
Turns out I misread something the first time, this fixes the initial estimation fo sigma for piesno. The current version uses the optimal quantile of the current slice, whereas the original paper suggest to use the full volume instead. This should hopefully fix this little discrepancy.
> Fixed initial estimation in piesno

- dipy/segment/tests/test_metric.py
Replaced an `assert_equal` with an `assert_almost_equal`.
http://nipy.bic.berkeley.edu/builders/dipy-py2.6-32/builds/551/steps/shell_6/logs/stdio
> BF: Make buildbot Pyhon26-32 happy

- dipy/align/bundlemin.pyx
- dipy/align/sumsqdiff.pyx
- dipy/align/tests/test_sumsqdiff.py
- dipy/reconst/recspeed.pyx
- dipy/tracking/distances.pyx
Including start of review of uses of int and size_t for things that refer to
array sizes / shapes.
> MRG: some Cython refactorings

- .travis.yml
See Travis docs for details:
http://docs.travis-ci.com/user/migrating-from-legacy/?utm_source=legacy-notice&utm_medium=banner&utm_campaign=legacy-upgrade
> TST: update Travis config to use container infrastructure.

- dipy/align/imaffine.py
- dipy/align/tests/test_imaffine.py
- dipy/align/tests/test_parzenhist.py
- dipy/align/tests/test_vector_fields.py
- dipy/align/vector_fields.pyx
This fixes the segmentation fault caused when attempting to interpolate an image at nan entries.
> BF: nan entries cause segfault

- dipy/reconst/dti.py
- dipy/reconst/tests/test_dti.py
- dipy/reconst/tests/test_shore_metrics.py
- dipy/sims/tests/test_voxel.py
- dipy/sims/voxel.py
As pointed out by @RafaelNH here: https://github.com/nipy/dipy/pull/582, there seems to be some inconsistency about whether eigenvectors of tensors should be arranged column-wise or row-wise in 3-by-3 arrays. I am trying to enforce something uniform here. At the moment, this triggers several other test failures, but I wonder whether these are because of patching around this inconsistency, and would just require some additional fixing to make all parts consistent. I am continuing to investigate.
> Test DTI eigenvectors

- dipy/data/__init__.py
- dipy/data/fetcher.py
> CENIR 'HCP-like' multi b-value data

- dipy/align/imaffine.py
- dipy/align/tests/test_imaffine.py
- doc/api_changes.rst
- doc/examples/affine_registration_3d.py
- doc/examples/syn_registration_3d.py
We recently renamed some utility functions (those that apply affine transforms) from 'warp...' to 'transform...', but did not update the tutorial appropriately. Here we use AffineMap instead of directly calling the utility function to make the code a bit cleaner.
> Fix syn-3d example

- doc/examples/affine_registration_3d.py
One-word fix (which is probably a no-op anyway), but would help clarify the example a tiny bit.
> DOC: Use the `identity` variable in the resampling transformation.

- dipy/core/sphere.py
- dipy/core/tests/test_sphere.py
Recent changes in scipy use a different heuristic to find the epsilon
parameter used for RBF interpolation, causing for us issue #688. This
should fix it, by using the old heuristic.
> BF: Keep up with changes in scipy 0.16

- dipy/io/gradients.py
- dipy/io/tests/test_io_gradients.py
This should fix #697. 
As with the previous one: the first two commits are fixes to the issue, and the last commit is a bit of cleanup (PEP8, etc).
> Check for bval dimensionality on read. 

- dipy/align/imaffine.py
- dipy/align/tests/test_imaffine.py
- dipy/align/tests/test_vector_fields.py
- dipy/align/vector_fields.pyx
This PR just adds tests for the AffineMap class.
> TEST: add tests for AffineMap

- dipy/data/fetcher.py
To get data from a single b-value 'tier'. 
Not really a BF, but increases usability a tiny bit.
> RF: In case a user just wants to use a single integer.

- dipy/denoise/noise_estimate.py
- dipy/denoise/tests/test_noise_estimate.py
Since this is a case that can happen, and was the old behavior, I added an option to disable the correction factor, which is the default as it was before.
> Added gaussian noise option to estimate_sigma

- .travis.yml
@arokem we need also python-tk. For some reason it is not installed by default in the bot. Can you merge this PR first?
> Added installation of python-tk package for VTK travis bot

- dipy/reconst/csdeconv.py
- dipy/reconst/tests/test_csdeconv.py
This PR adds a function to compute the csd response from a pre-computed mask. This complements auto_response() and recursive_response() functions.
> NF - CSD response from a mask

- dipy/reconst/dti.py
- dipy/reconst/tests/test_dti.py
- dipy/utils/arrfuncs.py
- dipy/utils/tests/test_arrfuncs.py
Speed up certain tensor fitting functions by vectorizing calculations.
> Optimize tensor fitting

- dipy/tracking/streamline.py
multiple streamlines selected twice.
> ENH: it is preferable to use choice rather than randint to not have 

- dipy/tracking/streamlinespeed.pyx
- dipy/tracking/tests/test_streamline.py
Refcount is not decreased when converting a numpy array, previously defined in Python space (i.e. not in the .pyx file), into a Cython typed memory view.
The workaround is to create a copy of the numpy array using `astype` while in Cython space. Luckily for us, most of the time no data is copied, only metadata (i.e. when the dtype stays the same).
Fixes #737
> BF: memleaks with typed memory views in Cython

- dipy/reconst/mapmri.py
- dipy/reconst/tests/test_mapmri.py
- doc/examples/reconst_mapmri.py
This is the second part of the MAPMRI pull request, which add RTOP, RTAP and RTPP, three microstructural EAP indices introduced in  Ozarslan E. et. al, "Mean apparent propagator (MAP) MRI: a novel diffusion imaging method for mapping tissue microstructure", NeuroImage, 2013.
p.s. The example is still missing, which dataset do you think I should use? The DSI data that I use as an example for the SHORE? Or do we have better multi-shell data?
> Add RTOP, RTAP and RTPP and the relative test

- dipy/align/bundlemin.pyx
- dipy/align/streamlinear.py
- dipy/align/tests/test_streamlinear.py
- dipy/denoise/denspeed.pyx
- dipy/denoise/nlmeans.py
- dipy/denoise/tests/test_nlmeans.py
- doc/installation.rst
- src/conditional_omp.h
- src/safe_openmp.pxd
This should be working now but it maybe need a few more checks with the tests. I will do that asap.
> Set number of OpenMP threads during runtime

- dipy/reconst/cross_validation.py
- dipy/reconst/dki.py
- dipy/reconst/dti.py
- dipy/reconst/multi_voxel.py
- dipy/reconst/tests/test_cross_validation.py
- dipy/reconst/tests/test_dki.py
- dipy/reconst/tests/test_dti.py
- dipy/reconst/tests/test_multi_voxel.py
This is an improvement on the previous API, which did not allow using masks for multi-voxel predictions, making predictions for cross-validation un-necessarily slow.
> RF: use masks in predictions and cross-validation

- dipy/tracking/_utils.py
In some case, tracts can be generated exactly on the border of the image volume. When mapped back to voxel coordinates, due to numerical imprecisions, they may have a coordinate with a value like -5.96046447754e-08, which trips up the negative coordinates test in _to_voxel_coordinates.
I added a tolerance to avoid rejecting valid points. Using a very small threshold so that genuinely invalid points still end up raising the error.
> BF: added tolerance for negative streamline coordinates checks

- dipy/tracking/tests/test_utils.py
Added the test that was missing in PR #678
> TST: added test for _to_voxel_tolerance.

- dipy/segment/mask.py
Try 
from dipy.segment.mask import median_otsu
with scikit-image installed, so that it uses the local version, and you get
/home/samuel/.local/lib/python2.7/site-packages/skimage/filter/__init__.py:6: skimage_deprecation: The `skimage.filter` module has been renamed to `skimage.filters`.  This placeholder module will be removed in v0.13.
warn(skimage_deprecation('The `skimage.filter` module has been renamed '
So now it's fixed. It should also use the local copy in case the user has an old version.
> Fixed deprecation warning in skimage

- dipy/align/reslice.py
- dipy/align/tests/test_reslice.py
- Using a 1D transformation matrix instead of a 2D diagonal matrix reduces computation time.
- Using the `output` argument in `affine_transform` reduces memory usage.
> Optimize dipy.align.reslice

- dipy/tracking/streamline.py
- dipy/tracking/tests/test_streamline.py
This is important in order to correctly pull out a core of a bundle based on a median operation on the coordinates. For details, see: 
https://github.com/arokem/AFQ-notebooks/blob/08ac2fc66d1ded0234eec898438d0c7f8380cafc/AFQ-registration-callosum.ipynb
> Reorient tracks according to ROI

- dipy/reconst/dti.py
Splits data into a number of chunks of specified size and iterates the
decorated fit_tensor function over them. This is useful to counteract
the temporary but significant memory usage increase in fit_tensor
functions that use vectorized operations and need to store large
temporary arrays for their vectorized operations.
> Add fit_tensor iteration decorator

- dipy/viz/tests/test_fvtk_actors.py
Depending on the hardware/software version of the bot sometimes the snapshot cannot work in stealthmode. For now I am changing for this test to offscreen=False. Hopefully this will resolve the current fail in master and in the future we can figure out how to stabilize xvfb.
> Offscreen is False for test_slicer

- dipy/reconst/dsi.py
- dipy/reconst/tests/test_dsi.py
- dipy/reconst/tests/test_dsi_metrics.py
Is this a problem? 
cc: @Garyfallidis
> TST: Test DSI with b0s.

- bin/dipy_peak_extraction
- dipy/direction/__init__.py
- dipy/direction/peaks.py
- dipy/direction/probabilistic_direction_getter.py
- dipy/direction/tests/test_peaks.py
- dipy/reconst/csdeconv.py
- dipy/reconst/peaks.py
- dipy/reconst/tests/test_csdeconv.py
- dipy/reconst/tests/test_dsi.py
- dipy/reconst/tests/test_dsi_deconv.py
- dipy/reconst/tests/test_gqi.py
- dipy/reconst/tests/test_mapmri_odf.py
- dipy/reconst/tests/test_peakdf.py
- dipy/reconst/tests/test_shm.py
- dipy/reconst/tests/test_shore_odf.py
- dipy/tracking/markov.py
- doc/examples/sfm_reconst.py
- doc/examples/sfm_tracking.py
> RF: Move the peaks module from dipy.reconst to dipy.directions. 

- dipy/viz/window.py
That one didn't do it, because we need a dual try to finally conclude
That there's no tkinter here anywhere.
> BF: This continues #776.

- dipy/align/imwarp.py
Pickle fails when attempting to save memory views. Here we simply convert the `forward` and `backward` deformation fields to numpy arrays so we can now save the `DiffeomorphicMap` instance returned from `SymmetricDiffeomorphicRegistration` to disk with pickle.
> Saving DiffeomorphicMap with pickle

- dipy/align/reslice.py
- dipy/viz/actor.py
- dipy/viz/tests/test_fvtk_actors.py
If the voxel size was not isotropic the slicer was not showing properly the image in world space. Now this is fixed. The previous version had the potential advantage of allowing to slice in 1mm voxel size rather than in voxel coordinates. This is still available by unsetting the flag voxel size and it should work nicely with isotropic voxel sizes but the results will not be nice with anisotropic voxel sizes therefore it is set to false by default.
> Fix anisotropic voxel size use by setting vox_size in vtkImageReslice of slicer actor

- dipy/viz/utils.py
Only an issue on some systems. For example:
http://nipy.bic.berkeley.edu/builders/dipy-py2.7-wheezy-sparc/builds/225/steps/shell_9/logs/stdio
> BF: Cast input to np.repeat into int32.

- dipy/testing/decorators.py
- dipy/viz/tests/test_fvtk.py
- dipy/viz/tests/test_fvtk_actors.py
This seems (just) a bit more civilized than my previous kludge.
> TST: Make skipping with TEST_WITH_XVFB=skip more explicit.

- bin/dipy_fit_tensor
- bin/dipy_peak_extraction
- bin/dipy_quickbundles
- bin/dipy_sh_estimate
- bin/dipy_tracking_gui
Scripts should have shebang line "#!python" for correct installation
from e.g. pip.
> BF: fix shebang lines for scripts

- .travis.yml
- dipy/utils/tests/test_tripwire.py
- dipy/utils/tripwire.py
- tools/travis_tools.sh
I was puzzled to see that current master doesn't have the `Tripwire` fixes
Ariel did on the maintenance branch.
After a bit of debugging, I think what happened is you (Ariel) did a ``git
merge -s ours`` on the maintenance branch, at merge commit 6d31467 .  This has
the effect of marking that part of the maintenance history as known, but
throwing away the changes from the maintenance branch.  It's the right thing to
do if you are making changes you *don't* want in mainline, but the wrong thing
to do if you do want the changes.
I don't know how to undo that in a nice way, so I just cherry-picked back the
relevant commits.
> MRG: pull in discarded changes from maintenance

- dipy/align/tests/test_imwarp.py
This is a proposal for relaxing the regression tests of the registration module.
The original idea about the regression tests was to detect subtle changes in the registration module which could affect the overall registration accuracy. Current tests attempt to reproduce the evolution of the energy profile along the full optimization, this is a **very** strict test because it basically means attempting to perform exactly the same sequence of computations with the same precision. However, we have been facing a lot of problems reproducing the full energy profile across platforms, especially in  64 bits windows.
Instead of requiring the full sequence of computations being the same, this change only measures the final registration result, so the optimization may take different paths depending …
> Relax regression tests

- dipy/tracking/life.py
- dipy/tracking/tests/test_life.py
- dipy/tracking/vox2track.pyx
> Round coords life

- dipy/COMMIT_INFO.txt
COMMIT_INFO.txt should be a template for the install, but the written
out instance of the template got committed back in commit c3a8f3f.
> BF: revert accidentally committed COMMIT_INFO.txt

- .gitignore
- .travis.yml
- cythexts.py
- dipy/info.py
- requirements.txt
- setup.py
- setup_helpers.py
Refactor setup.py to work better with pip.  Allow setuptools / pip installs
into systems that don't have Cython (Cython gets installed automatically).
Update requirements in requirements.txt file and info.py.
Check installation via sdist and wheels.
> MRG: refactor and test setup.py

- dipy/core/gradients.py
- dipy/core/tests/test_gradients.py
- dipy/fixes/scipy.py
Loosely based on @rfdougherty's implementation here: https://github.com/cni/nims/blob/master/scripts/pepolar_unwarp.py 
TODO:
> Function to reorient gradient directions according to moco parameters

- dipy/tracking/local/localtracking.py
- dipy/tracking/local/tests/test_local_tracking.py
- dipy/tracking/tests/test_utils.py
- dipy/tracking/utils.py
- This PR adds the fct ``random_seeds_from_mask_total`` to generate N seeds given a mask. This complements the fct ``random_seeds_from_mask_per_voxel`` that already generates seeds given a mask. This is useful when you want N streamlines per region, with regions of various size.
- It also fixes a small bug. If N seeds were sent to ``LocalTracking`` with ``return_all==True``, the returned streamlines excluded all seeds with no valid initial direction. Now, if a seed has no valid initial direction, it return a streamline containing only the seed position.
> NF - random seeds from mask

- dipy/segment/cythonutils.pxd
- dipy/segment/cythonutils.pyx
- dipy/segment/featurespeed.pyx
- dipy/segment/metricspeed.pyx
- dipy/segment/tests/test_feature.py
According to issue #813, on Windows 64bit machines, integer constants are of type `long` instead of `int`. I added a unit test that explicitly test using a `long` as the type of the value returned by `feature.infer_shape`.
This PR also fixes another issue that came up in `metric.dist` while creating the new unit test.
> Fixes issue #813 by not checking data type explicitly.

- dipy/core/gradients.py
- dipy/core/tests/test_gradients.py
This get's rid of warnings of the following type that currently show up
in our tests:
./Users/arokem/source/dipy/dipy/core/gradients.py:132: RuntimeWarning: invalid value encountered in less_equal
bvecs_close_to_1 = abs(vector_norm(bvecs) - 1) <= atol
> RF: Convert nan values in bvectors to 0's

- CONTRIBUTING
- doc/devel/python3.rst
This file gets rendered by Github into PRs (https://github.com/blog/1184-contributing-guidelines) and should help newcomers figure out what/how/why to contribute. For the git procedure, I am directing them to the existing developer documentation, but this also covers some other points that we like to look for in our review. Am I forgetting anything important?
> "Contributing"

- doc/examples/valid_examples.txt
This is a (very) small change in the documentation, but also a more general question about how we should go about updating the documentation, while keeping it compatible with the 0.10.1 released version. Is the right thing to make the PRs on the documentation against the maint/0.10.x branch and then merge (cherry pick?) from there into master?
> DOC: Add the DKI reconstruction example to the list of valid examples.

- dipy/align/crosscorr.pyx
- dipy/align/expectmax.pyx
- dipy/align/parzenhist.pyx
- dipy/align/sumsqdiff.pyx
- dipy/align/transforms.pyx
- dipy/align/vector_fields.pyx
Workaround to prevent this kind of memory leaks:
https://github.com/omarocegueda/cython_leak_repro/blob/master/memory_leak.ipynb
which occur when using memory views allocated and returned from cython functions
> Return numpy arrays instead of memory views from cython functions

- dipy/denoise/nlmeans.py
So it was always using everything instead of the specified number, so now it's on par with the 4D version.
> nlmeans use num threads option in 3d

- dipy/viz/actor.py
- dipy/viz/fvtk.py
- dipy/viz/window.py
- doc/examples/introduction_to_basic_tracking.py
- doc/examples/reconst_dsid.py
- doc/examples/viz_slice.py
- doc/examples/viz_widgets.py
I was testing out `fvtk` (which is very nice by the way!) and encountered a number of small issues related to integer division, etc on Python 3 in both `dipy.viz` and a few of the examples.
I can omit b99d107227058b7e8bc58c8f1f64810f69d74235 if you don't want that one here.  It is related to future VTK 7.0 compatibility which I will discuss in a separate issue.
> miscellaneous Python 3 compatibility problem fixes in fvtk

- dipy/align/vector_fields.pyx
- dipy/tracking/streamline.py
- dipy/tracking/tests/test_streamline.py
- dipy/tracking/tests/test_utils.py
- dipy/tracking/utils.py
- doc/examples/probabilistic_fiber_tracking.py
Still need to test affine transformations
> Extract values from an image based on streamline coordinates.

- dipy/reconst/sfm.py
- dipy/reconst/tests/test_sfm.py
- doc/examples/sfm_reconst.py
- doc/examples/sfm_tracking.py
Previous reference was to a preprint that is now superseded by a peer-reviewed publication.
> A few fixes to SFM.

- dipy/reconst/dti.py
- dipy/reconst/tests/test_dti.py
This should help us with the issues that are currently being discussed over on #840
I have not memory profiled this yet, though. This is what I intend to do next, so stay tuned. Would be great if others could try this out as well.
> DTI memory: use the same step in prediction as you use in fitting.

- README.rst
As a new contributor, I believe it is helpful if the chat room is mentioned in the README.
> Add reference to gitter chat room in the README

- dipy/direction/peaks.py
- dipy/reconst/tests/test_shm.py
- dipy/tracking/local/tests/test_local_tracking.py
- dipy/tracking/tests/test_markov.py
Is coming down the pipes quick. 
Bringing with it the following errors: 
```
======================================================================
ERROR: dipy.reconst.tests.test_shm.test_SphHarmFit
----------------------------------------------------------------------
File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
self.test(*self.arg)
File "/build/dipy-0.10.1/debian/tmp/usr/lib/python2.7/dist-packages/dipy/reconst/tests/test_shm.py", line 281, in test_SphHarmFit
slice = fit[..., 0]
File "/build/dipy-0.10.1/debian/tmp/usr/lib/python2.7/dist-packages/dipy/reconst/shm.py", line 577, in __getitem__
new_coef = self._shm_coef[coef_index]
IndexError: an index can only have a single ellipsis ('...') …
```
> Updates for upcoming numpy 1.11 release

- doc/examples/tracking_tissue_classifier.py
Following discussion in issue #831, this PR changes the seeding mask to voxel with 100% wm partial volume fraction. Seeds placed in voxel with a partial volume fraction of gm > 0.5 created unwanted short streamlines.
Thanks @samuelstjean, @arokem
> Tissue Classifier tracking example - changed seeding mask to wm only voxels

- dipy/viz/colormap.py
- dipy/viz/fvtk.py
- dipy/viz/projections.py
- dipy/viz/regtools.py
- dipy/viz/widget.py
> Fix pep8 errors in viz

- dipy/tracking/streamline.py
- dipy/tracking/tests/test_streamline.py
The goal: value_from_volume to deal with streamlines with only one node each. 
See: #909
> Singleton sl vals

- Changelog
- doc/developers.rst
- doc/examples/bundle_registration.py
- doc/examples/valid_examples.txt
- doc/examples_index.rst
- doc/index.rst
- doc/release0.11.rst
- tools/make_examples.py
Hi this PR fixes crucial issue #906 and minor issue #900. Also it adds the dki tutorial back in the index.
> Getting website ready for 0.11 release

- dipy/align/tests/test_expectmax.py
> Fix PEP8 in test_expectmax

- bin/dipy_quickbundles
- dipy/tests/test_scripts.py
Now using a splitext call to correctly get the full path of the output file.
Previously, setting the output_file as something in another directory (by using a path like "../other_dir/output.trk") would still output all files in the current directory, with a broken name.
EDIT: I also checked that the other scripts do not have a similar behavior. They don't.
> BF: correct handling of output paths in dipy_quickbundles.

- Changelog
- doc/index.rst
We need to update also the release notes...
Release notes for Dipy version 0.11
GitHub stats for 2015/12/03 - 2016/02/12 (tag: 0.10)
The following 16 authors contributed 230 commits.
> Updating release dates

- doc/conf.py
> DOC: switch to using mathjax for maths

- dipy/fixes/argparse.py
> Fix PEP8 in fixes

- dipy/align/tests/test_imwarp.py
- dipy/align/tests/test_metrics.py
- dipy/align/tests/test_parzenhist.py
- dipy/align/tests/test_transforms.py
- dipy/align/tests/test_vector_fields.py
This PR fixes the files mentioned in Issues #865 #866 #867 #870 and #871.
> FIX: PEP8 for test files

- dipy/align/tests/test_imaffine.py
pep 8 for test_imaffine.py. Issue #864
> FIX: PEP8 in test_imaffine

- dipy/boots/__init__.py
- dipy/boots/resampling.py
> Fix PEP8 in boots

- doc/index.rst
I cherry picked the change from maint/0.11.x and updated the 0.11 website.
> Update index.rst correcting the date of release 0.11

- dipy/utils/_importlib.py
- dipy/utils/optpkg.py
- dipy/utils/six.py
- dipy/utils/tests/test_arrfuncs.py
- dipy/utils/tripwire.py
> FIX: PEP8 in utils

- dipy/denoise/noise_estimate.py
- dipy/denoise/tests/test_denoise.py
- dipy/denoise/tests/test_noise_estimate.py
> FIX: PEP8 in denoise

- dipy/data/fetcher.py
> Add progress bar feature to dipy.data.fetcher

- dipy/reconst/dti.py
> Fixes #901 : Added documentation for "step" in dti

- dipy/segment/mask.py
When using crop tools, I get this warning message. My fix solves it.
```
skimage_deprecation: The `skimage.filter` module has been renamed to `skimage.filters`.  This placeholder module will be removed in v0.13.
warn(skimage_deprecation('The `skimage.filter` module has been renamed '
```
> BW: skimage.filter module name warning

- dipy/data/__init__.py
- dipy/data/fetcher.py
> Fix PEP8 in data

- dipy/utils/optpkg.py
- dipy/utils/tests/test_arrfuncs.py
- dipy/utils/tests/test_tripwire.py
- scratch/learning_old.py
Changed relative imports to absolute imports in utils and scratch.
Fixes a small part of https://github.com/nipy/dipy/issues/1002
> FIX: Use absolute import in utils and scratch

- dipy/pkg_info.py
Changed the import statement to use absolute import
Fixes https://github.com/nipy/dipy/issues/998
> FIX: Use absolute import in pkg_info

- dipy/core/gradients.py
- dipy/core/profile.py
- dipy/core/sphere.py
- dipy/core/subdivide_octahedron.py
- dipy/core/tests/test_sphere.py
The patch fixes the import statement to make use of absolute import in the scripts at core module.
Fixes a small part of https://github.com/nipy/dipy/issues/969
> FIX: Update the import statements to use absolute import in core

- dipy/data/fetcher.py
- dipy/data/tests/test_fetcher.py
- setup.py
Fallback to metadata download size when content-length is not defined in http headers
> Fix progressbar of fetcher

- dipy/denoise/enhancement_kernel.pyx
- dipy/denoise/shift_twist_convolution.pyx
- dipy/denoise/tests/test_kernel.py
- doc/examples/contextual_enhancement.py
This update fixes the SNR issue in the demo which was wrongly calculated. The SNR is now based on the b=0 volume instead of the entire diffusion volume. The SNR after applying noise should now be around 4.5.
One reference at the bottom of the demo has errors in it and was corrected.
> Contextual Enhancement update: fix SNR issue, fix reference

- dipy/io/dpy.py
- dipy/io/gradients.py
- dipy/io/pickles.py
- dipy/io/tests/test_dpy.py
- dipy/io/tests/test_io.py
Changes relative imports to absolute imports.
Fixes https://github.com/nipy/dipy/issues/997
> FIX: Use absolute imports in io

- dipy/testing/__init__.py
- dipy/testing/spherepoints.py
- dipy/testing/tests/test_decorators.py
> FIX: PEP8 in testing

- doc/examples/reconst_dki.py
Commenting out savefig() in the example should render the plots in sphinx.
> Fixes #979 : No figures in DKI example - commented savefig()

- tools/github_stats.py
> Minor change in `tools/github_stats.py`

- dipy/data/tests/test_fetcher.py
Fix for #1030 
'pathname2url' method is not needed in the test_fetcher.py
> Fix for fetcher files in Windows

- dipy/denoise/denspeed.pyx
The bugfix in the implementation of denspeed in reference to #1011 
Now we can use any patch_radius and block_radius for denoising purpose
- The implementation follows the block weighing approach which is then averaged for each voxel.
- Does not exactly follow the [coupe2008](http://www.ncbi.nlm.nih.gov/pubmed/18390341) block      averaging approach
- To follow the [coupe2008] approach, the existing code by @omarocegueda [here](https://github.com/omarocegueda/denoise/blob/master/ornlm/ornlm.pyx) is accurate, but it needs to be optimized (I am working on that currently!)
> Fix: denspeed.pyx to give correct output for nlmeans

- .travis.yml
- MANIFEST.in
- setup.py
- setup_helpers.py
- version_helpers.py
Fix a bug in dependency checking for heavy dependencies.
Make numpy an install dependency using extension builder that pulls in
include directories as late as possible.
> MRG: fix heavy dependency check; no numpy for setup

- dipy/reconst/shm.py
Can someone double check me, but I think this is right now.
> Doc - fix definition of real_sph_harm functions

- dipy/direction/probabilistic_direction_getter.py
- dipy/direction/tests/test_prob_direction_getter.py
- dipy/tracking/local/tests/test_local_tracking.py
- doc/api_changes.rst
This PR adds pmf_threshold parameter to ProbabilisticDirectionGetter, which set to 0 all directions with probability mass function value < pmf_threshold.. It is common to remove low CSD-ODF value (e.g. mrtrix)  from the probability mass function used in probabilistic tractography. Increasing pmf_threshold tends to reduce erroneous streamlines by following 'less noisy' directions of the CSD-ODF.
I set the default to 0.1 as suggested by [Tournier et al. 2012, Girard et al. 2014]. However, this will change probabilistic streamline output of current scripts.
> NF - Add PMF Threshold to Tractography

- dipy/reconst/dki.py
- dipy/reconst/tests/test_dki.py
The first commit introduces a test that demonstrates the bug: if the `S0` input to DKI prediction is provided as a ndarray (which should be possible!), this raises an error. 
The second commit fixes this bug, by separating into two cases: one when `S0` is an ndarray (assumed to have the right shape!), and one when it is a float.
> BF: Predict DKI with a volume of S0

- dipy/reconst/csdeconv.py
- dipy/reconst/tests/test_csdeconv.py
This small change should allow the csd.predict method to accept nd-arrays of coefficients.
> BF - fix CSD.predict to work with nd inputs.

- dipy/denoise/denspeed.pyx
Many jobs deployed by prange finish very quickly when using a mask. Since the default scheduling seems to assign jobs statically to workers by creation some worker run out of jobs quickly. I tested all possible settings with default parameters, num_threads=10 on a virtualized system on an HCP dataset (HCP/994273/T1w/Diffusion). The mask was computed with dipy and covers (=1) ~25% of the dataset.
Single runs, hence high variance, but the trend is pretty clear:
default: 1990s
guided: 1065s
dynamic: 1011s
static: 2077s
> improve OMP parallelization with scheduling

- dipy/core/gradients.py
- dipy/core/tests/test_gradients.py
A function to generate arbitary b vectors using the disperse function
> Generate b vectors using disperse_charges

- dipy/reconst/shm.py
There was one instance of the link to the Fibernavigator code pointing to the old Google Code repo. Updated it.
> DOC: update fibernavigator link

- dipy/segment/benchmarks/bench_quickbundles.py
- dipy/segment/clustering.py
- dipy/segment/mask.py
- dipy/segment/quickbundles.py
- dipy/segment/tests/test_clustering.py
- dipy/segment/tests/test_feature.py
- dipy/segment/tests/test_mask.py
- dipy/segment/tests/test_metric.py
- dipy/segment/tests/test_qb.py
- dipy/segment/tests/test_quickbundles.py
- dipy/segment/threshold.py
> PEP8: Fix pep8 in segment

- .travis.yml
- README.rst
> DOC: Added a coverage badge to README.rst

- dipy/denoise/denspeed.pyx
The changes proposed in #1018 for the nlmeans function are now omitted, after the discussion in #1083. This results in still having the corner case mentioned in #1011 
@Garyfallidis Do have a look.
> Restored the older implementation of nlmeans

- dipy/tracking/streamline.py
- dipy/tracking/tests/test_streamline.py
This is more consistent with other API for handling streamlines, and also makes more sense.
> Return a generator from `orient_by_roi`

- dipy/segment/tests/test_metric.py
Numpy does not implement the `__round__` method, causing the following
error when trying to use builtin `round`:
>>> round(np.array([1]))
File "<stdin>", line 1, in <module>
TypeError: type numpy.ndarray doesn't define __round__ method
For the test error in dipy, see:
https://travis-ci.org/MacPython/dipy-wheels/jobs/140257955#L357
Use numpy's `assert_almost_equal` instead of the version from nose, to
avoid this problem.
> BF: fix test error on Python 3

- dipy/data/__init__.py
- dipy/reconst/csdeconv.py
- dipy/reconst/dki.py
- dipy/reconst/dti.py
- dipy/reconst/mapmri.py
- dipy/reconst/shm.py
- dipy/reconst/shore.py
- dipy/sims/tests/test_voxel.py
- dipy/sims/voxel.py
There were specific places where S0=123. which I changed to 100.
> Fixes #1061 : Changed all S0 to 1.0

- doc/examples/fiber_to_bundle_coherence.py
Removed some import lines that weren't used. Added a fixed seed for reproducibility.
I was asked to fix PEP8 in this line
```mask_lgn[35-rad:35+rad, 42-rad:42+rad, 28-rad:28+rad] = True```
However the PEP8 checker I'm using doesn't complain about this line. Should it be changed to this?
```mask_lgn[35-rad : 35+rad, 42-rad : 42+rad, 28-rad : 28+rad] = True```
> Updates to FBC measures documentation

- .travis.yml
- dipy/reconst/shm.py
Add a Python 3.5 run with full dependendencies.  Add (py)tables to full
dependencies.
Replaces #1101.
> MRG: add pytables to travis-ci, Py35 full test run

- doc/examples/restore_dti.py
> Import reload function from imp module explicitly for python3

- doc/examples/segment_clustering_features.py
- doc/sphinxext/docscrape.py
- doc/sphinxext/github.py
- doc/sphinxext/numpydoc.py
- doc/tools/apigen.py
- doc/tools/build_modref_templates.py
- tools/make_examples.py
Change apigen.py for python3 support
And minor PEP8 changes
fixes #912
> Modifications for building docs with python3

- dipy/data/fetcher.py
In reference to @jchoude comment on #1106, I have changed the default value back to T2
> Changed default value of mni template

- doc/examples/sfm_reconst.py
> DOC: Math rendering issue in SFM gallery example.

- dipy/align/vector_fields.pyx
These are minor changes to remove python interaction from within some of the loops present in `vector_fields.pyx`. 
It is easiest to verify the reduction in Python interaction via observing the reduction in yellow lines in the annotated HTML files generated by ``cython -a vector_fields.pyx`` in this PR vs master.
The following four functions receive approximately 3 orders of magnitude speedup by avoiding calls to np.cos, np.arctan2 and/or np.sqrt:
`create_circle`, `create_sphere`, `create_harmonic_fields_2d`, `create_harmonic_fields_3d`
For the rest, there is negligable difference in performance.  I have also looked at enabling parallel processing via prange in some of these functions and plan to submit that as a separate future PR.  (In the multithreaded case, the change of …
> MAINT: minor cython cleanup in align/vector_fields.pyx

- dipy/direction/peaks.py
- dipy/direction/tests/test_peaks.py
Fixed behavior when nbr_processes parameter of peaks_from_model is less or equal to 0.
- returns peaks_from_model(..., parallel=False) when nbr_processes <= 0
- added tests
> BF - peaks_from_model with nbr_processes <= 0

- dipy/reconst/fwdti.py
- dipy/reconst/tests/test_fwdti.py
- doc/examples/reconst_fwdti.py
In this pull request the free water tensor model will be added to Dipy. The model's fit will be based on the method proposed in [http://www.ncbi.nlm.nih.gov/pubmed/25271843](http://www.ncbi.nlm.nih.gov/pubmed/25271843). 
As @arokem suggested this technique will be implemented in a separate reconst module which I named fwdti.py. Since this technique is an expansion of the simple DTI model, its classes will be defined from inheritance of the classes defined on Dipy's DTI module. 
At the moment, I just add the structures for the fwdti class. My very next step will be editing class FreeWaterTensorModel.
> NF: Free water tensor model

- dipy/reconst/fwdti.py
- dipy/reconst/tests/test_fwdti.py
Procedure was crashing when negative S0 are present. In theory such values are implausible. However, in practice this values can be present in datasets! For example, I found this cases when processing the full CENIR dataset.
When such cases are detected all parameters are directly set to zero.
> Small fix in free water DTI model

- dipy/align/crosscorr.pyx
This PR implements a new algorithm for computing the Cross Correlation metric, which is substantially faster than the original algorithm implemented in ANTS. The computational complexity of the original algorithm for a volume of size N^3 using rectangular windows of size K^3 is Theta(N^3 * K^2). This means that the time increases quadratically with the window radius. 
The computational complexity of this new algorithm is Theta(N^3), it does not depend on the window size, so we observe a substantial speed up, especially for large rectangular windows. After a conversation with @grlee77, the plan would be to add this algorithm instead of #1051, and then after #1050 is in, we can go ahead and use that framework to parallelize this sequential algorithm to obtain even higher speed up.
These are …
> Fast computation of Cross Correlation metric

- dipy/io/vtk.py
- dipy/viz/utils.py
- doc/examples/valid_examples.txt
- doc/examples/viz_surfaces.py
- doc/examples_index.rst
This PR updates what was merged with PR https://github.com/nipy/dipy/pull/1034
I also rendered the tutorial which outputs correctly a simple cube
@MarcCote and @ranveeraggarwal can you look at it and merge it?
> Minor corrections for showing surfaces 

- .travis.yml
- README.rst
This PR: 
- removes coveralls badge from README.md. It is currently displaying unknown and codecov seems better (see https://www.slant.co/versus/7928/7929/~coveralls_vs_codecov).
- makes sure we use COVERAGE=1 only in one Travis build. Having multiple builds with COVERAGE=1 generate several unnecessary coveralls posts in PRs. Also, currently no builds with COVERAGE=1 were running VTK tests, so the code coverage being reported wasn't accurate. 
- removes unnecessary Travis build which was supposedly testing with VTK6. However, Ubuntu 12.04 (the one use by Travis) doesn't offer the package python-vtk6 (see my comments in #759). So, that particular build was equivalent to another one that wasn't testing VTK code at all.
> Update .travis.yml and README.md

- dipy/reconst/dti.py
- dipy/reconst/tests/test_dti.py
- scratch/profile_dti.py
Speeds up DTI odf calculation, by calculating it only over regions of the volume that have non-zero eigen-values.
> Faster dti odf

- dipy/reconst/dki.py
- dipy/reconst/dti.py
- dipy/reconst/tests/test_dti.py
This looks like a bug to me: it shouldn't matter whether you fit the
entire data array or just one.
This happens because min_signal currently depends on the entire data array
that is passed, and that varies here depending on whether only one voxel
or the entire array is passed.
For now, I only have the bug and no fix, hence the WIP. Suggestions most welcome!
> TST: Test for invariance of model_params to splitting of the data.

- doc/examples/affine_registration_3d.py
- doc/examples/brain_extraction_dwi.py
- doc/examples/denoise_nlmeans.py
- doc/examples/deterministic_fiber_tracking.py
- doc/examples/introduction_to_basic_tracking.py
- doc/examples/linear_fascicle_evaluation.py
- doc/examples/piesno.py
- doc/examples/probabilistic_fiber_tracking.py
- doc/examples/quick_start.py
- doc/examples/reconst_dki.py
- doc/examples/reconst_dsi.py
- doc/examples/reconst_dsi_metrics.py
- doc/examples/reconst_dti.py
- doc/examples/reconst_fwdti.py
- doc/examples/reconst_gqi.py
- doc/examples/reconst_shore_metrics.py
- doc/examples/reslice_datasets.py
- doc/examples/sfm_tracking.py
- doc/examples/snr_in_cc.py
- doc/examples/streamline_tools.py
- doc/examples/syn_registration_3d.py
- doc/examples/tracking_eudx_tensor.py
- doc/examples/tracking_quick_start.py
- doc/examples/tracking_tissue_classifier.py
- doc/examples/viz_slice.py
get_header() / get_affine() method is deprecated from nibabel 2.1, we use header / affine property instead
> Update deprecated function.  

- .coveragerc
Right now, benchmarks count towards our coverage but we are not running them on Travis. I suggest we exclude them.
> Do not cover files related to benchmarks.

- dipy/reconst/dti.py
- dipy/reconst/fwdti.py
- dipy/reconst/tests/test_dti.py
Analogous to DTI non-linear code, I added some lines of code to insure that fwDTI does not crash when the non-linear procedure gives NaN.
> Small fix to insure that fwDTI non-linear procedure does not crash

- dipy/sims/tests/test_voxel.py
- dipy/sims/voxel.py
> Change DKI_signal to dki_signal

- dipy/tracking/vox2track.pyx
- src/dpy_math.h
Should fix issue #1138.
As @matthew-brett wrote, `fmin()` is not defined in the "old" versions of Visual Studio.
I defined it in `dpy_math.h`, used it in `vox2track.pyx` and ran `setup.py bdist_wheel` on Windows and Linux Mint to test the broken builds. Seem good.
> Define fmin() for Visual Studio

- tools/make_examples.py
It seems that although I was deleting the namespaces, the matplotlib plots were not deleted. This PR should hopefully fix this problem reported in issue https://github.com/nipy/dipy/issues/1154
> BF: closing matplotlib plots for each file while running the examples

- AUTHOR
- doc/developers.rst
- doc/examples_index.rst
@sahmed95 : could you please check that I have your details right?
> Add Shahnawaz to list of contributors.

- .travis.yml
- dipy/align/imwarp.py
- dipy/align/reslice.py
- dipy/align/tests/test_reslice.py
- dipy/data/fetcher.py
- dipy/external/fsl.py
- dipy/io/image.py
- dipy/io/utils.py
- dipy/tests/test_scripts.py
- dipy/tracking/eudx.py
- dipy/tracking/tests/test_life.py
- dipy/tracking/tests/test_propagation.py
- dipy/workflows/denoise.py
- dipy/workflows/reconst.py
- dipy/workflows/segment.py
- dipy/workflows/tests/test_reconst_dti.py
- doc/api_changes.rst
- doc/dependencies.rst
- doc/examples/denoise_ascm.py
- doc/examples/fiber_to_bundle_coherence.py
- requirements.txt
- scratch/very_scratch/registration_example.py
- scratch/very_scratch/warptalk.py
This (potentially) avoids a lot of annoying deprecation warnings that have started showing up recently.
> Replace `get_affine` with `affine` and `get_header` with `header`.

- dipy/tracking/local/localtracking.py
- dipy/tracking/local/tests/test_local_tracking.py
This PR supercedes PR #1045.
- Allows higher tolerance for affine with a small 'shear' components
- Tests various input affine matrices for local streamline tracking
> TST - add tests for various affine matrices for local tracking

- dipy/reconst/mapmri.py
- dipy/reconst/multi_voxel.py
- dipy/reconst/tests/test_mapmri.py
- dipy/sims/voxel.py
- doc/dependencies.rst
- doc/examples/reconst_mapmri.py
- doc/examples_index.rst
- doc/installation.rst
> Athena mapmri 

- doc/upload_docs.py
upload_docs.py script builds documentation for the current version and uploads it to gh-pages branche of the dipy_web repository
> Add documentation uploading script

- dipy/denoise/denspeed.pyx
- dipy/denoise/tests/test_nlmeans.py
- dipy/utils/omp.pxd
- dipy/utils/omp.pyx
- dipy/utils/tests/test_omp.py
- setup.py
I was recently working on adding OpenMP support to some functions in dipy.align and needed some utilities similar to the ones defined within `denoise/denspeed.pyx`.
I propose moving these to a common location `dipy.utils.omp` where they can be more easily found and reused.
The only change in functionality to `nlmeans` would be the default number of threads set when `num_threads` is not specified,but the user has also defined the `OMP_NUM_THREADS` environement variable.  Previously the default number of threads was always `openmp.omp_get_num_procs()`, but now it will try to default to the `OMP_NUM_THREADS` instead.  At least on my system, `omp_get_num_procs` returns the total number of possible threads including hyperthreading which actually makes things slower than just using the number …
> ENH: expand OpenMP utilities and move from denspeed.pyx to dipy.utils

- dipy/tracking/__init__.py
- dipy/tracking/benchmarks/bench_streamline.py
- dipy/tracking/streamlinespeed.pxd
- dipy/tracking/streamlinespeed.pyx
- dipy/tracking/tests/test_streamline.py
This small PR is the first of a series of PRs aiming to support Nibabel's `ArraySequence` objects.
Specifically, this PR improves `dipy.tracking.streamlinespeed.length` to support `ArraySequence` objects. This gives pretty good speedup even over the current Cython version (all speedups are in respect to the Python implementation):
```
Timing length() with 20,000 streamlines.
Python time: 3.9sec
Cython time: 0.46sec
Speed up of 8.41x
Cython time (ArraySequence): 0.08sec
Speed up of 48.38x
```
Edit: of course this needs the master branch of Nibabel or eventually v2.1.
> ENH: Add support for ArraySequence in `length` function

- dipy/tracking/local/interpolation.pyx
This fixed the issue described in https://github.com/nipy/dipy/issues/1176
Numpy 1.12 now Raises when indexing an with a double instead of an int. We cast to int.
> BF: fix interpolation call with Numpy 1.12

- dipy/data/__init__.py
- dipy/viz/tests/test_fvtk.py
> Deprecate the Accent colormap, in anticipation of changes in MPL 2.0

- dipy/direction/peaks.py
- dipy/direction/tests/test_peaks.py
- dipy/reconst/peak_direction_getter.pyx
Might help with #1190 
See: http://stackoverflow.com/a/2050357/3532933
> Make PeaksAndMetrics pickle-able

- doc/installation.rst
This is now possible, thanks to conda-forge: https://github.com/conda-forge/dipy-feedstock
> Conda install

- doc/examples/quick_start.py
> Use integer division to avoid errors in indexing

- dipy/align/reslice.py
undoes changes introduced in: https://github.com/nipy/dipy/pull/757/commits/b6fc887d4309f7bbd76ff10c20b86953de708bde
Should resolve https://github.com/nipy/dipy/issues/1107
> Suppress warnings regarding one-dimensional arrays changes in scipy 0.18

- dipy/align/reslice.py
> Revert #1204, and add a filter to suppress warnings.

- dipy/reconst/__init__.py
- dipy/reconst/base.py
- dipy/reconst/cache.py
- dipy/reconst/csdeconv.py
- dipy/reconst/dki.py
Using `pycodestyle` fixed every error, except for:
* `csdeconv.py`: The cited lines are docstrings
```
dipy/reconst\csdeconv.py:599:80: E501 line too long (88 > 79 characters)
dipy/reconst\csdeconv.py:601:80: E501 line too long (92 > 79 characters)
```
This is the first PR that replaces #1207
> Follow PEP8 in reconst

- dipy/align/vector_fields.pyx
Adds a clarification note to prevent confusion about the return value of `simplify_warp_funcion_3d` reported in #1213.
> DOC: add a clarification note to simplify_warp_funcion_3d

- dipy/denoise/non_local_means.py
- dipy/denoise/tests/test_ascm.py
- dipy/denoise/tests/test_non_local_means.py
Instead of the value of sigma in the corner of the image.
Addresses #1131
> RF: Use the average sigma in the mask.

- dipy/reconst/dsi.py
- dipy/reconst/dti.py
- dipy/reconst/fwdti.py
- dipy/reconst/gqi.py
- dipy/reconst/interpolate.py
- dipy/reconst/mapmri.py
- dipy/reconst/odf.py
Using `pycodestyle` fixed every error, except for:
* `dsi.py`: The long lines are TeX docstrings. Variable name `I` is not a problem
```
dsi.py:29:80: E501 line too long (116 > 79 characters)
dsi.py:245:80: E501 line too long (167 > 79 characters)
dsi.py:482:9: E741 ambiguous variable name 'I'
dsi.py:508:80: E501 line too long (174 > 79 characters)
dsi.py:509:80: E501 line too long (163 > 79 characters)
dsi.py:510:80: E501 line too long (166 > 79 characters)
```
* `dti.py`: Line contains an FTP url
```
dti.py:1103:80: E501 line too long (94 > 79 characters)
```
* `mapmri.py`: Variable names `I` or `l` are not a problem
```
mapmri.py:502:13: E741 ambiguous variable name 'I'
mapmri.py:504:17: E741 ambiguous variable name 'I'
mapmri.py:533:9: E741 ambiguous variable name 'I' …
```
> Follow PEP8 in reconst (part 2)

- dipy/core/gradients.py
- dipy/core/tests/test_gradients.py
Some models require that you have more than one (non-zero) b-value in your gradient table. 
This new feature implements a simple function that checks a gradient table, to see that it has enough different b-values.
> NF: Check multi b-value

- dipy/data/__init__.py
- dipy/data/fetcher.py
This one is smaller than the CENIR data-set, and is not preprocessed.
> Add one more multi b-value data-set

- dipy/reconst/mapmri.py
factorial, factorial2 should come from scipy.special.
See https://s3.amazonaws.com/archive.travis-ci.org/jobs/223388982/log.txt for
current failure on --pre testing, where warnings overcome the travis-ci log
limit.
> RF: allow for scipy pre-release deprecations

- .travis.yml
- dipy/info.py
- dipy/tracking/streamlinespeed.pyx
- requirements.txt
A small patch addressing the issue @arokem raised in comment https://github.com/nipy/dipy/pull/1076#issuecomment-274866713
> BF: Use np.npy_intp instead of assuming long for ArraySequence attributes

- dipy/segment/clustering_algorithms.pyx
- dipy/segment/clusteringspeed.pyx
- dipy/tracking/distances.pyx
- dipy/tracking/streamlinespeed.pyx
Small refactoring as suggested by @matthew-brett (see comment https://github.com/nipy/dipy/pull/1076#issuecomment-294845381)
> RF: Use cython imports instead of relying on extern

- doc/examples/reconst_dki.py
Non-ASCII characters were introduced in the reconst_dki.py example;
since no encoding was specified in that file, a syntax error was being
reported by Python.
> BUG: Fix non-ASCII characters in reconst_dki.py example.

- dipy/data/fetcher.py
- dipy/data/tests/test_fetcher.py
The fetcher module defines a path based from the users home directory. This can cause a problem when running in a cluster environment where the home directory can be machine specific.
This PR enables an environment variable DIPY_HOME to override the default setting.
> Feature: Added environment override for dipy_home variable

- .travis.yml
- dipy/io/peaks.py
- dipy/io/tests/test_io_peaks.py
- doc/examples/introduction_to_basic_tracking.py
- doc/examples/viz_widgets.py
Hi @matthieudumont and all this PR is resolving the issue with saving the peaks object. Making it an HDF5 file allows to be read by other languages etc.
Mr. Dumont you will need to update your workflow PRs to use this one and then we can move to merging them asap.
Do you agree with the file extension .pam or .pam5 (as in hdf5)?
Also have in mind that the helper peaks_to_niftis is not in this PR so you will have to use it from your other PR. Let me know how it goes.
> New hdf5 file format for saving PeaksAndMetrics objects

- doc/examples/reconst_dki.py
Fix documentation typos in reconst_dki.py DKI reconstruction example.
> DOC: Fix reconst_dki.py DKI example documentation typos.

- bin/dipy_reconst_csa
- bin/dipy_reconst_csd
- dipy/io/peaks.py
- dipy/io/tests/test_io_peaks.py
- dipy/workflows/reconst.py
- dipy/workflows/tests/test_reconst_csa_csd.py
- setup.py
This is a rebase of https://github.com/nipy/dipy/pull/1155
with some additional testing and using the new hdf5 format (.pam5) for saving PeaksAndMetrics.
@matthieudumont, @arokem and all give it a try.
> Csa and csd reconstruction workflow rebased

- dipy/tracking/utils.py
- dipy/viz/actor.py
- doc/examples/valid_examples.txt
- doc/examples/viz_ui.py
- doc/tools/build_modref_templates.py
All dipy.*.utils (ex: dipy.tracking.utils) are missing on the documentation so this PR change the regular expression to make this files available on api reference. (see #322)
> Fix missing documentation content

- setup.py
resolving #1253 : find files recursively instead of static files list for automating script installation
> Automate script installation

- dipy/tracking/streamlinespeed.pyx
See: https://nipy.bic.berkeley.edu/builders/dipy-bdist64-27/builds/122/steps/shell_12/logs/stdio
> Cast Streamline attrs to numpy ints, to avoid buffer mismatch.

- dipy/utils/tests/test_tripwire.py
- dipy/utils/tripwire.py
- dipy/viz/fvtk.py
> Better fvtk.viz error when no VTK installed

- dipy/denoise/tests/test_nlmeans.py
The goal of this PR is to avoid test failure on mac when openmp is not avalaible. is it ok for you @matthew-brett @Garyfallidis  ?
> Adding a decorator for skipping test if openmp is not available

- dipy/viz/fvtk.py
If an error is raised, we don't need that warning
> Following up on #1243.

- dipy/denoise/tests/test_nlmeans.py
This small PR will help for understanding builder error
> small correction for debugging purpose on nlmeans

- dipy/core/gradients.py
Separated two different error conditions for clarity.
> Corrected a small error condition

- dipy/reconst/csdeconv.py
- dipy/reconst/tests/test_csdeconv.py
Add a new parameter (fa_operator) in auto_response to give an operator for the comparison with the FA threshold.
@jchoude, @arokem, @MrBago Can you review ? This PR will be useful when the MSMT PR will be merged.
> NF Add the parameter fa_operator in auto_response function

- dipy/direction/peaks.py
- dipy/direction/tests/test_peaks.py
- dipy/reconst/csdeconv.py
- dipy/reconst/odf.py
- dipy/reconst/tests/test_mapmri.py
- dipy/reconst/tests/test_odf.py
- dipy/reconst/tests/test_shore_odf.py
Suppress the warning described in #1181? Still needs testing.
> MRG: Suppress a divide-by-zero warning.

- doc/theory/b_and_q.rst
Add missing label to reciprocal space equation in b_and_q.rst file in
the doc/theory folder.
Although according to
http://www.sphinx-doc.org/en/stable/ext/math.html
cross-referencing equations via their label will not work across
different documents.
The equation at issue is referenced from doc/faq.rst.
> DOC: Add missing label to reciprocal space eq.

- dipy/reconst/dti.py
Fix typos in method documentation for the dti.py reconstruction file.
> DOC: Fix typos in dti.py reconstruction file doc.

- dipy/reconst/dti.py
According to the article referenced in the docstring and some quick tests **-1=planar anisotropy** and **1=linear anisotropy**
> Fix inversion in the dti mode doc

- dipy/io/dpy.py
- dipy/io/peaks.py
- dipy/io/tests/test_io_peaks.py
The goal of this PR is to resolve #1306.
@arokem @aarya22, can you have a look ?
Thanks !
> PyTables Error-handling

- cythexts.py
- setup.py
- setup_helpers.py
The goal is this PR is to setup correctly flags following the operating system. Moreover This should resolve #804.
> Flags correction for windows

- dipy/viz/tests/test_ui.py
- dipy/viz/ui.py
- doc/examples/viz_advanced.py
Previously, `TextActor2D` was used by other classes like `TextBox2D` and `LineSlider2D`, but could not be added to the `ShowManager` nor to a `Panel2D` as a standalone UI element. However, `TextActor2D` can be useful as a text label which is not editable by users, so this PR promotes it to a full member of `viz.ui`.
> Make TextActor2D extend UI instead of object

- dipy/denoise/localpca.py
- dipy/denoise/tests/test_lpca.py
- dipy/reconst/dti.py
- doc/theory/b_and_q.rst
Denoising with LocalPCA:
The bottleneck of LocalPCA is decomposition of the data into the eigenvalues/singular values and the corresponding vectors (basis). For this purpose, Eigenvalue decomposition was used but was previously replaced with Singular Values Decomposition, for more accuracy. However, SVD is many times slower than EVD. In this pull request, the code is changed to include both of them, as an optional parameter, "pca_method".
Also for more speed up, the function accepts the brain mask as an optional parameter and the denoising will be only applied to the voxels inside the mask.
> Added eigh version of localpca to svd version

- doc/examples/reconst_fwdti.py
Otherwise, figures don't render.
I believe this closes #1317
> Correct white-space for fwdti example.

- dipy/reconst/tests/test_csdeconv.py
The goal of this PR is to fix #1323.
Like @arokem said, the test was catching too many warnings. In this case, the test was catching this : 
`FutureWarning: 'rcond' parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass 'rcond=None', to keep using the old, explicitly pass 'rcond=-1'. `
> Catch a more specific warning in test_csdeconv

- dipy/reconst/tests/test_dti.py
This PR is a correction for test_dti.py which is failing on windows 10 / numpy 1.14
The arrays seems to be different on the 14nth decimal place. This is really strange. 
This problem does not appear on linux.
> Test modification for windows 10 / numpy 1.14

- dipy/workflows/multi_io.py
Fix typos in the docstring of `ìo_iterator` and `ìo_iterator_` methods.
> DOC: Fix typos in multi_io.py workflow file docstring.

- doc/examples/reconst_mapmri.py
Fix the `small_delta` and `big_delta` parameters of the `reconst_mapmri`
example being flipped.
> BUG: Address small_delta vs. big_delta flipped parameters.

- README.rst
Also, added a few more small things + links.
Follow up to #1285
> Remove GPL from our README.

- README.rst
Add the Travis CI badge to the `README.rst` file so that we can visualize
the health of the master branch of DIPY.
> ENH: Add Travis badge to README.rst.

- README.rst
Use the reST syntax to highlight code blocks in `README.rst` when describing
the DIPY installation commands.
> DOC: Format README.rst file code blocks.

- dipy/__init__.py
- dipy/core/geometry.py
- dipy/testing/__init__.py
- dipy/tracking/life.py
- dipy/tracking/metrics.py
- dipy/tracking/streamline.py
- dipy/tracking/utils.py
This PR is inspired by @effigies to resolve printing problem. Indeed, Numpy change printing strategies so we revert printing behavior to keep Doctests from breaking.
Thanks to @matthew-brett for his advise.
this should resolve #1346
> use legacy float array for printing numpy array

- dipy/__init__.py
- dipy/core/geometry.py
- dipy/testing/__init__.py
- dipy/tracking/life.py
- dipy/tracking/metrics.py
- dipy/tracking/streamline.py
- dipy/tracking/utils.py
- dipy/workflows/base.py
- dipy/workflows/tests/test_iap.py
- dipy/workflows/tests/workflow_tests_utils.py
The goal of this PR is to resolve #1344. 
Now, epilog is setting up via the keyword `References` in workflow docstring.
> FIX : improve epilogue accessibility for workflow

- .travis.yml
- dipy/info.py
- dipy/io/dpy.py
- dipy/io/peaks.py
- dipy/io/tests/test_dpy.py
- dipy/io/tests/test_io_peaks.py
- dipy/workflows/tests/test_reconst_csa_csd.py
- doc/dependencies.rst
- doc/installation.rst
- requirements.txt
- setup.py
Switching from pytables to h5py. H5py still works with older numpy versions. pytables needs newer versions. Therefore h5py is easier to depend on. Also it seems that h5py gives better access to low level functions. Finally, testing in travis should be much simpler without the pytables dependency as that api has been changing quite a bit.
> From tables to h5py

- dipy/direction/peaks.py
- dipy/direction/tests/test_peaks.py
- dipy/reconst/sfm.py
- doc/Makefile
- doc/examples/viz_ui.py
- tools/make_examples.py
This seems to work when running this directly in IPython, but I am still not sure if this works generally, so needs to be switched on with some care. Shouldn't affect normal doc building, though.
> Enable memory profiling of the examples.

- dipy/tracking/benchmarks/bench_streamline.py
- dipy/tracking/streamlinespeed.pyx
- dipy/tracking/tests/test_streamline.py
Second small PR that aims to support Nibabel's `ArraySequence`objects (the first one was #1076).
Specifically, this PR improves `dipy.tracking.streamlinespeed.set_number_of_points` to support `ArraySequence` objects. This gives pretty good speedup even over the current Cython version (all speedups are with respect to the Python implementation):
```bash
Timing set_number_of_points() in 100,000 streamlines.
Cython time: 0.590 sec
Python time: 61.76 sec
Speed up of 104.68x
Cython time (ArrSeq): 0.13 sec
Speed up of 475.08x
```
> ENH: Add support for ArraySequence in`set_number_of_points` function

- CONTRIBUTING.md
- doc/devel/coding_style_guideline.rst
- doc/devel/index.rst
Add a coding style guideline mainly aimed at establishing some criteria
for the example and rst documentation files.
> DOC: Add a coding style guideline.

- dipy/io/dpy.py
> BF: Import Streamlines object directly from nibabel.

- dipy/tracking/local/tests/test_local_tracking.py
- Added a new test for eudx direction getter (PeaksAndMetricsDirectionGetter) following the discussion in PR #1342
- this PR should be merged before PR #1342
> TST - add tracking tests for PeaksAndMetricsDirectionGetter

- doc/developers.rst
Update the DIPY developers' affilitations to reflect their current
institution.
Take advantage of the topic to fix accents for MA-Côté.
> DOC: Update developers' affiliations.

- dipy/testing/__init__.py
This PR is for resolving #1376  due to the change [here](https://github.com/numpy/numpy/commit/734b907fc2f7af6e40ec989ca49ee6d87e21c495#diff-6c34f1538350ce17eb53b35d2f0282a1R512) on Numpy
> FIX: update printing format for numpy 1.14

- dipy/denoise/nlmeans.py
- dipy/denoise/noise_estimate.py
- dipy/denoise/tests/test_noise_estimate.py
I found a problem with piesno. The line 
np.sum(data**2, axis=-1, dtype=np.float32)
doesn't do what you think it does. For a dwi for example, the `dtype` is `int16` and some values^2 are greater then 2^15.
The problem is that `data**2` is still in `int16`, then it's converted to a `float32` so this image is curiously bounded with the `int16` bounds :)
Moreover, I changed `axis=-1` to `axis=2` because we always know the right axis... it's 2.
> Fix piesno type

- dipy/tracking/tests/test_utils.py
- dipy/tracking/utils.py
Attempting to address #1299. 
It looks like the test that is failing there is related to a patch of numpy's ravel_multi_index for older versions of numpy. I am putting in this PR to see whether we can do without that patch altogether at this point.
> RF: Remove patch for older numpy ravel_multi_index.

- dipy/utils/fast_numpy.pxd
- dipy/utils/fast_numpy.pyx
I'm not sure this will actually fix the problem because I have several others problems on Windows here. This PR is more of a way to test on your server.
> Possible fix for the inline compilation problem

- doc/examples/combined_workflow_creation.py
- doc/examples/gradients_spheres.py
- doc/examples/reconst_csa.py
- doc/examples/workflow_creation.py
I believe these are all the corrections that are left that were not addressed by the documentation in the current master branch.  I am not able to run `make` on this, as that seems to want to download data and run dypy.  If there is a way to make _just_ the documentation and you can send me instructions and/or a link to the instructions for making just the docs, then I will be happy to give it a try.
Sorry for all the hassle this has caused.
> Re-entering conflict-free typos from deleted PR 1331

- dipy/reconst/mapmri.py
- dipy/reconst/tests/test_mapmri.py
Fix the factorial function import module in test_mapmri.py. The function
was duplicated from the scipy.misc module to scipy.special in SciPy
release 0.14.0:
https://docs.scipy.org/doc/scipy-0.14.0/reference/special.html
vs.
https://docs.scipy.org/doc/scipy-0.13.0/reference/special.html
and
https://docs.scipy.org/doc/scipy-0.13.0/reference/misc.html
> BUG: Fix factorial import module in test_mapmri.py.

- dipy/reconst/tests/test_shm.py
- dipy/segment/tests/test_clustering.py
- dipy/segment/tests/test_metric.py
- dipy/tracking/tests/test_streamline.py
- dipy/workflows/tests/test_masking.py
- dipy/workflows/tests/test_reconst_csa_csd.py
- dipy/workflows/tests/test_reconst_dti.py
> [MRG] assert_true which checks for equality replaced with assert_equal

- doc/examples/reconst_csd.py
- doc/examples/reconst_dsid.py
- doc/examples/reconst_mapmri.py
- doc/examples/reconst_shore.py
- doc/examples/sfm_reconst.py
- doc/examples/simulate_multi_tensor.py
Fixes #1403 
An even better thing to do will be to not replace `jet` with `plasma` but to remove it altogether. This will ensure the example always loads the default colormap.
Suggestions and review please.
> [MRG] Default colormap changed in examples

- dipy/direction/pmf.pyx
- dipy/direction/tests/test_pmf.py
- dipy/segment/tests/test_mrf.py
- dipy/tracking/local/__init__.py
- dipy/tracking/local/localtrack.pyx
- dipy/tracking/local/localtracking.py
- dipy/tracking/local/tests/test_tissue_classifier.py
- dipy/tracking/local/tests/test_tracking.py
- dipy/tracking/local/tissue_classifier.pxd
- dipy/tracking/local/tissue_classifier.pyx
- doc/examples/particle_filtering_fiber_tracking.py
- doc/examples/valid_examples.txt
- doc/examples_index.rst
This PR replaces #1340, and follows the changes of PR #1342.
This PR add a new tissue classifier (CMC) and a new tractography algorithm (PFT). Both methods are described in [Girard et al., NImg, 2014].
CMC - new tissue Classifier. CmcTissueClassifier used probabilities and the tissue partial volume fraction maps to determine when the tracking stops. As it is very similar to ActTissueClassifier, both classes now extend an a new abstract class ConstrainedTissueClassifier.
PFT - new tractography method. ParticleFilteringTracking is inherited from the LocalTracking class. The particle filter is used to find a valid streamline path when the streamline being traced reach the state INVALIDPOINT.
An example is giving in doc/examples/particle_filtering_fiber_tracking.py
References
---------- …
> NF - Particle Filtering Tractography (merge)

- dipy/reconst/csdeconv.py
> Suppress rcond warning

- dipy/core/geometry.py
Another one of these annoying ones.
> Suppress a warning in geometry.

- dipy/workflows/multi_io.py
> BF::Fix inspect.getargspec deprecation warning in Python 3

- doc/faq.rst
- doc/links_names.inc
The goal of this PR is to fix #987
> Updated links

- doc/devel/coding_style_guideline.rst
- doc/index.rst
- doc/stateoftheart.rst
Fix RST markup issues in the `coding_style_guideline.rst` file.
Fixes #1390.
> DOC: Fix reStructuredText formatting issues in coding style guideline.

- dipy/segment/clustering.py
- dipy/segment/tests/test_qbx.py
- doc/examples/segment_clustering_metrics.py
…Actually the AveragePointwiseEuclideanMetric has the correct behavior of the MDF metric as explained in the QuickBundles paper.  @MarcCote this one is for you to check.
> Raise Error when MDFmetric is used in QB or QBX

- doc/examples/segment_extending_clustering_framework.py
Fix missing reference to QuickBbundles paper in the "Enhancing
QuickBundles with different metrics and features" example:
http://nipy.org/dipy/examples_built/segment_extending_clustering_framework.html#example-segment-extending-clustering-framework
Fixes #1371.
> DOC: Fix missing reference to QuickBundles paper.

- README.rst
Fix the format of the link to the `CONTRIBUTING.md` document from the
`README.rst` file.
Take advantage to change `contributor guidelines` for the common form
`Contributing guidelines`.
> DOC: Fix bad hyperlink format to CONTRIBUTING.md from README.rst.

- README.rst
Add GitHub badges to make DIPY's GitHub home page more informative.
Specificically, add the
- Release badge
- Python (PyPI) badge
- License badge
> DOC: Add different GitHub badges to the `README.rst` file.

- dipy/align/imaffine.py
- dipy/align/tests/test_imaffine.py
PR from discussion in #1442 
Changes pass the tests in dipy.align/tests/test_imaffine.py
Still need to discuss
1. whether we should remove affine.affine, and make it private
2. the alternative: @property and @property.setter etc
> repr and get methods for AffineMap, w/ precise exceptions

- README.rst
Add the **DIPY** banner to the `README.rst` file to strenghten the
visual appeal of the repository and help the community better identify
the toolkit.
> DOC: Add the DIPY banner to the README file.

- README.rst
Limit the DIPY logo height in `README.rst` for a better rendering.
> DOC: Limit the DIPY logo height in README for better rendering.

- dipy/viz/ui.py
- doc/examples/viz_ui.py
This PR fixes issue #1458 
- The problem was that the actor was being rotated every-time by the angle between the line joining center of `base_disk` and `handle` and the horizontal axis. It should have been rotated by angle equal to the change in angle between the line and horizontal axis.
- To implement this, an attribute - `pvalue` was added to the `DiskSlider2D` class to store the previous value of rotation. This is used to calculate the angle by which the actor must be rotated.
> Fix for "DiskSlider does not rotate actor in opposite direction"

- dipy/reconst/tests/test_mapmri.py
Fix typo: posivitivity -> positivity.
Also, use capitals to start a sentence.
> DOC: Fix typo in `test_mapmri.py` file.

- dipy/reconst/dsi.py
- dipy/reconst/forecast.py
- dipy/reconst/gqi.py
- dipy/reconst/mapmri.py
- dipy/reconst/shm.py
- dipy/reconst/shore.py
- dipy/workflows/reconst.py
- doc/examples/bundle_registration.py
- doc/examples/reconst_csa_parallel.py
- doc/examples/reconst_dsi_metrics.py
- doc/examples/reconst_forecast.py
- doc/examples/reconst_mapmri.py
- doc/examples/reconst_shore.py
- doc/examples/reconst_shore_metrics.py
> DOC: Use the correct punctuation marks for `et al.`.

- dipy/viz/ui.py
- doc/examples/viz_advanced.py
- doc/examples/viz_ui.py
- test.py
This PR fixes issue #1454 
- A callback was added to call `translate_green_cube` on `"LeftButtonPressEvent"`. 
- Priority given to ` self.line_click_callback` in `ui.py` to ensure that the position of disk gets updated before moving the cube.
> Fix for "Sliders in examples don't react properly to clicks"

- doc/examples/reconst_csd.py
This is to fix the bugs in example of reconst_csd.py:
File “~/dipy/dipy/viz/actor.py", line 717, in odf_slicer
(szx, szy, szz) = odfs.shape[:3]
ValueError: not enough values to unpack (expected 3, got 1)
and
TypeError: peak_slicer() got an unexpected keyword argument ‘scale’
The modifications are:
1. change image data 'response_signal' from 1D to 4D before calling to 'actor.odf_slicer()';
2. reduce the parameter 'scale' to 'actor.odf_slicer()' because it's too large in 'csd_odfs.png';
3. remove unexpected argument ‘scale' when calling 'actor.peak_slicer()'.
> BF: fix bug in example of reconst_csd.py

- doc/examples/sfm_reconst.py
This is to fix the bug in example of sfm_reconst.py:
TypeError: peak_slicer() got an unexpected keyword argument ‘scale’
The modifications are:
1. reduce the parameter 'scale' to 'actor.odf_slicer()' because it's too large in 'sf_both.png';
2. remove unexpected argument ‘scale' when calling 'actor.peak_slicer()'.
> BF: fix bug in example of sfm_reconst.py

- doc/examples/streamline_tools.py
This is to fix the bug in example of streamline_tools.py:
>  TypeError: save_trk() missing 1 required positional argument: 'affine'
The modification is just adding the argument 'affine=affine' to 'save_trk()'.
> BF: fix bug in example of streamline_tools.py

- doc/examples/fiber_to_bundle_coherence.py
The last modification of fiber_to_bundle_coherence.py make this error:
File "~/dipy/dipy/tracking/streamline.py", line 150, in <listcomp>
n_elements = np.sum([len(e) for e in elements])
TypeError: object of type 'numpy.bool_' has no len()
So to fix the bug, I just changed back to where it was.
> BF: fix bug in example of fiber_to_bundle_coherence.py

- dipy/viz/actor.py
- dipy/viz/utils.py
Update some defaults and remove a deprecated feature for the new OpenGL2 rendering backend in VTK7+. 
Also removed an unused `light` parameter that is missing from the doc string.
This PR fixes #1490 and replaces #1481.
> Fix surface rendering bugs in VTK8

- doc/examples/reconst_mapmri.py
Fix formatting issues in the `reconst_mapmri` file to get the
documentation correctly rendered in:
http://nipy.org/dipy/examples_built/reconst_mapmri.html#example-reconst-mapmri
Changes:
- Indent lists properly.
- Indent literal blocks properly.
- Remove unnecessary double quotes for indented code/literal blocks.
- Use double backquotes for inline code samples.
> DOC: Fix `reconst_mapmri` example markup.

- CONTRIBUTING.md
Link the Coding Style Guideline reference in `CONTRIBUTING.md` to the
website docs once it got merged, as suggested by @arokem in PR #1316.
> DOC: Link Coding Style Guide ref in CONTRIBUTING to the website.

- dipy/direction/__init__.py
- dipy/direction/bootstrap_direction_getter.pyx
- dipy/direction/closest_peak_direction_getter.pxd
- dipy/direction/closest_peak_direction_getter.pyx
- dipy/direction/pmf.pxd
- dipy/direction/pmf.pyx
- dipy/direction/probabilistic_direction_getter.pyx
- dipy/direction/tests/test_bootstrap_direction_getter.py
- dipy/direction/tests/test_pmf.py
- dipy/tracking/local/localtrack.pyx
- dipy/tracking/local/tests/test_interpolation.py
- dipy/tracking/local/tests/test_tracking.py
- dipy/utils/fast_numpy.pxd
- dipy/utils/fast_numpy.pyx
- doc/examples/tracking_bootstrap_peaks.py
- doc/examples/valid_examples.txt
- doc/examples_index.rst
- setup.py
This follows PR #1184.
- Cythonized the Boot direction getter of @kesshijordan
> NF - Bootstrap Direction Getter (cythonized)

- doc/examples/segment_quickbundles.py
The last modification of segment_quickbundles.py makes this error:
File "dipy/segment/clustering_algorithms.pyx", line 108, in 
dipy.segment.clustering_algorithms.quickbundles
ValueError: setting an array element with a sequence.
So to fix the bug, I just changed back to where it was. 
Then it turns to the attribute error of VTK 8.1:
"~/dipy/dipy/viz/actor.py", line 448, in streamtube
poly_mapper.GlobalImmediateModeRenderingOn()
AttributeError: 'vtkRenderingOpenGL2Python.vtkOpenGLPolyDataMapper' object 
has no attribute 'GlobalImmediateModeRenderingOn'
And I checked that the PR #1493 solves this problem. The resulting pictures look good.
> BF: fix bug in example of segment_quickbundles.py

- doc/examples/reconst_mapmri.py
Following the discussion in #1291, use the ``CFIN`` dataset instead of
the ``CENIR`` dataset.
Also, make an explicit mention to the `MAPL` acronym so that the use of
the Laplacian-regularized MAP-MRI method seems no longer to be hidden.
> ENH: Use the CFIN dataset rather than the CENIR dataset.

- doc/examples/quick_start.py
fix typo in example of quick_start
> fix typo in example of quick_start

- .pep8speaks.yml
For checking pep8 issues automatically, I think we should try to use pep8speaks bots.
To get more information about this service, [Here the link](https://github.com/OrkoHunter/pep8speaks#private-repos).
I would like your opinion @arokem, @Garyfallidis.
> Adding pep8speak config file

- doc/installation.rst
Just a small installation instruction update.
> [DOC] Installation instruction update

- doc/developers.rst
Didn't see PR #1517 before it got in. Just updating a few developers' affiliations that I know of.
I also added @nilgoyette since I didn't see him mentionned. He has a few merged PRs (#1342 for example, see the [list](https://github.com/nipy/dipy/pulls?q=is%3Apr+is%3Aclosed+author%3Anilgoyette), and has provided a few reviews recently.
> DOC: updated some developers affiliations.

- dipy/tracking/streamline.py
- dipy/tracking/tests/test_streamline.py
Small bug fix, that accommodates use of the new nibabel Streamlines API with this function.
The first commit demonstrates the bug with a test.
The second commit is a one-line change that fixes it.
> Values from streamlines object

- doc/examples/workflow_creation.py
1) This change will be reflected on the page http://nipy.org/dipy/examples_built/workflow_creation.html#example-workflow-creation
2) Added one more import statement to import the AppendTextFlow method from the workflow class.
3) Added few lines to explain why we need to import the methods.
Added the desired import statement into the workflow_creation.py file.
The original tutorial mentions that the lines need to be added in a separate file in the "bin" directory but did not mention that this will also require importing the AppendTextFlow method from the newly created class.
Tested the file in ```bin``` directory after adding the import statement and the script executes perfectly.
> Updating the documentation for the workflow creation tutorial.

- dipy/tracking/utils.py
Hi,
There were a small mistake in documentation of connectivity_matrix function parameter symmetric. Its default value is True but it was given as False. This PR fix it.
> Wrong default value for parameter 'symmetric' connectivity_matrix function

- dipy/viz/test.py
- dipy/viz/tests/test_ui.py
- dipy/viz/ui.py
This PR adds two elements to the viz.ui module.
LineDoubleSlider2D
-----------------
This element allows the user to have two handles on the same slider. These handles can slide on the track, while not crossing each other at any point.
This element is useful for setting a range for a parameter.
For example, in CT images, this can be used to select a mapping for some window of pixel values to values between 0-255.
RangeSlider
---------------
This element uses a `LineDoubleSlider2D` to select a range which restricts a `LineSlider2D` to move within that range. This can be useful when a user wants to fine tune the value of a parameter by narrowing the permissible range for that parameter.
Shape of Handles
-----------------
This PR also gives the user an option to choose the shape of the …
> Range slider element for viz.ui

- dipy/viz/ui.py
This PR changes the variable `major_version` used to check the user's version of the vtk library.
When it need to be used to provide the input to the texture mapper, the `set_input` function from `viz.utils` has been used.
At other places, `major_version` has been replaced with `VTK_MAJOR_VERSION`.
> Replacing major_version in viz.ui

- dipy/direction/probabilistic_direction_getter.pyx
- dipy/direction/tests/test_prob_direction_getter.py
this fix #1566.
Thanks @nilgoyette @jchoude
> BF - bad condition in maximum dg

- doc/examples/register_binary_fuzzy.py
- doc/examples/valid_examples.txt
- doc/examples_index.rst
Writing a simple example of registering binary and fuzzy images together with addressing tuning some particular parameters. see #1541
> add example SDR for binary and fuzzy images

- bin/dipy_info
- bin/dipy_nlmeans
- bin/dipy_reslice
- dipy/fixes/argparse.py
- dipy/workflows/base.py
- dipy/workflows/flow_runner.py
This change is made in the base.py file to check if the user has provided any arguments or not.
Currently, if the workflows are run without any parameters then there is no help message to prompt the user of what went wrong.
Added the check and put an appropriate error message.
> Showing help when no input parameters are given and suppress warnings for cmds

- dipy/workflows/base.py
A simple check is implemented in the base.py script to display a message if the number of arguments in the doc string and the run method mismatches.
> Show message if number of arguments mismatch between the doc string and the run method.

- .travis.yml
- doc/devel/make_release.rst
To follow the suggestion on #1579,  This PR allow `PRE=1` to fail.
> Allow PRE=1 job to fail  

- dipy/reconst/shm.py
- dipy/reconst/tests/test_shm.py
Starting to think about addressing gh-1588.
> Fix calculation of highest order for a sh basis set

- dipy/reconst/dsi.py
- dipy/reconst/tests/test_dsi.py
- dipy/reconst/tests/test_dsi_deconv.py
- dipy/reconst/tests/test_dsi_metrics.py
- dipy/testing/__init__.py
- dipy/tracking/life.py
The goal of this PR is to reduce the number of warnings and avoid what you can see [here](https://travis-ci.org/nipy/dipy/jobs/408195332#L2879).
This should make Travis happy.
more information on #1565
> Fix: Decrease Nosetest warning

- dipy/viz/ui.py
This PR fixes #1586 .
The problem is solved by allowing the mouse release events to propagate by removing `i_ren.event.abort()`
> Removed event.abort for release events

- doc/examples/introduction_to_basic_tracking.py
Because Trackvis uses LPS but DIPY uses RAS, using affine with both tracking and saving as .trk file causes incorrect display in Trackvis. So, affine matrices removed from tracking functions to perform tracking in voxel coordinates.
> Removed affine matrices from tracking. 

- dipy/direction/closest_peak_direction_getter.pyx
- dipy/tracking/local/localtracking.py
- dipy/tracking/local/tests/test_tracking.py
Following the 4D interpolation and the fit, the amplitude of the values on the sphere are not always between 0 and 1, they can be very large or very small. Right after, a condition using a threshold (between 0 and 1) is performed.
The values on the sphere need to be scaled between 0 and 1 before applying the threshold.
As mentionned in #1582 , without this a simple linear scaling of the same FODf affect the tracking (ranging from a complete absence of streamlines to a broad tracking where most direction are acceptable)
> Fix the relative SF threshold Issue

- doc/installation.rst
Documentation update to show proper warnings for python versions to be used with VTK 7 and VTK < 7 .
> [DOC] update VTK version

- dipy/io/tests/test_utils.py
- dipy/io/utils.py
> NF: Convert between 4D DEC FA and 3D 24 bit representation.

- dipy/viz/actor.py
- dipy/viz/tests/test_actors.py
If eigenvalues and aigenvector array shapes are not compatible, tensor_slicer actor does not give clear error message. In this PR, compatibility cheking of eigenvalue and eigenvector shapes is added.  It gives more clear error when shapes are not compatible.
> Eigenvalue - eigenvector array compatibility check 

- dipy/workflows/multi_io.py
- dipy/workflows/tests/test_workflow.py
1) Added a utility function 'file_existence_check' to
check if the input file or directory exists or not.
2) The workflows now report a friendly message to the user
if the input file or directory does not exist.
3) The error stack is still reported in addition to the message.
> Checking if the input file or directory exists when running a workflow

- README.rst
- Fix duplicate link to documentation and installation documentation.
- Fix AppVeyor CI badge.
> DOC: Fix duplicate link and AppVeyor badge.

- doc/examples/workflow_creation.py
The build of this tutorial was failing because of this error:
`ModuleNotFoundError: No module named 'dipy.workflows.my_workflow'`
This PR is a just quick fix.
> Fix worflows creation tutorial error

- .codecov.yml
- .travis.yml
Drops on the order 0.01% are typical even when no change occurs. So, Having this threshold set a little higher (0.1%) than that makes it a little more tolerant to fluctuations.
> Increase codecov tolerance

- dipy/direction/peaks.py
- dipy/reconst/csdeconv.py
- dipy/reconst/shm.py
- dipy/reconst/tests/test_shm.py
Honor the authors in the naming for SH basis choice: replace and deprecate
`fibernav` and `mrtrix` and use `descoteaux07` and `tournier07` instead.
The change includes:
- Using the author's name rather than the software/implementation's.
- Testing that the deprecation warning is effectively exercised.
- Adding the necesary references.
> STYLE: Honor 'descoteaux'and 'tournier' SH basis naming.

- dipy/segment/tissue.py
I moved the conditional which assigned "tolerance" if it was None outside of the for-loop, as that check  only needs to be done once.
> OPT - moved the tolerance check outside of the for loop

- doc/theory/index.rst
- doc/theory/sh_basis.rst
Add spherical harmonics function basis documentation.
> DOC: Add spherical harmonics basis documentation.

- dipy/workflows/reconst.py
- dipy/workflows/tests/test_reconst_csa_csd.py
- dipy/workflows/tests/test_reconst_dki.py
- dipy/workflows/tests/test_reconst_mapmri.py
I just added a warning when b0 threshold is smaller than all b-values.
I had to duplicate the code many times. It is not the first time. This means a new PR is needed to create a parent class (ReconstWorkflow) and avoid the redundancy.
> workflows : warn user for strange b0 threshold 

- dipy/workflows/reconst.py
- dipy/workflows/tests/test_reconst_csa_csd.py
In using the CSD workflow, I discovered that changing the `sh_order` input parameter doesn't seem to do anything. Tracking this down [in the code](https://github.com/nipy/dipy/blob/master/dipy/workflows/reconst.py#L523), I see that it was hard-coded as `sh_order = 8`. This PR changes that and also adds some testing around that. It also more flexibly checks the inputs, so that we are not making assumptions about the input data.
> Flow csd sh order

- dipy/align/streamlinear.py
- dipy/data/fetcher.py
- dipy/workflows/align.py
- dipy/workflows/segment.py
- doc/examples/bundle_extraction.py
> fixed RecoBundle workflow, SLR reference, and updated fetcher.py

- dipy/reconst/mapmri.py
- dipy/tracking/life.py
This should take care of a lot of the PendingDeprecation warnings we are seeing in our CI.
> Numpy matrix deprecation

- dipy/workflows/base.py
- dipy/workflows/io.py
- dipy/workflows/multi_io.py
- dipy/workflows/tests/test_iap.py
- dipy/workflows/tests/workflow_tests_utils.py
- doc/examples/gradients_spheres.py
The aim of this PR is to fix #1338.
This allows `variable string` type for `self.get_io_iterator()` function
> [Fix] workflow variable string

- bin/dipy_snr_in_cc
- dipy/workflows/stats.py
- dipy/workflows/tests/test_stats.py
Given DWI data (mask, bounding box thresholds optional), computes the signal/noise ratio in the corpus callosum
> Stats, SNR_in_CC workflow

- dipy/io/image.py
- dipy/workflows/denoise.py
- dipy/workflows/mask.py
- dipy/workflows/reconst.py
- dipy/workflows/stats.py
- dipy/workflows/tests/test_io.py
- dipy/workflows/tests/test_reconst_mapmri.py
- dipy/workflows/tests/test_stats.py
A quick PR to clean a little bit all workflows
- Standardize some positional arguments: It helps with parsing.
- Docstring correction, it was missing some `optional` keywords
- fix some pep8 issues
> Standardize workflow

- dipy/tracking/tests/test_utils.py
The aim of this PR is to fix #1679. 
line-based target function was failing for some random case so I replaced `np.random`by a static array.
> [FIX] testing line-based target function

- .mailmap
- AUTHOR
- doc/release0.15.rst
Sorry for only noticing this now. I do believe @wasserth spells his name with a "K": https://www.dkfz.de/en/mic/team/people/Jakob_Wasserthal.html
> Typo in release notes

- doc/examples/deterministic_fiber_tracking.py
- doc/examples/particle_filtering_fiber_tracking.py
- doc/examples/probabilistic_fiber_tracking.py
- doc/examples/tracking_bootstrap_peaks.py
- doc/examples/tracking_tissue_classifier.py
Fix `dipy.io.trackvis` deprecation warnings: substitute by
`dipy.io.streamline` as per the DIPY 0.14. API changes:
https://github.com/nipy/dipy/blob/master/doc/api_changes.rst
Partially addresses #1664.
> BUG: Fix `dipy.io.trackvis` deprecation warnings.

- doc/index.rst
Variable names in instruction and sample snippet in homepage are not consistent.
> DOC: fix typo in instruction below sample snippet 

- dipy/core/sphere.py
> BF: Clip the values before passing to arccos, instead of fixing nans.

- doc/examples/linear_fascicle_evaluation.py
Fix blank image being recorded at `linear_fascicle_evaluation.py`:
provide the `fury.window.record` method with the rendered scene.
Fixes #1633.
> BUG: Fix blank image being recorded at `linear_fascicle_evaluation.py`.

- dipy/reconst/qtdmri.py
- dipy/viz/projections.py
- scratch/very_scratch/joint_hist.py
Address `numpy.matrix` `PendingDeprecation` warnings:
- Change the uses of `numpy.matrix` to `numpy.array`.
- Change the use of `numpy.matrix.trace` to `numpy.trace`.
Fixes warnings:
```
/home/travis/build/nipy/dipy/venv/lib/python3.4/site-packages/numpy/matrixlib/defmatrix.py:68:
PendingDeprecationWarning: the matrix subclass is not the recommended
way to represent matrices or deal with linear algebra (see
https://docs.scipy.org/doc/numpy/user/numpy-for-matlab-users.html).
Please adjust your code to use regular ndarray.
return matrix(data, dtype=dtype, copy=False)
```
This should complete the work in PR #1678.
> BUG: Address `numpy.matrix` `PendingDeprecation` warnings.

- doc/examples/linear_fascicle_evaluation.py
Fix typo in `linear_fascicle_evaluation.py` script: change `streamliness`
to `streamlines`.
> DOC: Fix typo in `linear_fascicle_evaluation.py` script.

- dipy/segment/tests/test_mrf.py
- dipy/tracking/tests/test_utils.py
Fix Numpy `.random.random_integer` deprecation warning. Fixes:
```
DeprecationWarning: This function is deprecated. Please call randint(1, 20
+ 1) instead
```
and similar warnings.
> BUG: Fix Numpy `.random.random_integer` deprecation warning.

- dipy/align/bundlemin.pyx
- dipy/reconst/recspeed.pyx
- dipy/tracking/distances.pyx
- dipy/tracking/propspeed.pyx
Fix Cython one-liner non-trivial type declaration warnings. Fixes
```
dipy/tracking/distances.pyx:246:14: Non-trivial type declarators in shared
declaration (e.g. mix of pointers and values). Each pointer declaration
should be on its own line.
```
and similars.
> BUG: Fix Cython one-liner non-trivial type declaration warnings.

- doc/devel/coding_style_guideline.rst
Avoid the bullet points being interpreted as quoted blocks: the
indentation introduced in some previous commit made the bullet points be
interpreted as quoted blocks.
> DOC: Avoid the bullet points being interpreted as quoted blocks.

- doc/examples_index.rst
Images aren't rendering in the website gallery (http://nipy.org/dipy/examples_built/path_length_map.html#example-path-length-map). I think this is because of a syntax error (there's an extra space in the examples_index.rst). I also fixed a random typo I found.
> BF: Syntax fix example images not rendering

- doc/devel/coding_style_guideline.rst
Add an `Imports` section to the style guideline on package shorthands
recommendations.
> DOC: Add `Imports` section on package shorthands recommendations.

- dipy/denoise/enhancement_kernel.pyx
- dipy/tracking/fbcmeasures.pyx
This PR should fix the "PRE" Travis build error as you can see [here](https://travis-ci.org/nipy/dipy/jobs/487740657#L1346)
> [Fix] Cython syntax error

- dipy/reconst/mapmri.py
This PR is a workaround to fix our problem with `cvxpy 1.0.15` on Mapmri. More details on this issue https://github.com/cvxgrp/cvxpy/issues/672.
I would like to know by the MapMRI expert (@rutgerfick @RafaelNH @arokem @Garyfallidis) if this approximation is ok or not.
Thank you for your feedback
> [FIX] mapmri  with cvxpy 1.0.15

- tools/ex2rst
- tools/github_stats.py
- tools/make_examples.py
This PR is just an update of some useful script because they were only compatible with python 2...
I used the opportunity to fix some pep8.
> [FIX] Python 3 compatibility for some tools script

- doc/index.rst
A quick PR to add NIH to the sponsor list.
> [DOC] Add NIH to sponsor list

- dipy/segment/bundles.py
- dipy/segment/tests/test_refine_rb.py
Pass down the _num_thread_ parameters and fix verbose
No change in behaviour, the default is still all CPU available
Without this option, using recobundles in a pipeline is sub-optimal
> Adjust number of threads for SLR in Recobundles

- dipy/align/crosscorr.pyx
- dipy/align/expectmax.pyx
- dipy/align/parzenhist.pyx
- dipy/align/sumsqdiff.pyx
- dipy/align/vector_fields.pyx
- dipy/segment/clustering_algorithms.pyx
- dipy/segment/clusteringspeed.pxd
- dipy/segment/clusteringspeed.pyx
- dipy/segment/featurespeed.pxd
- dipy/segment/featurespeed.pyx
- dipy/segment/metricspeed.pxd
- dipy/segment/metricspeed.pyx
The goal of this PR is to fix Travis PRE build error. As you can see [here](https://travis-ci.org/nipy/dipy/jobs/493526375#L1399), DIPY was failing during compilation due to the change of the default Cython `language_level` (from `py2` to `py3str`, warning [here](https://travis-ci.org/nipy/dipy/jobs/493526375#L1343)). This implies to switch our relative import to absolute import to respect python 3 semantics. 
So, this is just an update of some `*.pyx`  and `*.pxd` files. Let's see if it works now...
> [Fix]  Pre-build : From relative to absolute import

- dipy/io/tests/test_utils.py
- dipy/io/utils.py
> BF: Fixes #1751, by adding a `scale` key-word arg to `decfa`

- doc/devel/coding_style_guideline.rst
Add Cython style guideline for DIPY.
Fixes #583.
> DOC: Add Cython style guideline for DIPY.

- .mailmap
- Changelog
- dipy/info.py
- doc/api_changes.rst
- doc/index.rst
- doc/old_highlights.rst
- doc/release_notes/release0.16.rst
- doc/stateoftheart.rst
Preparation for 0.16.0 release, targeting Friday, March 8.  The last 0.X.X series. DIPY 1.0.0 in June!!!
It will be good to merge the following PR before the release on Friday.
- your suggestion ?
Just a note that any of this PR can block the release. If they are not in, it will be for the next release in
june.
> REL: 0.16.0

- dipy/io/tests/test_utils.py
- dipy/io/utils.py
> Implements the inverse of decfa

- dipy/reconst/mapmri.py
This is causing an error in python 3.7
> Change "is" check for 'GCV'

- dipy/direction/tests/test_prob_direction_getter.py
This tests whether https://github.com/nipy/dipy/issues/1783 is still an issue, which I believe is not the case anymore. 🤷‍♂️
> Add test for different dtypes

- dipy/workflows/base.py
this PR should fix @jchoude [comment](https://github.com/nipy/dipy/issues/1793#issuecomment-476027822) concerning the line break strips the space.
Reference: #1793
Before (look at positional args documentation):
After (look at positional args documentation):
> [Fix] stripping in workflow documentation

- dipy/workflows/reconst.py
- dipy/workflows/tests/test_reconst_csa_csd.py
Adding parallelization to `peaks_from_models` for CSA and CSD in the reconstruction workflows.
> Parallel reconst workflows

- doc/examples/reconst_ivim.py
This is a small follow-up to #1789, in which the varpro and lm are plotted together. 
@ShreyasFadnavis : could you please take a look?
> Plot both IVIM fits on the same axis

- dipy/workflows/reconst.py
This should fix #1808. It was an error during doc parsing. NumpyDoc seems sensitive to space after the semicolon. Good to know for a future review.
@arokem, Can you test it? Thank you
> [Bug FIx]  dipy_fit_csa and dipy_fit_csd workflow

- dipy/reconst/shm.py
- dipy/reconst/tests/test_shm.py
Addresses https://github.com/nipy/dipy/issues/1763
The default value for `min_signal` in all Q-ball models in reconst/shm.py is set to 1. This causes all ODFs to be reconstructed the same if the data happens to be between [0,1] prior to reconstruction. 
I checked the history, and at some point in the past, the default was set to 1e-5. I'm assuming there was a reason it was changed up to 1.0, but as far as I know, changing it back to 1e-5 shouldn't affect the stability.
> BF: changes min_signal defaults from 1 to 1e-5

- dipy/workflows/tracking.py
- dipy_track_local
- added step_size option
- change default algorithm from deterministicMaxDG to EuDX (#1787)
- Update the DOC
this addresses #1758 .
> NF - add tracking workflow parameters

- doc/README.MD
- doc/doc-requirements.txt
This PR adds a basic readme for doc generation. It is always useful and should fix #436 (really old issue)
> [Fix] Add Readme for doc generation

- dipy/core/histeq.py
This PR should fix #1761. As you can see on [numpy documentation](https://docs.scipy.org/doc/numpy/reference/generated/numpy.histogram.html), `normed` parameter has been deprecated and superseded by `density` since a long time.
> [FIX] median_otsu deprecated parameter

- dipy/viz/app.py
- dipy/viz/tests/test_apps.py
> [Fix]  add a basic check on dipy_horizon

- dipy/align/metrics.py
- dipy/align/tests/test_metrics.py
This PR is just an implementation of [this comment](https://github.com/nipy/dipy/issues/1048#issue-154572349). It should fix #1048.
> [Fix] Diffeormorphic + CCMetric on small image

- dipy/reconst/peaks.py
- doc/examples/streamline_tools.py
This PR removes the deprecated module `dipy.reconst.peaks`. This module has been replaced by `dipy.direction.peaks`.
> Remove deprecated module dipy.reconst.peaks

- dipy/align/tests/test_imaffine.py
- dipy/data/__init__.py
- dipy/reconst/tests/test_peak_finding.py
- doc/examples/reconst_shore_metrics.py
This PR is the first of a long series to remove all deprecated function/module in DIPY.
`get_data` has been replaced by `get_fnames`
> Remove Deprecated function  dipy.data.get_data

- .travis.yml
- appveyor.yml
- cythexts.py
- dipy/info.py
- requirements.txt
- setup_egg.py
Implements as discussed in #1731 
Also, https://github.com/travis-ci/travis-ci/issues/9815 seems to now be resolved.
> Remove Python 2 dependency.

- .travis.yml
- dipy/segment/mask.py
- dipy/segment/tests/test_mask.py
- dipy/workflows/segment.py
- dipy/workflows/stats.py
- dipy/workflows/tests/test_segment.py
- dipy/workflows/tests/test_workflow.py
- doc/api_changes.rst
> Fixes 238, by requiring vol_idx input with 4D images.

- doc/tools/docgen_cmd.py
this PR should fix @arokem  [comment](https://github.com/nipy/dipy/issues/1793#issuecomment-476239226) concerning the command line documentation.
Reference: #1793 
- Maybe we need to "cherry-pick" on maint/0.16.x branch and regenerate the documentation after merging.
- We need a new PR to reformat this docstring. It is not beautiful for the moment.
> Update command line documentation generation

- CONTRIBUTING.md
This PR adds instructions for running tests and coverage reports for a single module without running the entire DIPY test suite. I found this useful for my first DIPY contributions since I was running into a lot of test errors for parts of the code base that I hadn't touched. These instructions might be more inviting to first-time contributors.
> DOC: Add single-module test/coverage instructions

- dipy/segment/mask.py
- doc/examples/brain_extraction_dwi.py
- doc/examples/reconst_csa.py
- doc/examples/reconst_csa_parallel.py
- doc/examples/reconst_csd_parallel.py
- doc/examples/reconst_dki.py
- doc/examples/reconst_dti.py
- doc/examples/reconst_fwdti.py
- doc/examples/reconst_msdki.py
- doc/examples/syn_registration_2d.py
- doc/examples/syn_registration_3d.py
- doc/examples/tracking_quick_start.py
The prior function declaration breaks all these tutorials that use median_otsu:
brain_extraction_dwi.py
reconst_msdki.py
reconst_dti.py
reconst_csa_parallel.py
reconst_fwdti.py
reconst_csa.py
reconst_csd_parallel.py
reconst_dki.py
syn_registration_2d.py
syn_registration_3d.py
tracking_quick_start.py
You can test this by running any of these scripts in dipy/doc/examples or here http://nipy.org/dipy/examples_built/reconst_csa.html. My modification corrects this so that all the tutorials still function normally.
> Corrected median_otsu function declaration that was breaking tutorials

- dipy/workflows/reconst.py
As discussed with @jchoude, the goal of this PR is to fix #1764. The docstring was not coherent with the current behavior. Indeed, `mask` is mandatory for all reconstruction workflow.
> [Fix]  Workflow mask documentation

- .travis.yml
This is due to breaking changes in the scipy API that will be fixed on an eventual release of statsmodels. For now, let's pin this and unpin when a new release of scipy comes along.
Should help deal with this breakage: https://travis-ci.org/nipy/dipy/jobs/542426220#L6092
> Pin scipy version for bots that need statsmodels.

- dipy/core/geometry.py
- dipy/core/tests/test_geometry.py
This PR adds the `is_hemispherical()` function to `dipy.core.geometry` and adds associated unit tests. We found this function usefull in [dmriprep](https://github.com/nipy/dmriprep) to see if bvecs were collected from all points on a sphere or only hemispherically. @arokem suggested that it might by useful in other contexts and that I should add it to DIPY.
> NF: Add is_hemispherical test

- .travis.yml
- dipy/info.py
- requirements.txt
> MAINT: Drop support for Python 3.4

- bin/dipy_fetch
- dipy/workflows/io.py
- dipy/workflows/tests/test_io.py
This PR adds a new workflow: `FetchFlow`. This command line is an easy way to grab our tutorial data via a command line.
Example:
----------
```
$ dipy_fetch standford_hardi
$ dipy_fetch all
$ dipy_fetch all --out_dir=~/my_folder
$ dipy_fetch standford_hardi bundle_fa_hcp
$ dipy_fetch standford_hardi bundle_fa_hcp --out_dir=~/my_folder
```
> [NF] new workflow: FetchFlow

- dipy/align/imaffine.py
- dipy/align/tests/test_streamlinear.py
- dipy/core/optimize.py
- dipy/core/tests/test_optimize.py
- dipy/reconst/ivim.py
- dipy/reconst/tests/test_ivim.py
This PR should fix #1863. It removes all SCIPY_LESS_0.x.x
> Clean up: Remove all SCIPY_LESS_0.x.x

- dipy/reconst/dti.py
- dipy/utils/arrfuncs.py
- dipy/utils/tests/test_arrfuncs.py
As a follow up of #1877, this PR remove NUMPY_LESS_0.8.x and `eigh` function
> Clean up: Remove NUMPY_LESS_0.8.x

- doc/examples/tracking_tissue_classifier.py
> DOC - clarified the state of the tracking process once stopped

- dipy/workflows/tests/test_tracking.py
- dipy/workflows/tracking.py
Add binary tissue classifier option for tracking workflow.
Fixes #1811.
> ENH: Add binary tissue classifier option for tracking workflow

- dipy/tracking/streamline.py
Since our Nibabel minimum version is 2.4, we do not need this patch anymore. This patch was fixing a memory issue on streamlines API and has been fixed on Nibabel 2.3
> Clean up: Remove streamlines memory patch

- doc/examples/deterministic_fiber_tracking.py
- doc/examples/particle_filtering_fiber_tracking.py
- doc/examples/probabilistic_fiber_tracking.py
- doc/examples/sfm_tracking.py
- doc/examples/tracking_tissue_classifier.py
This addresses #1779 and clarifies the examples.
Any idea on the root of the problem in #1779 ?
> DOC - explicitly run the streamline generators before saving the trk

- dipy/data/__init__.py
- dipy/reconst/forecast.py
- dipy/reconst/mapmri.py
- dipy/reconst/shore.py
- dipy/reconst/tests/test_dsi.py
- dipy/reconst/tests/test_dsi_deconv.py
- dipy/reconst/tests/test_dsi_metrics.py
- dipy/reconst/tests/test_forecast.py
- dipy/reconst/tests/test_gqi.py
- dipy/reconst/tests/test_mapmri.py
- dipy/reconst/tests/test_qtdmri.py
- dipy/reconst/tests/test_shore.py
- dipy/reconst/tests/test_shore_metrics.py
- dipy/reconst/tests/test_shore_odf.py
- dipy/sims/phantom.py
- dipy/sims/tests/test_voxel.py
- dipy/sims/voxel.py
- doc/api_changes.rst
This PR removes the backward compatibilities with `SingleTensor`, `MultiTensor` and StickAndBall`.
`dipy.sims.voxel.SingleTensor` has been replaced by `dipy.sims.voxel.single_tensor`
`dipy.sims.voxel.MultiTensor` has been replaced by `dipy.sims.voxel.multi_tensor`
`dipy.sims.voxel.SticksAndBall` has been replaced by `dipy.sims.voxel.sticks_and_ball`
This should fix #844
> Replace SingleTensor by single_tensor

- dipy/reconst/peak_direction_getter.pyx
I believe this PR should fix #1642 and more specifically, the following error we have seen intermittently:
`ValueError: cannot expose native-only dtype 'g' in non-native byte order '<' via buffer interface`
Let's see
> Fix: Byte ordering error on Python 3.5

- dipy/align/crosscorr.pyx
- dipy/core/sphere.py
- dipy/denoise/nlmeans.py
- dipy/reconst/csdeconv.py
- doc/examples/affine_registration_3d.py
- doc/examples/syn_registration_2d.py
- doc/examples/syn_registration_3d.py
Improve documentation:
- Fix typos in authors names/use accented characters.
- Use `ANTs` for the Advanced Normalization Tools software acronym, as
authors do.
- Fix typos.
- Remove some spare whitespaces.
> DOC: Improve documentation

- dipy/io/vtk.py
- dipy/viz/__init__.py
- dipy/viz/app.py
- dipy/viz/panel.py
- dipy/viz/tests/test_apps.py
- dipy/workflows/tests/test_viz.py
And provide a link to information about install
> Warn users if they don't have FURY installed 

- dipy/reconst/csdeconv.py
- dipy/reconst/tests/test_csdeconv.py
This allows the user to pass the maximum number of iterations as an argument when setting up a CSD model. This functionality already existed in the `csdeconv` function, but was not accessible with a standard workflow of setting up a CSD model object, then calling the `fit` method.
> Adds control for number of iterations in CSD recon

- dipy/direction/tests/test_prob_direction_getter.py
- dipy/reconst/shm.py
- dipy/reconst/tests/test_shm.py
- doc/api_changes.rst
> ENH: Remove deprecated SH bases

- doc/examples/streamline_tools.py
Changed the call from EuDX to LocalTracking. EuDX is still the algorithm use here, but in the new framework.
> DOC - updated streamline_tools example with the LocalTracking Framework

- doc/devel/gitwash/index.rst
- doc/examples/affine_registration_3d.py
- doc/examples/afq_tract_profiles.py
- doc/examples/cluster_confidence.py
- doc/examples/combined_workflow_creation.py
- doc/examples/contextual_enhancement.py
- doc/examples/linear_fascicle_evaluation.py
- doc/examples/particle_filtering_fiber_tracking.py
- doc/examples/path_length_map.py
- doc/examples/reconst_csa.py
- doc/examples/reconst_fwdti.py
- doc/examples/reconst_ivim.py
- doc/examples/reconst_msdki.py
- doc/examples/reconst_qtdmri.py
- doc/examples/register_binary_fuzzy.py
- doc/examples/sfm_tracking.py
- doc/examples/snr_in_cc.py
- doc/examples/streamline_length.py
- doc/examples/tracking_bootstrap_peaks.py
- doc/examples/tracking_tissue_classifier.py
- doc/examples/viz_bundles.py
- doc/examples/viz_roi_contour.py
- doc/examples/viz_slice.py
- doc/examples/viz_timers.py
- doc/examples/viz_ui.py
- doc/examples_index.rst
Fix examples documentation generation warnings.
Fixes:
```
WARNING: Title overline too short.
```
and
```
/doc/examples_built/viz_bundles.rst:209: WARNING: Error in "figure"
directive:
invalid option block.
.. figure:: bundle5.png
:align: center
**Color every streamline by the length of the streamline **
```
warnings reported in
https://buildd.debian.org/status/fetch.php?pkg=dipy&arch=s390x&ver=0.14.0-1&stamp=1526401155&raw=0
Take advantage of the commit to increase consistency in titles:
- Use the same pattern for sections.
- Limit punctuation characters to the length of the text.
> DOC: Fix examples documentation generation warnings

- doc/examples/snr_in_cc.py
This PR fix `snr_in_cc.py` tutorial. Since we are using 4d data for this tutorial, `vol_idx` was missing on `median_otsu` function. I use the opportunity to fix some pep8
> [Fix] vol_idx missing in snr_in_cc Tutorial

- dipy/reconst/shm.py
Remove unused `warning` package import.
> ENH: Remove unused `warning` package import

- dipy/direction/tests/test_bootstrap_direction_getter.py
- dipy/direction/tests/test_pmf.py
- dipy/reconst/csdeconv.py
- dipy/reconst/tests/test_csdeconv.py
- doc/examples/reconst_csd.py
I've created this PR basically to address issue #283. 
After analysing the issue, I've decided that the best solution is to remove the response=None option. If one wants to use a predefined response function, it can just defined it on its own risk by calling:
response=(np.array([AD, RD, RD]), S0)
Using an None option is not ideal also because it does not allows the adjustment of S0. At the current version of the CSD implementation, data is normalised based on this inputed S0 estimate, so having it properly estimated might be crucial for the estimation of the fODF shape. 
After revising  the CSD example, I've noticed that it might be hard to ready for non diffusion MRI experts. For instance, it might not be clear that the time consuming response function calibration procedure is optional. …
> Spherical deconvolution model CANNOT be constructed without specifying a response

- dipy/tracking/_utils.py
- dipy/tracking/tests/test_utils.py
- dipy/tracking/utils.py
- dipy/tracking/vox2track.pyx
- doc/api_changes.rst
Since `voxel_size` was deprecated since a long time, this parameter has been removed from the following function:
``dipy.tracking.utils.connectivity_matrix``
``dipy.tracking.utils.density_map``
``dipy.tracking.utils.streamline_mapping``
``dipy.tracking._util._mapping_to_voxel``
> Remove deprecated parameter voxel_size

- dipy/direction/tests/test_peaks.py
- dipy/direction/tests/test_pmf.py
- dipy/reconst/csdeconv.py
- dipy/reconst/tests/test_csdeconv.py
- dipy/reconst/tests/test_ivim.py
- dipy/reconst/tests/test_mapmri.py
- dipy/workflows/docstring_parser.py
- dipy/workflows/tests/test_reconst_csa_csd.py
During Travis build or example build, There is a bunch of warning. 
This PR is the first of a series that track and resolve/remove them. 
- Fix nb processor UserWarning [here](https://travis-ci.org/nipy/dipy/jobs/420571741#L2878) and [here](https://travis-ci.org/nipy/dipy/jobs/420571741#L2880) 
- Fix csdeconv [here](https://travis-ci.org/nipy/dipy/jobs/420571741#L2887) [here](https://travis-ci.org/nipy/dipy/jobs/420571741#L2936) [here](https://travis-ci.org/nipy/dipy/jobs/420571741#L2941) [here](https://travis-ci.org/nipy/dipy/jobs/420571741#L2941) [here](https://travis-ci.org/nipy/dipy/jobs/420571741#L2959)
- Fix Yield warning [here](https://travis-ci.org/nipy/dipy/jobs/420571741#L2573)
> [Fix] remove Userwarning message

- dipy/tracking/local/localtracking.py
- dipy/tracking/local/tests/test_tracking.py
Since #1666, it was possible to return "valid" streamlines with a single point. This could happen in corner cases with a sequence of voxels: gm - wm - gm, wherein a single tracking step the tracking stops in the gm on both sides, resulting in a correctly ending streamline of a single point.
This PR fixes this.
> BF - remove single pts streamline

- dipy/direction/peaks.py
- dipy/tracking/tests/test_life.py
The goal of this PR is to fix #389.  I use the opportunity to fix one test not related
> [Fix] removing minmax_norm parameter from peak_direction

- dipy/testing/__init__.py
I'm not sure why I getting this now, but it crashes at line 68, `warning` not imported.
> BF - move import to top level

- dipy/data/fetcher.py
- dipy/io/stateful_tractogram.py
- dipy/io/streamline.py
- dipy/io/utils.py
- dipy/tracking/utils.py
- doc/examples/streamline_formats.py
Considering the new StatefulTractogram and the fact that the old example only covered the Dpy format. This update now contain a more complete list of file format, the new API and new data that can be fetched.
> Update streamlines formats example

- dipy/tracking/vox2track.pyx
In the `_streamline_in_mask` function, if two or more consecutive points shared exactly the same coordinates, the loop would never finish. Added a quick check on the distance to avoid such case.
This is a test that is already present in our in house code and has been tested extensively.
> BF: added check to avoid infinite loop on consecutive coordinates.

- dipy/segment/tests/test_bundles.py
this PR should resolve #1587.
@arokem and @yarikoptic, Can you have a look? 
I do not know how we can add a test. Any idea?
> Skip some tests on big endian architecture (like s390x)

- dipy/stats/analysis.py
- dipy/stats/tests/test_analysis.py
- dipy/tracking/life.py
- dipy/tracking/tests/test_life.py
- doc/api_changes.rst
- doc/examples/afq_tract_profiles.py
To increase consistency within Dipy and increase cautious behaviors when coding the affine is now required when it was previously optional.
Older/unused functions that had complex behavior related to spatial transform and trackvis file format were deleted to prevent confusion.
Docstring is now uniform when describing the affine.
Tests were executed and examples tested.
> Increase affine consistency in dipy.tracking.life and dipy.stats.analysis

- dipy/reconst/fwdti.py
- doc/examples/reconst_dki.py
- doc/examples/reconst_dki_micro.py
- doc/examples/reconst_fwdti.py
- doc/examples/valid_examples.txt
- doc/examples_index.rst
Hi! In this PR, I am submitting a documentation update of the following models fwDTI, DKI, and WMTI. 
Basically I've improved the following aspects.
- Add the Rescience paper that reports all the code adaptions done for fwDTI implementation in Dipy (we were still citing the previous implementation proposed by Hoy et al.)
- Splitting the DKI example - this to address issue #1774.
- Give more highlight to WMTI and fwDTI models in Dipy's gallery. Previously, these models were added as a subsection of DTI and DKI models, which might be decreasing WMTI and fwDTI visibility.
PS: This is my last PR for Dipy's release 1.0
> Update DKI, WMTI, fwDTI examples and give more evidence to WMTI and fwDTI models

- doc/examples/reconst_mcsd.py
This tutorial is also intended to delineate DIPY's ability to create pipelines.
Steps involved:
- Denoising
- Registration
- Tissue Classifier
- MCSD
Addresses #1870
> [WIP] - MTMS-CSD Tutorial

- dipy/denoise/localpca.py
- dipy/denoise/tests/test_lpca.py
- doc/examples/denoise_localpca.py
- doc/examples/denoise_mppca.py
- doc/examples/valid_examples.txt
- doc/examples_index.rst
Hi all! I am working on a functional implementation of the Random matrix local PCA for Dipy's next release. I've already added the classifier based on the moments of the Marchenko–Pastur probability distribution according to [Veraart et al., 2016](https://www.ncbi.nlm.nih.gov/pubmed/27523449) -  which seems to pass my added tests. Now, I just need to:
In the meantime, I need our opinion on the follow aspect - The new feature does not require the estimation of noise sigma, so what should I do with the previous implemented noise estimate procedure? @arokem, @skoudoro did you mentioned that this procedure is not working well? The current version of the code is still compatible with this previous procedure; however if it is not working I don't mind removing it to simplified a bit the code. …
> A functional implementation of Random matrix local pca.

- dipy/io/stateful_tractogram.py
- dipy/io/tests/test_stateful_tractogram.py
As of right now loading and saving empty tractogram is crashing because of the bbox in voxel space being checked.
Addition of a simple condition in the verification.
> Fix empty tractogram loading saving

- .mailmap
- Changelog
- dipy/core/interpolation.pyx
- dipy/core/tests/test_interpolation.py
- doc/api_changes.rst
- doc/developers.rst
- doc/examples/bundle_extraction.py
- doc/examples/denoise_ascm.py
- doc/examples/denoise_gibbs.py
- doc/examples/denoise_mppca.py
- doc/examples/denoise_nlmeans.py
- doc/examples/reconst_dki_micro.py
- doc/examples/reconst_fwdti.py
- doc/examples/reconst_msdki.py
- doc/examples/reconst_shore.py
- doc/examples/tracking_bootstrap_peaks.py
- doc/examples/tracking_sfm.py
- doc/examples/viz_advanced.py
- doc/examples_index.rst
- doc/index.rst
- doc/introduction.rst
- doc/old_highlights.rst
- doc/old_news.rst
- doc/release_notes/release1.0.rst
- doc/stateoftheart.rst
Preparation for 1.0.0 release, targeting Wednesday, July 31.  The new 1.X.X series !!! Python 3 only !!!
Just a note that any PR can block the release. If they are not in, it will be for the next release in
October.
> [Upcoming] Release 1.0 for wednesday

- doc/examples/reconst_shore.py
Following references were missing:
- E. Özarslan, C. G. Koay, and P. J. Basser, "Simple harmonic oscillator based estimation and reconstruction for one-dimensional q-space MR,” in Proc Intl Soc Mag Reson Med, 16, Toronto, Canada, 2008, p. 35.
- E. Özarslan, C. G. Koay, T. M. Shepherd, S. J. Blackband, and P. J. Basser, "Simple harmonic oscillator based reconstruction and estimation for three-dimensional q-space MRI," in Proc Intl Soc Mag Reson Med, 17, Honolulu, HI, 2009, p. 1396.
> Adding Missing References in SHORE docs

- doc/examples/streamline_registration.py
- doc/examples/valid_examples.txt
- doc/examples_index.rst
Add streamline deformation example and workflow.
Resolves #1840.
> ENH: Add streamline deformation example and workflow

- cythexts.py
- setup_helpers.py
Gets rid of a couple dozen warnings of the form:
```
.../Cython/Compiler/Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /home/larsoner/python/dipy/dipy/denoise/enhancement_kernel.pyx
```
It's probably safer to use `-2` (it should be what's currently being used) but I put in `-3` to at least see if it works. And if you know you don't use `str` in your Cython code and you've been careful with `/` vs `//` then `-3` might actually be the right change.
From the source code it looked like there were probably two places this was needed, though for my particular use case (`pip install -e .`) I only needed the one in `setup_helpers.py`.
There might be a better way to do this, but it was difficult to get to …
> ENH: Use language level 3

- dipy/core/interpolation.pyx
Gets rid of a slew of warnings of the form:
```
warning: dipy/core/interpolation.pyx:749:25: Use boundscheck(False) for faster access
```
when building from source. Also should make things a tiny bit faster.
Alternatively this can be enabled using more fine-grained control via individual decorators like:
```
@cython.boundscheck(False)
```
From a quick look it seems like these are reasonable options for this file, but I did not look super closely. This is thus really more of a "suggestion PR" so feel free to close if it does not make sense.
> ENH: Speed up Cython, remove warnings

- CONTRIBUTING.md
Fix the broken link under the subtitle "The development process" of the file "CONTRIBUTING.md".
It looks like after we released version 1.0.0, the route of the website change a little bit. This might cause other broken links. And also, there might be a better way to fix this. Discussion and advice are welcoming.
> fix broken link of devel

- dipy/core/gradients.py
Since this uses bval.min() it's not the first, but rather the smallest b-value
> Small fix in warning message

- doc/examples/README.md
Improve the `doc/examples/README` file contents:
- Make the syntax be consistent with the one `README` file in the `doc`
folder (headings style and literal text markup).
- Capitalize DIPY.
> DOC: Improve the `doc/examples/README` file contents

- dipy/io/streamline.py
- doc/examples/streamline_registration.py
This PR fix `streamlines_registration.py` tutorial and some pep8. The documentation generation was failing because of this tutorial.
> [Fix] one example

- dipy/viz/__init__.py
- dipy/viz/tests/test_viz_import.py
Would this properly address #1976 ? 
The cryptic error is still raised, but is preceded by a warning:
> Add a warning on attempted import.

- dipy/segment/bundles.py
Also, fixes the docstring to the used default.
Addresses https://github.com/nipy/dipy/issues/1982
> BF: use MAM distance when that is requested.

- dipy/io/streamline.py
Fix parameter docstring in `dipy.io.streamline.load_tractogram`: fix
name and type.
> DOC: Fix parameter docstring in `dipy.io.streamline.load_tractogram`

- dipy/align/metrics.py
Fixes on latest `scipy` master branch:
```
DeprecationWarning: scipy.gradient is deprecated and will be removed in SciPy 2.0.0, use numpy.gradient instead
```
> MAINT: Update gradient for SciPy deprecation

- dipy/workflows/io.py
- dipy/workflows/tests/test_io.py
Fix workflows IO `FetchFlow` `all` dataset fetching: the `fetch_data` is
contained in the `available_data` dictionary because as the actual data fetcher
function it starts with  `fetch_`. However, the `fetch_data` function is what
the actual fetchers call with the necessary arguments. Thus, the
`dipy.workflows.tests.test_io.test_io_fetch` test fails if we specify
`fetch_flow.run(['all'])` because the parameters of `fetch_data` are empty.
The fix is to avoid adding the `fetch_data` function when the dictionary is
created.
Fixes
```
File
"/src/dipy/dipy/workflows/tests/test_io.py",
line 80, in <module>
test_io_fetch()
File
"src/dipy/dipy/workflows/tests/test_io.py",
line 54, in test_io_fetch
fetch_flow.run(['all'])
File
"/src/dipy/dipy/workflows/io.py",
line 172, in run
fetcher_function() …
```
> BUG: Fix workflows IO `FetchFlow` `all` dataset fetching
